[CI][VSTS] Add required profiles for mac.
xamarin/xamarin-macios pull request #10366
Opened 2021-01-08 20:33 UTC by mandel-macaque

2021-01-08 20:42 UTC, mandel-macaque commented
/azp run

2021-01-08 20:45 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16094/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16094//console)
🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16094//console) 🔥

2021-01-08 20:51 UTC, dalexsoto approved these changes

2021-01-08 22:52 UTC, monojenkins commented
Build failure
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16095//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16095//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16095//API_20diff_20_28from_20stable_29)
🔥 [Failed to compare API and create generator diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16095//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;** Error: Working directory isn't clean:
&nbsp;&nbsp;&nbsp;&nbsp;HEAD detached at 52a442923
&nbsp;&nbsp;&nbsp;&nbsp;Untracked files:
&nbsp;&nbsp;&nbsp;&nbsp;(use "git add <file>..." to include in what will be committed)
&nbsp;&nbsp;&nbsp;&nbsp;tools/dotnet-linker/packages/
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;nothing added to commit but untracked files present (use "git add" to track)
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
✅ [Test run succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16095//Test_20Report)

2021-01-09 01:00 UTC, vs-mobiletools-engineering-service2 commented
### :x: Device tests failed on Build :x:

Device tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4356859&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210108.10/4356859/sim/;/tests/vsdrops_index.html)


# Test results

<details>
<summary>1 tests failed, 40 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 7)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4356859&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1103

2021-01-11 10:44 UTC, rolfbjarne requested changes

2021-01-11 10:44 UTC, rolfbjarne commented on tools/devops/automation/templates/packages/build.yml
> +    rm -f ~/Library/Caches/com.xamarin.provisionator/Provisions/*mobileprovision
The `install-qa-provisioning-profiles.sh` script already does this, so these lines shouldn't be necessary.

2021-01-11 21:44 UTC, vs-mobiletools-engineering-service2 commented
### :x: Device tests failed on Build :x:

Device tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4361311&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210111.17/4361311/sim/;/tests/vsdrops_index.html)


# Test results

<details>
<summary>1 tests failed, 40 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 7)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4361311&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1095'

2021-01-11 22:07 UTC, spouliot approved these changes

2021-01-12 05:07 UTC, monojenkins commented
Build failure
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16104//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16104//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16104//API_20diff_20_28from_20stable_29)
🔥 [Failed to compare API and create generator diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16104//console) 🔥
&nbsp;&nbsp;&nbsp;&nbsp;** Error: Working directory isn't clean:
&nbsp;&nbsp;&nbsp;&nbsp;HEAD detached at 3cc245432
&nbsp;&nbsp;&nbsp;&nbsp;Untracked files:
&nbsp;&nbsp;&nbsp;&nbsp;(use "git add <file>..." to include in what will be committed)
&nbsp;&nbsp;&nbsp;&nbsp;tools/dotnet-linker/packages/
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;nothing added to commit but untracked files present (use "git add" to track)
&nbsp;&nbsp;&nbsp;&nbsp;Search for `Comparing API & creating generator diff` in the log to view the complete log.
✅ [Test run succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16104//Test_20Report)

2021-01-12 06:31 UTC, rolfbjarne approved these changes

2021-01-12 20:26 UTC, vs-mobiletools-engineering-service2 commented
### :x: Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4364984&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210112.10/4364984/sim/;/tests/vsdrops_index.html)


# Test results

<details>
<summary>1 tests failed, 40 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 7)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4364984&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1096'

2021-01-12 20:29 UTC, mandel-macaque commented
The last comments shows the expected result, one single failure and @spouliot is working on it.

2021-01-12 20:29 UTC, merged

2021-01-12 20:30 UTC, mandel-macaque commented
/sudo backport d16-9

2021-01-12 20:30 UTC, mandel-macaque commented
/sudo backport xcode12.3

2021-01-12 20:30 UTC, vs-mobiletools-engineering-service2 commented
Backport Job Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=)

2021-01-12 20:31 UTC, vs-mobiletools-engineering-service2 commented
Backport Job Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=)

2021-01-12 20:32 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4365994 for more details.

2021-01-12 20:32 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4365996 for more details.