[CI][VSTS] Clean .xip files.
xamarin/xamarin-macios pull request #10398
Opened 2021-01-12 22:02 UTC by mandel-macaque

At some point either due to a manual error or a bug in provisionator a
*.xip file was left behind. Those files make provisioantor fail, for
example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4361631&view=logs&j=f0137cdf-e292-5541-69aa-72303a08a0ba&t=59bea1c0-f907-5818-000e-f6fef9d3ffa2&l=230

We will remove those files to make sure provisionator works and we get
device tests back.

2021-01-12 22:05 UTC, dalexsoto approved these changes
yay

2021-01-12 22:07 UTC, spouliot approved these changes

2021-01-13 01:27 UTC, mjbond-msft approved these changes

2021-01-13 02:21 UTC, vs-mobiletools-engineering-service2 commented
### :x: Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4366384&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210112.39/4366384/sim/;/tests/vsdrops_index.html)


# Test results

<details>
<summary>1 tests failed, 40 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 7)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4366384&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1097

2021-01-13 06:47 UTC, rolfbjarne requested changes

2021-01-13 06:47 UTC, rolfbjarne commented on tools/devops/automation/scripts/bash/clean-bot.sh
> +sudo rm -Rf "/Applications/Xcode*.xip"
The wildcard won't expand if you use quotes:

```
$ ls -lad "/Applications/Xcode*.app"
ls: /Applications/Xcode*.app: No such file or directory

$ ls -lad /Applications/Xcode*.app  
drwxr-xr-x  3 rolf  staff  96 Nov 11 05:00 /Applications/Xcode-12.3.0-beta1.app
lrwxr-xr-x  1 rolf  admin  30 Dec  9 16:37 /Applications/Xcode.app -> /Applications/Xcode_12.2.0.app
lrwxr-xr-x  1 rolf  admin  27 Sep 24  2019 /Applications/Xcode_10.2.1.app -> /Applications/Xcode1021.app
lrwxr-xr-x  1 rolf  admin  26 Jan 20  2020 /Applications/Xcode_11.3.0.app -> /Applications/Xcode113.app
drwxr-xr-x  3 rolf  staff  96 May  3  2020 /Applications/Xcode_11.5.0.app
drwxr-xr-x  3 rolf  staff  96 Jul  2  2020 /Applications/Xcode_11.6.0.app
lrwxr-xr-x  1 rolf  admin  30 Jul 23 11:44 /Applications/Xcode_11.6.app -> /Applications/Xcode_11.6.0.app
drwxr-xr-x  3 rolf  staff  96 Aug 12 19:30 /Applications/Xcode_11.7.0.app
drwxr-xr-x  3 rolf  staff  96 Sep  9 20:30 /Applications/Xcode_12.0.0.app
drwxr-xr-x  3 rolf  staff  96 Oct  8 10:25 /Applications/Xcode_12.1.0.app
drwxr-xr-x  3 rolf  staff  96 Oct 24 04:24 /Applications/Xcode_12.2.0.app
drwxr-xr-x  3 rolf  staff  96 Dec  3 23:20 /Applications/Xcode_12.3.0.app
```

```suggestion
sudo rm -Rf /Applications/Xcode*.xip
```

2021-01-13 10:03 UTC, monojenkins commented
Build success
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16116//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16116//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16116//API_20diff_20_28from_20stable_29)
✅ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16116//API_20diff_20_28PR_20only_29) (no change)
✅ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16116//Generator_20Diff) (no change)
✅ [Test run succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/16116//Test_20Report)

2021-01-13 14:38 UTC, rolfbjarne approved these changes

2021-01-13 18:25 UTC, vs-mobiletools-engineering-service2 commented
### :x: Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4368825&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210113.12/4368825/sim/;/tests/vsdrops_index.html)


# Test results

<details>
<summary>1 tests failed, 40 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 5)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4368825&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1097'

2021-01-13 21:12 UTC, merged

2021-01-13 21:13 UTC, mandel-macaque commented
/sudo backport d16-9

2021-01-13 21:13 UTC, mandel-macaque commented
/sudo backport xcode12.3

2021-01-13 21:13 UTC, vs-mobiletools-engineering-service2 commented
Backport Job Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=)

2021-01-13 21:13 UTC, vs-mobiletools-engineering-service2 commented
Backport Job Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=)

2021-01-13 21:14 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4369976 for more details.

2021-01-13 21:14 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4369973 for more details.