[src] Move enums into files that are processed by the generator
xamarin/xamarin-macios pull request #10645
Opened 2021-02-15 19:38 UTC by spouliot

The generator has been able to read and re-generate enums for a while.
However not all enums were in file processed by the generator. That was
not a huge problem since the output was identical, unless this was a
"smart enum".

Supporting .net5+ `[Uns|S]upportedOSPlatformAttribute` on API requires
a lot of changes. Generated bindings are much easier since the generator
will output the new attributes for dotnet and keep the older ones for
_legacy_.

So moving the enums to generated code means a lot less code to update
for dotnet - and means additional enums (new Xcode) won't have to include
both new and legacy attributes.

The number of manual updates (for iOS) is about 1500 less (5792 down to
4219) than before.

Helps https://github.com/spouliot/xamarin-macios/pull/new/gh10170

2021-02-15 21:07 UTC, dalexsoto approved these changes
yay! ♥️

2021-02-16 07:07 UTC, rolfbjarne requested changes
The important changes here is that structs shouldn't have a different size between COREBUILD and not, because then the generator might generate the wrong code. All the other changes are just cosmetic and not really important.

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		ObstructionAttenuation = 11
```suggestion
		ObstructionAttenuation = 11,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Linear = 3
```suggestion
		Linear = 3,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		InterruptAtLoop        = 0x20
```suggestion
		InterruptAtLoop        = 0x20,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		LayerItem	= 7
```suggestion
		LayerItem	= 7,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		DoNotCheckRenderArgs = (1 << 9)
```suggestion
		DoNotCheckRenderArgs = (1 << 9),
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Rewind				= 3
```suggestion
		Rewind				= 3,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Output = 2
```suggestion
		Output = 2,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Cycling = 8
```suggestion
		Cycling = 8,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		MidiSysEx = 9
```suggestion
		MidiSysEx = 9,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Immediate = unchecked ((long) 0xffffffff00000000)
```suggestion
		Immediate = unchecked ((long) 0xffffffff00000000),
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		InProcess = 2
```suggestion
		InProcess = 2,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		IsWritable = unchecked((uint)1 << 31)
```suggestion
		IsWritable = unchecked((uint)1 << 31),
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Linear = 3
```suggestion
		Linear = 3,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		DistanceAttenuation = (1 << 2)
```suggestion
		DistanceAttenuation = (1 << 2),
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Release = 2
```suggestion
		Release = 2,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		InterruptAtLoop = 32
```suggestion
		InterruptAtLoop = 32,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		LargeHall2 = 12
```suggestion
		LargeHall2 = 12,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		ConstantReverbBlend = (1 << 6)
```suggestion
		ConstantReverbBlend = (1 << 6),
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Linear = 3
```suggestion
		Linear = 3,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		UnauthorizedErrorInit
```suggestion
		UnauthorizedErrorInit,
```

2021-02-16 07:07 UTC, rolfbjarne commented on src/AudioUnit/AUEnums.cs
> +		Output = 2
```suggestion
		Output = 2,
```

2021-02-16 14:01 UTC, spouliot commented on src/CoreGraphics/CGAffineTransform.cs
> +#if !COREBUILD
I had to adjust a few `#if` for compilation issues but I don't recall that one in particular. Will fix...

2021-02-16 15:45 UTC, rolfbjarne approved these changes

2021-02-16 19:44 UTC, tj-devel709 approved these changes

2021-02-16 22:46 UTC, vs-mobiletools-engineering-service2 commented
### :x: Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4472673&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210216.6/4472673/sim/;/tests/vsdrops_index.html)


# Test results

<details>
<summary>1 tests failed, 180 tests passed.</summary>

## Failed tests

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 3.2): Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4472673&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1095'

2021-02-17 00:26 UTC, spouliot commented
Failure is unrelated to PR

introspection/watchOS 32-bits - simulator/Debug (watchOS 3.2): Failed
* https://github.com/xamarin/maccore/issues/2378

2021-02-17 00:27 UTC, merged