[Tests] Fix intro tests on older macOS
xamarin/xamarin-macios pull request #11736
Opened 2021-05-28 18:57 UTC by mandel-macaque

2021-05-28 18:58 UTC, mandel-macaque commented
I have tested all of this on:

* Mojave
* Catalina
* High Sierra
* Big Sur

2021-05-28 19:00 UTC, dalexsoto approved these changes

2021-05-28 19:27 UTC, spouliot requested changes

2021-05-28 19:27 UTC, spouliot commented on tests/introspection/Mac/MacApiSelectorTest.cs
> +						return true;
that's skipping OS <= 10.15
if it pass on older you need a different check, like
```csharp
// Fail on Catalina, pass in older OS	
if (Mac.CheckSystemVersion (10, 14))
	break;
if (Mac.CheckSystemVersion (10, 15)) 
	return true;
// 11.x
break;
```

2021-05-28 19:27 UTC, spouliot commented on tests/introspection/Mac/MacApiProtocolTest.cs
> +				return TestRuntime.IsVM || IntPtr.Size != 8; // skip on vms or 64b
we don't support 32bits for macOS anymore, you can always skip `NSMenuView`

2021-05-28 19:27 UTC, spouliot commented on tests/introspection/Mac/MacApiCtorInitTest.cs
> +					return true;
does it work on earlier macOS ? 
if so see my other comment

2021-05-28 22:59 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4813951&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/a81cf795166d3796f514fd27453911e9)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/d22bce7e9fb3828e54876838f0e7e255)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/978e11d688065810bab3f0cb2c5656a8)
* macCatiOS  [gist](https://gist.github.com/179b633ae3366657738ff22000e81bf8)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/e4fac3defec55b44fbee31c8a2587d56)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/bacd14919452a853e6cbe6685fcbfaeb)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210528.31/4813951/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR11736/4813951/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR11736/4813951/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR11736/4813951/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 80 tests passed.</summary>

## Failed tests

 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4813951&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur
Merge 1907f3dd928c0f38daa21aae21302016917f7a72 into dc30bdf22006b08b945e132ec7e073c9bcef8e3d

2021-05-31 06:46 UTC, rolfbjarne approved these changes

2021-06-01 15:05 UTC, tj-devel709 approved these changes

2021-06-01 18:46 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4821002&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210601.22/4821002/sim/;/tests/vsdrops_index.html)
# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210601.22/4821002/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210601.22/4821002/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR11736/4821002/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR11736/4821002/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR11736/4821002/apicomparison/api-diff.html)


# :tada: All 81 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4821002&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1099.BigSur
Merge f5a6a59735c6e2d2b588f529a67ed708646ff196 into 0864407f78fc4930dcd6353bc03ca227c4fa791d

2021-06-03 14:17 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4830823&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/682de3e692f9341ea90d3c03861314e7)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/03c6f7479f317c987ad0583a1d055f17)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/37882faa7b297cb3b5cc55d13a2ad5a9)
* macCatiOS  [gist](https://gist.github.com/3620a3a616c55ef4bf019828ad52c1e5)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/bd64601aab4fdec468ebf5d1fb83e25d)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/abad692d576662356e09df9cb7e8422f)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.9/4830823/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR11736/4830823/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR11736/4830823/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR11736/4830823/apicomparison/api-diff.html)


# Test results

<details>
<summary>19 tests failed, 62 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 64-bits - simulator/Debug: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): TimedOut
 * fsharp/iOS Unified 64-bits - simulator/Debug: TimedOut
 * framework-test/iOS Unified 64-bits - simulator/Debug: TimedOut
 * xcframework-test/iOS Unified 64-bits - simulator/Debug: TimedOut
 * interdependent-binding-projects/iOS Unified 64-bits - simulator/Debug: TimedOut
 * introspection/iOS Unified 64-bits - simulator/Debug: TimedOut
 * dont link/iOS Unified 64-bits - simulator/Debug: TimedOut
 * dont link/iOS Unified 64-bits - simulator/Release: TimedOut
 * link all/iOS Unified 64-bits - simulator/Debug: TimedOut
 * link all/iOS Unified 64-bits - simulator/Release: TimedOut
 * link sdk/iOS Unified 64-bits - simulator/Debug: TimedOut
 * link sdk/iOS Unified 64-bits - simulator/Release: TimedOut
 * mono-native-compat/iOS Unified 64-bits - simulator/Debug: TimedOut
 * mono-native-compat/iOS Unified Today Extension 64-bits - simulator/Debug: TimedOut
 * mono-native-unified/iOS Unified 64-bits - simulator/Debug: TimedOut
 * mono-native-unified/iOS Unified Today Extension 64-bits - simulator/Debug: TimedOut
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4830823&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1099.BigSur'
Merge ccf90b56eebdf33625466637837d38d731e0337b into 7fb037c878da0965947b6c2b1b6b742a83e7af42

2021-06-03 19:22 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4831450&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/a67d94a5863b32164ea883627053d5ea)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/353eace43fd7c42c5b3d4cee30d599d3)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/b2bbb7f25f33d37fc49c44e22ec2308b)
* macCatiOS  [gist](https://gist.github.com/fb1751cfdd717f5c3fcc1c697e3702fc)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ec520d46a2d1373f3229bd31f1c7f04c)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/fb1086199b6fd56a19ef99ec5f2f2abf)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210603.21/4831450/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR11736/4831450/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR11736/4831450/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR11736/4831450/apicomparison/api-diff.html)


# :tada: All 81 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4831450&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur
Merge e956905b8ba82657fbc4bc5506fb1b1143c7aaf3 into 4e53d83befb434247ad531c1ca4abf62a5672325

2021-06-04 17:17 UTC, spouliot approved these changes

2021-06-04 17:22 UTC, merged