[tools] Fix quoting quotes in StringUtils.QuoteForProcess.
xamarin/xamarin-macios pull request #11949
Opened 2021-06-16 13:31 UTC by rolfbjarne

Previously quoting a string with a quote:

    a"b

would result in:

    "a\"""b"

There are way too many quotes there.

We'll now get:

    "a\"b"

which is correct.

2021-06-16 13:54 UTC, spouliot requested changes
`tests/mtouch/StringUtilsTest.cs` is begging for attention ;-)

2021-06-16 14:03 UTC, dalexsoto approved these changes
After attention is given 😄

2021-06-16 14:25 UTC, tj-devel709 commented on tools/common/StringUtils.cs
>  					s.Append ('\\');
In your example, you used single backslash `\` but it looks like here you are using double backslash. Is this desired?

2021-06-16 14:25 UTC, tj-devel709 approved these changes

2021-06-16 15:21 UTC, mandel-macaque approved these changes

2021-06-16 22:58 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4877317&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/6be07e8d5a1b114bcfa92afb0a891d5d)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/4cb44d1368100e940f00911d66ea4362)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/99274af2cc5658c8ed65ceb01f230b3d)
* macCatiOS  [gist](https://gist.github.com/61f6a6c71ceabd486400cfdd1f7a0738)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/02d7f983a151ccf870c692d6aabfb31f)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/7fbf04713b6a704778c0127d24283da7)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.11/4877317/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR11949/4877317/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR11949/4877317/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR11949/4877317/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 219 tests passed.</summary>

## Failed tests

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 5.0): Failed
 * Generator tests/NUnit: Failed (Execution failed with exit code 1)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4877317&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge 1e134be3574426823bbcd761b1b928a3529db3e0 into c8e854c15190f5894f195c31d74ef7b3758abd16

2021-06-17 15:20 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4881786&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/f7e4ef2e16777e3a5ff7fa13a4fa531a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/4dea6bc0fc52c59e66fae4e57077ec21)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/470715b3127acafccbee3a70f3a3a9b3)
* macCatiOS  [gist](https://gist.github.com/7a9b5a78a507de65d6d9f5c709bbb71f)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/175977e35cc7b64c72e5d50ed72b4fe0)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/e5ca7d6c00b0f7bf84e121d0d98aa459)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210617.16/4881786/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR11949/4881786/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR11949/4881786/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR11949/4881786/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 220 tests passed.</summary>

## Failed tests

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 5.0): Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4881786&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1104.BigSur'
Merge a7d8253cfa4d27703e25aa8c866bbb819ec7e210 into 9278ee16108a59513563e5f27d788b45622d07da

2021-06-17 15:51 UTC, spouliot approved these changes

2021-06-17 16:23 UTC, rolfbjarne commented
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2454).

2021-06-17 16:23 UTC, merged