[CloudKit] Add support for Xcode13 beta1.
xamarin/xamarin-macios pull request #11961
Opened 2021-06-16 19:14 UTC by mandel-macaque

2021-06-16 19:14 UTC, mandel-macaque commented on tests/xtro-sharpie/common-CloudKit.ignore
> +!missing-selector! CKRecord::encryptedValues not bound
Not to be added due to the same reason, also intro says the type cannot be loaded.

2021-06-16 19:19 UTC, mandel-macaque commented on src/CloudKit/Enums.cs
> +		[Mac(12,0), iOS(15,0), TV(15,0), MacCatalyst(15,0)]
```suggestion
		[Mac (12,0), iOS (15,0), TV (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:20 UTC, mandel-macaque commented on src/CloudKit/Enums.cs
> +		[Mac(12,0), iOS(15,0), TV(15,0), MacCatalyst (15,0)]
```suggestion
		[Mac (12,0), iOS (15,0), TV (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:20 UTC, mandel-macaque commented on src/CloudKit/Enums.cs
> +		[Mac(12,0), iOS(15,0), TV(15,0)]
```suggestion
		[Mac (12,0), iOS (15,0), TV (15,0)]
```

2021-06-16 19:20 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:21 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:21 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:21 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0)]
```suggestion
	[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0), MacCatalyst (15,0)]
```

2021-06-16 19:22 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:22 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:22 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:22 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:23 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:23 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:23 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:23 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:23 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:24 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:24 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:24 UTC, spouliot requested changes

2021-06-16 19:24 UTC, spouliot commented on src/CloudKit/Enums.cs
> +		[Mac(12,0), iOS(15,0), TV(15,0), MacCatalyst(15,0)]
minor: space before `(`

but that looks like an error enum... and those, being output only, do not need availability

2021-06-16 19:24 UTC, spouliot commented on src/CloudKit/Enums.cs
> +		[Mac(12,0), iOS(15,0), TV(15,0), MacCatalyst (15,0)]
not needed

2021-06-16 19:24 UTC, spouliot commented on src/CloudKit/Enums.cs
> +		[Mac(12,0), iOS(15,0), TV(15,0)]
minor: space before `(`

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
minor: space before `(`

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
minor: space before `(`

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +	[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0)]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
missing space before `(`

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
missing space before `(1

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
missing space before `(`

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
missing space before `(`

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use 'RecordMatchedHandler' instead.")]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
missing space before `(`

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
do a find and replace :)

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +	[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0)]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use 'PerShareParticipantCompletionHandler' instead.")]
catalyst ?

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0), MacCatalyst(15,0)]
f&r

2021-06-16 19:24 UTC, spouliot commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
f&r

2021-06-16 19:24 UTC, spouliot commented on tests/xtro-sharpie/common-CloudKit.ignore
> +!missing-selector! CKRecord::encryptedValues not bound
is the comment above applicable here ?

2021-06-16 19:24 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:24 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:24 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:24 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:24 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:25 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
	[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:25 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:25 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:25 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:25 UTC, mandel-macaque commented on src/cloudkit.cs
> +	[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0)]
```suggestion
	[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0), MacCatalyst (15,0)]
```

2021-06-16 19:26 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0), MacCatalyst(15,0)]
```suggestion
		[iOS (15,0), Watch (8,0), TV (15,0), Mac (12,0), MacCatalyst (15,0)]
```

2021-06-16 19:26 UTC, mandel-macaque commented on src/cloudkit.cs
> +		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst(15,0)]
```suggestion
		[Watch (8,0), TV (15,0), Mac (12,0), iOS (15,0), MacCatalyst (15,0)]
```

2021-06-16 19:29 UTC, mandel-macaque commented on tests/xtro-sharpie/common-CloudKit.ignore
> +!missing-selector! CKRecord::encryptedValues not bound
yes, same issue.

2021-06-16 23:55 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4879080&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/52bac9baab893dc7e54ac246fbd1eed1)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/b51b3052c335720c0398e033331c9c26)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/8225458294e79f569af24a18da9cf324)
* macCatiOS  [gist](https://gist.github.com/4273798af2a38c2927cbb86d30fde6ef)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/c2b1e6e2642acf991234aef597a2d053)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c0a41095980f0d776487a4085dbaf87b)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210616.32/4879080/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR11961/4879080/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR11961/4879080/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR11961/4879080/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 85 tests passed.</summary>

## Failed tests

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 5.0): Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4879080&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1097.BigSur'
Merge 8ea5c6257a160ebc9c01296b5f356214fd512875 into e19591f47b27f34881b94402d66cc6b69a142877

2021-06-17 00:16 UTC, spouliot approved these changes

2021-06-17 01:26 UTC, merged