[Accounts] Update bindings for Xcode 13.0 beta 1
xamarin/xamarin-macios pull request #12024
Opened 2021-06-25 21:10 UTC by rachelkang

WIP - need to figure out why Catalyst tests are failing

2021-06-25 21:38 UTC, tj-devel709 commented
Does this framework have a MacCatalyst todo file?

2021-06-25 21:43 UTC, rachelkang commented
> Does this framework have a MacCatalyst todo file?

@tj-devel709 nope! Based on what I saw on web docs and my chat with @rolfbjarne, I thought I had to add [NoMacCatalyst] to these APIs as well, but I removed them because that caused xtro errors

2021-06-26 01:03 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4916273&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/bf6696c86a22032465f60fc70a7b0cbe)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/362a8989925bd7ae428984624ca497d4)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/a8a1cefd9396c174f9fc7c9125f944bd)
* macCatiOS  [gist](https://gist.github.com/225b5f9c5150a44dc5ab7e89093c429f)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/87ba99bd583657332e4e9d0ed7add2f1)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/84285dc014dcbddc19d2bf9d4cddff30)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/apigeneratordiff/;//api-diff.html) (no change)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210625.22/4916273/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12024/4916273/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12024/4916273/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12024/4916273/apicomparison/api-diff.html)


# :tada: All 86 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4916273&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge 9bb53a38dbde71262b341b86b15685d80708ea06 into b1e8b29fd665528ef7036fb9c48eb93cdad49821

2021-06-28 12:13 UTC, rolfbjarne approved these changes

2021-06-28 16:15 UTC, mandel-macaque approved these changes

2021-06-28 17:04 UTC, tj-devel709 approved these changes

2021-06-28 20:02 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4921300&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210628.14/4921300/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210628.14/4921300/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/04b5435817508edce2403876ceb3a798)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210628.14/4921300/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/ac227e03ec5d82b5716031d8777cf41b)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210628.14/4921300/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/02ccf94208e9bfd7af3a46513d67a102)
* macCatiOS  [gist](https://gist.github.com/c30d6943ac0934e3b190d72da98e6e3d)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210628.14/4921300/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/325e8be45fa230fd4ee299c97f3bee5b)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210628.14/4921300/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c7b90ccfaab9719533f753775d016643)
</details>

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12024/4921300/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12024/4921300/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12024/4921300/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 85 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4921300&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1104.BigSur'
Merge 888544e48b91b7215878bb0bab70bfad5bd77fc7 into 32402490b64aeb5e04f118ff68f4c22d2d17efb4

2021-06-29 14:20 UTC, mandel-macaque commented
Test failure is unrelated. I updated it again main since it is using Xcode13 beta2, everything should pass.

2021-06-29 19:19 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4925855&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/ed97d614929b5fc28e7ce576b219d050)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/393ff15ab1573a48b36c61ed42f5f352)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/892c8b9e965e9080c0e2b97001bb32b4)
* macCatiOS  [gist](https://gist.github.com/2c59a820351efe7eab60c54d5fcdacf6)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/1ef87b3acf4f53667c8d93b36d884c64)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/27fc8efa285ea3afc33c5c13d7dea077)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/apigeneratordiff/;//api-diff.html) (no change)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210629.11/4925855/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12024/4925855/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12024/4925855/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12024/4925855/apicomparison/api-diff.html)


# :tada: All 86 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4925855&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge adf56cc45b577d60c2074658b469d08b164de6ca into ebf6c13bd1e419c20112a4702c10876b21c0ba75

2021-06-29 21:03 UTC, dalexsoto requested changes
Some comments here :)

2021-06-29 21:03 UTC, dalexsoto commented on src/accounts.cs
> +	[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
Same

```suggestion
	[Deprecated (PlatformName.iOS, 15, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
	[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
```

2021-06-29 21:03 UTC, dalexsoto commented on src/accounts.cs
> +	[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
```suggestion
	[Deprecated (PlatformName.iOS, 15, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
	[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
```

2021-06-29 21:03 UTC, dalexsoto commented on src/social.cs
> +		[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
Same

```suggestion
		[Deprecated (PlatformName.iOS, 15, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
		[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
```

2021-06-29 21:03 UTC, dalexsoto commented on src/twitter.cs
> +		[Deprecated (PlatformName.MacOSX, 12, 0, message: "Use the non-Apple SDK relating to your account type instead.")]
Not needed, the parent class is already deprecated.

```suggestion
```

2021-06-30 15:19 UTC, vs-mobiletools-engineering-service2 commented
### :fire: Tests failed catastrophically on Build (no summary found). :fire:

Result file $(TEST_SUMMARY_PATH) not found. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4931093&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210630.12/4931093/sim/;/tests/vsdrops_index.html)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4931093&view=ms.vss-test-web.test-result-details) on Agent 
Merge d5a293a7042d2b67594a539b647c1d65d3fab78c into 801063d7bfb5e366c96994ab7dd586306daafe0a

2021-06-30 17:56 UTC, rachelkang commented
intro and xtro are all passing!

2021-06-30 18:00 UTC, rachelkang commented
not sure why build is failing

2021-07-06 16:16 UTC, tj-devel709 commented
/azp run

2021-07-06 21:40 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4948756&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/0f62d8feda104c99232fb18a09c51c30)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/daacc1be9b25a4a956966479d7d38d04)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/4ed12684b46798fdd7a4fe0e5dc974dd)
* macCatiOS  [gist](https://gist.github.com/18fedeb4927dea54510357f39c1ccf23)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/144d992c1dc4ac24dc1cecdd95fe4838)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/83d0da21763f6f354676ed7b6b557133)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/apigeneratordiff/;//api-diff.html) (no change)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210706.6/4948756/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12024/4948756/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12024/4948756/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12024/4948756/apicomparison/api-diff.html)


# :tada: All 86 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4948756&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge fcf16bf09c45d30780f7edd2c80018a2c05c57e1 into 3b6f059863e2435422769cbe2fa11c41cd095ff8

2021-07-07 21:26 UTC, merged