[Generator] Do not throw a NRE but an error for badly formed platform strings.
xamarin/xamarin-macios pull request #12089
Opened 2021-07-08 18:22 UTC by mandel-macaque

If a user did:
```csharp
  [SupportedOSPlatform ("maccatalyst)]
   int Foo { get; }
```
We would get the following:
```
error BI0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.NullReferenceException: Object reference not set to an instance of an object.
   at AttributeManager.ConvertOldAttributes(CustomAttributeData attribute) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/generator-attribute-manager.cs:line 298
   at AttributeManager.CreateAttributeInstance[T](CustomAttributeData attribute, ICustomAttributeProvider provider) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/generator-attribute-manager.cs:line 354
   at AttributeManager.FilterAttributes[T](IList`1 attributes, ICustomAttributeProvider provider) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/generator-attribute-manager.cs:line 453
   at AttributeManager.GetCustomAttributes[T](ICustomAttributeProvider provider) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/generator-attribute-manager.cs:line 468
   at ReflectionExtensions.IsUnavailable(ICustomAttributeProvider provider, Generator generator) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/generator.cs:line 96
   at Generator.SkipGenerationOfType(Type t) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/generator.cs:line 2216
   at Generator.Go() in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/generator.cs:line 2337
   at BindingTouch.Main3(String[] args) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/btouch.cs:line 542
   at BindingTouch.Main2(String[] args) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/btouch.cs:line 196
   at BindingTouch.Main(String[] args) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/btouch.cs:line 88
   at System.Environment.get_StackTrace() in System.Private.CoreLib.dll:token 0x6000333+0x0
   at ErrorHelper.ShowInternal(Exception e) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/error.cs:line 175
   at ErrorHelper.Show(Exception e, Boolean rethrow_errors) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/error.cs:line 125
   at BindingTouch.Main(String[] args) in /Users/mandel/Xamarin/xamarin-macios/main/xamarin-macios/src/btouch.cs:line 88
make[1]: *** [build/dotnet/maccatalyst/maccatalyst-generated-sources] Error 1
``

Instead we will get a biding error telling the user he forgot the os version number.

2021-07-08 22:21 UTC, tj-devel709 approved these changes

2021-07-08 22:48 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4958522&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/a0a7249807fc4cb54e20fffdaef1d8a4)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/391ce463108ec930d444e1db4cd27c3b)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/cca3b8f310ef0f36835c303eb6c1414c)
* macCatiOS  [gist](https://gist.github.com/ff7b39b77752fe3618f4fcde4ce45c9f)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/71a4e972aaf26bfb06bb2f079517f19b)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/1fd61644400dc4acb0456b6e09fdd288)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210708.9/4958522/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12089/4958522/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12089/4958522/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12089/4958522/apicomparison/api-diff.html)


# :tada: All 88 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4958522&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge 2eff9823aa1fa1ef52525daf90c60febf2b9d6bf into 956828f0c41afca6a4a73c7459514c3acbebbc1d

2021-07-12 13:48 UTC, rolfbjarne requested changes
A test would be nice!

Somewhere in this class: https://github.com/xamarin/xamarin-macios/blob/2eff9823aa1fa1ef52525daf90c60febf2b9d6bf/tests/generator/ErrorTests.cs#L11

2021-07-12 13:48 UTC, rolfbjarne commented on docs/website/generator-errors.md
> +### <a name='BI1120'/>BI1120: Unsupported platform string: *. Platform strings should contain the version of the platform supported. Examples are: maccatalyst15.0, mac10.9, ios8.0, tvos15.0
I think this should go below the next paragraph ("If the property is inlined ..."), because otherwise that paragraph will be out of place.

2021-07-14 15:56 UTC, rolfbjarne approved these changes

2021-07-14 19:55 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4978204&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/32ba0d29b82084046e440addb42be041)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/7b59be3174b31686dd0a51bc5fc11dfb)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/4a68b16fd2c055100d7ce5aec2c97c5a)
* macCatiOS  [gist](https://gist.github.com/e0d4182b08f589c9da48ed5604d44180)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/544309e75962102c44091e450939aab8)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/59f5f344fa4bd67a311dda793c583574)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/apigeneratordiff/;//api-diff.html) (no change)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210714.9/4978204/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12089/4978204/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12089/4978204/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12089/4978204/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 86 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2626 Passed: 2490 Inconclusive: 35 Failed: 1 Ignored: 135)
 * Generator tests/.NET: Failed (Execution failed with exit code 1)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4978204&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge f39750d5dead518322f584b6233593c0020fd329 into e0e0a716c9ad66ab02bf3638cea568239e4bbdf3

2021-07-20 13:06 UTC, spouliot requested changes
It's legit to have `[SupportedOSPlatform ("maccatalyst")]` without a version...

Now it makes no sense for _our_ bindings (at least the generated ones), however it might be useful for 3rd party bindings. E.g.

API `X` is only available on iOS - but it not related to a specific version (like something related to the cellular availability). The 3rd-party binding might want to have `[SupportedOSPlatform ("ios")]` on that binding (and `UnsupportedOSPlatform` on other platforms).

I think it's better to fix the generator to support them... even if it means we might have to add (later) an introspection test to spot them inside the platform assemblies.

2022-01-22 03:06 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests didn't execute on Build. :x:

Tests didn't execute on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5658148&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220122.6/5658148/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5658148/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
* :warning: API diff urls have not been provided.
* :warning: API Current PR diff urls have not been provided.
* :warning: Generator diff comments have not been provided.
# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12089/5658148/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12089/5658148/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12089/5658148/apicomparison/api-diff.html)


No test summary was found (something probably failed before the tests could execute)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5658148&view=ms.vss-test-web.test-result-details) on Agent 
Merge ff53e362e0b7d57580cfe78768c7fb08e27dca46 into d0519351e85d529c88966f48852a58fd4cbee757

2024-05-06 15:14 UTC, closed without merging