[IOSurface] Updates for Xcode13 Beta 1
xamarin/xamarin-macios pull request #12096
Opened 2021-07-09 22:17 UTC by tj-devel709

I don't feel too confident with this one.
I added the missing p-invokes to the ignore since they are ignored in other platforms.

I added the two fields. They say they are supported in older versions and the iOS 11.4 intro test did not complain about them, but a good amount of other IOSurface* fields are in the common ignore and I am not sure why.

2021-07-10 02:30 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4963991&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/d2b7c6f2ddf2395886b384568e9c4c8b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/014029123eb7fdd3e76f709751b2acb9)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/bc6fc8732a35038c9c28f39f4bd065f5)
* macCatiOS  [gist](https://gist.github.com/6a3bc99a3ef3ff2670f303c08e2f87a2)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ee7e3a33fb705329dff18461ef897775)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/9fef6317608fab0b4dd787e2b7292950)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210709.16/4963991/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12096/4963991/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12096/4963991/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12096/4963991/apicomparison/api-diff.html)


# :tada: All 86 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4963991&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge cfcb958e13aa951e8ceb10f8af737b1fb2002066 into 797a2f57d349f97f887dc35686359e0e5d429196

2021-07-12 13:46 UTC, mandel-macaque requested changes

2021-07-12 13:46 UTC, mandel-macaque commented on src/iosurface.cs
> +		NSString kIOSurfaceColorSpace { get; }
kIOSurfaceColorSpace is not correct. Those are global in objc and that is why they add the framework name and also that k which stands for key.

2021-07-12 13:46 UTC, mandel-macaque commented on src/iosurface.cs
> +		NSString kIOSurfaceICCProfile { get; }
Same.

2021-07-12 14:37 UTC, rolfbjarne requested changes
Just add the two new fields and P/Invokes to the common ignore file, there are a lot of other API that we haven't bound in this framework, and which we'll probably have to bind first for any of these to make sense.

2021-07-12 17:58 UTC, rolfbjarne approved these changes

2021-07-12 22:30 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4969108&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/df535a27fda6b9ea5cdc1b381a1aacf3)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/8db2f045150a10feb5a2695fe4700a88)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/5508815774946264c7260321decbfa92)
* macCatiOS  [gist](https://gist.github.com/3269e3af395a44094b00cce426b5b5bd)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/1710ac95a286990ef7809a497750752a)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/32e6fd683f102fb6b75ce9b1661cf584)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210712.13/4969108/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12096/4969108/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12096/4969108/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12096/4969108/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 84 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2625 Passed: 2489 Inconclusive: 35 Failed: 1 Ignored: 135)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4969108&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1096.BigSur'
Merge 3648b2ef2a3abebd8d61bd3c0cd77f7e495b54a9 into 26a8abe76ecd85e06bdffcc289fc9b74f8acef4e

2021-07-13 17:08 UTC, tj-devel709 commented
Unrelated Test Failure: https://github.com/xamarin/maccore/issues/2443

2021-07-13 17:46 UTC, mandel-macaque approved these changes

2021-07-13 17:57 UTC, merged