[CHIP] Add support fox Xcode 13 beta 3.
xamarin/xamarin-macios pull request #12143
Opened 2021-07-19 21:54 UTC by mandel-macaque

2021-07-20 01:43 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4995640&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/fb3adbb8a033051004652c24974ebf1c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/0ee4bb46586fcaf12861bb172df021aa)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/131963153571daa8a2156f8ca0cad94d)
* macCatiOS  [gist](https://gist.github.com/ac55945788661010b05adba303122695)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/747c722ed42fae1b43893c9a7cb7f2c4)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/0f308d8c6f968d7394770d5e9dac6e48)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210719.23/4995640/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12143/4995640/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12143/4995640/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12143/4995640/apicomparison/api-diff.html)


# :tada: All 86 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4995640&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur'
Merge 1675dd5bf359b8831d4262fe954d8737b10cce3b into e968a932827a8fcba3a617e43c837203fa12de6f

2021-07-20 06:15 UTC, rolfbjarne approved these changes

2021-07-20 12:39 UTC, spouliot requested changes

2021-07-20 12:39 UTC, spouliot commented on src/chip.cs
> +		void OpCSRRequest (NSData cSRNonce, ChipResponseHandler responseHandler);
`OpCsrRequest` -> `Csr` -> TLA

2021-07-20 12:39 UTC, spouliot commented on src/chip.cs
> +		void Login (string tempAccountIdentifier, string setupPIN, ChipResponseHandler  responseHandler);
-> `setupPin`

2021-07-20 12:39 UTC, spouliot commented on src/chip.cs
> +		void OpCSRRequest (NSData cSRNonce, ChipResponseHandler responseHandler);
parameter name should be `csrNonce` too

2021-07-20 14:21 UTC, spouliot commented on src/chip.cs
> +		void OpCsRrequest (NSData csrNonce, ChipResponseHandler responseHandler);
wrong `r`
`OpCsRrequest` -> `OpCsrRequest`

2021-07-20 14:52 UTC, rachelkang reviewed
The diff shows that the NSError param in the CHIPDevicePairingDelegate methods onPairingComplete, onPairingDeleted, and onAddressUpdated are now nullable. Should there be a [NullAllowed] attribute added to those?

Similarly, should CHIPGetKeyValue be decorated with a [NullAllowed] attribute as well?

2021-07-20 15:07 UTC, rachelkang commented on src/chip.cs
> +		void WindowCoveringUpOpen (ChipResponseHandler responseHandler);
I think you can (maybe?) get rid of the `WindowCovering` prefix on all of the above

2021-07-20 17:26 UTC, mandel-macaque commented on src/chip.cs
> +		void OpCsRrequest (NSData csrNonce, ChipResponseHandler responseHandler);
```suggestion
		void OpCsrRequest (NSData csrNonce, ChipResponseHandler responseHandler);
```

2021-07-20 17:33 UTC, spouliot approved these changes
nice catches @rachelkang !

2021-07-20 18:27 UTC, vs-mobiletools-engineering-service2 commented
### :fire: Tests failed catastrophically on Build (no summary found). :fire:

Result file $(TEST_SUMMARY_PATH) not found. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4998881&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.34/4998881/sim/;/tests/vsdrops_index.html)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4998881&view=ms.vss-test-web.test-result-details) on Agent 
Merge 72c1e08cee2ac0e2beb0a5bfb131d65137536e2b into 09f911b504ec9b803eb6d725cca14cc7d3ed986e

2021-07-20 22:04 UTC, tj-devel709 commented on src/chip.cs
> +
small: extra newline

2021-07-20 22:05 UTC, tj-devel709 commented on src/chip.cs
> +		void Login (string tempAccountIdentifier, string setupPin, ChipResponseHandler  responseHandler);
```suggestion
		void Login (string tempAccountIdentifier, string setupPin, ChipResponseHandler responseHandler);
```
small: extra space here and next selector

2021-07-20 22:06 UTC, tj-devel709 commented on src/chip.cs
> +		void ReadAttributeClusterRevision (ChipResponseHandler  responseHandler);
```suggestion
		void ReadAttributeClusterRevision (ChipResponseHandler responseHandler);
```

2021-07-20 22:10 UTC, tj-devel709 approved these changes

2021-07-21 00:55 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4999892&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/10c178b32ba17c61563fb64b1e6922f1)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/56fd2155f35a29036f72bbc8030473bb)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/9d55addd8488e7def528932395149e2b)
* macCatiOS  [gist](https://gist.github.com/eda6d12e76bbae2b65638073f6d67ba0)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/c0e7986c55ccaaf08861a27c9587e3b5)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/72094808eaea755daac9aab02e030287)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210720.48/4999892/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12143/4999892/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12143/4999892/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12143/4999892/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 85 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2494 Inconclusive: 35 Failed: 1 Ignored: 134)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=4999892&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge a06f5c2c75e62ab8c7f8276a335c82e5870f1405 into eea8142e6ba6a8c63f0fb1cc5493e1e0d923d24a

2021-07-21 17:04 UTC, mandel-macaque commented on src/chip.cs
> +
```suggestion

```

2021-07-21 17:04 UTC, merged

2021-07-22 08:43 UTC, rolfbjarne commented
/sudo backport release/6.0.1xx-preview7

2021-07-22 08:43 UTC, vs-mobiletools-engineering-service2 commented
Backport Job to branch **release/6.0.1xx-preview7** Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=)

2021-07-22 08:44 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5007513 for more details.