[HealthKit] Add support for xcode13 beta3.
xamarin/xamarin-macios pull request #12184
Opened 2021-07-22 20:20 UTC by mandel-macaque

2021-07-22 20:25 UTC, spouliot commented on src/healthkit.cs
> +		NSData JWSRepresentation { get; }
-> `Jws`

2021-07-22 20:25 UTC, spouliot commented on src/healthkit.cs
> +		[Field ("HKMetadataKeyDateOfEarliestDataUsedForEstimate")]
suspect prefix ;-)

2021-07-22 20:54 UTC, rolfbjarne requested changes

2021-07-22 20:54 UTC, rolfbjarne commented on src/HealthKit/HKAppleWalkingSteadiness.cs
> +			=> Runtime.GetNSObject<HKQuantity> (HKAppleWalkingSteadinessMinimumQuantityForClassification ((nint) (long) classification), true);
According to the name of the P/Invoke, you do not own the return value (so `owns:false` instead of `owns:true`).

2021-07-22 20:54 UTC, rolfbjarne commented on src/HealthKit/HKAppleWalkingSteadiness.cs
> +			=> Runtime.GetNSObject<HKQuantity> (HKAppleWalkingSteadinessMaximumQuantityForClassification ((nint) (long) classification), true);
Same wrt return value.

2021-07-22 21:51 UTC, tj-devel709 commented on src/healthkit.cs
> +
```suggestion
```
small, extra line

2021-07-22 21:53 UTC, tj-devel709 approved these changes

2021-07-23 01:14 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5009936&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/146b245e83529c5f6fda9027f63b57f0)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/343c2e5b5b06f98e57554e0b4808e979)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/37ecf970d588c004e007c99f7c76f9a5)
* macCatiOS  [gist](https://gist.github.com/31f1c5c0a3c9bd9f1d84516e805adeff)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/7d54247df46598b3b276743ac39e8e26)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/58455fdb2b6b40d530e867291fcf49d2)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210722.41/5009936/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12184/5009936/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12184/5009936/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12184/5009936/apicomparison/api-diff.html)


# Test results

<details>
<summary>7 tests failed, 82 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2491 Inconclusive: 35 Failed: 2 Ignored: 136)
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): TimedOut
 * link sdk/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 129 Passed: 105 Inconclusive: 6 Failed: 1 Ignored: 23)
 * Xtro/Mac: Failed (Test run failed.)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5009936&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge da24cab528c41c6f54edb64736c22464f8b1aa5d into 7dd7960f57ed5d7c4fbcd2617cae07a523e00211

2021-07-23 16:21 UTC, rolfbjarne approved these changes

2021-07-23 20:20 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5013118&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/12d45d44e2bb487487d886833947946c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/c8444ee05988f966369158bdbfc30105)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/fa1979e2858c239fcaf28a6914177531)
* macCatiOS  [gist](https://gist.github.com/f4e7606e67915de87464e0c68b52cc8d)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/baccc8db8ee59bef7fb1a55662ccb939)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/e4342e10b6605b5e6c4a1a0ddf62989b)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.34/5013118/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12184/5013118/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12184/5013118/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12184/5013118/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 87 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2486 Inconclusive: 35 Failed: 2 Ignored: 141)
 * Xtro/Mac: Failed (Test run failed.)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5013118&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1107.BigSur'
Merge 7d79213ffcce796255f0bffe425b56e74fd96729 into de862502ae5ec14dd043d97458d1d3ded1e69b1d

2021-07-27 14:41 UTC, mandel-macaque commented
/azp run

2021-07-27 19:13 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5025050&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/759cc3e5f2c4d5fcc00634f2c8ef9280)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/24330e9006f722e9f5ba998bb13abb9b)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/8e5c2786677f5d298773efa2d7318cad)
* macCatiOS  [gist](https://gist.github.com/ab8980211e0cb200e3c9966958e8a3b4)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/222a37efac3b5316dbc0b0a1b6e4c55f)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/070a355102efd256dc5b4b893e9f9776)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.37/5025050/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12184/5025050/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12184/5025050/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12184/5025050/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 88 tests passed.</summary>

## Failed tests

 * introspection/watchOS 32-bits - simulator/Debug: Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5025050&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1103.BigSur'
Merge 915f8e668f610839294f17ccdb5fa1b90db39867 into 2900ccb1738b756630df72a2398c772be6e06e69

2021-07-27 23:56 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5026597&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/4036633ff302d7267afc8abdc5a65919)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/21e7decdf512f3825a89f09d67df7522)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/80310bdeebded756500d7a84e6b98fdc)
* macCatiOS  [gist](https://gist.github.com/2545b0bff395eb17988406a59970fe32)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/013a91a21acc12019535d519bd46d02f)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/9e273caa8b50d0b93d3180f450305355)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.64/5026597/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12184/5026597/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12184/5026597/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12184/5026597/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 87 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2488 Inconclusive: 35 Failed: 1 Ignored: 140)
 * Xtro/Mac: Failed (Test run failed.)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5026597&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1103.BigSur'
Merge dcbbdf3c86f8ac7f5e70f3e4fa95c80ef7c6ad80 into f611cd8caec8842039fd691c27b6cd0acd5bc026

2021-07-29 02:29 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5032401&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/cf85cf6e141745cd8ea70d0e1163f137)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/c5bd4a2ff47f6ee318cd77c2b39cc125)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/41c5909e5fbda21da4e691d729f75743)
* macCatiOS  [gist](https://gist.github.com/afb78e2a9099e17cafabeff50cc6e2f4)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ac2fe6708e2ca0e4a6eae4d11f2e2f9f)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/34a509887fa3d2c4ddce2fd70d302ca0)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210728.51/5032401/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12184/5032401/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12184/5032401/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12184/5032401/apicomparison/api-diff.html)


# Test results

<details>
<summary>4 tests failed, 85 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2460 Passed: 2398 Inconclusive: 10 Failed: 1 Ignored: 61)
 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2490 Inconclusive: 35 Failed: 1 Ignored: 138)
 * link all/Mac Catalyst/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * dont link/Mac Catalyst/Debug: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5032401&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge 670683bfa20168b92e874d5069029de1771a6d2a into 38140f2cceda7a1c4a9cbeb18e3623d93cbe3d45

2021-07-29 15:11 UTC, mandel-macaque commented
Unrelated failures: https://github.com/xamarin/maccore/issues/2481 and

2021-07-29 15:11 UTC, merged

2021-07-29 16:42 UTC, rolfbjarne commented
/sudo backport release/6.0.1xx-preview7

2021-07-29 16:43 UTC, vs-mobiletools-engineering-service2 commented
Backport Job to branch **release/6.0.1xx-preview7** Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=)

2021-07-29 16:44 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5035959 for more details.