[generator] Skip protocols that aren't available on the current platform.
xamarin/xamarin-macios pull request #12208
Opened 2021-07-23 19:00 UTC by rolfbjarne

That way we can do this in api definitions:

    [BaseType (typeof (NSObject))]
    interface MyType : MyProtocol { }

    [Protocol]
    [NoMacCatalyst]
    interface MyProtocol {}

instead of this:

    [BaseType (typeof (NSObject))]
    interface MyType
    #if __MACOS__
        : MyProtocol
    #endif
    {
    }

    [Protocol]
    [NoMacCatalyst]
    interface MyProtocol {}

for a type that implements a protocol on macOS, but not on Mac Catalyst.

2021-07-23 19:12 UTC, spouliot requested changes
looks good but should come with a unit test

2021-07-24 00:24 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5014272&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/c96114bee9b71e6ad0090e3632588f23)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/4df814e9e6cddaf145ac60e21083e056)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/bf2fb06cc39a2059e2001be7175b4b49)
* macCatiOS  [gist](https://gist.github.com/9892801ecaedc5600dfb491e988be1be)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/1ee7857c62c6869af79fd44445b71911)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/b7baedd0111f1b6771bf52a916b1da82)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210723.48/5014272/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12208/5014272/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12208/5014272/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12208/5014272/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 89 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2486 Inconclusive: 35 Failed: 2 Ignored: 141)
 * link all/Mac Catalyst/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5014272&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1106.BigSur'
Merge 979c52c257596ad8f9e17e1fc257f9d1bf213ed8 into 24acd2da840a7c5a3cfa5d7b2e463c4fd9d2e212

2021-07-26 14:11 UTC, mandel-macaque approved these changes
Looks good, I do agree about the test.

2021-07-26 18:27 UTC, dalexsoto approved these changes
+3 on the test :P

2021-07-27 18:44 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5025064&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/42c393852d0075c9bb97a5b73043037b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/2f67bb649d0e156972c583ea46cb4c43)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/182227e14165c1e9322c52098663b400)
* macCatiOS  [gist](https://gist.github.com/774c2f4cd0893aa3c41fc6f62c743768)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/35faf9c0beacf195bbcec089bb7715e0)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/79947b6bbbdd1c16017b6861149b3cc5)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.38/5025064/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12208/5025064/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12208/5025064/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12208/5025064/apicomparison/api-diff.html)


# :tada: All 91 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5025064&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1105.BigSur'
Merge 3c68a3224eaf850440c8a173e749394b0df95568 into 2900ccb1738b756630df72a2398c772be6e06e69

2021-07-27 20:20 UTC, spouliot approved these changes

2021-07-28 07:35 UTC, merged