[dotnet] Make it clearer that the linker is off by default for Mac Catalyst (like it already is for macOS).
xamarin/xamarin-macios pull request #12242
Opened 2021-07-27 10:33 UTC by rolfbjarne

There's no real change here, the code did exactly this in before, but it was a
side effect of '_SdkIsSimulator' being 'true' for Mac Catalyst, which isn't
obvious. Now the logic is explicit for all platforms.

2021-07-27 13:14 UTC, spouliot requested changes

2021-07-27 13:14 UTC, spouliot commented on dotnet/targets/Xamarin.Shared.Sdk.targets
> +			<_DefaultLinkMode Condition="'$(_PlatformName)' != 'macOS' And '$(_PlatformName)' == 'MacCatalyst' Abd '$(_SdkIsSimulator)' != 'true'">SdkOnly</_DefaultLinkMode> <!-- Linking is SdkOnly for iOS/tv
`Adb` won't work :)

2021-07-27 13:14 UTC, spouliot commented on dotnet/targets/Xamarin.Shared.Sdk.targets
> +			<_DefaultLinkMode Condition="'$(_PlatformName)' != 'macOS' And '$(_PlatformName)' == 'MacCatalyst' Abd '$(_SdkIsSimulator)' != 'true'">SdkOnly</_DefaultLinkMode> <!-- Linking is SdkOnly for iOS/tv
should not it be `'$(_PlatformName)' != 'MacCatalyst'`
since it's for everything but Mac* ?

2021-07-27 13:16 UTC, spouliot commented
I'm not sure if that not-linking default is still the right choice considering that AOT is required (at least on ARM targets) and the build will become very long...

App size will also be quite larger, but that's likely not an issue (and it can be changed to linking if/when it becomes one)

2021-07-27 13:47 UTC, rolfbjarne commented
> I'm not sure if that not-linking default is still the right choice considering that AOT is required (at least on ARM targets) and the build will become very long...

The interpreter still works, and that's the default (it still requires AOT-compiling System.Private.CoreLib.dll, but that's it).

2021-07-27 13:50 UTC, spouliot commented
> > I'm not sure if that not-linking default is still the right choice considering that AOT is required (at least on ARM targets) and the build will become very long...
> 
> The interpreter still works, and that's the default (it still requires AOT-compiling System.Private.CoreLib.dll, but that's it).

That (interpreter) make sense for debug builds but I was thinking about release builds

2021-07-27 14:43 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5024628&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/233e11900d55c18acfef8d839f4613af)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/83b8a821194d34351350afa31ffcb167)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/9790b93da5f2a7fcc8f0c9f8829d3954)
* macCatiOS  [gist](https://gist.github.com/a8caaff32a131c1716afd4280b5bf8ed)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/feb9dc4b17caf3ef3b8da0292b23ea87)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/9719a115bf556e2ee59de6d6e4a031a6)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.19/5024628/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12242/5024628/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12242/5024628/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12242/5024628/apicomparison/api-diff.html)


# Test results

<details>
<summary>34 tests failed, 81 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: HarnessException (Harness exception for 'monotouch-test': System.ArgumentException: '', hexadecimal value 0x1D, is an invalid character.
  at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar (System.Int32 ch, System.Char* pDst, System.Boolean entitize) [0x00026] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1420 
  at System.Xml.XmlEncodedRawTextWriter.WriteCDataSection (System.String text) [0x00251] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1370 
  at System.Xml.XmlEncodedRawTextWriter.WriteCData (System.String text) [0x0012a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:470 
  at System.Xml.XmlEncodedRawTextWriterIndent.WriteCData (System.String text) [0x00007] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1750 
  at System.Xml.XmlWellFormedWriter.WriteCData (System.String text) [0x00029] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:771 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.TestReportGenerator.WriteFailure (System.Xml.XmlWriter writer, System.String message, System.IO.TextReader stderr) [0x00031] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/TestReportGenerator.cs:41 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.NUnitV3TestReportGenerator.GenerateFailure (System.Xml.XmlWriter writer, System.String title, System.String message, System.IO.TextReader stderr) [0x0030e] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/NUnitV3TestReportGenerator.cs:122 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailureXml (System.String destination, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00033] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:226 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x000a4] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:248 
  at Xharness.Jenkins.TestTasks.RunTest.BuildAsync () [0x00274] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:74 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x000d8] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:99 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:283 )
 * monotouch-test/Mac [dotnet]/Debug (CoreCLR) [dotnet]: BuildFailure
 * monotouch-test/Mac [dotnet]/Debug (CoreCLR, static registrar) [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst/Debug [dotnet]: HarnessException (Harness exception for 'monotouch-test': System.ArgumentException: '', hexadecimal value 0x1D, is an invalid character.
  at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar (System.Int32 ch, System.Char* pDst, System.Boolean entitize) [0x00026] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1420 
  at System.Xml.XmlEncodedRawTextWriter.WriteCDataSection (System.String text) [0x00251] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1370 
  at System.Xml.XmlEncodedRawTextWriter.WriteCData (System.String text) [0x0012a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:470 
  at System.Xml.XmlEncodedRawTextWriterIndent.WriteCData (System.String text) [0x00007] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1750 
  at System.Xml.XmlWellFormedWriter.WriteCData (System.String text) [0x00029] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:771 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.TestReportGenerator.WriteFailure (System.Xml.XmlWriter writer, System.String message, System.IO.TextReader stderr) [0x00031] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/TestReportGenerator.cs:41 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.NUnitV3TestReportGenerator.GenerateFailure  [...]

2021-07-27 17:07 UTC, spouliot approved these changes

2021-07-27 22:48 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5025507&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/3e5779a17d010f24914cd5059f0dc4c3)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/79c32e8330a645d27ff71b517054aa98)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/fa394b10e2d12edf219618ffc22cf682)
* macCatiOS  [gist](https://gist.github.com/1c45254fa270df45e51a653a02054bb0)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/5b0592de784bc4602e85d4245e26bc3e)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/04d886e8bdb3d022da55c3499907445d)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.52/5025507/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12242/5025507/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12242/5025507/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12242/5025507/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 114 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2488 Inconclusive: 35 Failed: 1 Ignored: 140)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5025507&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1107.BigSur'
Merge a856b15c7a33e3592646daf47b999a49c43c3563 into 3b0d79df6ae144b8bda69db3cf37920329a7586b

2021-07-28 07:21 UTC, rolfbjarne commented
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2451).

2021-07-28 07:27 UTC, rolfbjarne commented
> > > I'm not sure if that not-linking default is still the right choice considering that AOT is required (at least on ARM targets) and the build will become very long...
> > 
> > 
> > The interpreter still works, and that's the default (it still requires AOT-compiling System.Private.CoreLib.dll, but that's it).
> 
> That (interpreter) make sense for debug builds but I was thinking about release builds

Yes, I'm not sure what's the best default behavior here. I filed #12264 so that we can make a decision.

2021-07-28 07:28 UTC, merged