[DataDetection] Add new framework for Xcode 13 beta 3.
xamarin/xamarin-macios pull request #12259
Opened 2021-07-27 18:53 UTC by mandel-macaque

2021-07-27 19:04 UTC, stephen-hawley approved these changes

2021-07-27 19:51 UTC, spouliot requested changes
It's not clear how those API can be used since there's no actions, just properties.

Maybe beta 4 will make it usable ?
Until then I'm not sure we should be adding it (in case it's not mean to be public).

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
base does not have a default ctor
I don't see how having one here would be helpful (since you can't set any of the values)

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
`[DisableDefaultCtor]`

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
`[DisableDefaultCtor]`

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
`[DisableDefaultCtor]`

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
`[DisableDefaultCtor]`

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
`[DisableDefaultCtor]`

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
`[DisableDefaultCtor]`

2021-07-27 19:51 UTC, spouliot commented on src/datadetection.cs
> +	[BaseType (typeof (DDDetectedValue))]
`[DisableDefaultCtor]`

2021-07-27 20:08 UTC, mandel-macaque commented
@spouliot will address the review and will set it to do-not-merge

2021-07-28 02:12 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5026894&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/1672e51aef5d27ce71c7a481b3aab5ee)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/3f36c8c9228a5c37c73c50214989a465)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/a0aa2ef4d89cbf3380554f7878ba2969)
* macCatiOS  [gist](https://gist.github.com/b7c7bb75a9efc11a32dd6d8d5b08e92f)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ee56689101cfc13c865234be219858f9)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/bc76a25907f70f0a92958386eb2710c8)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.70/5026894/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12259/5026894/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12259/5026894/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12259/5026894/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 90 tests passed.</summary>

## Failed tests

 * Xtro/Mac: Failed (Test run failed.)
 * link all/Mac Catalyst/Debug: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5026894&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge 82e2127edbb6871a2e20a69fb0ad981ec130971d into f611cd8caec8842039fd691c27b6cd0acd5bc026

2021-07-28 08:52 UTC, rolfbjarne requested changes

2021-07-28 08:52 UTC, rolfbjarne commented on src/frameworks.sources
> +	DataDetection \
You need to add the framework to `MACCATALYST_FRAMEWORKS` too if you want these bindings in Mac Catalyst (like your availability attributes seem to indicate).

2021-07-28 16:43 UTC, tj-devel709 commented on src/datadetection.cs
> +	[BaseType (typeof(NSObject))]
```suggestion
	[BaseType (typeof (NSObject))]
```
small

2021-07-28 16:44 UTC, tj-devel709 approved these changes
Looks good after other fixes!

2021-08-05 09:42 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5059134&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/139f200c8479b4711c33f3e5d6e41759)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/e2d8a1d7e5e71b7220fae61f3a8d260e)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/5aed59a86436cda67e699aaa6a76ab6e)
* macCatiOS  [gist](https://gist.github.com/8455768cfa28f7cb4df9e1f108f3fedf)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/c11d15f4a8df646b437f580c05f23511)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/69febfe1346f4ba62bab1becda6d5a82)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210805.7/5059134/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12259/5059134/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12259/5059134/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12259/5059134/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 91 tests passed.</summary>

## Failed tests

 * link sdk/Mac Catalyst/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * Xtro/Mac: Failed (Test run failed.)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5059134&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1096.BigSur'
Merge 7227d42736aa5a16fe655bc6d8d528ece6c76d9a into 41253c3636b1619a8d27ce9387c63a2abb7685be

2024-05-06 15:22 UTC, mandel-macaque commented
Never got to land, makes no sense to try and get it in in the current state.

2024-05-06 15:22 UTC, closed without merging