[Xtro] If the sanitizer removed all selectors, remove the file.
xamarin/xamarin-macios pull request #12256
Opened 2021-07-27 17:17 UTC by mandel-macaque

A new check was added to ensure that empty .todo files are not added,
yet when the sanitizer removes all lines we get an error per empty file.

Since we are auto-sanitizing, we want to remove those empty files.

2021-07-27 19:14 UTC, stephen-hawley approved these changes

2021-07-27 20:14 UTC, spouliot requested changes

2021-07-27 20:14 UTC, spouliot commented on tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
> +					if (!(File.ReadLines(file).Count() > 0)) {
wrong style, space before `(`

2021-07-27 20:14 UTC, spouliot commented on tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
> +					if (!(File.ReadLines(file).Count() > 0)) {
why not simply look if `sanitized` is empty ?
instead of reading back the file (that was just written)

2021-07-27 20:42 UTC, spouliot commented on tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
> +					if (!(sanitized.Count () > 0)) {
Simpler
```csharp
if (sanitized.Count == 0) {
```

2021-07-27 20:59 UTC, mandel-macaque commented on tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
> +					if (!(sanitized.Count () > 0)) {
```suggestion
					if (sanitized.Count == 0) {
```

2021-07-28 01:15 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5027197&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/7e1b1a98fcc3f57549c53baf60ab8bc1)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/9a76c5fa03378bb71ea960b0e0fea56e)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/14aa5a3f695184855d8448f455e200ad)
* macCatiOS  [gist](https://gist.github.com/8639f2fd63b17ca9fde95cbcaba84fda)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/839d6a43ad67a7b564a50da42feccd04)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/93e9780d6ed36acb09dd942e9ef2f8f3)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210727.74/5027197/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12256/5027197/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12256/5027197/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12256/5027197/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 86 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2629 Passed: 2488 Inconclusive: 35 Failed: 1 Ignored: 140)
 * framework-test/Mac Catalyst/Debug: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5027197&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur'
Merge b6d4d7a4a9454705783215fb25f9197f84ee7e3f into f611cd8caec8842039fd691c27b6cd0acd5bc026

2021-07-28 06:59 UTC, rolfbjarne approved these changes

2021-07-28 13:24 UTC, spouliot approved these changes

2021-07-28 15:21 UTC, merged