[MetricKit] Add support for Xcode 13 beta4.
xamarin/xamarin-macios pull request #12326
Opened 2021-08-02 21:05 UTC by mandel-macaque

2021-08-03 02:48 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5047559&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/67bdcb219be57003e7d942292cc6d9a0)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/e12d5944459892c1faef3eabb2fb9a30)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/e5c24469d348732441c98208aeb8d438)
* macCatiOS  [gist](https://gist.github.com/a7a6496e2b3e9cdc817f30e5956d521e)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/d69828829e77f3686b4e69cd810a9236)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/add3185126502a24297e4647ef7d87a4)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210802.30/5047559/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12326/5047559/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12326/5047559/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12326/5047559/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 91 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst/Debug: Failed (Tests run: 44 Passed: 38 Inconclusive: 0 Failed: 1 Ignored: 5)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5047559&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge 9bb680c38e1556f9a75e828922388c0dfcbea7c0 into 0ca2038d7f3b5e80a977e28cb5296ed4086f2543

2021-08-03 05:51 UTC, rolfbjarne requested changes

2021-08-03 05:51 UTC, rolfbjarne commented on src/metrickit.cs
> +#if !XAMCORE_4
```suggestion
#if !XAMCORE_4_0
```

2021-08-03 05:51 UTC, rolfbjarne commented on tests/xtro-sharpie/MacCatalyst-MetricKit.ignore
> +# Added for xamcore
```suggestion
# Added for xamcore 4.0
```

2021-08-03 05:51 UTC, rolfbjarne commented on tests/xtro-sharpie/iOS-MetricKit.ignore
> +# Added for xamcore
```suggestion
# Added for xamcore 4.0
```

2021-08-03 10:00 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5049295&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/b47ac8334510fb70b095ce27398c1e68)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/c396a0f61415a78fb3a1f5d8855579a4)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/9caf26c8ba7fd865e84bb704474e6ca7)
* macCatiOS  [gist](https://gist.github.com/a9cd9633e13b191550be343f500943ff)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/a34e5fb3e4755e49e3dea6b868e5c237)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/298faf79545822109aceda7a9d88746a)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.3/5049295/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12326/5049295/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12326/5049295/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12326/5049295/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 91 tests passed.</summary>

## Failed tests

 * Xtro/Mac: Failed (Test run failed.)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5049295&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge d7820ef38b442edcd4ba99a04a9acdab18b91344 into f3758812ec0962466a630af697a2ace1f4681a3e

2021-08-03 11:48 UTC, mandel-macaque commented on src/metrickit.cs
> +#if !XAMCORE_4
I'm stupid

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +#if !MONOMAC
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac, iOS (14,0)]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 12:43 UTC, spouliot commented on src/metrickit.cs
> +		[NoMac, iOS (14,0)]
minor: not needed, there's a `[NoMac]` on the type-level

2021-08-03 13:19 UTC, rolfbjarne approved these changes

2021-08-03 14:03 UTC, dalexsoto approved these changes

2021-08-03 22:47 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5050524&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/860d58b151f40509dc9f3340d70dd36d)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/d7f5e831d46fcef01b304ff9e2073469)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/4e69c89c5bc13ef6a685b2d934895e93)
* macCatiOS  [gist](https://gist.github.com/10f9e6c32155272359478fb62be9111b)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/fa85234dd04bbdd1c7295a6d279423ee)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/823e1399e75f45ac6757c0ac9b40fdfe)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210803.25/5050524/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12326/5050524/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12326/5050524/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12326/5050524/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 92 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5050524&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge 7acbadeb5b4657e720ae28ae6b3716fd01fa1ec2 into eafe528591922af168aa5ed8b95eaa63e14fad6e

2021-08-04 14:12 UTC, mandel-macaque commented
Unrelated issue: https://github.com/xamarin/maccore/issues/2414

2021-08-04 14:12 UTC, merged