[VideoToolbox] Add support for Xcode13 beta5.
xamarin/xamarin-macios pull request #12466
Opened 2021-08-17 20:28 UTC by mandel-macaque

2021-08-17 20:28 UTC, mandel-macaque commented on src/VideoToolbox/VTVideoEncoder.cs
> +		[SupportedOSPlatform ("maccatalyst1515.0")]
```suggestion
		[SupportedOSPlatform ("maccatalyst15.0")]
```

2021-08-18 00:27 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5101776&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/a59a2675aa7d13f5deec6f55172f1b4c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/690886524456a3be4c27e2508d34bf52)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/de7e039acdd3f80a4169c3cf06e73c1e)
* macCatiOS  [gist](https://gist.github.com/7ddd7968c208f43fb0cd05bbe19596f6)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/abf1f3182466eafc6bcfad18091e611a)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/f1d8bf2e5df92d501a3af02e3516cfeb)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210817.35/5101776/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12466/5101776/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12466/5101776/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12466/5101776/apicomparison/api-diff.html)


# :tada: All 105 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5101776&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge 6341b4be7ea1d5404fa9840fcc74dcb821f12b57 into 0b01c405f3394382f7ccb620762f681b22f3dcc8

2021-08-18 09:10 UTC, rolfbjarne requested changes

2021-08-18 09:10 UTC, rolfbjarne commented on src/videotoolbox.cs
> +		NSString  EnableLtr { get; }
Extra space:

```suggestion
		NSString EnableLtr { get; }
```

2021-08-18 09:10 UTC, rolfbjarne commented on src/videotoolbox.cs
> +		NSString AcknowledgedLTRTokens { get; }
`LTR` was lower-cased to `Ltr` further above:

```suggestion
		NSString AcknowledgedLtrTokens { get; }
```

2021-08-18 09:10 UTC, rolfbjarne commented on src/videotoolbox.cs
> +		NSString ForceLTRRefresh { get; }
```suggestion
		NSString ForceLtrRefresh { get; }
```

2021-08-18 09:10 UTC, rolfbjarne commented on src/videotoolbox.cs
> +		NSString RequireLTRAcknowledgementToken { get; }
```suggestion
		NSString RequireLtrAcknowledgementToken { get; }
```

2021-08-18 13:40 UTC, spouliot requested changes
forgot to submit review yesterday :(
largely identical to Rolf's comments

2021-08-18 17:48 UTC, spouliot approved these changes

2021-08-18 19:24 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5104916&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/67370c0dfd129a9dd8bf5cd35923f0fc)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/b03e9d35fa10876ecd563c94712cc74a)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/d7403ac224efbb96cb1736a1ea0a202a)
* macCatiOS  [gist](https://gist.github.com/7713cae12343c8f2fc7fbd5d295f78cc)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/b20f0fd0a07373e691c0e0853dd043a5)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c30ee0065c278f9e4ee51e29adc143e6)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.9/5104916/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12466/5104916/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12466/5104916/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12466/5104916/apicomparison/api-diff.html)


# Test results

<details>
<summary>4 tests failed, 104 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Release (all optimizations): Failed (Test run failed.
Tests run: 2469 Passed: 2402 Inconclusive: 10 Failed: 1 Ignored: 66)
 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2638 Passed: 2489 Inconclusive: 35 Failed: 1 Ignored: 148)
 * link sdk/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * link sdk/Mac [dotnet]/Release [dotnet]: BuildFailure
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5104916&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1104.BigSur'
Merge 6edaf8320c4da55279c9a7c0fce28369020a42c2 into e3bbec476e243b73517ae8d29b6114a056e8f963

2021-08-18 20:12 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5104917&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/31e5f5635d2b6c3ca738cbf331b1b26c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/27c37bab66172b6d02989652d21e9bf7)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/d8cfa3bf7a5ec72f048eea084f788128)
* macCatiOS  [gist](https://gist.github.com/148f728fc31fcf55c892434fa6f975ae)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/b6d42a020ab416e35e82f6558292b212)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/30b9f1d2c4c7b25f383e8e8826c529ad)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.10/5104917/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12466/5104917/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12466/5104917/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12466/5104917/apicomparison/api-diff.html)


# Test results

<details>
<summary>4 tests failed, 104 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * dont link/Mac Catalyst/Debug [dotnet]: Failed (Test run crashed (exit code: 134).
Tests run: 11 Passed: 6 Inconclusive: 0 Failed: 0 Ignored: 5)
 * link sdk/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * link sdk/Mac [dotnet]/Release [dotnet]: BuildFailure
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5104917&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge 6edaf8320c4da55279c9a7c0fce28369020a42c2 into e3bbec476e243b73517ae8d29b6114a056e8f963

2021-08-18 21:36 UTC, mandel-macaque commented
Unrelated failures: https://github.com/xamarin/maccore/issues/2409

2021-08-19 06:54 UTC, rolfbjarne approved these changes

2021-08-19 15:40 UTC, merged