[msbuild] Add a task to compute the path to the AOT compiler.
xamarin/xamarin-macios pull request #12474
Opened 2021-08-18 17:07 UTC by rolfbjarne

The MonoAotCrossCompiler item group is empty when executing remotely from
Windows, so in that case we evaluate a csproj on the Mac side to compute the
AOT compiler path instead of relying in the task input from Windows.

Ref: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1362367

2021-08-18 17:18 UTC, lambdageek commented
@rolfbjarne For `UseLLVM`, How do you set LLVMPath? Those files are also on the Mac in the runtime cross-compiler pack, I believe.

2021-08-18 17:25 UTC, emaf requested changes

2021-08-18 17:25 UTC, emaf commented on dotnet/targets/Xamarin.Shared.Sdk.targets
> +		<Error Text="The AOT compiler '$(_AOTCompiler)' does not exist." Condition="!Exists ($(_AOTCompiler))" />
This won't work from Windows, because the AOT Compiler won't exist there. Probably this check should be done from inside the FindAotCompiler task.

2021-08-19 01:32 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5105329&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/423060e32fb68994ff4065c4d1401639)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/aa22af4ac73e1d2226b5d1ae0576a705)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/65a67274980b1d15e97a02c9b0741c5d)
* macCatiOS  [gist](https://gist.github.com/4a26bffa06d0daa9ab7ed8953bff67a9)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/b372688fdef32f489db5fea1b1e97113)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c075104c197b5a3de070a59802d7a2a0)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210818.13/5105329/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12474/5105329/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12474/5105329/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12474/5105329/apicomparison/api-diff.html)


# Test results

<details>
<summary>15 tests failed, 129 tests passed.</summary>

## Failed tests

 * introspection/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac [dotnet]/Debug (CoreCLR) [dotnet]: BuildFailure
 * monotouch-test/Mac [dotnet]/Debug (CoreCLR, static registrar) [dotnet]: BuildFailure
 * dont link/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac [dotnet]/Release [dotnet]: BuildFailure
 * link all/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * link all/Mac [dotnet]/Release [dotnet]: BuildFailure
 * link sdk/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * link sdk/Mac [dotnet]/Release [dotnet]: BuildFailure
 * fsharp/Mac [dotnet]/Debug [dotnet]: BuildFailure ( (failed to parse the logs: '.', hexadecimal value 0x00, is an invalid character.))
 * framework-test/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * xcframework-test/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * interdependent-binding-projects/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * DotNet tests: Failed (Execution failed with exit code 1)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5105329&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge a94a5fd2e22509454cdb3ef0b295aafa3c49ec2a into e3bbec476e243b73517ae8d29b6114a056e8f963

2021-08-19 06:46 UTC, rolfbjarne commented
@lambdageek 

> @rolfbjarne For `UseLLVM`, How do you set LLVMPath? Those files are also on the Mac in the runtime cross-compiler pack, I believe.

We compute it from the path to the AOT compiler (we assume it's the directory where the AOT compiler is).

> (I think you use the MonoAOTCompiler task from the runtime SDK, right?)

No, we haven't switched yet (but we still need the path to the LLVM compiler, so your question still applies).

2021-08-19 13:15 UTC, emaf approved these changes

2021-08-19 13:24 UTC, dalexsoto approved these changes

2021-08-19 13:41 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5108660&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/ecec447ed1e52556821716d125440257)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/be34073d4e83764caacdf5ddb3ad4ee6)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/0c1b6f8a5bb9c7cb7a14bfb5cf505cc1)
* macCatiOS  [gist](https://gist.github.com/a991ee756ebceb70256ac3ebfb333e0b)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/95061d91d578042663d62ad1fca5c227)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/44f220f279cb3b17370c493df58e6316)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210819.10/5108660/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12474/5108660/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12474/5108660/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12474/5108660/apicomparison/api-diff.html)


# :tada: All 144 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5108660&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1104.BigSur'
Merge ccb84cbd0c51b1307fa83609054d3372e91a582d into 335d7575fcbb9e56dd1ff493f98017d3bdc2d43b

2021-08-19 13:48 UTC, merged

2021-08-19 13:49 UTC, rolfbjarne commented
/sudo backport release/6.0.1xx-rc.1

2021-08-19 13:49 UTC, vs-mobiletools-engineering-service2 commented
Backport Job to branch **release/6.0.1xx-rc.1** Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=)

2021-08-19 13:50 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5109502 for more details.