[Security] Add Support for DotNet Attributes Part 2
xamarin/xamarin-macios pull request #12520
Opened 2021-08-24 00:00 UTC by tj-devel709

2021-08-24 03:52 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5124339&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/8a85bdd385faca2d200d2976a9cddee1)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/fad1340f8964eeba7dc15ca3cc51d53b)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/cf8eb86c3ef53ccc7486b529e757101b)
* macCatiOS  [gist](https://gist.github.com/cc2e378d6b1b672e83ae666f976063b5)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/14ad6830ccedb1150622d5c165730bf7)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/8d7cb1b3b77879038fc836d462528092)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.2/5124339/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12520/5124339/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12520/5124339/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12520/5124339/apicomparison/api-diff.html)


# :tada: All 108 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5124339&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur'
Merge 6aefe0316599175ea82d0778592724e75ad07438 into bbb21180e2183348855555ef4e9183f76fe9bd85

2021-08-24 13:35 UTC, mandel-macaque requested changes
Please undo the changes done in the progiial attributes before the PR.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecIdentity2.cs
> +	[iOS (12,0), TV (12,0), Mac (10,14), Watch (5,0)]
AS with the other PRs and as requested by @spouliot  lets not change the original.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecIdentity2.cs
> +		[iOS (13,0), TV (13,0), Mac (10,15), Watch (6,0)]
same.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecIdentity2.cs
> +		[iOS (13,0), TV (13,0), Mac (10,15), Watch (6,0)]
same.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecPolicy.cs
> +		[Mac (10,9)]
same.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecPolicy.cs
> +		[Mac (10,9)]
same.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecPolicy.cs
> +		[Mac (10,9)]
same.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecProtocolMetadata.cs
> +		[iOS (12,0), TV (12,0), Mac (10,14), Watch (5,0)]
same.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecProtocolMetadata.cs
> +		[Deprecated (PlatformName.WatchOS, 6, 0, message:  "Use 'NegotiatedTlsProtocolVersion' instead.")]
same.

2021-08-24 13:35 UTC, mandel-macaque commented on src/Security/SecProtocolMetadata.cs
> +		[Obsolete ("Starting with macos10.15 ", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
Not a valid message. Correct message would be 'Use "sec_protocol_metadata_get_negotiated_tls_ciphersuite" instead.'

2021-08-25 00:07 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5127449&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/b4de1fcc4b617ee4b3f749a8e737b6d0)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/78fed298df77c11037e78ad0bfd5f889)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/d6df083dbde9c0e619d325fcca3e1fc3)
* macCatiOS  [gist](https://gist.github.com/c797372f1eb577eea175cc050983d780)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/c96060b65390b10ead387974ddd21749)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/a138fba3323c178de4a6a31e1e52f845)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210824.41/5127449/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12520/5127449/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12520/5127449/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12520/5127449/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * xammac tests/Mac Modern/Release: Failed (Test run failed.
Tests run: 2469 Passed: 2403 Inconclusive: 10 Failed: 1 Ignored: 65)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5127449&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1097.BigSur'
Merge a97723d9116ca9896ef71b36102243ab2426a7a7 into 3847fe018e5321ff5595b1b7ddc53a1294772ce6

2021-08-25 08:54 UTC, rolfbjarne approved these changes

2021-08-30 14:44 UTC, spouliot approved these changes

2021-08-30 22:36 UTC, mandel-macaque commented on src/Security/SecProtocolOptions.cs
> +		[Obsolete ("Starting with tvos13.0 use 'SetTlsMinVersion (TlsProtocolVersion)' instead.' instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```suggestion
		[Obsolete ("Starting with tvos13.0 use 'SetTlsMinVersion (TlsProtocolVersion)' instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```

2021-08-30 22:36 UTC, mandel-macaque commented on src/Security/SecProtocolOptions.cs
> +		[Obsolete ("Starting with tvos13.0 use 'SetTlsMinVersion (TlsProtocolVersion)' instead.' instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```suggestion
		[Obsolete ("Starting with tvos13.0 use 'SetTlsMinVersion (TlsProtocolVersion)' instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```

2021-08-30 22:36 UTC, mandel-macaque commented on src/Security/SecProtocolOptions.cs
> +		[Obsolete ("Starting with tvos13.0 use non-DHE cipher suites instead.' instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```suggestion
		[Obsolete ("Starting with tvos13.0 use non-DHE cipher suites instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```

2021-08-30 22:37 UTC, mandel-macaque commented on src/Security/SecProtocolOptions.cs
> +		[Obsolete ("Starting with tvos13.0 use non-DHE cipher suites instead.' instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```suggestion
		[Obsolete ("Starting with tvos13.0 use non-DHE cipher suites instead.", DiagnosticId = "BI1234", UrlFormat = "https://github.com/xamarin/xamarin-macios/wiki/Obsolete")]
```

2021-08-30 22:38 UTC, mandel-macaque approved these changes
Approving after I fixed the strings.

2021-08-31 02:28 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5151011&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/764c18fa0e7a2e09f94dcd8bd778caf8)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/f925792ddf06dd23e79248719af51303)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/57150594ee58d5a3a655cf44f69fc0ff)
* macCatiOS  [gist](https://gist.github.com/7e473c98580a8268d28078c24963d6f2)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/3a733267647ea11c7e1d161c755b7408)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/d4dd1b3f4b3f9bd51803b990a611e819)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210830.36/5151011/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12520/5151011/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12520/5151011/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12520/5151011/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * dont link/Mac Catalyst/Debug [dotnet]: Failed (Test run crashed (exit code: 134).
Tests run: 11 Passed: 6 Inconclusive: 0 Failed: 0 Ignored: 5)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5151011&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1105.BigSur'
Merge 1bfa851ab649a19c60f1d47e4a1ee5030556aac6 into 57cf3c7e064a0986451cda5713181b4e3e463d09

2021-08-31 16:58 UTC, tj-devel709 commented
Thanks, @mandel-macaque!!

2021-08-31 20:43 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5153968&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/f62fa9f461f06ec87ff2b844c3a07429)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/4c882232bb8a379a95089d93fce97688)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/4f88a82b1ac8d588efe01abdf6a54b71)
* macCatiOS  [gist](https://gist.github.com/50ed9e2c8e80f1ed864e8428f98b67a2)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/5f5ee572db59a832e9773b4a79798e32)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/74f332f64fb7e56d0772ceb25c335131)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.22/5153968/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12520/5153968/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12520/5153968/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12520/5153968/apicomparison/api-diff.html)


# Test results

<details>
<summary>3 tests failed, 105 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2642 Passed: 2490 Inconclusive: 35 Failed: 1 Ignored: 151)
 * link sdk/Mac Catalyst/Release [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * link sdk/Mac Catalyst/Debug: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5153968&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.BigSur'
Merge 6d97def4d69d1f06ab8f3860c0094555703bd4aa into 20bf555ccd47c075b5ff72baa85d1327496758ea

2021-08-31 21:32 UTC, tj-devel709 commented
Unrelated Test failures: https://github.com/xamarin/maccore/issues/2443 and https://github.com/xamarin/maccore/issues/2414

2021-08-31 21:32 UTC, merged