[FileProvider] Add Support for DotNet Attributes
xamarin/xamarin-macios pull request #12593
Opened 2021-08-31 00:59 UTC by tj-devel709

2021-08-31 01:29 UTC, mandel-macaque requested changes

2021-08-31 01:29 UTC, mandel-macaque commented on src/FileProvider/Compat.cs
> +		[UnsupportedOSPlatform ("maccatalyst")]
The unsupported that are not macOS are not needed because it is inside a #if MONOMAC

2021-08-31 01:29 UTC, mandel-macaque commented on src/FileProvider/Structs.cs
> +	[UnsupportedOSPlatform ("maccatalyst")]
No needed is inside a #if MONOMAC

2021-08-31 04:53 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5151909&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/6206a4baf7d4649355a1125f4d3dfc0b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/040055ec0cdd923929f96c2b6c12d003)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/f827b4270d89dc68b64721364e239d05)
* macCatiOS  [gist](https://gist.github.com/0f6fc3892f9372326f9f99c0cf4f3fee)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/238da4c34cfa4225c1f1cdc1bf129d8b)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/156db84f042609bc3240bb1cb3cbd759)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.5/5151909/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12593/5151909/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12593/5151909/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12593/5151909/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 106 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst/Debug [dotnet]: Failed (Tests run: 2642 Passed: 2490 Inconclusive: 35 Failed: 1 Ignored: 151)
 * dont link/Mac Catalyst/Debug [dotnet]: Failed (Test run crashed (exit code: 134).
Tests run: 11 Passed: 6 Inconclusive: 0 Failed: 0 Ignored: 5)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5151909&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1104.BigSur'
Merge f7c7ca5581689d69351675135e8e17968ae0b059 into 12d8b37f4f876e4f8fe34bbbe802ea073166ed6a

2021-08-31 13:12 UTC, spouliot approved these changes

2021-08-31 13:41 UTC, dalexsoto approved these changes

2021-08-31 21:20 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5154447&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/7b1c01a0c17a2b78d641afe16f9ef5f8)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/42eda40088fb1af45f642c519c37fbdb)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/ddc2d492a7726114aee58ad2db581599)
* macCatiOS  [gist](https://gist.github.com/013f70748e3cb4238e54ed159e774f74)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ae1ab8eb2098647eb1e9700a9aa6496e)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/7712c9f8757f55a2c7a95f8eb3e26fba)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210831.29/5154447/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12593/5154447/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12593/5154447/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12593/5154447/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * dont link/Mac Catalyst/Debug [dotnet]: Failed (Test run crashed (exit code: 134).
Tests run: 11 Passed: 6 Inconclusive: 0 Failed: 0 Ignored: 5)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5154447&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1103.BigSur'
Merge 3fb944dca626a1e0288b0173ba2477232d62176e into 066d5b5740ac8938affe78249f2013a602fe1714

2021-09-01 15:36 UTC, mandel-macaque approved these changes

2021-09-01 16:32 UTC, tj-devel709 commented
/azp run

2021-09-01 21:13 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5159286&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/0723959fdab56ff5d7aababd93749e68)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/1b7ae872cc23699a883782726c8f2557)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/13adc530aaeb36416191f2ee7997cb5d)
* macCatiOS  [gist](https://gist.github.com/631ed3f485e8e606944fa60eab9e55fd)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/439a158604f6a883ae033602d063d75c)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/fa7a9d5ab7f8f81e2792b7e15479f875)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.12/5159286/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12593/5159286/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12593/5159286/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12593/5159286/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * dont link/Mac Catalyst/Release [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5159286&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge 3fb944dca626a1e0288b0173ba2477232d62176e into 5b896c778939439525f2aa62f670a5c817a29412

2021-09-02 16:11 UTC, mandel-macaque commented
Known issue: https://github.com/xamarin/maccore/issues/2414

2021-09-02 16:11 UTC, merged