[XKit] Update for xcode13 beta 5.
xamarin/xamarin-macios pull request #12610
Opened 2021-09-01 22:26 UTC by mandel-macaque

Add the bindings for the classes shared between AppKit and UIKit.

Done as its own PR so that we can work on UIKit and AppKit in parallel.

2021-09-02 02:45 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5161243&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/306be36d1e60a993801818ab6ba43137)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/3999812f610350ad25cca05041c7fc5d)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/99b61b30a111e149874f16bd75728d91)
* macCatiOS  [gist](https://gist.github.com/62d90de08e8fe9d0b6d4de40f87afac1)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/2ba735ba84f4cf39976ed88a9737c78b)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c622f829939c4213b0705eec2fbcac87)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210901.26/5161243/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12610/5161243/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12610/5161243/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12610/5161243/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * dont link/Mac Catalyst/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5161243&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge a128c68423f4b81bf0ed095a82aeef018eca7fc8 into 14b77dc8ea39d56a8562b71cf5a1210403db6c70

2021-09-02 17:25 UTC, spouliot requested changes

2021-09-02 18:48 UTC, tj-devel709 approved these changes

2021-09-02 20:10 UTC, dalexsoto approved these changes

2021-09-06 18:27 UTC, rolfbjarne requested changes

2021-09-09 18:54 UTC, spouliot approved these changes

2021-09-09 23:29 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5187785&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/d77926f9650679978f14137af4c1e098)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/cbd6553f8464e800378158391e88b58e)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/72c89366edcad36bdd720216919b4628)
* macCatiOS  [gist](https://gist.github.com/40ea3385530f4d37b55deef0db8775f1)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/90f0696ee48fa39d154091b5cc456bcd)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/dc4bda819c7d69f4a96636febca6fb5f)
</details>

# API & Generator diff

:information_source: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/apigeneratordiff/;//api-diff.html) (please review changes)
:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210909.35/5187785/apigeneratordiff/;//generator-diff/index.html) (please review changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12610/5187785/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12610/5187785/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12610/5187785/apicomparison/api-diff.html)


# Test results

<details>
<summary>3 tests failed, 99 tests passed.</summary>

## Failed tests

 * link all/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 134).
Tests run: 90 Passed: 79 Inconclusive: 0 Failed: 0 Ignored: 11)
 * link sdk/tvOS - simulator/Debug: Failed
 * link sdk/tvOS - simulator/Release: Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5187785&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur'
Merge da1ef9bbb388b0c1a17301776a085e1f0e7e6585 into 55e8c60e0dcd4a46577b32c42c7bf0625e6ea846

2021-09-10 11:29 UTC, rolfbjarne approved these changes

2021-09-10 16:16 UTC, mandel-macaque commented
Unrelated failures: https://github.com/xamarin/xamarin-macios/issues/12640

2021-09-10 16:16 UTC, merged