[net6][msbuild] Set SelfContained for AppExtensions sooner to fix publishing
xamarin/xamarin-macios pull request #12703
Opened 2021-09-10 21:52 UTC by chamons

This PR resolves a crash when running the linker on publishing iOS extensions.

The crash would occur [here](https://github.com/xamarin/xamarin-macios/blob/143a2216a60873ea530cd304f8a41f14a2f0b8a6/tools/common/StaticRegistrar.cs#L996) in failing to resolve corelib.

The reason this would fail was System.Private.CoreLib.dll was not in input_assemblies.

This was because we were passes the set of reference assemblies not the expected 'real' ones, and those do not include CoreLib.

After a bunch of digging, this was because _ComputeManagedRuntimePackAssembliesIfSelfContained target was not being set as a condition of  _ComputeAssembliesToPostprocessOnPublish.

_ComputeManagedRuntimePackAssembliesIfSelfContained happened to be the place these were added, and wasn't being set since it has a condition of $(SelfContained) == 'true'

Now confusingly SelfContained WAS being set to true, but only in the targets file, which was to late, as it was checked in a 'global' property group outside of a target.

This means we'd fail to set SelfContained until after the condition, and not run.

This was verified by setting /p:SelfContained=true to true.

I also looked at removing the condition above, since https://github.com/dotnet/runtime/issues/54406 is fixed, however this caused project that didn't set RuntimeIdentifier to fail.

2021-09-11 00:05 UTC, mandel-macaque approved these changes

2021-09-11 02:10 UTC, jonathanpeppers reviewed
I'd maybe suggest adding an app extension that is built in `Release` mode on CI? Would that make sure it's fixed going forwrd?

2021-09-11 03:35 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5193437&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/a2d80512a3231108b2b105088a771652)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/ae79e0449946ae8d3c68dfd13e7a2d55)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/e71af2c293d5f4f5414fbc72c1ca4dfd)
* macCatiOS  [gist](https://gist.github.com/dc656b77752482da581fb00bae0878e6)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/96cce6a598d310f85c3605fdb96f038c)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/b086e26ccdc5b887e768e3b9a7cae3ad)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210910.40/5193437/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12703/5193437/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12703/5193437/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12703/5193437/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 133 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5193437&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1104.BigSur'
Merge 003b18ec82df68254e48e5d3d24d92711d92ea18 into aadd53249fb3ca7734fb9b82ff9396dbe3d9778e

2021-09-13 08:20 UTC, rolfbjarne requested changes
We'll need a test case for this as well:

1. Add two test project to tests/dotnet, one container project and one extension project. This should be done for all our platforms, similar to how it's done in tests/dotnet/MySimpleApp. So something like:

        tests/dotnet/ExtensionProject/
            macOS/ <-- files specific to the macOS extension
            iOS/
            tvOS/
            MacCatalyst/
            <shared files>

    each platform will probably have to be a different type of extension, since I don't think there's an extension type that's available everywhere.

        tests/dotnet/ExtensionConsumer/
            macOS/ <-- files specific to the macOS project
            iOS/
            tvOS/
            MacCatalyst/
            <shared files>

2. Add a unit test to tests/dotnet/UnitTests/ProjectTest.cs

2021-09-13 08:20 UTC, rolfbjarne commented on dotnet/targets/Xamarin.Shared.Sdk.props
> +	<!-- App extensions are self-contained, even though their OutputType=Library. This must be done here at not targets as it is checked before targets are invoked. -->
```suggestion
	<!-- App extensions are self-contained, even though their OutputType=Library. This must be done here and not targets as it is checked before targets are invoked. -->
```

2021-09-13 14:05 UTC, spouliot approved these changes

2021-09-13 14:18 UTC, emaf approved these changes

2021-09-13 19:05 UTC, chamons commented
Tests added, but I had to do them without running. I hit the workload issue and was told a full git clean was needed for me to not get the dreaded:

```
 Possible reasons for this include:
   * You intended to execute a .NET program:
       The application 'build' does not exist.
   * You intended to execute a .NET SDK command:
       A compatible installed .NET SDK for global.json version [6.0.100-rc.2.21456.8] from [/Users/donblas/Programming/macios/master/xamarin-macios/tests/dotnet/ExtensionConsumer/macOS/global.json] was not found.
       Install the [6.0.100-rc.2.21456.8] .NET SDK or update [/Users/donblas/Programming/macios/master/xamarin-macios/tests/dotnet/ExtensionConsumer/macOS/global.json] with an installed .NET SDK:
         6.0.100-rc.2.21423.21 [/Users/donblas/Programming/macios/master/xamarin-macios/builds/downloads/dotnet-sdk-6.0.100-rc.2.21423.21-osx-x64/sdk]
```

2021-09-13 21:05 UTC, chamons commented
Tests are failing, but I can run them now then I did a full build...

2021-09-14 01:58 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5198510&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/a59a29470d35c7c197f7d930cc9667c0)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/6209ee18fec2e47dd5e99f5e68fa62bb)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/fed64597e12246eda0f9058942870027)
* macCatiOS  [gist](https://gist.github.com/31ac4156a3a48d69cc78f29cbb0852d2)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/f31a69fa54341289a2d0e2492d069490)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/b666db858669eb6b30132078b965225c)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210913.31/5198510/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12703/5198510/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12703/5198510/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12703/5198510/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 132 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * DotNet tests: Failed (Execution failed with exit code 1)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5198510&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1099.BigSur'
Merge 78d3681f9287cc2cbde2736501071b7a624f9650 into 71d2edbc804c51f6b643e329f175584e4f5a16b5

2021-09-14 22:20 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5202919&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/8b5ab76ecf02c22fcc09391c6ee6e73b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/780944d770e38fe941a2bf142ca5200c)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/092cdee298d9d79daa96779c49e5488e)
* macCatiOS  [gist](https://gist.github.com/53e7d1b5f9681ebd2e2a54a642ee6ae7)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/b08f7725577936ae6851a87567ba5f44)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/cf0a180ab4fdbd9e4239e236d4a14ed4)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210914.22/5202919/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12703/5202919/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12703/5202919/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12703/5202919/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 133 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Tests run: 2644 Passed: 2490 Inconclusive: 35 Failed: 1 Ignored: 153)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5202919&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge 166f9e9e76bd1e8a62573b791e290fa2b5436fc5 into c2b7df3e4106174cc11a670154f8da37a3ccceb1

2021-09-15 10:02 UTC, rolfbjarne requested changes

2021-09-15 10:02 UTC, rolfbjarne commented on tests/dotnet/ExtensionProject/tvOS/MyTVServicesExtension.csproj
> +    <RuntimeIdentifier>tvossimulator-x64</RuntimeIdentifier>
Same:

```suggestion
```

2021-09-15 10:02 UTC, rolfbjarne commented on tests/dotnet/UnitTests/ProjectTest.cs
> +		[TestCase (ApplePlatform.MacOSX, "ShareExtensionTest.csproj", "bin/Debug/net6.0-macos/osx-x64/MySimpleApp.app/Contents/PlugIns/ShareExtensionTest.appex")]
As mentioned before, if you name all the extension projects the same way, you can the platform-specific special casing here.

2021-09-15 10:02 UTC, rolfbjarne commented on tests/dotnet/UnitTests/ProjectTest.cs
> +			Configuration.CopyDotNetSupportingFiles (Path.GetDirectoryName(consumingProjectDir));
```suggestion
			Configuration.CopyDotNetSupportingFiles (Path.GetDirectoryName (extensionProjectDir));
			Configuration.CopyDotNetSupportingFiles (Path.GetDirectoryName (consumingProjectDir));
```

2021-09-15 10:02 UTC, rolfbjarne commented on tests/dotnet/UnitTests/ProjectTest.cs
> +			var extensionPath = Path.Combine (Path.GetDirectoryName(consumingProjectDir), appPath);
```suggestion
			var extensionPath = Path.Combine (Path.GetDirectoryName (consumingProjectDir), appPath);
```

2021-09-15 10:02 UTC, rolfbjarne commented on tests/dotnet/UnitTests/ProjectTest.cs
> +			Assert.That (Directory.Exists(extensionPath), $"App extension directory does not exist: {extensionPath}");
```suggestion
			Assert.That (Directory.Exists (extensionPath), $"App extension directory does not exist: {extensionPath}");
```

2021-09-15 10:02 UTC, rolfbjarne commented on tests/dotnet/UnitTests/ProjectTest.cs
> +			DotNet.AssertBuild (extensionProjectDir, verbosity);
You shouldn't have to build the extension project manually first, just building the consuming project should be enough.

2021-09-16 15:09 UTC, chamons commented on tests/dotnet/ExtensionProject/iOS/ShareViewController.cs
> +
I literally copy pasted this from an exisitng test, but you are right.

2021-09-16 20:30 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5213166&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/8ffb0188fe1e35852a3ebd3aa6ae01d2)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/c7e06f5615dccf92274b61fdc097abcd)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/1dc95da309d22b497372b81258913818)
* macCatiOS  [gist](https://gist.github.com/9b47af0d02cb4d939cf5b21c63e30180)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/e7828fbed69dc6379a0d66d4af512496)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/3cb1c4b6a11408f96f20019fc3872a09)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.28/5213166/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12703/5213166/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12703/5213166/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12703/5213166/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 133 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Tests run: 44 Passed: 40 Inconclusive: 0 Failed: 1 Ignored: 3)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5213166&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1104.BigSur'
Merge 00d04ebfcf684cdb3fe20ac36087848b49505b66 into d142a3756f215841f0724217994abf06243f9653

2021-09-16 21:21 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5213165&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/aca483b74b17d205a7fca31ddca8f79a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/5e405fede602e2fc70951d7d32e03dcb)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/65e16afeb54bd628713e137dbb12f661)
* macCatiOS  [gist](https://gist.github.com/2c42b49362006ae65d60738ec0f44a39)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/896a78092c37218b3b2da13fa5d4f5fe)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/f0341542e31261c52791394a4d8090b0)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.27/5213165/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12703/5213165/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12703/5213165/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12703/5213165/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 133 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Tests run: 44 Passed: 40 Inconclusive: 0 Failed: 1 Ignored: 3)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5213165&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge 00d04ebfcf684cdb3fe20ac36087848b49505b66 into d142a3756f215841f0724217994abf06243f9653

2021-09-17 19:10 UTC, chamons commented
@rolfbjarne - I believe I have all of your requested test changes in.

2021-09-17 20:51 UTC, dalexsoto approved these changes

2021-09-18 00:27 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5219576&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/b2e9a9324e3a2351ba498e400f20753a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/473f8816bd2c767aab06909077831df5)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/9a1169cea67d5df8edb9b2d440a20c92)
* macCatiOS  [gist](https://gist.github.com/9e12b6ade9b5b36bb6811751117b8366)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/f218bc76fc7d41b93b8942f30d34135f)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/915422a6bf98df89abfd797d5e4cd1de)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210917.24/5219576/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12703/5219576/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12703/5219576/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12703/5219576/apicomparison/api-diff.html)


# :tada: All 134 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5219576&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur'
Merge cf7527a9c5cf0ad9b53196b78cd8d52f06cf16fb into d94a0f53bd75aa9b79beab68ca41d71e7175ee16

2021-09-20 07:11 UTC, rolfbjarne approved these changes

2021-09-20 07:11 UTC, rolfbjarne commented on tests/dotnet/ExtensionConsumer/shared.csproj
> +    	</ProjectReference>
Minor: indentation is off here.

2021-09-20 14:40 UTC, merged

2021-09-20 20:24 UTC, vs-mobiletools-engineering-service2 commented
### :fire: Tests failed catastrophically on Build (no summary found). :fire:

Result file $(TEST_SUMMARY_PATH) not found. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5225015&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210920.19/5225015/sim/;/tests/vsdrops_index.html)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5225015&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1096.BigSur'
Merge 35087bc7b882b63e5481dd87c18519a18d5c58a2 into 499a69e7720daf37cfb527f66127d46a89892ab9