[Xtro] Allow to run xtro with some platforms ignored.
xamarin/xamarin-macios pull request #12742
Opened 2021-09-15 22:26 UTC by mandel-macaque

Do not add dependencies to targets that have been disabled via ifdef.

2021-09-15 22:27 UTC, spouliot approved these changes

2021-09-15 22:28 UTC, dalexsoto approved these changes

2021-09-16 02:46 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5210148&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/03a737cc0b518251fcbdf40720ed6279)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/52a124f82d52988b0c7ef6e05c5ebdfa)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/484f1f9610884dbf122635c37648be62)
* macCatiOS  [gist](https://gist.github.com/eca05c5ade0d753bd2a2d4f360c7c713)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/836fedc712b829e5c03393c4d4dbcd21)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/f14d90d73756a4668a68d3e0c888e4a3)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210915.27/5210148/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12742/5210148/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12742/5210148/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12742/5210148/apicomparison/api-diff.html)


# Test results

<details>
<summary>4 tests failed, 97 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Tests run: 44 Passed: 40 Inconclusive: 0 Failed: 1 Ignored: 3)
 * fsharp/Mac [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * link sdk/tvOS - simulator/Debug: Failed
 * link sdk/tvOS - simulator/Release: Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5210148&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge 6c1e8d223d0f4478d58413301b320718be0079aa into b9cde5eeea898ef28663ea939b98fb85c9cf41ca

2021-09-16 06:34 UTC, rolfbjarne requested changes

2021-09-16 06:34 UTC, rolfbjarne commented on tests/xtro-sharpie/Makefile
> +classify: build $(if $(INCLUDE_IOS), $(XIOS_PCH)) $(if $(INCLUDE_TVOS), $(XTVOS_PCH)) $(if $(INCLUDE_WATCH), $(XWATCHOS_PCH)) $(if $(INCLUDE_MAC), $(XMAC_PCH)) $(if $(INCLUDE_MACCATALYST), $(XCAT_PCH
That's kind of unwieldy to read.

Maybe do something like this in each "ifdef INCLUDE_*" above:

```make
ifdef INCLUDE_IOS
PCH_FILES+=$(XIOS_PCH)
...
endif

ifdef INCLUDE_TVOS
PCH_FILES+=$(XTVOS_PCH)
...
endif

...
```

and then this becomes:

```suggestion
classify: build $(PCH_FILES)
```

2021-09-16 15:21 UTC, rolfbjarne approved these changes

2021-09-16 16:58 UTC, tj-devel709 approved these changes

2021-09-16 19:22 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5213181&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/sim/;/tests/vsdrops_index.html)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/0882bef45f726014e22c943a9398fdbe)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/d6397c3c35f8bdbf94891f1785dec273)
* macCat [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/apidiff/;/maccat-api-diff.html) [gist](https://gist.github.com/d5416671402ad03ab63875ff741172ce)
* macCatiOS  [gist](https://gist.github.com/2dd859845c9222dbfba045566d5382b8)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/bbee26acefbad1651a4c470ac5c044ae)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/f2a41a2c12939594f311f14f091becc8)
</details>

# API & Generator diff

:white_check_mark: [API Diff (from PR only)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/apigeneratordiff/;//api-diff.html) (no change)
:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20210916.30/5213181/apigeneratordiff/;//generator-diff/index.html) (only version changes)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR12742/5213181/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR12742/5213181/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR12742/5213181/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 100 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5213181&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1096.BigSur'
Merge ae23264bb6c9b6984b7a45fe51af05034d583781 into d142a3756f215841f0724217994abf06243f9653

2021-09-16 20:08 UTC, merged