[Xcode13.2] Bump to Xcode 13.2 Beta 2
xamarin/xamarin-macios pull request #13497
Opened 2021-12-06 01:29 UTC by dalexsoto

Breaking changes addressed for legacy (Legacy API diff seems happy)
* HomeKit
* CallKit
* CoreLocation

2021-12-06 08:36 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5516317&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5516317/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/cf180c8faa526697d268943977d6179a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/a30ecba8872702dabc9a4c68765adbb6)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/879785a9a9efcd94daebee8fed72f51f)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/535b616f92c4df4549e59d12995c9f52)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/b05830406372ed86eebde0942b59ec7b)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/b81b9422759bec08d7e4b36a7d2848fb)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/5ab54a5bdf222de9f77324b986777ac4)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/bc4ad756a77b4f6f3ac8eb6e816219d8)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/945d5b1514d96ec9afdc2a0cd170f8f4)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/a70f4f9c04aadd8d4b5de8fddfac8beb)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/639627512d65ec2ad435ea938237b3c5)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211206.1/5516317/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/86c373c9d9f0d2219221f00c258c4c71)
</details>


# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13497/5516317/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13497/5516317/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13497/5516317/apicomparison/api-diff.html)


# Test results

<details>
<summary>13 tests failed, 124 tests passed.</summary>

## Failed tests

 * introspection/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5516317&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge 617a0d15f7da09d3a58b16c26784b7c4919d5454 into 8ec686c33382f727d4d0761d57e7fa3bf970e818

2021-12-06 16:16 UTC, chamons commented
Looks reasonable, but I've been out of binding practice for awhile so only tiny 👍.

My biggest concern here is API compat, which we'll have to lean on API diff + folks here.

2021-12-06 18:56 UTC, mandel-macaque approved these changes

2021-12-07 04:07 UTC, tj-devel709 approved these changes

2021-12-07 10:02 UTC, rolfbjarne requested changes
There are also a few breaking changes:
![Screen Shot 2021-12-07 at 10 58 02](https://user-images.githubusercontent.com/249268/145008165-a739ce37-643e-4480-a5d1-fc02ae1022a4.png)
![Screen Shot 2021-12-07 at 10 54 07](https://user-images.githubusercontent.com/249268/145008172-445eaa62-ad40-4a9b-aac6-4a6a671ed5d7.png)
![Screen Shot 2021-12-07 at 10 51 22](https://user-images.githubusercontent.com/249268/145008173-0c28f702-03b9-4858-982e-9f578b02a319.png)

2021-12-08 03:16 UTC, dalexsoto commented on src/corelocation.cs
> +#if !MONOMAC
I think the `ErrorDomain` was still generated I can double check this in the morning

2021-12-08 03:17 UTC, dalexsoto commented
@rolfbjarne I think I have addressed all the feedback and also updated to Xcode 13 RC which has only one change on intents

2021-12-08 13:12 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5525466&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5525466/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/89814728555523da84c3cd3d4a01475a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/6422aaf6a4e56b906b0698967fec0f3d)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/9263384db053a35adad89d4af0560303)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/2bc19bb9b3895d0fe1120ebe1e3d29b8)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/816676269b1fd55a894a52f6c3972599)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/2352dd5c5a64c4cfcf7faa4605702bfd)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/e8f78edafa621ffc7803e5a56db085bf)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/7e976e9ae44510bb281ecdb734336e17)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/02f90ef443eea58c652f0aaa18489268)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/bd0aad3d5abe762ced732123d3c572cf)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/aeffa95ec4ff0f692a332a7c3470ce18)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.3/5525466/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/98e07492b38f6d9e11588b9e992acd69)
</details>


# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13497/5525466/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13497/5525466/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13497/5525466/apicomparison/api-diff.html)


# Test results

<details>
<summary>3 tests failed, 192 tests passed.</summary>

## Failed tests

 * link all/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 134).
Tests run: 90 Passed: 79 Inconclusive: 0 Failed: 0 Ignored: 11)
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
 * xammac tests/Mac Modern/Release: Failed (Test run failed.
Tests run: 2567 Passed: 2421 Inconclusive: 10 Failed: 1 Ignored: 145)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5525466&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.BigSur'
Merge 849cf7ada585fcd273f723fe3af877bee7046ef3 into 8ec686c33382f727d4d0761d57e7fa3bf970e818

2021-12-09 04:12 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5527000&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5527000/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/758e0ebf4204c0882d3026ca1794425b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/11d579e48a08d37485f1f9d5e4ab69d3)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/e08bdfd04ac453a05eeab3d434ebb61a)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/b1b9cb6ce5f6713c0252277f8e4a1c74)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/03ae11b0b84353c4e940b55d1a6c0000)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/54399c82a3a1d793a2499847eb38efc5)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/256e0e054e6e0bf51ba40de14e65d847)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/e37a1fe72330f6076e4392bb190e047e)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/4893eb193b378315e211fe30dec4acaa)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/ec76b7836585145c37aeda14fa9cc53f)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/5fae18d1c08ff0c18c52a6f712e12d38)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211208.8/5527000/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/88d67948e46918e776d16c5882f38ad5)
</details>


# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13497/5527000/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13497/5527000/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13497/5527000/apicomparison/api-diff.html)


# Test results

<details>
<summary>4 tests failed, 191 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2730 Passed: 2503 Inconclusive: 38 Failed: 1 Ignored: 226)
 * link sdk/Mac Catalyst [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * Xtro/Legacy Xamarin: BuildFailure
 * Xtro/.NET: BuildFailure
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5527000&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1094.BigSur'
Merge ff07707e46133239b595a5e8e5818ae811d4384f into 8ec686c33382f727d4d0761d57e7fa3bf970e818

2021-12-09 04:27 UTC, dalexsoto commented
- known issue - [Bug17793](https://github.com/xamarin/maccore/issues/2443)
- xtro is fixed
- known issue - [*/Mac Catalyst/*: TimedOut](https://github.com/xamarin/maccore/issues/2414)

due to time constrains ✅

2021-12-09 04:27 UTC, merged