[Dotnet] Fix building twice in a row issue
xamarin/xamarin-macios pull request #13573
Opened 2021-12-15 05:25 UTC by tj-devel709

This PR addresses this issue: https://github.com/xamarin/maccore/issues/2530

If you build twice using DotNet.AssertBuild without cleaning in between, the project fails.
From tracing the binlogs, it looks like there is a file "scene.dae" that after the first build, failed to carry over it's metadata: primarily it's 'LogicalName'.
This caused an issue since the output file is composed of a directory + this logical name.
Thus with an empty LogicalName, the output file is a directory and causes the build to fail.
Inside the ComputeBundleResourceOutputPaths, it will now compute a default LogicalName of the filename if LogicalPath is not provided.

2021-12-15 07:27 UTC, rolfbjarne approved these changes

2021-12-15 13:59 UTC, mandel-macaque requested changes

2021-12-15 13:59 UTC, mandel-macaque commented on tests/dotnet/UnitTests/ProjectTest.cs
> +			var projectPath = GetProjectPath (project, runtimeIdentifiers: runtimeIdentifiers, platform: platform, out var appPath);
if you do not use an out var, please use _ for it as it is described here: https://devblogs.microsoft.com/dotnet/new-features-in-c-7-0/#out-variables
```suggestion
			var projectPath = GetProjectPath (project, runtimeIdentifiers: runtimeIdentifiers, platform: platform, out _);
```

2021-12-15 14:20 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5549898&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5549898/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/d5b6656c7e0bd0c506ecd711ee2ae127)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/043132ee22547c37969c853b5a5a4e19)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/978ef9e079ee9aefc5b9387cfd63d301)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/7c0e1829bd92e8dc6fb7621d27a3882e)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/ff2f4adc9f079ac76da0b53858ee8692)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/34518c2b086527348ceea0d30710be4d)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/30ab278d623f7e6ed6951e87a46dcc6e)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/83935e21f7b76bbb6954d1ae8d23dd8e)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/151c481bef25f4a8c7d50e36ecf12c8c)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/b7af46239b174eb7ca7ba1bd635ce097)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/600d97cb5a0ffa90245ae37dabef1ed8)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/10c5f6013444c248648892c029863246)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/ef765e33b701b606b00da9d4045aa594)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/7dc9676bc0e0d719e7115093499301c9)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/88cb5ffead0d926e0aedbc00d3582561)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/ee34f11f04f4569c43d84756723a85fc)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/d6a8458914724a69ec889ef31b4b85e0)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/963c6ca7619c7b50e3b94b13a585e17e)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/e6403eb9e6d9771fc6cbf8c6ae4571e6)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/4ba00b95b4abbb31bc456981685db197)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/6f9b0ab873695202de5975146c7d7238)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/43b0d042f256e3fd4f3ad18e32f8443e)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/43be8628cf479eed5737e96e2c314d37)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/7132d617c35e45fb01622d7fc0dcb71f)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.7/5549898/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13573/5549898/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13573/5549898/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13573/5549898/apicomparison/api-diff.html)


# Test results

<details>
<summary>3 tests failed, 130 tests passed.</summary>

## Failed tests

 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): TimedOut
 * monotouch-test/watchOS 32-bits -  [...]

2021-12-15 19:23 UTC, chamons approved these changes

2021-12-15 19:31 UTC, mandel-macaque approved these changes

2021-12-15 20:42 UTC, emaf approved these changes

2021-12-16 01:16 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5551095&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5551095/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/fbbaf4ce5c707e0a8417865e87b74e13)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/36232f59add904dc80a09d14ba24cce0)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/f76b9abf43a9fd2870b1d179535039f7)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/0d95c16d645340d20290f42965606bb2)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/3b4d79a90cf6dc058bb087b8217b7d46)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/8bf7f985824f6657d6384e191a27a513)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/368f01cf85451b326a91825eae1bbb9d)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/342e839247fc30a65e01d80953ca905a)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/267668c4ee3690fdfa37d20f6105dcb8)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/23838281bb07683e9b7ccfcd25892dd4)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/933a55bd57172e1882861e49b0379c4f)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/48b77037c6e5ee992170d58028947712)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/c1b4b51d3a19bef45304401fe4b10f96)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/640aa1b667039ed76398b89f358ac52a)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/0990e59376c479e07bbb906190559f83)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c41e0236f704bf652ac850922f1f26d7)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/93f4f85e9878b97d0d3386c007297d05)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/11ce2f775c3ac47c0ecbc92581f13db0)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/2fe85320aac5297ec2e029aa612bf957)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/40aed674872ffa980c3482abd8c2a5cc)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/d65bbf3f752317bb9a9f882e28666233)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/be87b66313f5b26a7fb582fb6452417a)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/c694fa2b87456bc94234fc2bf906a5f5)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/ef59a6bad4afc8769a97df94bbaa8990)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211215.23/5551095/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13573/5551095/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13573/5551095/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13573/5551095/apicomparison/api-diff.html)


# Test results

<details>
<summary>3 tests failed, 146 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac [dotnet]/Debug (static registrar) [dotnet]: Failed (Test run [...]

2021-12-16 02:06 UTC, tj-devel709 commented
I don't believe the `monotouch-test/Mac [dotnet]/Debug (static registrar) [dotnet]` crash is related nor did it appear in the first build, but I will build again to see if this is a repeating issue.

2021-12-16 02:07 UTC, tj-devel709 commented
/azp run

2021-12-16 02:13 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests didn't execute on Build. :x:

Tests didn't execute on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5553490&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.1/5553490/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5553490/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
API diff urls have not been provided.
API Current PR diff urls have not been provided.
Generator diff comments have not been provided.
# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13573/5553490/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13573/5553490/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13573/5553490/apicomparison/api-diff.html)


No test summary was found (something probably failed before the tests could execute)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5553490&view=ms.vss-test-web.test-result-details) on Agent 
Merge 96b4a83c4e3ced56a66b3a3142d7f1ccd07cdbc1 into 4cf12e36232f969fbf6e1c641f138728fe10c1a1

2021-12-16 03:32 UTC, tj-devel709 commented
/azp run

2021-12-16 11:47 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5553733&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5553733/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/ac1548360fba4fc46c86c6754ec5d9fe)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/cbb2d9094a0f044bd576500f860113ce)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/2a6f340480860bc0c7242e4492f1fc89)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/99f8cf4046af6ffcf6443cab081fa60d)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/e91cd1c9450ba787d1e5a74a1aaad627)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/f1dd885a2d44f6a27ef55d0f1132ada8)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/df5e7b6711edbfb4da064ef25557f613)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/1d031ebe0cd967f8c362b5b6d565d5f9)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/bc41249c4ff0795d7f33e27b92281e9d)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/f86085c75c700be069b4aea3e799754d)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/4a75db612e3bf7330d35ccfb55df34a1)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/96a3921dc704ced1db0108cc94877b63)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/72b91bbaa2ee45994f5a28bc1783a7b6)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/830443ab659c4cb1f336c3858e8d61e1)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/9f009d81d566914be3546924dba3232a)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/cd8aa8b576c00e81b1bbffbe91ed2eac)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/7dd0a242e0c54b9276c98c87817b3a69)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/f4389f18349d9e379dcf602ee0bce2fb)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/97d90a3386e3908db0c319772b87675c)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/8e92a87b15e70f6e571e8e4ec0ef4974)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/12c66443e6d98de9e5a132ca86efed0b)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/d873a759f000777ee843e2a02fe7fbef)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/a487c468019e17b7b35f725b0d46001c)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/bd5d1cb6c65900837d762f4f87a52d84)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20211216.2/5553733/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13573/5553733/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13573/5553733/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13573/5553733/apicomparison/api-diff.html)


# :tada: All 149 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5553733&view=ms.vss-test-web.test-result-details) on Agent XAMB [...]

2021-12-16 15:07 UTC, merged