[coregraphics] Fix some names for the NET profile
xamarin/xamarin-macios pull request #13668
Opened 2022-01-11 00:35 UTC by spouliot

* Fix `CGColorConversionInfoTriple` name (missing initial `C`)

* Rename `RectangleFExtensions` to `CGRectExtensions` since the former
  name has not been around for a while

* Remove API naming mistakes (already under XAMCORE_4_0)

2022-01-11 06:29 UTC, rolfbjarne requested changes
Surprise visit!

2022-01-11 06:29 UTC, rolfbjarne commented on src/CoreGraphics/CGColorConverter.cs
> +	[Obsoleted (PlatformName.TvOS, 10,0, message: "Replaced by 'CGColorConversionInfoTriple'.")]
This is for legacy Xamarin, it's the Obsolete attributes just below that should be updated instead.

2022-01-11 06:29 UTC, rolfbjarne commented on src/CoreGraphics/CGColorSpace.cs
> +#if XAMCORE_4_0 || NET
Just remove the `XAMCORE_4_0` symbol completely everywhere (makes it easier to grep to find what's left to do), so that only `NET` is used.

2022-01-11 14:21 UTC, tj-devel709 approved these changes

2022-01-11 14:22 UTC, tj-devel709 commented
I opened this PR and got very confused... thought I traveled back in time haha

2022-01-11 16:10 UTC, spouliot commented
@rolfbjarne @tj-devel709 I can't apply labels so it won't run on bots until someone does 😄

2022-01-11 16:19 UTC, mandel-macaque commented
/azp run

2022-01-11 16:20 UTC, mandel-macaque commented
@spouliot  community label ;)

2022-01-11 16:25 UTC, rolfbjarne approved these changes

2022-01-11 16:32 UTC, dalexsoto approved these changes
Good to see you ❤️

2022-01-11 21:25 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5614638&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5614638/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/07bd477edd85c20c78657af225b64631)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/d8a99aefdbb53cb1d6153cbd1655631f)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/18b08de080c593e93d6a5b47f44f0a69)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/19aaaeccd45f95706b64a020beb78478)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/38f636b264250431b5e60587002cd65d)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/a455d2403d6c583380241de19e2104c8)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/26390c3d14d8cd32f8ff810a6d21381b)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/750bc5ad9d476ecb6a4f1781c736bc5f)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/f435a10cd84eb8c94f8c5eba0aee57e0)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/857bdb62e10f7beb98e2afa52b1670df)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/24b8789921f73bd331c65f98fbcfbe17)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/f8eb0019cde10a4027b6cff8bdfbead4)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/bf3cce032e1baf35ecf650f05dc98315)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/9b81b7bdc9e81385fee3fb6dec32ebd9)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/b24952f3bf0f4abd1bb44f52179ec242)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/b60f1298298be4891d9b8ddf8f8b9b26)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/a1b897bb8499f3a8cc0fa58650cb2a1a)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/bbcd1ab5c6ea7033130a6287a1a7dfcd)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/8200cee8a52f077cfe4995431f283836)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/e63427402abc9713acc9d460232787d7)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/a21bae26f7cbe36e7d3d893c0a25655d)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/e023e908f4b232b4123202b67e48e215)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/4c3301bf8cb44fa43c08a4ec0fed76d5)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/da791fbb3b1f578544ef7084d84952e2)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220111.8/5614638/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13668/5614638/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13668/5614638/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13668/5614638/apicomparison/api-diff.html)


# Test results

<details>
<summary>3 tests failed, 105 tests passed.</summary>

## Failed tests

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac [dotnet]/Debug [do [...]

2022-01-12 01:00 UTC, mandel-macaque commented
/azp run

2022-01-12 01:00 UTC, mandel-macaque commented
@spouliot  I wish I could let the bots run for you :(

2022-01-12 05:16 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5617530&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5617530/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/fe3bd0f2440f5db93e51091679903b8d)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/98ee9c3041668867d44bd6c77945a6ef)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/81a3df4b9de6b7942727e6d1403ffbea)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/dceaf875556ac07598380e5016bf2de4)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/f2b0fdf7f985fa536ba7329a63c17065)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/5b4dead0dc7f4e5ff69b0de21a579a20)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/c58a825b3a6c88a20f64cb56ecb62e6a)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/77f44211854446823cca59f6fc31ed5c)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/ab9570abca148eab425c6aa5d1c706f5)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/52b28d5eabea5d3099d2e5eea55382ed)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/40174a7786c6969dcff8197a285b9262)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/1488fff4bb6d7f1a3b050d21dd416c9c)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/99a3e12d59b9e48a04699bab0490c67c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/816e8d82b5d2d03e4432b8e2bd319758)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/148975d8692efcfeab263889e3f0936e)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/e47b6b6cc5c3149fb94794a774bdac7a)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/80f72493d5ac87d9e1c995b5bc2205b4)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/cecdbe521844081b3166c52c33b16cfa)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/955198603af154b65c521f563f05c3be)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/962c1ca59dc8c1e423430ab103417f01)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/dd30d857f70be16a4851531676c5d2c7)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/cfabf0143d29bb2894a0b060eacd75f7)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/33c5802751fa07ddd6a63f9d7e3167ba)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/c2f45283396533485d7c4611b5958c48)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.7/5617530/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13668/5617530/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13668/5617530/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13668/5617530/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 106 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug [d [...]

2022-01-12 12:37 UTC, rolfbjarne commented
> /Users/builder/azdo/_work/1/s/xamarin-macios/tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs(59,22): error CS1061: 'CGColorSpace' does not contain a definition for 'GetICCProfile' and no accessible extension method 'GetICCProfile' accepting a first argument of type 'CGColorSpace' could be found (are you missing a using directive or an assembly reference?) [/Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/tmp-test-dir/monotouch-test82/monotouch-test.csproj]

2022-01-12 15:36 UTC, spouliot commented
@rolfbjarne thanks for the link 😄 

Weird that it compiled for me... (might be a runner cache issue?) and I do get unrelated crashes on arm64 :|

Do you now have bots running arm64 ?
Or are there known issues ? I can file my crash as an issue (will clean my tree first to be 100% sure)

2022-01-12 19:22 UTC, rolfbjarne commented
> Do you now have bots running arm64 ?

No, we don't yet.

> Or are there known issues ?

Not that I know of.

> I can file my crash as an issue (will clean my tree first to be 100% sure)

Yes, please!

2022-01-13 00:03 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5620697&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5620697/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/9bc460d66cd2fe15037dc40fef7ee6f0)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/7bd99df8e2581fea0b5fbb3268ea1cfa)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/b7904a3ede52a6c5fd66631041f8690c)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c9b093df63d69009e95885660bd20b53)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/243cc16da7dee9094890c594db291d8d)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/08d740f3cc70ac4952d82f95107d925f)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/9a88cd04f8e7edeaa37d6b58efa7f8ba)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/87898babdd59ea48c872a1bf5bef63f1)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/d31d9c4b60310b7b84a4f54769d780c1)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/e119f3b5456fe5a40b9620061cf5d4c8)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/3b5b1df60492f34f72307955743ab3de)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/80a8b6899d6f34f94f85e6d9b43b219d)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/d951575a1ea43134a474c48d2168ba12)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/91fa130a694d65d27c6be1a38bc7667f)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/c45d1395d829e5babf1978b5f08cf416)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/5c0b7d2a7e107a5b177f31ea7fb5ca95)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/2f39494f1bd53305d4541c03ee312445)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/ee168a36bd522e04273a342437d788f0)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/1d05b0759061f0d0263218fdc62af876)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/6b1c9816e5f5bcb48b9e0f9f72ed356b)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/100368008fd34965419f90d3ebfe9452)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/7ce56211e4ab7bdd4d617c7145d5ed5b)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/6deefe49452e4065a91b126703217b4b)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/b3eef4bbbbfa6ffdc73261d3fe0bdd56)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.36/5620697/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13668/5620697/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13668/5620697/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13668/5620697/apicomparison/api-diff.html)


# Test results

<details>
<summary>2 tests failed, 106 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after [...]

2022-01-13 06:16 UTC, rolfbjarne commented
Test failures are unrelated:

* monotouch-test/Mac [dotnet]/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2537
* monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: https://github.com/xamarin/maccore/issues/2443

2022-01-13 06:17 UTC, rolfbjarne approved these changes

2022-01-13 06:18 UTC, merged