[CI] Refactor code out to a function.
xamarin/xamarin-macios pull request #13672
Opened 2022-01-11 17:10 UTC by mandel-macaque

Make the code more readable, this is the first step to clean the scripts
and to be able to add a switch so that we can diff between comments for
device tests and general comments.

I'll have to fix a conflict with https://github.com/xamarin/xamarin-macios/pull/13671 :/

2022-01-11 17:22 UTC, rolfbjarne approved these changes

2022-01-11 17:29 UTC, tj-devel709 requested changes
Misspelling in the function name, but everything else seems good!

2022-01-11 17:29 UTC, tj-devel709 commented on tools/devops/automation/scripts/GitHub.psm1
> +function Write-APIDiffCotent {
```suggestion
function Write-APIDiffContent {
```

2022-01-11 17:29 UTC, tj-devel709 commented on tools/devops/automation/scripts/GitHub.psm1
> +    Write-APIDiffCotent -StringBuilder $sb -APIDiff $APIDiff -APIGeneratorDiffJson $APIGeneratorDiffJson -APIGeneratorDiff $APIGeneratorDiff
```suggestion
    Write-APIDiffContent -StringBuilder $sb -APIDiff $APIDiff -APIGeneratorDiffJson $APIGeneratorDiffJson -APIGeneratorDiff $APIGeneratorDiff
```

2022-01-11 17:38 UTC, tj-devel709 approved these changes

2022-01-11 17:38 UTC, dalexsoto approved these changes

2022-01-12 05:34 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5617482&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5617482/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/ab6a5b8018d897f8195f1614c23ccd4c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/c36b3ba17135eca93b0ef669df5d1654)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/a3a06d3e5f993bb505a8d7a4644f8363)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/b84e0c48969e10421bc979056ee524a5)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/b53e7b2c393dc78892858eed8105a0a8)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/dd533ecbef266a9ca96728531b704163)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/2f54811710fd511e4699ad9c43f59f4a)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/ec3d5661e873a19ccdcf3b8650409324)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/d7c11200cadd55068110f3607242990d)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/a9dc3dc4bd7160136e6d3e1a0bb14d25)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/257cac07c9814fdcea8d3e364f5624af)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/07a5304169592023f0dd88d0019bbf36)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/97cee42c377e22887d1bcb75e1632dc2)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/3d755c923f8917f0d5af73256130a54e)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ae95a913d2740b666ef3adb5d319c502)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/826b6691a95b577a7e5d4fff57a900d3)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/adcbc7dff4d5f9f74f9349d8558c5538)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/a0ac4bf6f8f0677c0a7099c467f12cba)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/742d1e74a73fad68605ef75f3514ea44)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/227079f01181a817e48badc98d32d5d0)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/9db4de2d3ecc0cc7f8c3587779b09ce4)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/2c8a638e3ceb7fbb6e7e7221dd6e61fd)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/e7ba44c713a03dd215ffaba3807554f1)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/3b145ad865e557c6a26bb7206f853a48)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.5/5617482/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13672/5617482/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13672/5617482/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13672/5617482/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 104 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
Test run cr [...]

2022-01-12 21:54 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5619877&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5619877/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/ios-api-diff.html) 
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/mac-api-diff.html) 
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/tvos-api-diff.html) 
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/watchos-api-diff.html) 
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/0623ce15c019dfa760b93794f1936975)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/45d4448b608c3cf34303ade9c34b3ac0)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/d8698673686cd30ca26d9b94798db2e9)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/d997dd11cc5e21ff4b5e24ec9f59f258)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/c8b963ca5365ad89b3eec2aac2ec977a)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/ff08491b89da8265d860bf8e49af2a58)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/1f1f8bdf6e8e05f92c7615c2eee7327c)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/0bea461933919ee8752bd271c2e91fdd)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/1c27689d380236ee4658682724db4d93)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/8e609a9f35ada4854d4a0c7bd24c4342)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/f19ed59c1c149ebe6db38fd1921749e7)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/fb969e33a3d85366f56cee5d13eaa51a)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220112.33/5619877/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13672/5619877/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13672/5619877/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13672/5619877/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 104 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
Test run crashed)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5619877&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur'
Merge c4f761db932532cfca84c739f8456158c64323d4 into 17fbe27c1adda70dfed10f13f13292f2f16ea2ee

2022-01-13 01:09 UTC, merged