[coremedia] Modernize types
xamarin/xamarin-macios pull request #13880
Opened 2022-01-25 18:24 UTC by spouliot

* Use `is` instead of `==` for null checks
* Use `ThrowHelper` to throw common exceptions
* Use faster `CFString` API (over the slower `NSString` variants)
* Use `HashCode.Combine` for net profile

2022-01-25 18:58 UTC, chamons commented
/azp run

2022-01-25 22:58 UTC, tj-devel709 approved these changes

2022-01-25 23:55 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5668912&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5668912/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/9954f1e2a8e4e84ecbfb43257af8c93a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/e5d711627962294b42d6d2e8152f1994)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/0fef80fb6110231c66c273732b43ac7d)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/70c03b290a9711f63f87d20e10b7cee4)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/12a03ad87f2dbfca0144d4fd8bcba0be)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/efef66a71045b8dfb5acb05a78092064)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/8469a1ee14b216c2db576dcba71a0f3a)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/23934800c489ff74d0c65fb46abf3990)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/7b4c3e2b482dfd4a67ed3d0b49b781d8)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/1a199a4fc4380673f4e7c57d19ef1fcd)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/3a7ee580dbef41fc2d4f8d2e6219b8a9)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/70d9dbfc999d48ae03a31a1fcaba38ab)
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/75078d6838ca40a9b811c100061590d8)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/4e5bbcf7a91b52435554dff762755915)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/935ea5b466c2bd6cc23a297bb47b36c5)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/37fea88b312177c6b80cb8009ec5292f)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/e282f8fb798cdb28a3c396f92a9ef30d)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/5ef9db6933b74dfbb1a4201b686f0441)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/598e448f376e40513d14a9d0a4ee92a1)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/72eb0e689596429a8750d08abe8874e7)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/28cf2c325fa33c2647439cd95418ad65)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/d0b1bea77da51e4cf0f881d4e2c0ae97)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/3a903fac528b5b4b8cc063e6cbc76cbc)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/57f7fbf4a6180fb3a82183e0cd20e235)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220125.56/5668912/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13880/5668912/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13880/5668912/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13880/5668912/apicomparison/api-diff.html)


# :tada: All 108 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5668912&view=ms.vss-test-web.test-res [...]

2022-01-26 08:20 UTC, rolfbjarne requested changes

2022-01-26 08:20 UTC, rolfbjarne commented on src/CoreMedia/CMFormatDescription.cs
> +				ObjCRuntime.ThrowHelper.ThrowArgumentException ("must contain at least three elements", nameof (parameterSets));
Argument name comes first, then the message:

```suggestion
				ObjCRuntime.ThrowHelper.ThrowArgumentException (nameof (parameterSets), "must contain at least three elements");
```

2022-01-26 08:20 UTC, rolfbjarne commented on src/CoreMedia/CMSampleBuffer.cs
> +				ObjCRuntime.ThrowHelper.ThrowArgumentException ("Only a single sample is allowed.", nameof (sampleTiming));
Same

2022-01-27 16:27 UTC, rolfbjarne approved these changes

2022-01-27 16:27 UTC, rolfbjarne commented
/azp run

2022-01-27 21:49 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5679536&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5679536/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/cc3df990a91738fe4801da862ff56ebe)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/cc3df990a91738fe4801da862ff56ebe)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/cc3df990a91738fe4801da862ff56ebe)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/cc3df990a91738fe4801da862ff56ebe)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/c14fee4ec371ed1dabff550998953d47)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/d134a851d901e7aacb58190beb4ac8ba)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/a91fd65271de8f2fa58e8ceb52c3ea36)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/5147ee7f2ef37412d427984aad7ab7a7)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/d578098322ff48a7e6718ca8c4826e4b)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/2ddf01cc8d9447a69e0cc87f9fb657c7)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/051815ea8cdce985f83d8fcc959a6020)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/14faa3ebdfb7c7a0040bedb7dd64268d)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.48/5679536/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13880/5679536/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13880/5679536/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13880/5679536/apicomparison/api-diff.html)


# :tada: All 108 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5679536&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1101.BigSur'
Merge 5c9ea8342f7ca5d52d9840d2d12f5fb797aefcb9 into cf043fa78733a829d7e0649d2157d463d06a1c2d

2022-01-28 09:18 UTC, merged