[NET 6 Attribute Conversion] Foundation
xamarin/xamarin-macios pull request #13905
Opened 2022-01-26 19:14 UTC by chamons

2022-01-26 19:43 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests didn't execute on Build. :x:

Tests didn't execute on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5674679&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.54/5674679/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5674679/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
* :warning: API diff urls have not been provided.
* :warning: API Current PR diff urls have not been provided.
* :warning: Generator diff comments have not been provided.
# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13905/5674679/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13905/5674679/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13905/5674679/apicomparison/api-diff.html)


No test summary was found (something probably failed before the tests could execute)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5674679&view=ms.vss-test-web.test-result-details) on Agent 
Merge 61727e71395d873f624813324467cb02a815d626 into 9695bf2182fb127e936b72a1e447626fa2cde9fe

2022-01-26 21:51 UTC, mandel-macaque approved these changes

2022-01-27 01:24 UTC, dalexsoto approved these changes
👍

2022-01-27 06:56 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5675730&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5675730/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/092625a0a20f9162f495237975e3b912)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/092625a0a20f9162f495237975e3b912)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/092625a0a20f9162f495237975e3b912)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/092625a0a20f9162f495237975e3b912)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/85c0fa049c65b8eeb108ea04fff9500d)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/1f8c90e7bd501d843a31306c413cdca6)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/76b0b6ba65dc1e7d9898bc2688bdf7fe)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/62e2357678b5d772c4f4c9a60ab1a96f)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/c6d791f42b4b72f209382d6e54933e9a)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/88b1a6ec7feefefeec498507313e53f5)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/27a5a7f19e02e9ab8e4ae7c5a6b7bb08)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/a1fe5ca9b8545782b24f1dedea4c6b89)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220126.69/5675730/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13905/5675730/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13905/5675730/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13905/5675730/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 147 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2767 Passed: 2570 Inconclusive: 11 Failed: 2 Ignored: 195)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5675730&view=ms.vss-test-web.test-result-details) on Agent XAMMINI-061.BigSur'
Merge 96972e5b6f3c04a80bb0b2e6a71924590ce041d2 into 401bf76d70571ad79f280d0db82ca159cb928d2b

2022-01-27 08:50 UTC, rolfbjarne requested changes

2022-01-27 08:50 UTC, rolfbjarne commented on src/Foundation/NSMetadataItem.cs
> +		[SupportedOSPlatform ("ios8.0")]
This is inside a !NET block from the #if NET just above, so it won't do the right thing. These attributes should be moved into the block above instead.

2022-01-27 08:50 UTC, rolfbjarne commented on src/Foundation/NSMetadataItem.cs
> +		[SupportedOSPlatform ("ios8.0")]
Same.

2022-01-28 08:01 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5680741&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5680741/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/908617d0f019edcba946a21e5d39654b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/908617d0f019edcba946a21e5d39654b)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/908617d0f019edcba946a21e5d39654b)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/908617d0f019edcba946a21e5d39654b)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/4b5021c2ee9adef87ea85b0955c04d8b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/c56c2feb41d71df9bf3e67cf7a1acd50)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/5dcc002d69503ac29598a60134d86b4a)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/e1e9ce91c0b3def2c0245b9f89895613)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/8fdca54f80dbf15ec071b9588fa39b2d)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/a0630eccdd6c7845774aad85e80bc565)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/e5f112bbe282fb7a6fd97c8de8087a72)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/51d75dac74227eb41eadd931183bb5d0)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220127.69/5680741/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13905/5680741/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13905/5680741/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13905/5680741/apicomparison/api-diff.html)


# Test results

<details>
<summary>5 tests failed, 143 tests passed.</summary>

## Failed tests

 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: TimedOut (Execution timed out after 1200 seconds.
No test log file was produced)
 * link sdk/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 117 Passed: 107 Inconclusive: 0 Failed: 1 Ignored: 9)
 * link sdk/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 129 Passed: 119 Inconclusive: 0 Failed: 1 Ignored: 9)
 * link sdk/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run failed.
Tests run: 129 Passed: 118 Inconclusive: 0 Failed: 1 Ignored: 10)
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 134).
Tests run: 11 Passed: 6 Inconclusive: 0 Failed: 0 Ignored: 5)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5680741&view=ms.vss-test-web.test-result-details) on Agent [...]

2022-01-28 12:55 UTC, rolfbjarne approved these changes

2022-01-31 19:31 UTC, chamons commented
Rekicking due to possibly flaky tests

2022-02-01 02:38 UTC, vs-mobiletools-engineering-service2 commented
### :x: [PR Build] Tests failed on Build :x:

Tests failed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5692983&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5692983/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/ios-api-diff.html) 
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/mac-api-diff.html) 
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/tvos-api-diff.html) 
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/watchos-api-diff.html) 
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/52010ed963ddc46ad750bdd5979d2c81)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/0e0101268c0ceaaa64adb3e625b15aa9)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/d4a7a773aae658e8ac7754e2f9be363c)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/993cd98cf928475aeb9ba45cf3717101)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/c970fbfbac0778c0fa107bc151d6ae6a)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/838d821234c22421db544f95146ccb05)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/c785c5fbbdefc186a9f95e34b4515a1f)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/695bbd85960c265f7609a72dc23dc188)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) 
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220131.51/5692983/apigeneratordiff/;//generator-diff/index.html) (no change)

# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR13905/5692983/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR13905/5692983/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR13905/5692983/apicomparison/api-diff.html)


# Test results

<details>
<summary>1 tests failed, 147 tests passed.</summary>

## Failed tests

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2764 Passed: 2570 Inconclusive: 11 Failed: 2 Ignored: 192)
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5692983&view=ms.vss-test-web.test-result-details) on Agent XAMMINI-061.BigSur'
Merge dab6f68208e17ed38257a8f54da59e2403e28773 into a16c79c50a9a27af87217ba2250b78f6f3da91ef

2022-02-01 17:23 UTC, chamons commented
https://github.com/xamarin/maccore/issues/2443 strikes again.

2022-02-01 17:23 UTC, merged