[CI] Do not show a warning if we cannot disable the lock screen.
xamarin/xamarin-macios pull request #14361
Opened 2022-03-10 17:34 UTC by mandel-macaque

If we have an issue unlocking the UI prompt we continue on error. This
is considered a warning in the pipeline, but doing so teaches users to
ignore warnings and will result in us ignoring real actual issues.
Setting the step to not have a warning will ensure that we only see
warnings that we care about.

2022-03-10 19:58 UTC, rolfbjarne requested changes

2022-03-10 19:58 UTC, rolfbjarne commented on tools/devops/automation/templates/common/setup.yml
> +    if [ $RC -eq 0 ]; then
RC will never be 0, because `RC=$?` won't be executed in that case.

You need to do `RC=0` first.

2022-03-10 21:10 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5864773&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5864773/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/ios-api-diff.html) 
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/mac-api-diff.html) 
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/tvos-api-diff.html) 
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/watchos-api-diff.html) 
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) 
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/ios-api-diff.html) 
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/mac-api-diff.html) 
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/tvos-api-diff.html) 
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/watchos-api-diff.html) 
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.18/5864773/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) 
</details>


* :warning: Generator diff comments have not been provided.
# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR14361/5864773/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR14361/5864773/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR14361/5864773/apicomparison/api-diff.html)


# :tada: All 105 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5864773&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1109.Monterey'
Merge 70349d8541956730e561ccdd9f126f4dd973c555 into d8d90572ce8cdd1b88c719abc551bdc456ae766e

2022-03-10 21:53 UTC, rolfbjarne approved these changes

2022-03-11 00:16 UTC, dalexsoto approved these changes

2022-03-11 00:54 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [PR Build] Tests passed on Build. :white_check_mark:

Tests passed on Build. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5866144&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/sim/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5866144/artifacts?artifactName=HtmlReport-sim&api-version=6.0&$format=zip)
# API diff
:white_check_mark: API Diff from stable
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/ios-api-diff.html) 
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/mac-api-diff.html) 
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/tvos-api-diff.html) 
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/watchos-api-diff.html) 
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) 
</details>


# API Current PR diff
:information_source: API Diff (from PR only) (please review changes)
<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/ios-api-diff.html) 
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/mac-api-diff.html) 
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/tvos-api-diff.html) 
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/watchos-api-diff.html) 
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) 
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) 
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.Mac-api-diff.html) 
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) 
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220310.30/5866144/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) 
</details>


* :warning: Generator diff comments have not been provided.
# GitHub pages

Results can be found in the following github pages (it might take some time to publish):

* [Test results](https://xamarin.github.io/macios.ci/pr/PR14361/5866144/HtmlReport-sim/tests/vsdrops_index.html)
* [API diff ](https://xamarin.github.io/macios.ci/pr/PR14361/5866144/HtmlReport-sim/api-diff/api-diff.html)
* [API & Generator diff](https://xamarin.github.io/macios.ci/pr/PR14361/5866144/apicomparison/api-diff.html)


# :tada: All 105 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5866144&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1105.Monterey'
Merge d354e88bd77601a46c5ab427d623ed24a2a4d0f6 into 23c8620af087d3da00d41fd2c218cff8879c97a2

2022-03-11 04:09 UTC, merged