[nnyeah] Add tool to be made via makefiles.
xamarin/xamarin-macios pull request #14513
Opened 2022-03-25 20:23 UTC by mandel-macaque

Adding the needed Makefile and the dir to the parent one so that the
tool is also built in the CI.

2022-03-25 20:23 UTC, chamons approved these changes

2022-03-25 20:29 UTC, dalexsoto approved these changes

2022-03-28 06:56 UTC, rolfbjarne requested changes

2022-03-28 06:56 UTC, rolfbjarne commented on tools/nnyeah/Makefile
> +bin/Debug/net5.0/nnyeah.dll: $(wildcard **/*.cs) $(wildcard **/*.csproj) $(wildcard *.snl) Makefile
```suggestion
bin/Debug/net5.0/nnyeah.dll: $(wildcard **/*.cs) $(wildcard **/*.csproj) $(wildcard *.sln) Makefile
```

2022-03-28 06:56 UTC, rolfbjarne commented on tools/nnyeah/Makefile
> +	$(Q_BUILD) $(SYSTEM_MSBUILD) "/bl:$@.binlog" /restore $(MSBUILD_VERBOSITY) $(wildcard *.snl)
```suggestion
	$(Q_BUILD) $(SYSTEM_DOTNET) build "/bl:$@.binlog" /restore $(MSBUILD_VERBOSITY) $(wildcard *.sln)
```

2022-03-28 06:56 UTC, rolfbjarne commented on tools/nnyeah/Makefile
> +	$(Q_BUILD) $(SYSTEM_MSBUILD) "/bl:$@.binlog" /restore $(MSBUILD_VERBOSITY) /t:Clean $(wildcard *.snl)
```suggestion
	$(Q_BUILD) $(SYSTEM_DOTNET) build "/bl:$@.binlog" /restore $(MSBUILD_VERBOSITY) /t:Clean $(wildcard *.sln)
```

2022-03-28 15:53 UTC, merged