[gamecontroller] Add nullability to (generated and manual) bindings
xamarin/xamarin-macios pull request #14612
Opened 2022-04-01 17:22 UTC by tj-devel709

This PR aims to bring nullability changes to GameController.
Following the steps [here](https://github.com/xamarin/xamarin-macios/wiki/Nullability):

1. I am adding `nullable enable` to all manual files that are not "API_SOURCES" in src/frameworks.sources and making the required nullability changes
2. Changing any `== null` or `!= null` to `is null` and `is not null`

2022-04-01 19:07 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: Tests on macOS Mac Catalina (10.15) passed :white_check_mark:

Tests passed

**All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5971202&view=ms.vss-test-web.test-result-details) on Agent 
Merge 0be1ba20a8985ed9c5cc7618d7c859b8405dfb00 into 180b561cfe235a02406daf53c3e68b19d0fb5f3b

2022-04-01 19:18 UTC, vs-mobiletools-engineering-service2 commented
### :x: Tests on macOS M1 - Mac Big Sur (11.5) failed :x:


Tests timed out


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=5971202&view=ms.vss-test-web.test-result-details) on Agent 
Merge 0be1ba20a8985ed9c5cc7618d7c859b8405dfb00 into 180b561cfe235a02406daf53c3e68b19d0fb5f3b

2022-04-01 19:47 UTC, stephen-hawley reviewed
Later on in the GCMotion.cs - is this valid?
```
public GCDualSenseAdaptiveTriggerPositionalAmplitudes (float [] values)
		{
			if (values is null)
				ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (values));
```

if I write this:
```
		public void Foo (float [] values)
		{
			if (values is null)
				throw new ArgumentNullException (nameof (values));
		}

		public void UseFoo ()
		{
			Foo (null);
		}
```
In trying to call Foo, I get "Cannot convert null literal to non-null reference type"

2022-04-01 20:54 UTC, mandel-macaque approved these changes

2022-04-01 21:24 UTC, tj-devel709 commented
> Later on in the GCMotion.cs - is this valid?
> 
> ```
> public GCDualSenseAdaptiveTriggerPositionalAmplitudes (float [] values)
> 		{
> 			if (values is null)
> 				ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (values));
> ```
> 
> if I write this:
> 
> ```
> 		public void Foo (float [] values)
> 		{
> 			if (values is null)
> 				throw new ArgumentNullException (nameof (values));
> 		}
> 
> 		public void UseFoo ()
> 		{
> 			Foo (null);
> 		}
> ```
> 
> In trying to call Foo, I get "Cannot convert null literal to non-null reference type"

@stephen-hawley  hmmm interesting point, I think maybe this would fall under what @mandel-macaque  said here https://github.com/xamarin/xamarin-macios/pull/14611#discussion_r840913912 that if someone doesn't have nullability enabled on their project, they won't see the compiler error

2022-04-01 22:35 UTC, vs-mobiletools-engineering-service2 commented
### :x: [CI Build] Tests failed on VSTS: simulator tests iOS :x:

Tests failed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5971202&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220401.42/5971202/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/5971202/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * link all/watchOS 32-bits - simulator/Debug: Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=5971202&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1035.Monterey'
Merge 0be1ba20a8985ed9c5cc7618d7c859b8405dfb00 into 180b561cfe235a02406daf53c3e68b19d0fb5f3b

2022-04-03 22:55 UTC, dalexsoto approved these changes

2022-04-04 07:02 UTC, rolfbjarne requested changes

2022-04-04 07:02 UTC, rolfbjarne commented on src/GameController/GCExtendedGamepadSnapshot.cs
>  		public static bool TryGetExtendedSnapShotData (NSData data, out GCExtendedGamepadSnapshotData snapshotData)
Same:

```suggestion
		public static bool TryGetExtendedSnapShotData (NSData? data, out GCExtendedGamepadSnapshotData snapshotData)
```

2022-04-04 07:02 UTC, rolfbjarne commented on src/GameController/GCExtendedGamepadSnapshot.cs
>  		public static bool TryGetSnapShotData (NSData data, out GCExtendedGamepadSnapShotDataV100 snapshotData)
If the parameter can be null, you should also change it to say as much:

```suggestion
		public static bool TryGetSnapShotData (NSData? data, out GCExtendedGamepadSnapShotDataV100 snapshotData)
```

2022-04-04 07:02 UTC, rolfbjarne commented on src/GameController/GCGamepadSnapshot.cs
>  		public static bool TryGetSnapshotData (NSData data, out GCGamepadSnapShotDataV100 snapshotData)
```suggestion
		public static bool TryGetSnapshotData (NSData? data, out GCGamepadSnapShotDataV100 snapshotData)
```

2022-04-04 07:02 UTC, rolfbjarne commented on src/GameController/GCMicroGamepadSnapshot.cs
>  		public static bool TryGetSnapshotData (NSData data, out GCMicroGamepadSnapShotDataV100 snapshotData)
```suggestion
		public static bool TryGetSnapshotData (NSData? data, out GCMicroGamepadSnapShotDataV100 snapshotData)
```

2022-04-04 07:02 UTC, rolfbjarne commented on src/GameController/GCMicroGamepadSnapshot.cs
>  		public static bool TryGetSnapshotData (NSData data, out GCMicroGamepadSnapshotData snapshotData)
```suggestion
		public static bool TryGetSnapshotData (NSData? data, out GCMicroGamepadSnapshotData snapshotData)
```

2022-04-08 15:17 UTC, vs-mobiletools-engineering-service2 commented
# :books: Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/delete-xma-build-host.pkg)
* [Microsoft.iOS.Bundle.15.4.200-ci.pr.gh14612.61.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Bundle.15.4.200-ci.pr.gh14612.61.pkg)
* [Microsoft.iOS.Ref.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Ref.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Runtime.ios-arm.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Runtime.ios-arm64.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Sdk.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Sdk.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Templates.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Templates.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.iOS.Windows.Sdk.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.200-ci.pr.gh14612.61.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.MacCatalyst.Bundle.15.4.200-ci.pr.gh14612.61.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.MacCatalyst.Ref.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.MacCatalyst.Sdk.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.MacCatalyst.Templates.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.macOS.Bundle.12.3.200-ci.pr.gh14612.61.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.macOS.Bundle.12.3.200-ci.pr.gh14612.61.pkg)
* [Microsoft.macOS.Ref.12.3.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.macOS.Ref.12.3.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.macOS.Runtime.osx-arm64.12.3.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.macOS.Runtime.osx-x64.12.3.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.macOS.Sdk.12.3.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.macOS.Sdk.12.3.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.macOS.Templates.12.3.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.macOS.Templates.12.3.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.200-ci.pr.gh14612.61.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.NET.Workload.iOS.15.4.200-ci.pr.gh14612.61.msi)
* [Microsoft.tvOS.Bundle.15.4.200-ci.pr.gh14612.61.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.tvOS.Bundle.15.4.200-ci.pr.gh14612.61.pkg)
* [Microsoft.tvOS.Ref.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.tvOS.Ref.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.200-ci.pr.gh14612.61.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/abf7380e84eb732bcb27059723bb97c88f45a5e1/6000501/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.200-ci.pr.gh14612.61.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.200-ci.pr.gh [...]

2022-04-08 15:37 UTC, vs-mobiletools-engineering-service2 commented
### :fire: Tests failed catastrophically on VSTS: simulator tests iOS (no summary found). :fire:

Result file D:\a\1\s\Reports\TestSummary-simulator\TestSummary.md not found. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6000501&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220408.11/6000501/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6000501/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6000501&view=ms.vss-test-web.test-result-details) on Agent 
Merge 04e40a7af29d6a9689ba3a37cd62c54e9163298f into aa98164c0fd7ade2df8417fe3ffc926fe35ad019

2022-04-08 15:41 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: Tests on macOS Mac Catalina (10.15) passed :white_check_mark:

Tests passed

**All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6000501&view=ms.vss-test-web.test-result-details) on Agent 
Merge 04e40a7af29d6a9689ba3a37cd62c54e9163298f into aa98164c0fd7ade2df8417fe3ffc926fe35ad019

2022-04-08 16:09 UTC, vs-mobiletools-engineering-service2 commented
### :x: Tests on macOS M1 - Mac Big Sur (11.5) failed :x:


Tests timed out


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6000501&view=ms.vss-test-web.test-result-details) on Agent 
Merge 04e40a7af29d6a9689ba3a37cd62c54e9163298f into aa98164c0fd7ade2df8417fe3ffc926fe35ad019

2022-04-09 16:41 UTC, vs-mobiletools-engineering-service2 commented
# :books: Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/delete-xma-build-host.pkg)
* [Microsoft.iOS.Bundle.15.4.300-ci.pr.gh14612.7.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Bundle.15.4.300-ci.pr.gh14612.7.pkg)
* [Microsoft.iOS.Ref.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Ref.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Runtime.ios-arm.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Runtime.ios-arm64.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Sdk.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Sdk.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Templates.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Templates.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.iOS.Windows.Sdk.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.300-ci.pr.gh14612.7.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.MacCatalyst.Bundle.15.4.300-ci.pr.gh14612.7.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.MacCatalyst.Ref.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.MacCatalyst.Sdk.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.MacCatalyst.Templates.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.macOS.Bundle.12.3.300-ci.pr.gh14612.7.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.macOS.Bundle.12.3.300-ci.pr.gh14612.7.pkg)
* [Microsoft.macOS.Ref.12.3.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.macOS.Ref.12.3.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.macOS.Runtime.osx-arm64.12.3.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.macOS.Runtime.osx-x64.12.3.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.macOS.Sdk.12.3.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.macOS.Sdk.12.3.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.macOS.Templates.12.3.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.macOS.Templates.12.3.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.300-ci.pr.gh14612.7.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.NET.Workload.iOS.15.4.300-ci.pr.gh14612.7.msi)
* [Microsoft.tvOS.Bundle.15.4.300-ci.pr.gh14612.7.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.tvOS.Bundle.15.4.300-ci.pr.gh14612.7.pkg)
* [Microsoft.tvOS.Ref.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.tvOS.Ref.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dce0891ffb51dbd1a5f9b95a8e0468769d869724/6005122/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.300-ci.pr.gh14612.7.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.300-ci.pr.gh14612.7.nupkg](https://bosstoragemirror.blob.core.windows.net/ [...]

2022-04-09 16:43 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: API Diff :clipboard:

# API Current PR diff

:white_check_mark: API Diff (from PR only) (no change)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/83492a10b8b5da94588bf9e770704874)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/8103f78f0b672ea375b2c0a1726e2d60)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/5cc0f221c48797f00f8657f2c19aace4)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/79f73bf5738e62a924350af2394193e8)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/2bfe8a21028aa63af6be078470d056a1)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/52fa50694b536b824eb65f28b135e8c7)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/1ec5c1f32a680e0aac7832a100064738)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/a547cc9856e38d8ad04d09ff09a5ef03)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/4e172913c0f01984892b64c76c3e94d7)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/5f070f91d9464a99b0a3836ee01ee9fa)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/0f577a29811ec3aedbfd811f1bf563d3)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/26c0e565a7426dcb8cc3e0c993b0a440)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/60084c53e6edae45a09c17a5ffdddec3)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/7d4605caebe525c4d1b5a6bccc31b5e2)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/39d8df5db9064b39d7790a2fa206e6a2)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/7b4b508636e4c14d125f798cd1b20e49)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/92b6f4d79aeb8ba8070f24189011b2af)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/65aab32bd1a1eeaba3231313d0c21908)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/e39d398962c4d015ddeef84462e1fa65)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Xamarin.MacCatalyst-api-diff.html) [gist](https://gist.github.com/25b362303a2c56fc5a735ed55d866e66)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS-api-diff.html) [gist](https://gist.github.com/9ad1326a10abf9c3915611e07c6bf916)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Xamarin.Mac-api-diff.html) [gist](https://gist.github.com/63c4ddeb7b7a7ef844053241dd462d2d)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Xamarin.TVOS-api-diff.html) [gist](https://gist.github.com/87dc1b0de0f76a0f6e2599f841907810)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Xamarin.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/e138d5986ae743b29a43f4762a5afbbb)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6005122&view=ms.vss-test-web.test-result-details) on Agent 
Merge abe62de1aa957a90862cc76e2f57256fd46b4ee4 into b9d95213c4c9bb8447f0ce2bc768dce454b80f20

2022-04-09 16:59 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: Tests on macOS Mac Catalina (10.15) passed :white_check_mark:

Tests passed

**All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6005122&view=ms.vss-test-web.test-result-details) on Agent 
Merge abe62de1aa957a90862cc76e2f57256fd46b4ee4 into b9d95213c4c9bb8447f0ce2bc768dce454b80f20

2022-04-09 19:54 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6005122&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220409.12/6005122/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6005122/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 108 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6005122&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1023.Monterey'
Merge abe62de1aa957a90862cc76e2f57256fd46b4ee4 into b9d95213c4c9bb8447f0ce2bc768dce454b80f20

2022-04-11 14:18 UTC, tj-devel709 commented
@rolfbjarne this one is ready for when you return :)

2022-04-19 13:09 UTC, rolfbjarne approved these changes

2022-04-20 21:07 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API Current PR diff

:white_check_mark: API Diff (from PR only) (no change)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/995c2a230e7d761755fac672531370bc)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/a83b27deecf3aac1d79448fea0244d45)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/e1ef91b8527c85688c1e2b89d022ade3)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/ac66905d48a2acf9bf246bf9d1b2e1fe)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/5f7ac41f027999cf2ffa00b4ce9c2b17)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/def03ffc16abe6dd466d92512e940aa0)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/dfa849be578706b96a3ae21736a7a327)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/80c2ac060e980064ae699cd0e9edeea0)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/b7ab93b39a24158a92da68eff9fcd1d7)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/07957cc1060c6e5b57db344383bdf90e)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/40c2c22a0639548ff1d81db2ddfc7a5d)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/05219ea51fb2eb837efe3e1f90880d8a)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/73f847adbd4c9a501689f73967a61e50)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/72c47222074ee6c75045e82541c1c599)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/2dd44e8e93d43d5022007c5e685837d2)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/fb79f70cb1785e96be4dfe2e8929ba96)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/46777cf8d07f3e8f711381c60a1a286b)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/009e8b64ccd2af98f2d10a1ec573cf02)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/3220d3d283e65df17c9deddda5439554)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/7c8f8f75a75eea35c8fbfee84f9b1686)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/7b9d9fb084054ad683b9ea2d46ac15fb)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/cccb54802c798ee434f75619b928688a)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/5460422d60fc3bd9b8280598336e2e0d)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/bf2fbde783b86400d130e98fe0415732)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6050160&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1108.Monterey'
Hash: [460be52821a79e1a54f8b1606e0ca8044981b201](https://github.com/xamarin/xamarin-macios/pull/14612/commits/460be52821a79e1a54f8b1606e0ca8044981b201)

2022-04-20 21:09 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/delete-xma-build-host.pkg)
* [Microsoft.iOS.Bundle.15.4.300-ci.pr.gh14612.57.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Bundle.15.4.300-ci.pr.gh14612.57.pkg)
* [Microsoft.iOS.Ref.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Ref.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Runtime.ios-arm.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Runtime.ios-arm64.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Sdk.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Sdk.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Templates.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Templates.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.iOS.Windows.Sdk.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.300-ci.pr.gh14612.57.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.MacCatalyst.Bundle.15.4.300-ci.pr.gh14612.57.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.MacCatalyst.Ref.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.MacCatalyst.Sdk.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.MacCatalyst.Templates.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.macOS.Bundle.12.3.300-ci.pr.gh14612.57.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.macOS.Bundle.12.3.300-ci.pr.gh14612.57.pkg)
* [Microsoft.macOS.Ref.12.3.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.macOS.Ref.12.3.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.macOS.Runtime.osx-arm64.12.3.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.macOS.Runtime.osx-x64.12.3.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.macOS.Sdk.12.3.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.macOS.Sdk.12.3.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.macOS.Templates.12.3.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.macOS.Templates.12.3.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.300-ci.pr.gh14612.57.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.NET.Workload.iOS.15.4.300-ci.pr.gh14612.57.msi)
* [Microsoft.tvOS.Bundle.15.4.300-ci.pr.gh14612.57.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.tvOS.Bundle.15.4.300-ci.pr.gh14612.57.pkg)
* [Microsoft.tvOS.Ref.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.tvOS.Ref.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.300-ci.pr.gh14612.57.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/a75e64f5d3c0ebc33a287f1e992d575e3e695e6d/6050160/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.300-ci.pr.gh14612.57.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.3 [...]

2022-04-20 21:37 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6050160&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [460be52821a79e1a54f8b1606e0ca8044981b201](https://github.com/xamarin/xamarin-macios/pull/14612/commits/460be52821a79e1a54f8b1606e0ca8044981b201)

2022-04-20 21:44 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6050160&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [460be52821a79e1a54f8b1606e0ca8044981b201](https://github.com/xamarin/xamarin-macios/pull/14612/commits/460be52821a79e1a54f8b1606e0ca8044981b201)

2022-04-21 04:52 UTC, vs-mobiletools-engineering-service2 commented
### :x: [CI Build] Tests failed on VSTS: simulator tests iOS :x:

Tests failed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6050160&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220420.22/6050160/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6050160/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# Test results

<details>
<summary>2 tests failed, 146 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar) [dotnet]: Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6050160&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1042.Monterey
Merge 460be52821a79e1a54f8b1606e0ca8044981b201 into 7d229665c88b692bcd28bbf3992b498820b0ccf8

2022-04-21 17:55 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/delete-xma-build-host.pkg)
* [Microsoft.iOS.Bundle.15.4.300-ci.pr.gh14612.64.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Bundle.15.4.300-ci.pr.gh14612.64.pkg)
* [Microsoft.iOS.Ref.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Ref.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Runtime.ios-arm.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Runtime.ios-arm64.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Sdk.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Sdk.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Templates.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Templates.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.iOS.Windows.Sdk.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.300-ci.pr.gh14612.64.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.MacCatalyst.Bundle.15.4.300-ci.pr.gh14612.64.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.MacCatalyst.Ref.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.MacCatalyst.Sdk.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.MacCatalyst.Templates.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.macOS.Bundle.12.3.300-ci.pr.gh14612.64.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.macOS.Bundle.12.3.300-ci.pr.gh14612.64.pkg)
* [Microsoft.macOS.Ref.12.3.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.macOS.Ref.12.3.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.macOS.Runtime.osx-arm64.12.3.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.macOS.Runtime.osx-x64.12.3.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.macOS.Sdk.12.3.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.macOS.Sdk.12.3.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.macOS.Templates.12.3.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.macOS.Templates.12.3.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.300-ci.pr.gh14612.64.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.NET.Workload.iOS.15.4.300-ci.pr.gh14612.64.msi)
* [Microsoft.tvOS.Bundle.15.4.300-ci.pr.gh14612.64.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.tvOS.Bundle.15.4.300-ci.pr.gh14612.64.pkg)
* [Microsoft.tvOS.Ref.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.tvOS.Ref.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.300-ci.pr.gh14612.64.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/697eb375897dc2ed5d96a469b86c6e380d3e1856/6054282/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.300-ci.pr.gh14612.64.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.3 [...]

2022-04-21 17:59 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API Current PR diff

:white_check_mark: API Diff (from PR only) (no change)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/8dfc174bc28a12db2778436685992ec5)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/c1d35c1d76704694bc2fe3a17f9136f9)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/0a8cf93e02b96c53856c273a6b3d9052)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/37c219c5c4997322e4bb22563a9d29f3)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/62ddd54a62935d0e0ff669fe6bff8d6e)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/ad56ab3ffeb87d37c2a98739f1ca8036)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/db0a960cd033f35bb6a16eec814d81f3)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/e8808aae9b7101e1d3034fe7d6d1d3f7)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/cf30d4fb0fccbc0ed3a5465a0061bd89)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/7c5b65dff33a7145660a46f1b9d49854)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/027a2847dd97df1dc6ff73f1060aaa9d)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/d93c424e5b945ec730acd9cec13bf215)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/9fb31269ae6323118bbe0a2dbe803253)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/c7a7ccb94fd3c5b79f137d5bc445bc1c)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ec6f678c5ba9346e57aa73fe5708e86b)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/e683b77c44befe74e338dda5b164e35f)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/973e66acb4200c9974df336f9212b180)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/cb4614d5ca006bf606aaafe592440a2b)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/5effc907d5404a1ca87edc117f0592c0)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/60a778c041cd43ea77da2c918a97ac56)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/ca106605ee5610c3235e5ade485a2861)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/57d1e6b91bebc5feaf4acc6214d51fba)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/c112dadc172ccfec647d8e5825f88472)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/aeb6e5e5ce4c44960e4dc2425d5d1037)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6054282&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1039.Monterey
Hash: [b17e70804c5bb9d258dacf1f923734d75466ae0c](https://github.com/xamarin/xamarin-macios/pull/14612/commits/b17e70804c5bb9d258dacf1f923734d75466ae0c)

2022-04-21 18:23 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6054282&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b17e70804c5bb9d258dacf1f923734d75466ae0c](https://github.com/xamarin/xamarin-macios/pull/14612/commits/b17e70804c5bb9d258dacf1f923734d75466ae0c)

2022-04-21 18:31 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6054282&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b17e70804c5bb9d258dacf1f923734d75466ae0c](https://github.com/xamarin/xamarin-macios/pull/14612/commits/b17e70804c5bb9d258dacf1f923734d75466ae0c)

2022-04-22 01:52 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6054282&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220421.29/6054282/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6054282/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 148 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6054282&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1035.Monterey'
Merge b17e70804c5bb9d258dacf1f923734d75466ae0c into 8b80c5dd071153171431239c288e0ecd2e2825d6

2022-04-22 20:27 UTC, merged