[fabricbot] Update FabricBot with more useful commands
xamarin/xamarin-macios pull request #14749
Opened 2022-04-15 16:17 UTC by tj-devel709

Hi team, this PR introduces some updates to FabricBot to help us automate some steps in our triaging. A lot of these were brought over from the MAUI fabricbot.json but modified to fit into our workflow. As the person who has done the least amount of triaging on this team, feel free to let me know modifications / "things won't work because of ..." things!

While I cannot link the UI here, **if you want to see the items in the UI, you can download this json file and import it here** with FabricBot's UI Tool: https://portal.fabricbot.ms/bot/

### 1. Add comment when 'need-info' is applied to issue 

When a `need-info` label is added, we send out a message saying the issue will be closed in 7 days if no info is provided
* This one is already implemented by @rolfbjarne and shows up here: https://github.com/xamarin/xamarin-macios/issues/14725#issuecomment-1099576199

### 2. [Idle Issue Management] Close stale 'need-info' issues

If we have a `need-info` label and there has been no activity from anyone in the past 7 days, we will close this issue

### 3. [Idle Issue Management] Replace 'need-info' and 'awaiting-customer-response` with 'need-attention' label when the customer comments on an issue

If there is a `need-info` or `awaiting-customer-response` label and someone who does not have write permissions (I think anyone not on our team) comments, it will remove the `need-info` label and add the `need-attention` label

### 4. [Idle Issue Management] For issues closed due to inactivity, re-open an issue if issue author posts a reply within 7 days.

If an issue has been closed for less than 7 days, has the labels either `need-info` or `awaiting-customer-response`, and is commented on by issue author, then we will remove the `need-info` and or `awaiting-customer-response` labels, add the `need-attention` label, and reopen the issue

### 5. [Closed Issue Management] For issues closed with no activity over 7 days, ask non-contributor to consider opening a new issue instead.

If an issue has been closed for over 7 days and someone not on our team comments, we send out a message asking non-contributor to open a new issue and link this issue there for enhanced visibility

### 6. [Closed Issue Management] Lock issues closed without activity for over 30 days

If an issue has been closed with no activity for over 30 days, lock the issue

- @mandel-macaque  Do we already do something like this?

### 7. [Idle Issue Management] Close stale 'awaiting-customer-response' issues

If an issue has the label `awaiting-customer-response` for over 7 days, we can close the issue and provide a nice message

## New Labels

* `need-attention` - when a customer has provided feedback for us. This will be useful to alert us which issues really need our attention as these issues become more automated
* `awaiting-customer-response` - after we send a message to the customer and we are waiting on their response. New fabricbot action will allow auto-closing an issue if we are waiting for a response for over 7 days

2022-04-15 17:58 UTC, mandel-macaque requested changes
I like the idea, I'd like to have some documentation to read about this if possible. We can make the json more compact and correctly indented.

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +			"project_card"
Do we use project_cards? Why do we list to the project_card event?  I do know that project_cards can be converted to issues and vice versa. Do we know why we did this?

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +		"conditions": {
Indentation?

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +		"conditions": {
Indentation? Rolf had it correctly increased.

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +			"hours": [
We can write this in a single like, rather than using 24 lines just to say per hour.
```js
"hours": [0,1,2,... ]
```

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +			"hours": [
same.

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +			"name": "isIssue",
there is something wrong with the indentation of the objects here.

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +				{
same.

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +			"name": "removeLabel",
same, funny indentation.

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +				10,
single line to make the file more manageable.

2022-04-15 17:58 UTC, mandel-macaque commented on .github/fabricbot.json
> +			"hours": [
single line.

2022-04-15 18:48 UTC, mandel-macaque commented
@tj-devel709 let me know if the json was tool generated, in that case ignore my comments.

2022-04-15 19:23 UTC, tj-devel709 commented
> @tj-devel709 let me know if the json was tool generated, in that case ignore my comments.

Yes they were auto generated. The output used spaces instead of tabs though so it is possible that I messed up indentation when trying to use tabs to not show changes in Rolf's existing json

2022-04-15 19:30 UTC, tj-devel709 commented
Turning this into a draft since we will need more discussion on this before moving forward!

2022-04-18 19:53 UTC, mandel-macaque approved these changes

2022-04-21 14:37 UTC, chamons approved these changes

2022-04-21 14:47 UTC, rolfbjarne commented
It doesn't look like the `awaiting-customer-response` label is added automatically, are we supposed to add that manually?

2022-04-22 14:00 UTC, tj-devel709 commented
> It doesn't look like the `awaiting-customer-response` label is added automatically, are we supposed to add that manually?

@rolfbjarne  This was something I was going to bring up at our weekly meeting :)
So we could have this be an automatic thing that every time someone on our team comments, it will add the label,
**but** the downside of that is that if I am doing triage for example and write "@Rolf" to tag you, it will add the label and if we do not catch this, it will auto close the PR in 7 days catching one of the other rules.
The downside would be that we would need to add it manually if we did not want this behavior.

So I think it's just a matter of would we rather have to manually add the label every time we want a response from the customer (which will probably be a majority of the time), **or**, have it add the label automatically and we are responsible for removing the label every now and then with the repercussion of closing issues by accident if we forget to remove (this assumes that we do not touch other commands).

2022-04-25 18:57 UTC, tj-devel709 commented
Okay the `awaiting-customer-response` label has been removed as well as the corresponding tasks. Right now, the `need-info` label is not being auto-generated. Do we want to have that be auto-generated when we respond, or is this something we do not want / want to try later?

2022-04-26 06:21 UTC, rolfbjarne approved these changes
This looks great!

2022-04-26 13:04 UTC, dalexsoto approved these changes
I think we can try manually adding the `need-info` label ourselves since not all of our comments will be asking for information

2022-04-26 14:52 UTC, merged