Fix crash with NSUrl implicit conversion and null
xamarin/xamarin-macios pull request #14860
Opened 2022-04-29 21:29 UTC by chamons

- Fixes: https://github.com/xamarin/xamarin-macios/issues/14786

Before fix test crashed with same:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Foundation.NSUrl.op_Implicit(NSUrl url)
```

2022-04-29 22:57 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API Current PR diff

:white_check_mark: API Diff (from PR only) (no change)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/1b25ec160c6e8b18155ecdbbc9720e7c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/ec25039fe253a5b560e524c526cec11b)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/64803894b6f20a321dbd45afe17fd4a4)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/d55af4f5ed3b68077065b1ab04e8e515)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/7499467537b0c09fa95059bef057fa55)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/648acac6e4572a6e7e6f442f8b1bcff2)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/c2391e5e2fe66f81a3978f447d2aa490)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/dd05c44af39771e7ac58843c21ac73ab)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/ba9fa9d77dde0a7580e58e2814ec9dfe)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/a522ab43529b728be31722c50b9864d3)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/7f4300edfbe26bc469bf7c9daad1c4d2)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/7771533e6a272fdaec1d869cb63b43d1)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/6017b12b769c908a65eb9759ad2f175a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/f54f58453edd0e8e286da61f2f93281d)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/1e1e49961c0d7d0a2f88324ef610a578)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/283f9ee8ca69cd18d12fd2439d143aef)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/f3e3ddaab604f1d8f27f8d4f503d8b77)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/6015ec8b60b120999314ae6104b00c2b)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/696ee3a6a094861af4a44f5ed9c83cb3)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/64bc15a1bb69a4581c628ddee7e806fd)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/fa9d612cceb48c9655033450b0f4cc7a)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/65ee1e64e32cb1848dff34e0ae1f1bca)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/0981a32b68bcef7c450a6ed2bc403e59)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/4442346aca0528e8bce7b0738ea0df74)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6091653&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1042.Monterey
Hash: [0982f78ee88b4274a2523817e8b6dfb10980c258](https://github.com/xamarin/xamarin-macios/pull/14860/commits/0982f78ee88b4274a2523817e8b6dfb10980c258)

2022-04-29 23:07 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/delete-xma-build-host.pkg)
* [Microsoft.iOS.Bundle.15.4.400-ci.pr.gh14860.10.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Bundle.15.4.400-ci.pr.gh14860.10.pkg)
* [Microsoft.iOS.Ref.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Ref.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Runtime.ios-arm.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Runtime.ios-arm64.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Sdk.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Sdk.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Templates.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Templates.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.iOS.Windows.Sdk.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.400-ci.pr.gh14860.10.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.MacCatalyst.Bundle.15.4.400-ci.pr.gh14860.10.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.MacCatalyst.Ref.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.MacCatalyst.Sdk.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.MacCatalyst.Templates.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.macOS.Bundle.12.3.400-ci.pr.gh14860.10.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.macOS.Bundle.12.3.400-ci.pr.gh14860.10.pkg)
* [Microsoft.macOS.Ref.12.3.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.macOS.Ref.12.3.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.macOS.Runtime.osx-arm64.12.3.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.macOS.Runtime.osx-x64.12.3.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.macOS.Sdk.12.3.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.macOS.Sdk.12.3.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.macOS.Templates.12.3.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.macOS.Templates.12.3.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.400-ci.pr.gh14860.10.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.NET.Workload.iOS.15.4.400-ci.pr.gh14860.10.msi)
* [Microsoft.tvOS.Bundle.15.4.400-ci.pr.gh14860.10.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.tvOS.Bundle.15.4.400-ci.pr.gh14860.10.pkg)
* [Microsoft.tvOS.Ref.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.tvOS.Ref.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.400-ci.pr.gh14860.10.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e0eb087f7874c8ff75531e5aace87c1d9dcb182e/6091653/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.400-ci.pr.gh14860.10.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.4 [...]

2022-04-29 23:08 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6091653&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [0982f78ee88b4274a2523817e8b6dfb10980c258](https://github.com/xamarin/xamarin-macios/pull/14860/commits/0982f78ee88b4274a2523817e8b6dfb10980c258)

2022-04-29 23:11 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6091653&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [0982f78ee88b4274a2523817e8b6dfb10980c258](https://github.com/xamarin/xamarin-macios/pull/14860/commits/0982f78ee88b4274a2523817e8b6dfb10980c258)

2022-04-30 05:30 UTC, vs-mobiletools-engineering-service2 commented
### :x: [CI Build] Tests failed on VSTS: simulator tests iOS :x:

Tests failed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6091653&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220429.29/6091653/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6091653/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# Test results

<details>
<summary>1 tests failed, 147 tests passed.</summary>

## Failed tests

 * monotouch-test/tvOS - simulator/Release (all optimizations) [dotnet]: Failed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6091653&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1043.Monterey'
Merge 0982f78ee88b4274a2523817e8b6dfb10980c258 into 75f597662c09bf37bcd0e4e7161f0519d057f74b

2022-04-30 14:11 UTC, mandel-macaque requested changes

2022-04-30 14:11 UTC, mandel-macaque commented on src/Foundation/NSUrl.cs
> +			if (url == null) {
```suggestion
			if (url is null) {
```
Lets make tj work a little less.

2022-04-30 14:11 UTC, mandel-macaque commented on src/Foundation/NSUrl.cs
> +			if (uri == null) {
```suggestion
			if (uri is null) {
```
Same.

2022-05-02 15:43 UTC, tj-devel709 approved these changes

2022-05-02 16:00 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6097614&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [5cda95d0ea57d28213601d7971d94c05d0798752](https://github.com/xamarin/xamarin-macios/pull/14860/commits/5cda95d0ea57d28213601d7971d94c05d0798752)

2022-05-02 16:01 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API Current PR diff

:white_check_mark: API Diff (from PR only) (no change)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/abdf05ec8cff5894d2e3bce2b5110733)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/941bb621309dd55e41fff73427a56938)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/029371b5c69a50cdcab6f1575cc711d4)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/aeb26974582ed2a75b585f6daeb90437)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/946c63ef18de136f8ff59461094e1bdd)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/86f554ecaf6df6cac793b193e4851f0f)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/625811572b18f7bf80f38dc3091a9da2)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/fc008a3d7f6ccb182b7ee84565dd0ac2)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/cd996aebc58aa2ffa035e38ad4f40a2b)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/a27656f161aa6dedf42bd45e07154ac0)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/0747c07facddfebd86d55b5b45bdecf4)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/c3561e6c9cfa41ddf5074303a30eb29d)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/6927e208d09653498f8f5373301535cf)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/e88066bf50a0a58a121053e81cdd44f1)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/6f98b8af773ee0ab6a730c6952caf81d)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/5d59fdf447724fa26937e5f19f1607bf)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/15cd3c1829ce342673d131d7df7029aa)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/80a437ae49bc122d983cfc1e952e8097)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/4b2b1c0af890ec8034f40b4de0acc0fc)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/7d33c6e8ed0251642206a85c5851af29)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/ba1bba143d62feed9afc3306314fbccb)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/3683f68cd7ddeb3a978e50fc83eafb42)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/7b624c074c570e52e2d7b59657af74e8)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/1c7256c30f403f1a39993151a56e96b6)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6097614&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1043.Monterey'
Hash: [5cda95d0ea57d28213601d7971d94c05d0798752](https://github.com/xamarin/xamarin-macios/pull/14860/commits/5cda95d0ea57d28213601d7971d94c05d0798752)

2022-05-02 16:05 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/delete-xma-build-host.pkg)
* [Microsoft.iOS.Bundle.15.4.400-ci.pr.gh14860.11.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Bundle.15.4.400-ci.pr.gh14860.11.pkg)
* [Microsoft.iOS.Ref.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Ref.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Runtime.ios-arm.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Runtime.ios-arm64.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Sdk.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Sdk.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Templates.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Templates.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.iOS.Windows.Sdk.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.400-ci.pr.gh14860.11.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.MacCatalyst.Bundle.15.4.400-ci.pr.gh14860.11.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.MacCatalyst.Ref.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.MacCatalyst.Sdk.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.MacCatalyst.Templates.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.macOS.Bundle.12.3.400-ci.pr.gh14860.11.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.macOS.Bundle.12.3.400-ci.pr.gh14860.11.pkg)
* [Microsoft.macOS.Ref.12.3.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.macOS.Ref.12.3.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.macOS.Runtime.osx-arm64.12.3.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.macOS.Runtime.osx-x64.12.3.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.macOS.Sdk.12.3.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.macOS.Sdk.12.3.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.macOS.Templates.12.3.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.macOS.Templates.12.3.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.400-ci.pr.gh14860.11.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.NET.Workload.iOS.15.4.400-ci.pr.gh14860.11.msi)
* [Microsoft.tvOS.Bundle.15.4.400-ci.pr.gh14860.11.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.tvOS.Bundle.15.4.400-ci.pr.gh14860.11.pkg)
* [Microsoft.tvOS.Ref.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.tvOS.Ref.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.400-ci.pr.gh14860.11.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/68f909cac5b5cfa7377560aa978d61d7c38a265e/6097614/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.400-ci.pr.gh14860.11.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.4 [...]

2022-05-02 22:01 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6097614&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220502.1/6097614/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6097614/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 148 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6097614&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1105.Monterey'
Merge 5cda95d0ea57d28213601d7971d94c05d0798752 into 7a69d08cf05baf0e9763fc73201c509291876321

2022-05-02 23:22 UTC, mandel-macaque approved these changes

2022-05-03 09:25 UTC, rolfbjarne approved these changes
This would be a great opportunity to enable nullability in this file 😁

2022-05-03 20:40 UTC, mandel-macaque commented
@rolfbjarne  that's a trap! :P

2022-05-04 15:27 UTC, chamons commented
I'll take a stab.

2022-05-04 16:17 UTC, chamons commented
I added nullability as requested. @tj-devel709 please review my changes here.

2022-05-04 18:01 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6109443&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cae22317d3e5c66c83b813fcc475717689ef5dd0](https://github.com/xamarin/xamarin-macios/pull/14860/commits/cae22317d3e5c66c83b813fcc475717689ef5dd0)

2022-05-04 18:02 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API Current PR diff

:information_source: API Diff (from PR only) (please review changes)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/d24df7f50b264828dfc6dceaf4c2c088)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/4199a548d59321eb441f08392b3c9a74)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/318ad04a62d9fddac880ab5d47ca0c44)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/981bdf5117f4fe810daf24b0b7f4ef97)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/3729c0c28951d07cad01307b6f03a5ba)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/5ca207bf9aa2657b1aefe000e74b9882)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/d897d79a9d0a51c9554d8d060bccc692)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/0578298c8f31df8a1c7d77a4b5976fb5)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/f9e0a7391a70e0d288e700dc6df4293d)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/39bd6a6a601b406d6065c0ae2ae754ac)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/1f3a772e0649e2fc5042782d1a3ab930)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/d98f7839742b88c2565bdaba1ed5e2c7)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/1f58693fdd85f511becc4d641e8d5b9d)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/53e8b9fdd1b1927bc1f5067b4c015723)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/6b4ba4f84f527a48c4ddb81d507cc657)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/1aa5fb2d46d9de2de420a9712526f20b)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/a025b9a3b3cfd85cf02d9709a29c38fa)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/66843e8cfbe9a5bea1bec17a04d2abe8)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/80d809f34f395dbde6b8e517bdd2fb23)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/3677bb7d7ce3e6496366c63c1a5e5715)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/a7663a6d9d1b752f35c44c5bdab985d0)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/7520379dc3abb447853521327b1ab9ca)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/175182832b413c54aece01417bdf6e9c)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/3a66d26d2c59e9b71202198bff5ddc2b)
</details>


# Generator diff

:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/apigeneratordiff/;//generator-diff/index.html) (please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6109443&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1098.Monterey
Hash: [cae22317d3e5c66c83b813fcc475717689ef5dd0](https://github.com/xamarin/xamarin-macios/pull/14860/commits/cae22317d3e5c66c83b813fcc475717689ef5dd0)

2022-05-04 18:09 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6109443&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cae22317d3e5c66c83b813fcc475717689ef5dd0](https://github.com/xamarin/xamarin-macios/pull/14860/commits/cae22317d3e5c66c83b813fcc475717689ef5dd0)

2022-05-04 18:11 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [delete-xma-build-host.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/delete-xma-build-host.pkg)
* [Microsoft.iOS.Bundle.15.4.400-ci.pr.gh14860.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Bundle.15.4.400-ci.pr.gh14860.12.pkg)
* [Microsoft.iOS.Ref.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Ref.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Runtime.ios-arm.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Runtime.ios-arm64.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Sdk.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Sdk.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Templates.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Templates.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.iOS.Windows.Sdk.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.400-ci.pr.gh14860.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.MacCatalyst.Bundle.15.4.400-ci.pr.gh14860.12.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.MacCatalyst.Ref.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.MacCatalyst.Sdk.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.MacCatalyst.Templates.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.macOS.Bundle.12.3.400-ci.pr.gh14860.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.macOS.Bundle.12.3.400-ci.pr.gh14860.12.pkg)
* [Microsoft.macOS.Ref.12.3.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.macOS.Ref.12.3.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.macOS.Runtime.osx-arm64.12.3.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.macOS.Runtime.osx-x64.12.3.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.macOS.Sdk.12.3.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.macOS.Sdk.12.3.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.macOS.Templates.12.3.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.macOS.Templates.12.3.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.400-ci.pr.gh14860.12.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.NET.Workload.iOS.15.4.400-ci.pr.gh14860.12.msi)
* [Microsoft.tvOS.Bundle.15.4.400-ci.pr.gh14860.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.tvOS.Bundle.15.4.400-ci.pr.gh14860.12.pkg)
* [Microsoft.tvOS.Ref.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.tvOS.Ref.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.400-ci.pr.gh14860.12.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/12a2cf6932e8322405e91a71fbc408610585bd51/6109443/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.400-ci.pr.gh14860.12.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.4 [...]

2022-05-04 18:24 UTC, mandel-macaque approved these changes

2022-05-04 18:45 UTC, rolfbjarne approved these changes

2022-05-04 18:45 UTC, rolfbjarne commented on src/Foundation/NSUrl.cs
> +			if (((object?) x == null) || ((object?) y == null)) // If one is null, but not both, return false.
This can be simplified to:

```suggestion
			if (x is null || y is null) // If one is null, but not both, return false.
```

2022-05-05 01:38 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6109443&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220504.21/6109443/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6109443/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 148 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6109443&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1103.Monterey'
Merge cae22317d3e5c66c83b813fcc475717689ef5dd0 into caf68aac8233507dc70fa501bb5810ac8971fba3

2022-05-05 16:11 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6114506&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b7509d741e473cec1621ff8d2803125953dbd5fe](https://github.com/xamarin/xamarin-macios/pull/14860/commits/b7509d741e473cec1621ff8d2803125953dbd5fe)

2022-05-05 17:35 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Generate API diff'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6114506&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/14860/commits/)

2022-05-05 22:06 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6114506&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220505.15/6114506/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6114506/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 148 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6114506&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1105.Monterey'
Merge b7509d741e473cec1621ff8d2803125953dbd5fe into 01c3127c8c7fd8436307940e8f168ad49822a011

2022-05-06 06:37 UTC, rolfbjarne approved these changes

2022-05-06 13:52 UTC, merged