[Nnyeah] Improve error messages for missing required arguments
xamarin/xamarin-macios pull request #14949
Opened 2022-05-09 15:40 UTC by chamons

I had trouble figuring out what arguments the integration test was missing before looking at the source/asking.

2022-05-09 15:42 UTC, stephen-hawley requested changes

2022-05-09 15:42 UTC, stephen-hawley commented on tools/nnyeah/nnyeah/Program.cs
> +				ExitWithOptions (options, "File for conversion (--input) and output location (--output) are required options.");
These need to go into the resource for translation.

2022-05-09 15:50 UTC, stephen-hawley approved these changes

2022-05-09 15:53 UTC, rolfbjarne requested changes

2022-05-09 15:53 UTC, rolfbjarne commented on tools/nnyeah/nnyeah/Program.cs
> +			Environment.Exit (0);
If we're showing an error, we shouldn't exit with 0

2022-05-09 18:07 UTC, vs-mobiletools-engineering-service2 commented
# :books: [CI Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6126985&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1166.Monterey
Hash: [c3c49901709d84ec80bf66deeb7cf21203fff1b7](https://github.com/xamarin/xamarin-macios/pull/14949/commits/c3c49901709d84ec80bf66deeb7cf21203fff1b7)

2022-05-09 18:24 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

Failed tests are:

* linksdk
* linkall


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6126985&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c3c49901709d84ec80bf66deeb7cf21203fff1b7](https://github.com/xamarin/xamarin-macios/pull/14949/commits/c3c49901709d84ec80bf66deeb7cf21203fff1b7)

2022-05-09 18:25 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API Current PR diff

:white_check_mark: API Diff (from PR only) (no change)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/f4dec19fb79ee9c36b8e2fd08d102ae1)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/c3c986f0a1139c8de0279f297d123eb1)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/8bff203ac056e305ccace21a6f78adc2)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/f8318582870f8d44663cfa4fe1485933)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/38f78c3e76eb205ff2e72f195bade2c8)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/f5df47a61d1b421384bf5440405bc3dc)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/fca8497beed2868efaf729a51dbeb5b0)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/d211fd450dc33bdfd70ae64db0ff8bff)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/cce12fa6ac1a4928f64e53d15d7541a6)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/b058ebe329e3f4287b5b98504aa33474)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/cfc016af394c951b2c08af292adbc17e)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/6720d5b534412adbdb4ad78b3195d2cb)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/71555b8cb4d9d59d149b0b84d93661d2)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/a6becfad0e745b70cd83e210337df7cf)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ee75522d6a3df114848e345e4f0ba463)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/d677ed31a5a3b5e924aa65c1426f1b38)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/f75aba0e5505211604c955f1b23a86fb)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/bbb9a75e2b80bb749a4385faa3d08a2e)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/24abaaf15cccb9e3600c1fd02e49f108)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/ae9cba1e45f3dfdc85bec4e4556e168b)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/029300f0d3ad0738add8094584452d4e)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/f89a4aa3eb378c2105eef122cd1557b6)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/98ac653c7ea18b8c8cd2332907c282f6)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/1d586d06ef014806edec781bbb37f605)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6126985&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1167.Monterey'
Hash: [c3c49901709d84ec80bf66deeb7cf21203fff1b7](https://github.com/xamarin/xamarin-macios/pull/14949/commits/c3c49901709d84ec80bf66deeb7cf21203fff1b7)

2022-05-09 19:58 UTC, dalexsoto approved these changes

2022-05-09 21:13 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6126985&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.43/6126985/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6126985/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 2 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6126985&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1166.Monterey'
Merge c3c49901709d84ec80bf66deeb7cf21203fff1b7 into 5631ca5c8eeb4f2154b4dfd65b9c9dd6a1ab44c2

2022-05-10 07:45 UTC, rolfbjarne approved these changes

2022-05-10 14:07 UTC, merged