[nnyeah] Module information extensions
xamarin/xamarin-macios pull request #14956
Opened 2022-05-09 19:11 UTC by stephen-hawley

Added code to find what (if any) Xamarin platform we depend on.
Tests as per usual.
The code is not called from main (yet).

2022-05-09 19:21 UTC, tj-devel709 approved these changes

2022-05-09 19:40 UTC, chamons requested changes

2022-05-09 19:40 UTC, chamons commented on tools/nnyeah/tests/XamarinDependencyTests.cs
> +			var dir = Cache.CreateTemporaryDirectory ("BasicLibrary");
This string should be unique for each test. If set to null it walks up to the async wrapper of the test and creates a "funny" name, but we want each test to be independent.

2022-05-09 19:45 UTC, chamons approved these changes

2022-05-09 21:35 UTC, vs-mobiletools-engineering-service2 commented
# :books: [CI Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6128075&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1103.Monterey'
Hash: [6fa2517e490b76926ba5a41f505e2e2d06175a05](https://github.com/xamarin/xamarin-macios/pull/14956/commits/6fa2517e490b76926ba5a41f505e2e2d06175a05)

2022-05-09 21:48 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API Current PR diff

:warning: API Diff (from PR only) (:fire: breaking changes :fire:)

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/19e962e211a2ec35363b63cf5febb603)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/7c7fca3c25da7374aa8363249234a409)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/615567fbbbcd6f24cf1cb6b48196e07f)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/fc68ef296f737ba97315902d05f40950)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/1feb142c97681dcb99f33bd4be4adf02)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/965ad0ef914872a8130de7b621467648)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/81deaab067f2a0b8a97cf2d6b52edea6)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/ae432c6d9db761aa7d2edbab1ab95edd)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/51d4fc7804a22d94d31770133c61000c)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/6b787b69c020b5fff4db6e9e672661f0)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/8c406ba76f2fbf9370cc9b75d6e29051)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/10a0d2950d89203896a927d1919f6362)
</details>


# API diff

:white_check_mark: API Diff from stable

<details><summary>View API diff</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/ff673496dc321c4cf717c71c8619268d)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/b07c3a309eac7d41bb9276e73b10b630)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/76f02c7019ed1a64323db4746065030b)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/a288b9a42693aec91f4794fb251d8b00)
</details>

<details><summary>View dotnet API diff</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/d43ade2bc942bcdf2dec8f528012d610)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/b76a6b935d0ac51795dd57403c527919)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/b4435867fa47c49f4dd97ba61d4a6639)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/fc1759ca5034af3cafc920d2d0b9540d)
</details>

<details><summary>View dotnet legacy API diff</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/45535024847688ec87ff8836aac515c1)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/8c90e687d25f6f516e00eabddcb3d99f)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/ab39d6be9c1e9977d9d57e93c138bd43)
</details>

<details><summary>View dotnet iOS-MacCatalayst API diff</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/8587d8af5be8ba51911c489ab5263065)
</details>


# Generator diff

:information_source: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/apigeneratordiff/;//generator-diff/index.html) (please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6128075&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1099.Monterey
Hash: [6fa2517e490b76926ba5a41f505e2e2d06175a05](https://github.com/xamarin/xamarin-macios/pull/14956/commits/6fa2517e490b76926ba5a41f505e2e2d06175a05)

2022-05-09 21:51 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6128075&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6fa2517e490b76926ba5a41f505e2e2d06175a05](https://github.com/xamarin/xamarin-macios/pull/14956/commits/6fa2517e490b76926ba5a41f505e2e2d06175a05)

2022-05-09 21:53 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* linksdk
* linkall


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6128075&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6fa2517e490b76926ba5a41f505e2e2d06175a05](https://github.com/xamarin/xamarin-macios/pull/14956/commits/6fa2517e490b76926ba5a41f505e2e2d06175a05)

2022-05-10 01:03 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6128075&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220509.56/6128075/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6128075/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 2 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6128075&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1103.Monterey'
Merge 6fa2517e490b76926ba5a41f505e2e2d06175a05 into d8dfd37cc6b8b7d70dabced70661e690cc81e709

2022-05-10 13:51 UTC, merged