[nnyeah] Check dependencies in output
xamarin/xamarin-macios pull request #14987
Opened 2022-05-11 15:35 UTC by stephen-hawley

This PR includes:
- change visibility of methods in `Program.cs` to make it unit-testable
- infrastructure to find the Microsoft platform dlls
- tests to ensure that Xamarin and Microsoft dlls are where we expect
- a (failing) test that shows that dependency is not being removed

2022-05-11 15:52 UTC, rolfbjarne requested changes

2022-05-11 15:52 UTC, rolfbjarne commented on tools/nnyeah/tests/utils/Compiler.cs
> +		const string buildDirectory = "../../../../../../_build";
The Configuration class already contains all the logic you're adding:

https://github.com/xamarin/xamarin-macios/blob/92eda7f35399f442f8730aa539571ad8fd44d7da/tests/common/Configuration.cs#L14

It should be possible to just add that file to your project (although you might have to add more files too).

Other comments point to more specific locations in the Configuration class.

2022-05-11 15:52 UTC, rolfbjarne commented on tools/nnyeah/tests/utils/Compiler.cs
> +			platformName switch {
https://github.com/xamarin/xamarin-macios/blob/92eda7f35399f442f8730aa539571ad8fd44d7da/tests/common/Configuration.cs#L707-L723

2022-05-11 15:52 UTC, rolfbjarne commented on tools/nnyeah/tests/utils/Compiler.cs
> +		public static string MicrosoftPlatformLibDirectory (PlatformName platformName) =>
You should be able to use the reference assemblies:

https://github.com/xamarin/xamarin-macios/blob/92eda7f35399f442f8730aa539571ad8fd44d7da/tests/common/Configuration.cs#L514-L521

2022-05-11 16:24 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Generate API diff'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6138051&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/14987/commits/)

2022-05-11 17:32 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Tests on macOS M1 - Mac Big Sur (11.5) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6138051&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ee07341c907ba9953aa4c88c1b8603db7209c098](https://github.com/xamarin/xamarin-macios/pull/14987/commits/ee07341c907ba9953aa4c88c1b8603db7209c098)

2022-05-11 18:00 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.30-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Bundle.15.4.30-ci.pr.gh14987.pkg)
* [Microsoft.iOS.Ref.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Ref.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Runtime.ios-arm.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Runtime.ios-arm64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Sdk.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Sdk.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Templates.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Templates.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.iOS.Windows.Sdk.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.30-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.MacCatalyst.Bundle.15.4.30-ci.pr.gh14987.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.MacCatalyst.Ref.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.MacCatalyst.Sdk.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.MacCatalyst.Templates.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Bundle.12.3.30-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.macOS.Bundle.12.3.30-ci.pr.gh14987.pkg)
* [Microsoft.macOS.Ref.12.3.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.macOS.Ref.12.3.30-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.macOS.Runtime.osx-arm64.12.3.30-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.macOS.Runtime.osx-x64.12.3.30-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Sdk.12.3.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.macOS.Sdk.12.3.30-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Templates.12.3.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.macOS.Templates.12.3.30-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.30-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.30-ci.pr.gh14987.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.NET.Workload.iOS.15.4.30-ci.pr.gh14987.msi)
* [Microsoft.tvOS.Bundle.15.4.30-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.tvOS.Bundle.15.4.30-ci.pr.gh14987.pkg)
* [Microsoft.tvOS.Ref.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.tvOS.Ref.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.30-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Sdk.15.4.30-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/b3ffc3165e677b895c40a6bf873d17f334eb943d/6138051/package/Microsoft.tvOS.Sdk.15.4.30-ci.pr.gh14987.nup [...]

2022-05-11 18:01 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

Failed tests are:

* linksdk
* linkall


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6138051&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ee07341c907ba9953aa4c88c1b8603db7209c098](https://github.com/xamarin/xamarin-macios/pull/14987/commits/ee07341c907ba9953aa4c88c1b8603db7209c098)

2022-05-11 19:49 UTC, tj-devel709 commented on tools/nnyeah/tests/utils/Compiler.cs
> +				_ => throw new NotImplementedException (),
Would it be helpful to throw in the name of the platform?
```suggestion
				_ => throw new NotImplementedException (nameof (platformName)),
```

2022-05-11 19:50 UTC, tj-devel709 commented on tools/nnyeah/tests/utils/Compiler.cs
> +				_ => throw new NotImplementedException (),
same here?

2022-05-11 21:03 UTC, rolfbjarne approved these changes

2022-05-11 21:03 UTC, rolfbjarne commented on tools/nnyeah/tests/utils/Compiler.cs
> +		const string buildDirectory = "../../../../../../_build";
This `buildDirectory` variable doesn't seem to be needed anymore:

```suggestion
```

2022-05-11 23:12 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6140065&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [26ba09fc3195870768d0bb26df26233feefe2c86](https://github.com/xamarin/xamarin-macios/pull/14987/commits/26ba09fc3195870768d0bb26df26233feefe2c86)

2022-05-11 23:12 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.33-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Bundle.15.4.33-ci.pr.gh14987.pkg)
* [Microsoft.iOS.Ref.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Ref.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Runtime.ios-arm.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Runtime.ios-arm64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Sdk.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Sdk.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Templates.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Templates.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.iOS.Windows.Sdk.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.33-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.MacCatalyst.Bundle.15.4.33-ci.pr.gh14987.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.MacCatalyst.Ref.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.MacCatalyst.Sdk.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.MacCatalyst.Templates.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Bundle.12.3.33-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.macOS.Bundle.12.3.33-ci.pr.gh14987.pkg)
* [Microsoft.macOS.Ref.12.3.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.macOS.Ref.12.3.33-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.macOS.Runtime.osx-arm64.12.3.33-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.macOS.Runtime.osx-x64.12.3.33-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Sdk.12.3.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.macOS.Sdk.12.3.33-ci.pr.gh14987.nupkg)
* [Microsoft.macOS.Templates.12.3.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.macOS.Templates.12.3.33-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.33-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.33-ci.pr.gh14987.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.NET.Workload.iOS.15.4.33-ci.pr.gh14987.msi)
* [Microsoft.tvOS.Bundle.15.4.33-ci.pr.gh14987.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.tvOS.Bundle.15.4.33-ci.pr.gh14987.pkg)
* [Microsoft.tvOS.Ref.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.tvOS.Ref.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.33-ci.pr.gh14987.nupkg)
* [Microsoft.tvOS.Sdk.15.4.33-ci.pr.gh14987.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/30eeb45e3dbb81530f4b1b145417502dd9a5c149/6140065/package/Microsoft.tvOS.Sdk.15.4.33-ci.pr.gh14987.nup [...]

2022-05-11 23:25 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* linksdk
* linkall
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6140065&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [26ba09fc3195870768d0bb26df26233feefe2c86](https://github.com/xamarin/xamarin-macios/pull/14987/commits/26ba09fc3195870768d0bb26df26233feefe2c86)

2022-05-12 01:37 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6140065&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220511.48/6140065/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6140065/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 2 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6140065&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1037.Monterey
Merge 26ba09fc3195870768d0bb26df26233feefe2c86 into adb56501dae1c044bb0e60643870ba0b76bd1672

2022-05-12 18:44 UTC, mandel-macaque approved these changes

2022-05-12 18:45 UTC, merged