[nnyeah] Add rest of top nuget examples to integration suite
xamarin/xamarin-macios pull request #15058
Opened 2022-05-18 16:34 UTC by chamons

Through the use of ~~clever hacks~~ [poorly written shell scripts](https://gist.github.com/chamons/5db44d55107035972838d1eb3477114c), I added TestCases for our example suite of "high download nugets that support XI or XM legacy but not NET5/6."

The test today does not employ caching, so it is slow as it re-downloads and unzips each nuget, but thankfully most are very tiny. 

When iterating on a test, it should be easy to copy the nuget dll from `tests/bin/Debug/net6.0/tmp-test-dir` to a fixed place on disk and setup your debug settings to convert it over and over.

2022-05-18 17:01 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Generate API diff'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6170770&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15058/commits/)

2022-05-18 18:10 UTC, vs-mobiletools-engineering-service2 commented
### :fire: Tests failed catastrophically on VSTS: simulator tests iOS (no summary found). :fire:

Result file D:\a\1\s\Reports\TestSummary-simulator\TestSummary.md not found. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6170770&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220518.19/6170770/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6170770/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6170770&view=ms.vss-test-web.test-result-details) on Agent 
Merge 473580c6f7941f3c61358f4bdbd03f1733d0e208 into 2953cf1fed60e14c5b9d02cef6fef77fc2f1e0fd

2022-05-18 18:11 UTC, dalexsoto requested changes
From the List I think we should leave out anything "Forms" since there is no Xamarin.Forms for .NET 6

2022-05-18 18:18 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.84-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Bundle.15.4.84-ci.pr.gh15058.pkg)
* [Microsoft.iOS.Ref.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Ref.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Runtime.ios-arm.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Runtime.ios-arm64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Sdk.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Sdk.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Templates.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Templates.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.iOS.Windows.Sdk.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.84-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.MacCatalyst.Bundle.15.4.84-ci.pr.gh15058.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.MacCatalyst.Ref.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.MacCatalyst.Sdk.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.MacCatalyst.Templates.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Bundle.12.3.84-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.macOS.Bundle.12.3.84-ci.pr.gh15058.pkg)
* [Microsoft.macOS.Ref.12.3.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.macOS.Ref.12.3.84-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.macOS.Runtime.osx-arm64.12.3.84-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.macOS.Runtime.osx-x64.12.3.84-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Sdk.12.3.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.macOS.Sdk.12.3.84-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Templates.12.3.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.macOS.Templates.12.3.84-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.84-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.84-ci.pr.gh15058.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.NET.Workload.iOS.15.4.84-ci.pr.gh15058.msi)
* [Microsoft.tvOS.Bundle.15.4.84-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.tvOS.Bundle.15.4.84-ci.pr.gh15058.pkg)
* [Microsoft.tvOS.Ref.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.tvOS.Ref.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.84-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Sdk.15.4.84-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/182d974bb02fd74b1e488f71e0d9a0d1ccb76221/6170770/package/Microsoft.tvOS.Sdk.15.4.84-ci.pr.gh15058.nup [...]

2022-05-18 18:21 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6170770&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [473580c6f7941f3c61358f4bdbd03f1733d0e208](https://github.com/xamarin/xamarin-macios/pull/15058/commits/473580c6f7941f3c61358f4bdbd03f1733d0e208)

2022-05-18 18:25 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6170770&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [473580c6f7941f3c61358f4bdbd03f1733d0e208](https://github.com/xamarin/xamarin-macios/pull/15058/commits/473580c6f7941f3c61358f4bdbd03f1733d0e208)

2022-05-18 19:35 UTC, rolfbjarne approved these changes

2022-05-18 20:29 UTC, stephen-hawley approved these changes

2022-05-19 16:18 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.86-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Bundle.15.4.86-ci.pr.gh15058.pkg)
* [Microsoft.iOS.Ref.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Ref.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Runtime.ios-arm.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Runtime.ios-arm64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Sdk.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Sdk.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Templates.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Templates.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.iOS.Windows.Sdk.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.86-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.MacCatalyst.Bundle.15.4.86-ci.pr.gh15058.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.MacCatalyst.Ref.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.MacCatalyst.Sdk.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.MacCatalyst.Templates.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Bundle.12.3.86-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.macOS.Bundle.12.3.86-ci.pr.gh15058.pkg)
* [Microsoft.macOS.Ref.12.3.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.macOS.Ref.12.3.86-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.macOS.Runtime.osx-arm64.12.3.86-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.macOS.Runtime.osx-x64.12.3.86-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Sdk.12.3.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.macOS.Sdk.12.3.86-ci.pr.gh15058.nupkg)
* [Microsoft.macOS.Templates.12.3.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.macOS.Templates.12.3.86-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.86-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.86-ci.pr.gh15058.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.NET.Workload.iOS.15.4.86-ci.pr.gh15058.msi)
* [Microsoft.tvOS.Bundle.15.4.86-ci.pr.gh15058.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.tvOS.Bundle.15.4.86-ci.pr.gh15058.pkg)
* [Microsoft.tvOS.Ref.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.tvOS.Ref.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.86-ci.pr.gh15058.nupkg)
* [Microsoft.tvOS.Sdk.15.4.86-ci.pr.gh15058.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/34c3a1a23367c13a1428a64595636d653707024f/6175755/package/Microsoft.tvOS.Sdk.15.4.86-ci.pr.gh15058.nup [...]

2022-05-19 16:22 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6175755&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1da461295caffa512fb2e749de5e6a701af49978](https://github.com/xamarin/xamarin-macios/pull/15058/commits/1da461295caffa512fb2e749de5e6a701af49978)

2022-05-19 16:26 UTC, vs-mobiletools-engineering-service2 commented
### :fire: Tests failed catastrophically on VSTS: simulator tests iOS (no summary found). :fire:

Result file D:\a\1\s\Reports\TestSummary-simulator\TestSummary.md not found. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6175755&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6175755/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6175755&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1042.Monterey'
Merge 1da461295caffa512fb2e749de5e6a701af49978 into 1477c9bd517cb7e64eef1271577a3bfe71e9ca9c

2022-05-19 16:27 UTC, mandel-macaque approved these changes

2022-05-19 16:28 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API diff (for current PR)

:information_source: API Diff (from PR only) (please review changes)

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/api-diff.html) [gist](https://gist.github.com/a2745f08446fda03dbd433581db25603)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/ad5b50a6f78c917ccd2c39e7d34a164f)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/d526024d8c0d00c381d52a2d0df2e8e2)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/d35ecc563d7693f9722e1d0bca5725a7)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/352a4e7a6921f1cb588e3ba5412a7df3)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/b102a1ec41bd6122d0a672bb341724a0)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/e2e8637a3378bed536882d3d22f5cc31)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/0849b38922ed2712a5b0157d8816ec0b)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref//Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/4662dcb0da2a7752bbc987b56eb9c25a)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/f697cef2cfdbb80b8ca743c5760534d2)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/7dec9f354530b7810d846e4968bf0677)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/5e6ca75ec3bc5e93d8a5ab60904280b2)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/a7df7ba37cb2513db1ae29fd100076a6)
</details>


# API diff (vs stable)

:white_check_mark: API Diff from stable

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/api-diff.html) [gist](https://gist.github.com/a03c0d7723fdecb7f7176149c8a4c9b0)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/2411056bae790e09b4db43c1b9e61ac7)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/5c126dcc1c7bec98829f7ec2a6fe9fcb)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/3b5bbb1b840c86dcbd84749adff376cb)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/f8ce061ae4ddb6a56d76dbecb0eb6eb9)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/a1517f7064349c59e262548455798b0a)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/aa7d8e47b5052c54456599bf12511cb4)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/c084179ff97db6a838671980544e8ad0)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/c36357a3e816b028e6c8724c93e0e686)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/6218e0cf7ba8c4e31a964bcaa4336c5d)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/75e7e4114df0523f070ac23648c97456)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/057f5f6611f7fdb7c76759699deb5bf6)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/5e611dc2ce3789a15c7dca5ca65dae8e)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220519.8/6175755/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6175755&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1043.Monterey'
Hash: [1da461295caffa512fb2e749de5e6a701af49978](https://github.com/xamarin/xamarin-macios/pull/15058/commits/1da461295caffa512fb2e749de5e6a701af49978)

2022-05-20 01:40 UTC, dalexsoto approved these changes

2022-05-20 10:48 UTC, merged