[corefoundation] Add nullability to (generated and manual) bindings
xamarin/xamarin-macios pull request #15090
Opened 2022-05-20 22:38 UTC by tj-devel709

This PR aims to bring nullability changes to CoreFoundation.
Following the steps [here](https://github.com/xamarin/xamarin-macios/wiki/Nullability):

1. I am adding `nullable enable` to all manual files that are not "API_SOURCES" in src/frameworks.sources and making the required nullability changes
2. Changing all `throw new ArgumentNullException ("object"));` to `ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (object));` for size saving optimization as well to mark that this framework contains nullability changes
3. Changing any `== null` or `!= null` to `is null` and `is not null`

2022-05-20 22:42 UTC, tj-devel709 commented on src/CoreFoundation/CFMutableString.cs
> +			var t = CreateNative (transform);
Context, NSString.CreateNative (...) is obsolete and the recommendation was to use CFString.CreateNative (...)

2022-05-20 22:42 UTC, tj-devel709 commented on src/CoreFoundation/CFMutableString.cs
> +			var t = CreateNative (transform);
Context, NSString.CreateNative (...) is obsolete and the recommendation was to use CFString.CreateNative (...)

2022-05-21 01:01 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.93-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Bundle.15.4.93-ci.pr.gh15090.pkg)
* [Microsoft.iOS.Ref.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Ref.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Runtime.ios-arm.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Runtime.ios-arm64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Sdk.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Sdk.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Templates.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Templates.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.iOS.Windows.Sdk.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.93-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.MacCatalyst.Bundle.15.4.93-ci.pr.gh15090.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.MacCatalyst.Ref.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.MacCatalyst.Sdk.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.MacCatalyst.Templates.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Bundle.12.3.93-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.macOS.Bundle.12.3.93-ci.pr.gh15090.pkg)
* [Microsoft.macOS.Ref.12.3.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.macOS.Ref.12.3.93-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.macOS.Runtime.osx-arm64.12.3.93-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.macOS.Runtime.osx-x64.12.3.93-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Sdk.12.3.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.macOS.Sdk.12.3.93-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Templates.12.3.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.macOS.Templates.12.3.93-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.93-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.93-ci.pr.gh15090.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.NET.Workload.iOS.15.4.93-ci.pr.gh15090.msi)
* [Microsoft.tvOS.Bundle.15.4.93-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.tvOS.Bundle.15.4.93-ci.pr.gh15090.pkg)
* [Microsoft.tvOS.Ref.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.tvOS.Ref.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.93-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Sdk.15.4.93-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fd52357b5b362d46b509cb76fc206d5bc41e5202/6183659/package/Microsoft.tvOS.Sdk.15.4.93-ci.pr.gh15090.nup [...]

2022-05-21 01:04 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API diff (for current PR)

:warning: API Diff (from PR only) (:fire: breaking changes :fire:)

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/api-diff.html) [gist](https://gist.github.com/4b18799a66c02e1160fc6dd90902f244)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/43b2a6c809e32d3a287b587673257a3b)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/6ab1a4e9959d888f665d21aa81989267)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/bdf9cb3c8ffc6601972bbd9008601e44)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/f7971b85cf7629f3e202d07b92c6df4b)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/279d7f53f4ca7dc0a9a552e493997401)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/bbcc52d8d3d580950d34aa3f2dc5c39f)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/176e0cf288476bf81663a31ec0e4a59a)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref//Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/30b641248e9e200688259d529308822d)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/555afee49698fefd932eeff4af80d709)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/f623fe55591f8b1a31d002c73dd0d424)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/964d1c326328ab0d55173e2d811c4cd1)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/9b03104f2dc9e5054d781bea4d9cf930)
</details>


# API diff (vs stable)

:white_check_mark: API Diff from stable

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/api-diff.html) [gist](https://gist.github.com/780b48ea2640111a2d5fb4deb75f25ff)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/39b0e278b3c313cd4af51bdc40bc6f69)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/bc79944514e24996228b78346a7a56ee)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ee39b0c7e72aad6841d07ab22874e9b4)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/8cf80510cbb6462036b1d5e1fcfedafc)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/6f28f6b6b1f102850a959f69f43a00e7)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/e5997f9e823f7d48eb3b9c601936e2c9)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/4def747d4c93f197eaf153c241210899)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/1803199a4c06d541da0c44e461d1e481)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/83f54c0058cdc2fb3b8e24911fb6c26e)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/01f2893867628a1fc46310f07973b341)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/6d7ca677b0247dae376514128df1f48c)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/c649adaf445d1b32d236b57176941525)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6183659&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1017.Monterey
Hash: [e940a59a54fc7fb6d6f9db3f5fefb9a8b09f618f](https://github.com/xamarin/xamarin-macios/pull/15090/commits/e940a59a54fc7fb6d6f9db3f5fefb9a8b09f618f)

2022-05-21 01:05 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6183659&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e940a59a54fc7fb6d6f9db3f5fefb9a8b09f618f](https://github.com/xamarin/xamarin-macios/pull/15090/commits/e940a59a54fc7fb6d6f9db3f5fefb9a8b09f618f)

2022-05-21 01:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6183659&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e940a59a54fc7fb6d6f9db3f5fefb9a8b09f618f](https://github.com/xamarin/xamarin-macios/pull/15090/commits/e940a59a54fc7fb6d6f9db3f5fefb9a8b09f618f)

2022-05-21 06:25 UTC, vs-mobiletools-engineering-service2 commented
### :white_check_mark: [CI Build] Tests passed on VSTS: simulator tests iOS. :white_check_mark:

Tests passed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6183659&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220521.1/6183659/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6183659/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# :tada: All 60 tests passed :tada:



[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6183659&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1042.Monterey'
Merge e940a59a54fc7fb6d6f9db3f5fefb9a8b09f618f into 94e40c8b111f6213d124743280cec7445c8ade7c

2022-05-23 14:59 UTC, rolfbjarne requested changes

2022-05-23 14:59 UTC, rolfbjarne commented on src/CoreFoundation/CFDataBuffer.cs
> +			get { return data?.Handle ?? IntPtr.Zero; }
```suggestion
			get { return data.GetHandle (); }
```

2022-05-23 14:59 UTC, rolfbjarne commented on src/CoreFoundation/CFPreferences.cs
> +				if (value is not null)
This looks wrong, I think there's a missing `return;` statement after line 127, where it already handles the `value is null` case. Looks like the nullability attributes caught a bug here :)

2022-05-23 14:59 UTC, rolfbjarne commented on src/CoreFoundation/Dispatch.cs
> +				return right as object is null;
You don't need the `as object` part:

```suggestion
			if (left is null)
				return right is null;
```

2022-05-23 14:59 UTC, rolfbjarne commented on src/CoreFoundation/Dispatch.cs
> +				return right as object is not null;
```suggestion
			if (left is null)
				return right is not null;
```

2022-05-23 21:35 UTC, mandel-macaque approved these changes
After all rolfs comments have been addressed.

2022-05-24 14:05 UTC, tj-devel709 commented on src/CoreFoundation/CFNotificationCenter.cs
> +				ObjCRuntime.ThrowHelper.ThrowArgumentNullException ($"{nameof (name)}: When using the Darwin Notification Center, the value passed must not be null");
@rolfbjarne There is not one in the ObjCRuntime.ThrowHelper class, but I could easily create one!

2022-05-24 14:36 UTC, rolfbjarne commented on src/CoreFoundation/CFNotificationCenter.cs
> +				ObjCRuntime.ThrowHelper.ThrowArgumentNullException ($"{nameof (name)}: When using the Darwin Notification Center, the value passed must not be null");
Yep, adding a new method is the way to go :)

2022-05-31 15:26 UTC, tj-devel709 commented on src/CoreFoundation/CFDataBuffer.cs
> +			get { return data?.Handle ?? IntPtr.Zero; }
Oop was just missing the namespace :)

2022-05-31 16:31 UTC, rolfbjarne approved these changes

2022-05-31 18:03 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6222159&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2387e510e00a86c9428066932871d1ccde357fe6](https://github.com/xamarin/xamarin-macios/pull/15090/commits/2387e510e00a86c9428066932871d1ccde357fe6)

2022-05-31 18:12 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API diff (for current PR)

:warning: API Diff (from PR only) (:fire: breaking changes :fire:)

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/api-diff.html) [gist](https://gist.github.com/7bad03f6732557215c1a75fa26be9519)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/0811379aae14cd84857042fbd33d858c)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/052d4294e8aed36458362498ea4e3589)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/7c400fdf1fc7492bc697b1109c06fad8)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/abf5cc8b03ae7561e00ed6ef88b030b7)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/ef49da41cc32899af0c3b69682162205)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/1ad3578e51421a928f4f8d83073f5789)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/b0c8411c5e864fe452e1ccd9f56b79b2)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref//Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/cf2601406e4cca328a6a249580148df1)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/9eb0b42419ab909e452da813d9ce1e58)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/50442379de127fdfaa28e8ef5c898b72)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/77e1dd53d0e7bb86f64563da612019f9)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/bb95f7964e90b272a26913b0945bc1d9)
</details>


# API diff (vs stable)

:white_check_mark: API Diff from stable

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/api-diff.html) [gist](https://gist.github.com/1c79389516f8045540ac1f67c09f959d)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/e14b92f07ab760eba804b0244f7c683e)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/39ea328b5e3016aa4f2763d170510269)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/24a5f48ece1aa8f1c4e83131732c6020)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/714b3561ec5c8676f993978d3d482abd)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/3bd3c51c4fbdfe15faf5926c23fe4e8f)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/e3401a2858bd393d1fe9deca9166b85b)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/2303143518c090d69c64c941cf20953f)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/8f43d3632955bf98859306b56e082ce7)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/e90f39249b1f347d880ed6d24071d5e6)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/bd1f38156f67d5967dc6e19ee969418e)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/0834cb64bf0969554ace056d1d15bafb)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/1ffa0c3a3080496888753094be74fe67)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6222159&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1033.Monterey
Hash: [2387e510e00a86c9428066932871d1ccde357fe6](https://github.com/xamarin/xamarin-macios/pull/15090/commits/2387e510e00a86c9428066932871d1ccde357fe6)

2022-05-31 18:15 UTC, rolfbjarne requested changes

2022-05-31 18:15 UTC, rolfbjarne commented on src/CoreFoundation/CFException.cs
> +		public nint? Code {get; private set;}
You can't make this nullable, because it's a struct and that would be a breaking change.

2022-05-31 18:15 UTC, rolfbjarne commented on src/CoreFoundation/CFException.cs
> +		public CFException (string? description, NSString? domain, nint? code, string? failureReason, string? recoverySuggestion)
You can't make the `code` argument nullable, because it's a struct and it would be a breaking change.

2022-05-31 19:35 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6222158&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15090/commits/)

2022-06-01 00:37 UTC, vs-mobiletools-engineering-service2 commented
### :x: [CI Build] Tests failed on VSTS: simulator tests iOS :x:

Tests failed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6222159&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220531.16/6222159/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6222159/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# Test results

<details>
<summary>1 tests failed, 147 tests passed.</summary>

## Failed tests

 * framework-test/watchOS 32-bits - simulator/Debug: Crashed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6222159&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1160.Monterey'
Merge 2387e510e00a86c9428066932871d1ccde357fe6 into 4542fce4a200caa108a4db6528adeb385220e276

2022-06-02 16:06 UTC, tj-devel709 commented
@rolfbjarne  Changes applied!

2022-06-02 17:44 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.131-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Bundle.15.4.131-ci.pr.gh15090.pkg)
* [Microsoft.iOS.Ref.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Ref.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Runtime.ios-arm.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Runtime.ios-arm64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Sdk.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Sdk.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Templates.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Templates.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.iOS.Windows.Sdk.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.131-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.MacCatalyst.Bundle.15.4.131-ci.pr.gh15090.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.MacCatalyst.Ref.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.MacCatalyst.Sdk.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.MacCatalyst.Templates.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Bundle.12.3.131-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.macOS.Bundle.12.3.131-ci.pr.gh15090.pkg)
* [Microsoft.macOS.Ref.12.3.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.macOS.Ref.12.3.131-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.macOS.Runtime.osx-arm64.12.3.131-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.macOS.Runtime.osx-x64.12.3.131-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Sdk.12.3.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.macOS.Sdk.12.3.131-ci.pr.gh15090.nupkg)
* [Microsoft.macOS.Templates.12.3.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.macOS.Templates.12.3.131-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.131-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.131-ci.pr.gh15090.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.NET.Workload.iOS.15.4.131-ci.pr.gh15090.msi)
* [Microsoft.tvOS.Bundle.15.4.131-ci.pr.gh15090.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.tvOS.Bundle.15.4.131-ci.pr.gh15090.pkg)
* [Microsoft.tvOS.Ref.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.tvOS.Ref.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc7cdf/6234923/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.131-ci.pr.gh15090.nupkg)
* [Microsoft.tvOS.Sdk.15.4.131-ci.pr.gh15090.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6d0f6066bfce18fd0618df69152ceed504fc [...]

2022-06-02 17:45 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234923&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [24e648b914cc2adec8e05db055c2ce8653165be0](https://github.com/xamarin/xamarin-macios/pull/15090/commits/24e648b914cc2adec8e05db055c2ce8653165be0)

2022-06-02 17:59 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API diff (for current PR)

:information_source: API Diff (from PR only) (please review changes)

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/api-diff.html) [gist](https://gist.github.com/141328fd4fa3ce48ce7662d96c98eb14)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/8dc2fc934052d10a2a4863e75a788f5a)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/75482cb62578e55fa68d5296347f5504)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/ab7a53da03e3eb8d3c5662e720eba81a)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/b060830ba4d380a19923c94db0405048)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/2eba483213882d428ee713a39393f306)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/652860e10d7013dc0f5c8704f1cc83e5)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/d44e62f1ecd50c773fbf1f64db7dfab1)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref//Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/cd1d0d454dbb598030c7ba2b2795f9e4)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/416736b300beda750f9d7ad50d11d04e)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/b340e24c2ddc8e25d19c166d1995c2b0)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/96f0b21549e5097879e777a96a8f3e34)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/5883b2aff3eaa43c81a655e67757504c)
</details>


# API diff (vs stable)

:white_check_mark: API Diff from stable

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/api-diff.html) [gist](https://gist.github.com/9c14f5a0da60be6aaa06fceaa6ed8f63)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/7cae553e81a35f3f1f8055168b0ba419)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/44211c676149c79f70a77b5ba66f8d55)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/f90696d06d0db26f16b1feecff5c5709)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/15ef5e60f3619aa7bff052ce65cc4c04)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/8328d6a978b4adb15409ce4d3d2a3cd1)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/43e0b2ee555ff15ba4f7cd1a86bd7dc5)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/b985d0e65d9f8613afa80353cb10cc50)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/7e7b6c8f56705716563b128f1fbba400)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/807da7dc53b243ea5021d6c00592fe9b)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/7ff9843696038bd904fb1ce66d6f338e)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/1f57b96366fd940361e5d3b5652ebbec)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/1a778cc9c96b7a53d968fcb9ad15f1d3)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234923&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1100.Monterey
Hash: [24e648b914cc2adec8e05db055c2ce8653165be0](https://github.com/xamarin/xamarin-macios/pull/15090/commits/24e648b914cc2adec8e05db055c2ce8653165be0)

2022-06-02 20:56 UTC, rolfbjarne approved these changes

2022-06-03 01:59 UTC, vs-mobiletools-engineering-service2 commented
### :x: [CI Build] Tests failed on VSTS: simulator tests iOS :x:

Tests failed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234923&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.24/6234923/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6234923/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# Test results

<details>
<summary>4 tests failed, 144 tests passed.</summary>

## Failed tests

 * fsharp/watchOS 32-bits - simulator/Debug: Crashed
 * introspection/watchOS 32-bits - simulator/Debug: Crashed
 * dont link/watchOS 32-bits - simulator/Debug: Crashed
 * mono-native-compat/watchOS 32-bits - simulator/Debug: Crashed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234923&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1099.Monterey'
Merge 24e648b914cc2adec8e05db055c2ce8653165be0 into 030700470b3141fbfe0268f569172f7878ad087b

2022-06-06 12:51 UTC, chamons approved these changes

2022-06-06 12:51 UTC, chamons commented on src/CoreFoundation/CFProxySupport.cs
> +				var port = proxy?.Port;
I don't _love_ the usage of var here where the right hand size doesn't make it obvious if Port is a int or a string for example, but I think it's _fine_ enough.

2022-06-06 14:56 UTC, tj-devel709 commented
Unrelated Test Failures: https://github.com/xamarin/maccore/issues/2558

2022-06-06 14:56 UTC, merged