[runtime] Improve error reporting when calling mono_assembly_open.
xamarin/xamarin-macios pull request #15139
Opened 2022-05-27 09:02 UTC by rolfbjarne

2022-05-27 10:39 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.110-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Bundle.15.4.110-ci.pr.gh15139.pkg)
* [Microsoft.iOS.Ref.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Ref.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Runtime.ios-arm.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Runtime.ios-arm64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Sdk.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Sdk.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Templates.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Templates.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.iOS.Windows.Sdk.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.110-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.MacCatalyst.Bundle.15.4.110-ci.pr.gh15139.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.MacCatalyst.Ref.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.MacCatalyst.Sdk.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.MacCatalyst.Templates.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Bundle.12.3.110-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.macOS.Bundle.12.3.110-ci.pr.gh15139.pkg)
* [Microsoft.macOS.Ref.12.3.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.macOS.Ref.12.3.110-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.macOS.Runtime.osx-arm64.12.3.110-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.macOS.Runtime.osx-x64.12.3.110-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Sdk.12.3.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.macOS.Sdk.12.3.110-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Templates.12.3.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.macOS.Templates.12.3.110-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.110-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.110-ci.pr.gh15139.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.NET.Workload.iOS.15.4.110-ci.pr.gh15139.msi)
* [Microsoft.tvOS.Bundle.15.4.110-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.tvOS.Bundle.15.4.110-ci.pr.gh15139.pkg)
* [Microsoft.tvOS.Ref.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.tvOS.Ref.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed41cef/6211243/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.110-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Sdk.15.4.110-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7b83ebff496feefefd73184a0aa66ccd9ed4 [...]

2022-05-27 10:41 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

Failed tests are:

* dontlink
* introspection
* linksdk
* linkall
* monotouch-test


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6211243&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c6ba63ca51928ea950f8f3e7da6ed93a28e28220](https://github.com/xamarin/xamarin-macios/pull/15139/commits/c6ba63ca51928ea950f8f3e7da6ed93a28e28220)

2022-05-27 10:51 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API diff (for current PR)

:information_source: API Diff (from PR only) (please review changes)

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/api-diff.html) [gist](https://gist.github.com/2c2931a1753775398da756ee39fa725f)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/0408452eb8932030d0f608def1bf05ca)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/51f0f9957392759c051d18ab77316e90)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/2b8201e8e5a4d556234c60d871626e23)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/c97b450f0febc3536fc194eabc66ce7c)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/f98334754056fd93bf0a4e6e9c14cbba)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/552b498ee6bbd873b648ac15597ee7f5)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/90b30e1e08024e833dd3d580369255ee)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref//Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/18bf4bab152eaa461955d7a74cf62d6a)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/d814ac929b6d0bd8fc50b193b7a4b082)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/528a5c0f9b26c3ad7afa1eb4e51ca16d)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/a0d6050901ef3517241dcbac17e8f831)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/a83001eb969639959dcb0f10b60a08ef)
</details>


# API diff (vs stable)

:white_check_mark: API Diff from stable

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/api-diff.html) [gist](https://gist.github.com/4980054a7ba517950c620e3219d071eb)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/e3ea75436129fb8c8b6036d1fed92e74)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/099ba725b265ae1997ea5386122c0ea5)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/bed16e409917c05fd012f1a0280febdf)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/5c05f53f2432e15397075b2cc552d424)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/04c97dfcad0da61f66fb43ed142b3ccf)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/681cacb18ad30d0b415df6b46ee4b388)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/a12f009c02c7642970150cc8bedf8621)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/0d46254b1461ebc9062c73fc25cd74dc)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/02b34ac9a4260a1de22c199d9cd2cb1e)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/b19bc3429b8b2ff8682fcf857554e5b2)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/8cbf6f8a81fa5f217c3d312c18dcafaa)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/45f87490aeac6a726970a67d30be7880)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.6/6211243/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6211243&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1043.Monterey'
Hash: [c6ba63ca51928ea950f8f3e7da6ed93a28e28220](https://github.com/xamarin/xamarin-macios/pull/15139/commits/c6ba63ca51928ea950f8f3e7da6ed93a28e28220)

2022-05-27 10:52 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* dontlink
* introspection
* linksdk
* linkall
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6211243&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c6ba63ca51928ea950f8f3e7da6ed93a28e28220](https://github.com/xamarin/xamarin-macios/pull/15139/commits/c6ba63ca51928ea950f8f3e7da6ed93a28e28220)

2022-05-27 13:48 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.111-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Bundle.15.4.111-ci.pr.gh15139.pkg)
* [Microsoft.iOS.Ref.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Ref.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Runtime.ios-arm.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Runtime.ios-arm64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Sdk.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Sdk.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Templates.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Templates.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.iOS.Windows.Sdk.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.111-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.MacCatalyst.Bundle.15.4.111-ci.pr.gh15139.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.MacCatalyst.Ref.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.MacCatalyst.Sdk.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.MacCatalyst.Templates.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Bundle.12.3.111-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.macOS.Bundle.12.3.111-ci.pr.gh15139.pkg)
* [Microsoft.macOS.Ref.12.3.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.macOS.Ref.12.3.111-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.macOS.Runtime.osx-arm64.12.3.111-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.macOS.Runtime.osx-x64.12.3.111-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Sdk.12.3.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.macOS.Sdk.12.3.111-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Templates.12.3.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.macOS.Templates.12.3.111-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.111-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.111-ci.pr.gh15139.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.NET.Workload.iOS.15.4.111-ci.pr.gh15139.msi)
* [Microsoft.tvOS.Bundle.15.4.111-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.tvOS.Bundle.15.4.111-ci.pr.gh15139.pkg)
* [Microsoft.tvOS.Ref.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.tvOS.Ref.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85cf83/6211564/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.111-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Sdk.15.4.111-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dd39f846d4bf7308fee096b1f9748d3c6c85 [...]

2022-05-27 13:51 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6211564&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a99bc31dbe27c1e2003bcadfc3df9a7bf634dfb4](https://github.com/xamarin/xamarin-macios/pull/15139/commits/a99bc31dbe27c1e2003bcadfc3df9a7bf634dfb4)

2022-05-27 14:06 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API diff (for current PR)

:information_source: API Diff (from PR only) (please review changes)

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/api-diff.html) [gist](https://gist.github.com/68afb8ab401811c067569d1b8d11c9b1)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/7e9c207497860cd1e462c850c521b6f3)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/9a55e7752438d78a922ec1f62102a234)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/722a1992484453b035c720d986af78f5)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/8c86e9aa96cf57ec89b20904357cf728)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/760f97b95d7da43f7855fbb307f84596)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/2f7231f7f15e9f6260a627ba72b36c47)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/6aa241b0671e545f623042a5f1451549)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref//Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/83ead134a3675b3eba14271cc2843589)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/447c31766668b2f1cc0722cb6637a230)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/477628fed7e6d09246125dce40bd5892)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/a5a2f4e1cd994504d9e43492794b47ee)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/217178227211ff12db170db23ba76253)
</details>


# API diff (vs stable)

:white_check_mark: API Diff from stable

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/api-diff.html) [gist](https://gist.github.com/3ad30b589805cb07db618b8188a3a96d)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/22bff30715d1772ee2970b71014b6b4f)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/e6ea6f1406eac8fa5e834ef10d3ebcd9)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/0071c0f8869408415902961d8a9cc327)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/d9a51bff70b3b808e07682957250ad0e)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/4f50cc645ba10e9c35e6df8e297e112a)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/0d4b19b77b97d01302285e1753c1a151)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/77123c8efb927b6bdee1fd9ef4083a16)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/9b9926a1842e657f94f51202a927beca)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/d2bace5870fda4b9e18f56474ce5d58e)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/8b5684443ffca2f14edfc057b580a4ca)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/148d6a685b353ff0eb06bcb450587a66)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/cd6459806fa15d08bc05d8f069422834)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6211564&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1106.Monterey'
Hash: [a99bc31dbe27c1e2003bcadfc3df9a7bf634dfb4](https://github.com/xamarin/xamarin-macios/pull/15139/commits/a99bc31dbe27c1e2003bcadfc3df9a7bf634dfb4)

2022-05-27 14:10 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6211564&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a99bc31dbe27c1e2003bcadfc3df9a7bf634dfb4](https://github.com/xamarin/xamarin-macios/pull/15139/commits/a99bc31dbe27c1e2003bcadfc3df9a7bf634dfb4)

2022-05-27 21:33 UTC, vs-mobiletools-engineering-service2 commented
### :x: [CI Build] Tests failed on VSTS: simulator tests iOS :x:

Tests failed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6211564&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220527.14/6211564/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6211564/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# Test results

<details>
<summary>1 tests failed, 145 tests passed.</summary>

## Failed tests

 * xcframework-test/watchOS 32-bits - simulator/Debug: Crashed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6211564&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1108.Monterey'
Merge a99bc31dbe27c1e2003bcadfc3df9a7bf634dfb4 into 342fb340c80b76a5e66f91cb1035fed10b338424

2022-05-30 09:32 UTC, rolfbjarne commented
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2558).

2022-06-01 14:10 UTC, tj-devel709 approved these changes

2022-06-01 14:14 UTC, stephen-hawley requested changes

2022-06-01 14:14 UTC, stephen-hawley commented on runtime/runtime.m
> +			xamarin_assertion_message ("Failed to open the assembly '%s' from the app: %i (errno: %i). This is usually fixed by cleaning and rebuilding your project; if that doesn't work, please file a bug re
Since these are the same messages, how about using a constant for both of these?

2022-06-02 09:27 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Generate API diff'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6234152&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15139/commits/)

2022-06-02 09:29 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6234152&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15139/commits/)

2022-06-02 13:17 UTC, stephen-hawley approved these changes

2022-06-02 16:04 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.15.4.137-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Bundle.15.4.137-ci.pr.gh15139.pkg)
* [Microsoft.iOS.Ref.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Ref.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Runtime.ios-arm.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Runtime.ios-arm64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Runtime.iossimulator-arm64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Runtime.iossimulator-x64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Runtime.iossimulator-x86.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Sdk.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Sdk.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Templates.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Templates.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.iOS.Windows.Sdk.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.iOS.Windows.Sdk.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Bundle.15.4.137-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.MacCatalyst.Bundle.15.4.137-ci.pr.gh15139.pkg)
* [Microsoft.MacCatalyst.Ref.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.MacCatalyst.Ref.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Sdk.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.MacCatalyst.Sdk.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.MacCatalyst.Templates.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.MacCatalyst.Templates.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Bundle.12.3.137-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.macOS.Bundle.12.3.137-ci.pr.gh15139.pkg)
* [Microsoft.macOS.Ref.12.3.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.macOS.Ref.12.3.137-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.12.3.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.macOS.Runtime.osx-arm64.12.3.137-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.12.3.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.macOS.Runtime.osx-x64.12.3.137-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Sdk.12.3.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.macOS.Sdk.12.3.137-ci.pr.gh15139.nupkg)
* [Microsoft.macOS.Templates.12.3.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.macOS.Templates.12.3.137-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.12.3.137-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.NET.Workload.iOS.15.4.137-ci.pr.gh15139.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.NET.Workload.iOS.15.4.137-ci.pr.gh15139.msi)
* [Microsoft.tvOS.Bundle.15.4.137-ci.pr.gh15139.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.tvOS.Bundle.15.4.137-ci.pr.gh15139.pkg)
* [Microsoft.tvOS.Ref.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.tvOS.Ref.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.tvOS.Runtime.tvos-arm64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616ec84/6234635/package/Microsoft.tvOS.Runtime.tvossimulator-x64.15.4.137-ci.pr.gh15139.nupkg)
* [Microsoft.tvOS.Sdk.15.4.137-ci.pr.gh15139.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/61a993da5c3a75e0422976a2dcf5fef8e616 [...]

2022-06-02 16:07 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234635&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [22d6181f732874af857358a479039b4c2919273e](https://github.com/xamarin/xamarin-macios/pull/15139/commits/22d6181f732874af857358a479039b4c2919273e)

2022-06-02 16:12 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6234635&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [22d6181f732874af857358a479039b4c2919273e](https://github.com/xamarin/xamarin-macios/pull/15139/commits/22d6181f732874af857358a479039b4c2919273e)

2022-06-02 16:16 UTC, vs-mobiletools-engineering-service2 commented
# :clipboard: [PR Build] API Diff :clipboard:

# API diff (for current PR)

:information_source: API Diff (from PR only) (please review changes)

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/api-diff.html) [gist](https://gist.github.com/c2330417a19ea3814d8458339915a12f)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/ios-api-diff.html) [gist](https://gist.github.com/c96dd24ff0ecd9f169d930695ba6397f)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/mac-api-diff.html) [gist](https://gist.github.com/511bf26f11c85a3640414aa85d300d0a)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/tvos-api-diff.html) [gist](https://gist.github.com/27cc623fe960a29703205be8b9921771)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/watchos-api-diff.html) [gist](https://gist.github.com/fac43970c7a69c1f1f3c12d8bf803099)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/0ee933af62e0dea2dd1d045e42df47fc)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/0424d3a0467ae8d6d5cee6ed7a002986)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/34a1d8fd8283ca944ea0c510deb3880c)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref//Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/2f48cc4aef931c86570724584831e160)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/bf36b09c4ed4bd0dbd44b2df3c2b9a96)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref//Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/b6af0a4203f9fab8e850983dd6bd4930)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref//Microsoft.tvOS-api-diff.html) [gist](https://gist.github.com/3218d27c5395081a8d791c643dd2d3e9)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref//Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/fd2d5464447b191830d376933c339f92)
</details>


# API diff (vs stable)

:white_check_mark: API Diff from stable

API diff:  [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/api-diff.html) [gist](https://gist.github.com/c57f84e4e513af07e1609e3428c141bf)

<details><summary>Xamarin</summary>

* iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/ios-api-diff.html) [gist](https://gist.github.com/a32e755d0308598325ec1d1130af2db8)
* macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/mac-api-diff.html) [gist](https://gist.github.com/6243bdc250afc750ab9d6639f9c58d0b)
* tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/tvos-api-diff.html) [gist](https://gist.github.com/8f6c3be1efdf69399c8946f97427a66e)
* watchOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/watchos-api-diff.html) [gist](https://gist.github.com/4a4a7bf0fb9b7e405cc873bf20a0e410)
</details>

<details><summary>.NET</summary>

* dotnet-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/84bd159686af2dea259d29449ac37864)
* dotnet-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/b6bb0ad9f8c3c12255659ce35de195ca)
* dotnet-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/d231b9dce8f972f65d3f3a66f8dd2cd1)
* dotnet-MacCatalyst [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst-api-diff.html) [gist](https://gist.github.com/5b2ae69132256e98961f6ae699186dc4)
</details>

<details><summary>Xamarin vs .NET</summary>

* dotnet-legacy-iOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS-api-diff.html) [gist](https://gist.github.com/62e3f22d9e3884fca81a489ff72e386b)
* dotnet-legacy-macOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS-api-diff.html) [gist](https://gist.github.com/db6bf4b901e7119cb3bd3c559a2afd92)
* dotnet-legacy-tvOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.TVOS-api-diff.html) [gist](https://gist.github.com/60da633037ef3885633dfea7176d93bd)
</details>

<details><summary>iOS vs Mac Catalyst (.NET)</summary>

* dotnet-macCatiOS [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apidiff/;/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst-api-diff.html) [gist](https://gist.github.com/cb0ee1eabb36e90824a15c8485a9ff1c)
</details>


# Generator diff

:white_check_mark: [Generator Diff](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/apigeneratordiff/;//generator-diff/index.html) (no change)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234635&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1163.Monterey'
Hash: [22d6181f732874af857358a479039b4c2919273e](https://github.com/xamarin/xamarin-macios/pull/15139/commits/22d6181f732874af857358a479039b4c2919273e)

2022-06-03 00:17 UTC, vs-mobiletools-engineering-service2 commented
### :x: [CI Build] Tests failed on VSTS: simulator tests iOS :x:

Tests failed on VSTS: simulator tests iOS. 
* [Azure DevOps](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234635&view=ms.vss-test-web.test-result-details)
* [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220602.20/6234635/simulator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6234635/artifacts?artifactName=HtmlReport-simulator&api-version=6.0&$format=zip)


# Test results

<details>
<summary>1 tests failed, 145 tests passed.</summary>

## Failed tests

 * link sdk/watchOS 32-bits - simulator/Debug: Crashed
</details>


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6234635&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1044.Monterey
Merge 22d6181f732874af857358a479039b4c2919273e into 030700470b3141fbfe0268f569172f7878ad087b

2022-06-03 08:41 UTC, rolfbjarne commented
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2558).

2022-06-03 08:41 UTC, merged