[ClockKit] Add support for Xcode 14 beta 1 & 2.
xamarin/xamarin-macios pull request #15417
Opened 2022-07-07 21:11 UTC by mandel-macaque

2022-07-07 22:38 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

Tests on macOS Mac Catalina (10.15) failed for unknown reasons.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6384501&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [21c0991478b6d2e728256d0686f029185bd8b90a](https://github.com/xamarin/xamarin-macios/pull/15417/commits/21c0991478b6d2e728256d0686f029185bd8b90a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 00:29 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/18eae8741a799c336c1e4e17b0fdeb58) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/73c510bb69b22ac57a5731d88f4c5532) (No breaking changes)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/5b7ee7bea2dc1d9cb97dcebf7d23637a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/55a4147942d343453d0be410224d5b55) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/b6d50e1515785a026ff1e42eba0d3931) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/2ba6cf88dfba071dc366c0fcb7c6f6ec) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/6c53779d130e548eeb6aaac75b944627) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/e1a6581cf47f928a5ba5f3b4a74fae4d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/c334b3a5a24f190659385c5510b1a5e6) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/9a516fb5ca8c8df3d88a221412c44661) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/fa89e1c02b7fd72762356ea886f237b9)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/0494f13866acba14727963b23ac476af)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/1a014d811a2e87f25e4a5b272f092de6)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/728655c07fc6238a669e7a8d6e2d94b5)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220707.18/6385025/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/c3b4ae51e1cc96f22872b89a4d7d2f70) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6385025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ac4dee14fa620286af9311ae60a94b47ba142434](https://github.com/xamarin/xamarin-macios/pull/15417/commits/ac4dee14fa620286af9311ae60a94b47ba142434)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 00:30 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6385025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ac4dee14fa620286af9311ae60a94b47ba142434](https://github.com/xamarin/xamarin-macios/pull/15417/commits/ac4dee14fa620286af9311ae60a94b47ba142434)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 00:47 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6385025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ac4dee14fa620286af9311ae60a94b47ba142434](https://github.com/xamarin/xamarin-macios/pull/15417/commits/ac4dee14fa620286af9311ae60a94b47ba142434)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 00:48 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.157-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Bundle.16.0.157-ci.pr.gh15417.pkg)
* [Microsoft.iOS.Ref.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Ref.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Runtime.ios-arm.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Runtime.ios-arm64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Sdk.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Sdk.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Templates.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Templates.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.iOS.Windows.Sdk.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.157-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.MacCatalyst.Bundle.16.0.157-ci.pr.gh15417.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.MacCatalyst.Ref.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.MacCatalyst.Sdk.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.MacCatalyst.Templates.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Bundle.13.0.157-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.macOS.Bundle.13.0.157-ci.pr.gh15417.pkg)
* [Microsoft.macOS.Ref.13.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.macOS.Ref.13.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.macOS.Runtime.osx-arm64.13.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.macOS.Runtime.osx-x64.13.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Sdk.13.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.macOS.Sdk.13.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Templates.13.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.macOS.Templates.13.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.157-ci.pr.gh15417.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.NET.Workload.iOS.16.0.157-ci.pr.gh15417.msi)
* [Microsoft.tvOS.Bundle.16.0.157-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.tvOS.Bundle.16.0.157-ci.pr.gh15417.pkg)
* [Microsoft.tvOS.Ref.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.tvOS.Ref.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a752c3a/6385025/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.157-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Sdk.16.0.157-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6a81a7e0202ac37cd7d65008158e13052a75 [...]

2022-07-08 01:10 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

:tada: All 20 tests passed :tada:

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

:fire: Failed catastrophically on VSTS: simulator tests - cecil (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: framework tests

:fire: Failed catastrophically on VSTS: simulator tests - framework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

:fire: Failed catastrophically on VSTS: simulator tests - linker (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

### :x: xtro tests

:fire: Failed catastrophically on VSTS: simulator tests - xtro (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220707.18/6385025//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6385025/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrop [...]

2022-07-08 13:40 UTC, rolfbjarne requested changes

2022-07-08 13:40 UTC, rolfbjarne commented on src/clockkit.cs
> +		CLKComplicationStaticWidgetMigrationConfiguration StaticWidgetMigrationConfigurationWithKind (string kind, string extensionBundleIdentifier);
```suggestion
		CLKComplicationStaticWidgetMigrationConfiguration Create (string kind, string extensionBundleIdentifier);
```

2022-07-08 15:32 UTC, rolfbjarne approved these changes

2022-07-08 16:41 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6388035&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cfef6446a4f72a07092d2854519a9a35d8c07e42](https://github.com/xamarin/xamarin-macios/pull/15417/commits/cfef6446a4f72a07092d2854519a9a35d8c07e42)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 16:49 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6388035&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1168.Monterey'
Hash: [cfef6446a4f72a07092d2854519a9a35d8c07e42](https://github.com/xamarin/xamarin-macios/pull/15417/commits/cfef6446a4f72a07092d2854519a9a35d8c07e42)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 16:59 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6388035&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cfef6446a4f72a07092d2854519a9a35d8c07e42](https://github.com/xamarin/xamarin-macios/pull/15417/commits/cfef6446a4f72a07092d2854519a9a35d8c07e42)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 17:00 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/64986023685ea62d070bd00083dd869a) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/bd296c8c87138ee7f8de696b29636242) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/305e99976af4f7ea9aeeb71775f5ba7c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/a913e619a59d82a92758e6465c5ed0ca) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/0d1a094c879cc3cdd604d29076d5f2e2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/c3d7c4082c1ff4d80f6307ef9ebb783a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/269b824276398ff6136754c9be560d38) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/783c09c2a38ef09324af5a6629c77c6b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/8b391504b1db6d2a8a37af1a7373df75) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/d264ada9486d2aa23e1696f41fb47270)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/ff15f176d306557d5e177a6489524acb)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/72de2b313dde0bcfb2d5681685f3a835)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/986f2c8a6c3cb1541d7ac9f30dd53d35)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.21/6388035/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/148ae463c2200a8b43be42927029d391) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6388035&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cfef6446a4f72a07092d2854519a9a35d8c07e42](https://github.com/xamarin/xamarin-macios/pull/15417/commits/cfef6446a4f72a07092d2854519a9a35d8c07e42)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 17:08 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/0e409e72a5f40859680e5c421d1256a6) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/b4d6f4dc3c690fb57990c51ea83688de) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/4753c767282a99df8c53a89c2f6c5d01) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/6e6971cfa08d02af7a237770384ab506) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/a9c914aab036c06549792cf8b8f144c9) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/c39f6d3790bc12d349f7fb73f1c80112) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/7108364cd0a1e962415fb75d07a6bdbc) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/52438906d9003dfe3653a9427fa6b889) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/ffb2178db1d4b3d3ec2b0f2c2f37763e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/065d428b8f2dcc11006a12a43349ffe2)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/eb39459ab4bcb1bcb4c5fc776bc759da)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/5e864a1a5b7ddcb4c5e9795b7a494e26)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/6a174c75e500780e7f7cb5a6a9ab472a)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220708.22/6388036/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/eb6ecd2eb7123ffe9ac443ee81a63fee) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6388036&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cfef6446a4f72a07092d2854519a9a35d8c07e42](https://github.com/xamarin/xamarin-macios/pull/15417/commits/cfef6446a4f72a07092d2854519a9a35d8c07e42)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 17:13 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.160-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Bundle.16.0.160-ci.pr.gh15417.pkg)
* [Microsoft.iOS.Ref.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Ref.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Runtime.ios-arm.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Runtime.ios-arm64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Sdk.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Sdk.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Templates.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Templates.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.iOS.Windows.Sdk.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.160-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.MacCatalyst.Bundle.16.0.160-ci.pr.gh15417.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.MacCatalyst.Ref.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.MacCatalyst.Sdk.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.MacCatalyst.Templates.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Bundle.13.0.160-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.macOS.Bundle.13.0.160-ci.pr.gh15417.pkg)
* [Microsoft.macOS.Ref.13.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.macOS.Ref.13.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.macOS.Runtime.osx-arm64.13.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.macOS.Runtime.osx-x64.13.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Sdk.13.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.macOS.Sdk.13.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Templates.13.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.macOS.Templates.13.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.160-ci.pr.gh15417.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.NET.Workload.iOS.16.0.160-ci.pr.gh15417.msi)
* [Microsoft.tvOS.Bundle.16.0.160-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.tvOS.Bundle.16.0.160-ci.pr.gh15417.pkg)
* [Microsoft.tvOS.Ref.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.tvOS.Ref.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7b154/6388036/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.160-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Sdk.16.0.160-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/7f669af44a04d10d08db22bca6dfca8fbef7 [...]

2022-07-08 17:15 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6388036&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cfef6446a4f72a07092d2854519a9a35d8c07e42](https://github.com/xamarin/xamarin-macios/pull/15417/commits/cfef6446a4f72a07092d2854519a9a35d8c07e42)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 17:21 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6388036&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cfef6446a4f72a07092d2854519a9a35d8c07e42](https://github.com/xamarin/xamarin-macios/pull/15417/commits/cfef6446a4f72a07092d2854519a9a35d8c07e42)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 18:29 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

:tada: All 96 tests passed :tada:

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

:fire: Failed catastrophically on VSTS: simulator tests - cecil (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: install_source tests

:fire: Failed catastrophically on VSTS: simulator tests - install_source (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

### :x: xtro tests

:fire: Failed catastrophically on VSTS: simulator tests - xtro (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388035/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.21/6388035//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstud [...]

2022-07-08 19:12 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

:tada: All 23 tests passed :tada:

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

:fire: Failed catastrophically on VSTS: simulator tests - cecil (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: framework tests

:fire: Failed catastrophically on VSTS: simulator tests - framework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

:fire: Failed catastrophically on VSTS: simulator tests - interdependent_binding_projects (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)

### :x: install_source tests

:fire: Failed catastrophically on VSTS: simulator tests - install_source (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

:fire: Failed catastrophically on VSTS: simulator tests - linker (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

### :x: xtro tests

:fire: Failed catastrophically on VSTS: simulator tests - xtro (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220708.22/6388036//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6388036/arti [...]

2022-07-12 00:04 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6398170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [453c4b31db44507928567b992278e4ab7017280c](https://github.com/xamarin/xamarin-macios/pull/15417/commits/453c4b31db44507928567b992278e4ab7017280c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-12 00:11 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/82770d4f68c98a04419e975a4b0a5275) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/e616bdc2fa488accf22d4337b9e2d512) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/dbc99aa57ca45d816883a97b833a3e73) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/7178fdd9d2b4e5d360ccd3e3711b4c94) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/7f2342940b54bb0c7fdbcd5ccf730fa0) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/981eb30435e44e34bda62b19485d5d02) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/b39e02837149e865128eb3bacfc606e1) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/7d8f8f424b9636cf9d22687c2826d4f9) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/cd2d9a8ddddb6e5d01ff9552e96b67d0)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/5bb4cf4552acc37eb40688bd64128220)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/9b721b0d465d6bc68a17ac1fee60ecd9)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220711.40/6398170/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/7ee1e1c3067a35ff0af9112ea2122f56)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6398170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [453c4b31db44507928567b992278e4ab7017280c](https://github.com/xamarin/xamarin-macios/pull/15417/commits/453c4b31db44507928567b992278e4ab7017280c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-12 00:13 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6398170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [453c4b31db44507928567b992278e4ab7017280c](https://github.com/xamarin/xamarin-macios/pull/15417/commits/453c4b31db44507928567b992278e4ab7017280c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-12 00:15 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.162-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Bundle.16.0.162-ci.pr.gh15417.pkg)
* [Microsoft.iOS.Ref.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Ref.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Runtime.ios-arm.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Runtime.ios-arm64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Sdk.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Sdk.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Templates.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Templates.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.iOS.Windows.Sdk.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.162-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.MacCatalyst.Bundle.16.0.162-ci.pr.gh15417.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.MacCatalyst.Ref.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.MacCatalyst.Sdk.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.MacCatalyst.Templates.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Bundle.13.0.162-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.macOS.Bundle.13.0.162-ci.pr.gh15417.pkg)
* [Microsoft.macOS.Ref.13.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.macOS.Ref.13.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.macOS.Runtime.osx-arm64.13.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.macOS.Runtime.osx-x64.13.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Sdk.13.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.macOS.Sdk.13.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Templates.13.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.macOS.Templates.13.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.162-ci.pr.gh15417.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.NET.Workload.iOS.16.0.162-ci.pr.gh15417.msi)
* [Microsoft.tvOS.Bundle.16.0.162-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.tvOS.Bundle.16.0.162-ci.pr.gh15417.pkg)
* [Microsoft.tvOS.Ref.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.tvOS.Ref.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e0555/6398170/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.162-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Sdk.16.0.162-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e619afd31401cd0e993bbd3a83ceca89358e [...]

2022-07-12 01:45 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

16 tests crashed, 1 tests failed, 73 tests passed.

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

:fire: Failed catastrophically on VSTS: simulator tests - cecil (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: framework tests

:fire: Failed catastrophically on VSTS: simulator tests - framework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: install_source tests

:fire: Failed catastrophically on VSTS: simulator tests - install_source (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220711.40/6398170//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6398170/artifacts?a [...]

2022-07-13 21:17 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Tests on macOS M1 - Mac Big Sur (11.5) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6409778&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c981695c1ef42542855f58faf7f5d7893d3231f3](https://github.com/xamarin/xamarin-macios/pull/15417/commits/c981695c1ef42542855f58faf7f5d7893d3231f3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-13 21:31 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6409778&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c981695c1ef42542855f58faf7f5d7893d3231f3](https://github.com/xamarin/xamarin-macios/pull/15417/commits/c981695c1ef42542855f58faf7f5d7893d3231f3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-13 21:32 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/185aafe78a89eb2ad40f6acfdfb0e9f3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/72994704a8c43b7abf57df61078b04f6) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/e52b2400fa02c4d6d97be9164ca1423c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/ef47f1287768ca958f7f1dfd9b5ea19f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/9040c1e9a637db3240fd6d80ac123c80) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/8d6034ecb212bb6890e561b788c08b1d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/75f608a58c0efe8e72f1bd932a1940ca) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/b4ddea09a3ea2247d669bfc998816de3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/e8235d495520ed21720b0f5e548a08e1) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/2d7207dfb756061c68b59d684be7516d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/40d14db5076945925025a450edd85185) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/d42968e8580f697b6d216e37b62c8370) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/9979f5871c6881f21a72358d63e166ba) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/e0fb79646bad0ce2e141bacbb48a0e1a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/d8c8e7489a9382127da1fd22aefb9d6e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/e4c78b2400eef08174e92c0ac6d3aa78) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/174c5e1268c1193387f0de76bf1f1d04)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/57c0387c25a77d1894096f4200d84664)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/44ab20ff7a8487fe928dbd3f2c3c9e9b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/7cb914d753219568899f2b17ef21f3c8)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220713.12/6409778/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/f6fec6361dcec67904e5a3adc23ad035) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6409778&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c981695c1ef42542855f58faf7f5d7893d3231f3](https://github.com/xamarin/xamarin-macios/pull/15417/commits/c981695c1ef42542855f58faf7f5d7893d3231f3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-13 21:35 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.193-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Bundle.16.0.193-ci.pr.gh15417.pkg)
* [Microsoft.iOS.Ref.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Ref.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Runtime.ios-arm.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Runtime.ios-arm64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Sdk.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Sdk.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Templates.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Templates.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.iOS.Windows.Sdk.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.193-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.MacCatalyst.Bundle.16.0.193-ci.pr.gh15417.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.MacCatalyst.Ref.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.MacCatalyst.Sdk.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.MacCatalyst.Templates.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Bundle.13.0.193-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.macOS.Bundle.13.0.193-ci.pr.gh15417.pkg)
* [Microsoft.macOS.Ref.13.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.macOS.Ref.13.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.macOS.Runtime.osx-arm64.13.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.macOS.Runtime.osx-x64.13.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Sdk.13.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.macOS.Sdk.13.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Templates.13.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.macOS.Templates.13.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.193-ci.pr.gh15417.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.NET.Workload.iOS.16.0.193-ci.pr.gh15417.msi)
* [Microsoft.tvOS.Bundle.16.0.193-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.tvOS.Bundle.16.0.193-ci.pr.gh15417.pkg)
* [Microsoft.tvOS.Ref.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.tvOS.Ref.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9757f/6409778/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.193-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Sdk.16.0.193-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/5a17467590147c96f8000c548ad5430b34f9 [...]

2022-07-14 01:20 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 217 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>9 tests failed, 14 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2758 Passed: 2647 Inconclusive: 9 Failed: 1 Ignored: 110)
 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6409778/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220713.12/6409778//simulator_xammac/;/tests/vsdrops_index.html) [Download](https:// [...]

2022-07-14 18:32 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.195-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Bundle.16.0.195-ci.pr.gh15417.pkg)
* [Microsoft.iOS.Ref.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Ref.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Runtime.ios-arm.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Runtime.ios-arm64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Sdk.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Sdk.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Templates.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Templates.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.iOS.Windows.Sdk.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.195-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.MacCatalyst.Bundle.16.0.195-ci.pr.gh15417.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.MacCatalyst.Ref.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.MacCatalyst.Sdk.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.MacCatalyst.Templates.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Bundle.13.0.195-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.macOS.Bundle.13.0.195-ci.pr.gh15417.pkg)
* [Microsoft.macOS.Ref.13.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.macOS.Ref.13.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.macOS.Runtime.osx-arm64.13.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.macOS.Runtime.osx-x64.13.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Sdk.13.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.macOS.Sdk.13.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Templates.13.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.macOS.Templates.13.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.195-ci.pr.gh15417.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.NET.Workload.iOS.16.0.195-ci.pr.gh15417.msi)
* [Microsoft.tvOS.Bundle.16.0.195-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.tvOS.Bundle.16.0.195-ci.pr.gh15417.pkg)
* [Microsoft.tvOS.Ref.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.tvOS.Ref.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b83c2a/6415246/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.195-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Sdk.16.0.195-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/dcebc89aeb407ffc9c747802fb49fc6246b8 [...]

2022-07-14 18:42 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/54453c0e3887688ee1b85027f4ddb71f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/70422a9a1ea4f27b7e2e6ee7b9e15515) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/3febfe00e7fab4c0b298acaa0e87f3bb) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/6901e0662895d3f0a5717924c62f78ab) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/5817a0be33793e15433d9a6d1cdc4546) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/1cae7201a28183abdb42c091d406e12a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/2fcc3e8e44ea54b8dc3a3e89721a92e0) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/e094e737cbf93bb4a3033f37b13ce708) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/b5f932431fbaa4b674307497435e683a)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/0eaf3dd22efa5515b90420e9983d6cde)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/30c438f24057824b05a1e7d4bc1aab7b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/0a433ff440db150cb0e7ca2d4a9bc6ce)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.21/6415246/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/6c959f12777dd35256cee46039f17bfe) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6415246&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [08cdf3a868fdbf419d20708635ba8f1e5d5dfefd](https://github.com/xamarin/xamarin-macios/pull/15417/commits/08cdf3a868fdbf419d20708635ba8f1e5d5dfefd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-14 18:44 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6415246&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [08cdf3a868fdbf419d20708635ba8f1e5d5dfefd](https://github.com/xamarin/xamarin-macios/pull/15417/commits/08cdf3a868fdbf419d20708635ba8f1e5d5dfefd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-14 21:14 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/b99e68c176c346beb43e6e64efdb30e6) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/6d94fe9efecf6129db0ca74213e718b6) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/e519bfc048ea06b5cbdb077191c4ccc7) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/48a888f5dead14d3dbfa156739d105b8) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/ff348312225a4ba8bf14deb6d5b9cf4f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/82a06a20436bf78438d33dac2a7c40d2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/3dcf532e938b3ca4d81d74c3ae4ac829) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/02da0e934922b0953d34896c28f97581) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/2c2b50a7ede62bab89506eb6543de543) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/d208c932a2149c35352d67444451425a)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/4d443be97867973867a52ceea112a6e0)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a3c0f6cdff978609f0a5a794080eb11d)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/1e962b241f1344e701aace3e78a803f9)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220714.25/6416432/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/94cca6fdde222af647cb11eaa1e0e6bd) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6416432&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a1e680b8cf3559afdbd1225ff95eeb7f53f7cd24](https://github.com/xamarin/xamarin-macios/pull/15417/commits/a1e680b8cf3559afdbd1225ff95eeb7f53f7cd24)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-14 21:21 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.196-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Bundle.16.0.196-ci.pr.gh15417.pkg)
* [Microsoft.iOS.Ref.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Ref.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Runtime.ios-arm.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Runtime.ios-arm64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Sdk.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Sdk.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Templates.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Templates.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.iOS.Windows.Sdk.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.196-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.MacCatalyst.Bundle.16.0.196-ci.pr.gh15417.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.MacCatalyst.Ref.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.MacCatalyst.Sdk.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.MacCatalyst.Templates.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Bundle.13.0.196-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.macOS.Bundle.13.0.196-ci.pr.gh15417.pkg)
* [Microsoft.macOS.Ref.13.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.macOS.Ref.13.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.macOS.Runtime.osx-arm64.13.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.macOS.Runtime.osx-x64.13.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Sdk.13.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.macOS.Sdk.13.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.macOS.Templates.13.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.macOS.Templates.13.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.196-ci.pr.gh15417.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.NET.Workload.iOS.16.0.196-ci.pr.gh15417.msi)
* [Microsoft.tvOS.Bundle.16.0.196-ci.pr.gh15417.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.tvOS.Bundle.16.0.196-ci.pr.gh15417.pkg)
* [Microsoft.tvOS.Ref.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.tvOS.Ref.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaab83e/6416432/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.196-ci.pr.gh15417.nupkg)
* [Microsoft.tvOS.Sdk.16.0.196-ci.pr.gh15417.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f390d324f8ae60f472b6eff5de76ed1fdaaa [...]

2022-07-14 21:31 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6416432&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a1e680b8cf3559afdbd1225ff95eeb7f53f7cd24](https://github.com/xamarin/xamarin-macios/pull/15417/commits/a1e680b8cf3559afdbd1225ff95eeb7f53f7cd24)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-15 01:54 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 217 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>9 tests failed, 14 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2758 Passed: 2647 Inconclusive: 9 Failed: 1 Ignored: 110)
 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6416432/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220714.25/6416432//simulator_xcframework/; [...]

2022-07-15 15:23 UTC, mandel-macaque commented
Cailling tests are unrelated. https://github.com/xamarin/xamarin-macios/pull/15503

2022-07-15 15:24 UTC, merged