[AuthenticationServices] Update bindings for Xcode 14 beta 1 and 2
xamarin/xamarin-macios pull request #15427
Opened 2022-07-08 15:16 UTC by tj-devel709

Binding updates for AuthenticationServices for Xcode 14

2022-07-08 15:29 UTC, rolfbjarne requested changes
Looks good! Just a few minor comments.

2022-07-08 15:42 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6388022&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15427/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 15:50 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6388022&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [5e309488a4294a56461a9221544f329d2f041c6b](https://github.com/xamarin/xamarin-macios/pull/15427/commits/5e309488a4294a56461a9221544f329d2f041c6b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-08 15:53 UTC, mandel-macaque requested changes

2022-07-08 15:53 UTC, mandel-macaque commented on src/authenticationservices.cs
> +		[TV (16,0)]
The type has NoTV already.

2022-07-08 15:53 UTC, mandel-macaque commented on src/authenticationservices.cs
> +		[TV (16,0)]
Same.

2022-07-08 15:53 UTC, mandel-macaque commented on src/authenticationservices.cs
> +		[Mac (10,15,4), iOS (13,4), TV (16,0)]
Same.

2022-07-08 16:03 UTC, tj-devel709 commented
I also am getting this build failure: `error BI1079: bgen: Do not know how to make a signature for Security.SecCertificate in parameter `certificate' from AuthenticationServices.ASAuthorizationProviderExtensionLoginManager.SaveCertificate`
that I don't believe I was getting before. I will continue to look into this

2022-07-18 17:49 UTC, tj-devel709 commented
@mandel-macaque this one should be updated to reflect requested changes now!

2022-07-18 22:20 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6429982&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fad7949a1649a64785af5656cb260ce7331df99a](https://github.com/xamarin/xamarin-macios/pull/15427/commits/fad7949a1649a64785af5656cb260ce7331df99a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-18 22:20 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/31fa15a47a93bcf07a67fdb0216408cc) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/1a37924a99c5c5583a75ac504525394e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/975713e3c1221f434f55de382998a639) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/822100ecafb2a0a76e3f2b2b8b85e98f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/b3e2695526305aea70eaaa8510e497f2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/0fb0b89ad469826287d0a35986f6f0cf) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/00513f0075f133ef507526bdd3486843) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/0e45c1feff08ec188df0acafd84e374f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/306761b3e306435f0088ea92a1febfef)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/f3a43a5c51b54f0fa0b500b1f670cc47)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/76f29da762f22fc4e7c1981b7a396aaa)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/d2a4dd650f24ef41cd0ea87c341ee638)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220718.27/6429982/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/41b308042e439bf93c3c8d53d330f592) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6429982&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fad7949a1649a64785af5656cb260ce7331df99a](https://github.com/xamarin/xamarin-macios/pull/15427/commits/fad7949a1649a64785af5656cb260ce7331df99a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-18 22:24 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.193-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Bundle.16.0.193-ci.pr.gh15427.pkg)
* [Microsoft.iOS.Ref.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Ref.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Runtime.ios-arm.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Runtime.ios-arm64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Sdk.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Sdk.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Templates.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Templates.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.iOS.Windows.Sdk.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.193-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.MacCatalyst.Bundle.16.0.193-ci.pr.gh15427.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.MacCatalyst.Ref.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.MacCatalyst.Sdk.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.MacCatalyst.Templates.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Bundle.13.0.193-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.macOS.Bundle.13.0.193-ci.pr.gh15427.pkg)
* [Microsoft.macOS.Ref.13.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.macOS.Ref.13.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.macOS.Runtime.osx-arm64.13.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.macOS.Runtime.osx-x64.13.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Sdk.13.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.macOS.Sdk.13.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Templates.13.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.macOS.Templates.13.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.193-ci.pr.gh15427.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.NET.Workload.iOS.16.0.193-ci.pr.gh15427.msi)
* [Microsoft.tvOS.Bundle.16.0.193-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.tvOS.Bundle.16.0.193-ci.pr.gh15427.pkg)
* [Microsoft.tvOS.Ref.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.tvOS.Ref.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d4532/6429982/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.193-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Sdk.16.0.193-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c395970de5ad06ed9cc56a075b071322fc1d [...]

2022-07-18 22:38 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6429982&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fad7949a1649a64785af5656cb260ce7331df99a](https://github.com/xamarin/xamarin-macios/pull/15427/commits/fad7949a1649a64785af5656cb260ce7331df99a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-19 01:20 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 217 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>2 tests failed, 11 tests passed.</summary>
<details>

 * introspection/tvOS - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>8 tests failed, 15 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220718.27/6429982//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6429982/artifac [...]

2022-07-20 18:07 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6440969&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1164.Monterey'
Hash: [9578c9b4931b67fea378e1d7027e468a205a32f7](https://github.com/xamarin/xamarin-macios/pull/15427/commits/9578c9b4931b67fea378e1d7027e468a205a32f7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-20 18:18 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6440969&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9578c9b4931b67fea378e1d7027e468a205a32f7](https://github.com/xamarin/xamarin-macios/pull/15427/commits/9578c9b4931b67fea378e1d7027e468a205a32f7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-20 18:24 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6440969&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9578c9b4931b67fea378e1d7027e468a205a32f7](https://github.com/xamarin/xamarin-macios/pull/15427/commits/9578c9b4931b67fea378e1d7027e468a205a32f7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-20 18:26 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/aadd2704f7c67be225075d03eb13c328) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/cebc8ca0dde765f7dab945f1c91d7888) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/71e5f107c9e71c2156f419817ccb9136) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/42b2e53ec389eaf805c42b62f29fedbf) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/50700699de74b0c5bb8a72505a0d44c5) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/953d902a69928813a41d1c028625fd6c) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/2ea8194ccd37a15a55a598f094cd72c6) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/de2054b6118312d57ba4405a21cdd7b0) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/97f28db36d5e11513c461fed340eebf1) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/44ff095467bb163a958e6f4e44ded3b1) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/f9979dabcd2cb4a5cb9609394ed1f600) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/001cf703eb3785e8ede41356d54748f3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/6c7bc21818feccea1fadc35aeb48edc2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/cf90f20156f4cc496ea791f7ea73f05b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/e5db8ac40853e40864f7b99097f261a2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/1cd4cc40dfd1baa8c20f19cd34b14bab) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/2d2aed48ff81e70c97bf185847ca2738)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/86fa3dd5941a48da339093751db406e2)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/e52685716ab5913dd1147364b2a44bcf)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/830e331f5f3eefebfbad66bc9c104d77)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220720.12/6440969/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/b2687c0acff4c2e9e6a9a9bea66393eb) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6440969&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9578c9b4931b67fea378e1d7027e468a205a32f7](https://github.com/xamarin/xamarin-macios/pull/15427/commits/9578c9b4931b67fea378e1d7027e468a205a32f7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-20 21:20 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 3 tests failed, 225 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 4)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>2 tests failed, 11 tests passed.</summary>
<details>

 * introspection/tvOS - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220720.12/6440969//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6440969/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6440969&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15427/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-25 17:40 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/1855784d2c523cdd1bf07f19595d5144) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/ddcd40b0f26f58d0407445537778528b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/22157b10e7f3ac76159a46405aece168) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/1a5a4a2ca6a52b868ef23977f0269688) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/56f4459a364e4fe79c07a0e70cf9efdc) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/c6ff180e04ec70577e92acc41aa4d44a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/934324ac8359d9f489beefe837aa81fb) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/a9b3f897584f1dc2199f62362e2ca426) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/4455a6589508a74364d50050f53f3c3f)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/247309c23ae1c7a2c10d53eca414c327)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/316e8e59ff5cc0fb11c9a1b440d7fcac)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220725.3/6462389/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/33a05fdab3ede34053faf924b68594bf)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6462389&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [209929833baa9a0b04c9e72fdef40f0419cd05e3](https://github.com/xamarin/xamarin-macios/pull/15427/commits/209929833baa9a0b04c9e72fdef40f0419cd05e3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-25 17:43 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6462389&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [209929833baa9a0b04c9e72fdef40f0419cd05e3](https://github.com/xamarin/xamarin-macios/pull/15427/commits/209929833baa9a0b04c9e72fdef40f0419cd05e3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-25 17:45 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.220-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Bundle.16.0.220-ci.pr.gh15427.pkg)
* [Microsoft.iOS.Ref.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Ref.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Runtime.ios-arm.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Runtime.ios-arm64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Sdk.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Sdk.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Templates.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Templates.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.iOS.Windows.Sdk.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.220-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.MacCatalyst.Bundle.16.0.220-ci.pr.gh15427.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.MacCatalyst.Ref.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.MacCatalyst.Sdk.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.MacCatalyst.Templates.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Bundle.13.0.220-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.macOS.Bundle.13.0.220-ci.pr.gh15427.pkg)
* [Microsoft.macOS.Ref.13.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.macOS.Ref.13.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.macOS.Runtime.osx-arm64.13.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.macOS.Runtime.osx-x64.13.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Sdk.13.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.macOS.Sdk.13.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Templates.13.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.macOS.Templates.13.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.220-ci.pr.gh15427.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.NET.Workload.iOS.16.0.220-ci.pr.gh15427.msi)
* [Microsoft.tvOS.Bundle.16.0.220-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.tvOS.Bundle.16.0.220-ci.pr.gh15427.pkg)
* [Microsoft.tvOS.Ref.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.tvOS.Ref.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e335e9/6462389/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.220-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Sdk.16.0.220-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/d76b4a1a4ee277d089fac5f1240e6868c0e3 [...]

2022-07-25 18:05 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6462389&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [209929833baa9a0b04c9e72fdef40f0419cd05e3](https://github.com/xamarin/xamarin-macios/pull/15427/commits/209929833baa9a0b04c9e72fdef40f0419cd05e3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-25 20:09 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 226 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 4)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220725.3/6462389//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6462389/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6462389&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15427/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-01 15:41 UTC, tj-devel709 commented
Needs updating to Beta 4

2022-08-02 18:11 UTC, tj-devel709 commented
Beta 4 changes found here: https://github.com/xamarin/xamarin-macios/pull/15604

2022-08-02 19:50 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6503251&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [df88774d80edc62a4dc1eeb360074ed265b62962](https://github.com/xamarin/xamarin-macios/pull/15427/commits/df88774d80edc62a4dc1eeb360074ed265b62962)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-02 19:52 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/f250fccdd25a0324c47d1462f917e2de) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/03f92e0c0801471b31530fc585c15697) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/a7e6871a0d167e3abe2f9d7a7a3bd55d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/66b19913bac3da91b773dc4c8b8a5714) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/e7897a2d803caefc6af5983cc377a340) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/bac691606911e89b28b1ce629c79260e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/8f9d4598f1e4f55f27604818c93b3209) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/52de7c07381e0eb76ab94ac1dc5b413d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/c3e941190cd26f47be2f97750de3feaf) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/c3cef92d2755c247eff8b507860fb012) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/c5958e6f61f42046ccf29ff570eba6f6) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/0720c0f6b59c644a5a5abf77d9adb371) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/7635daccf226f52c2490f407f89defd8) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a58e9a88c1ce460b9cafcce4828dc790) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/f6bcbcdeb6eeffb432b1f6b6dee64fdf) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/2053cebd29e473094c49cd820d1f9ca8) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/5327a588fb4f4d74fda468eeaf7337c9)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/d825ac1d23a00a5ae991b5599068487b)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/24d6048e0d809cda46e68f532d1ae475)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/9fdf464f76dfcbf465d58b42551f5dbd)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220802.7/6503251/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/7a71724f1e96823abd6151f49bb1144f) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6503251&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [df88774d80edc62a4dc1eeb360074ed265b62962](https://github.com/xamarin/xamarin-macios/pull/15427/commits/df88774d80edc62a4dc1eeb360074ed265b62962)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-02 19:56 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.274-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Bundle.16.0.274-ci.pr.gh15427.pkg)
* [Microsoft.iOS.Ref.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Ref.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Runtime.ios-arm.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Runtime.ios-arm64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Sdk.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Sdk.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Templates.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Templates.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.iOS.Windows.Sdk.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.274-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.MacCatalyst.Bundle.16.0.274-ci.pr.gh15427.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.MacCatalyst.Ref.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.MacCatalyst.Sdk.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.MacCatalyst.Templates.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Bundle.13.0.274-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.macOS.Bundle.13.0.274-ci.pr.gh15427.pkg)
* [Microsoft.macOS.Ref.13.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.macOS.Ref.13.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.macOS.Runtime.osx-arm64.13.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.macOS.Runtime.osx-x64.13.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Sdk.13.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.macOS.Sdk.13.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.macOS.Templates.13.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.macOS.Templates.13.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.274-ci.pr.gh15427.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.NET.Workload.iOS.16.0.274-ci.pr.gh15427.msi)
* [Microsoft.tvOS.Bundle.16.0.274-ci.pr.gh15427.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.tvOS.Bundle.16.0.274-ci.pr.gh15427.pkg)
* [Microsoft.tvOS.Ref.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.tvOS.Ref.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2b234/6503251/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.274-ci.pr.gh15427.nupkg)
* [Microsoft.tvOS.Sdk.16.0.274-ci.pr.gh15427.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/53322732188b088d3e7676556bd3091ec9b2 [...]

2022-08-02 20:03 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6503251&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [df88774d80edc62a4dc1eeb360074ed265b62962](https://github.com/xamarin/xamarin-macios/pull/15427/commits/df88774d80edc62a4dc1eeb360074ed265b62962)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-02 22:29 UTC, dalexsoto commented
I think everything is now updated and covered in Manuel's PR https://github.com/xamarin/xamarin-macios/pull/15604 so probably we can close this one to avoid clashes

2022-08-02 22:29 UTC, closed without merging