[Vision] Add support for Xcode 14 beta 1,2 & 3
xamarin/xamarin-macios pull request #15538
Opened 2022-07-18 16:34 UTC by mandel-macaque

2022-07-18 21:13 UTC, dalexsoto requested changes

2022-07-18 21:13 UTC, dalexsoto commented on src/vision.cs
> +		ScaleFitRotate90CCW = 256 + ScaleFit,
```suggestion
		ScaleFitRotate90Ccw = 256 + ScaleFit,
```

2022-07-18 21:13 UTC, dalexsoto commented on src/vision.cs
> +		ScaleFillRotate90CCW = 256 + ScaleFill,
```suggestion
		ScaleFillRotate90Ccw = 256 + ScaleFill,
```

2022-07-18 21:13 UTC, dalexsoto commented on src/vision.cs
> +		CGAffineTransform TransformForImageWidth (nuint width, nuint height);
```suggestion
		CGAffineTransform CreateTransform (nuint width, nuint height);
```

2022-07-18 21:52 UTC, dalexsoto approved these changes

2022-07-18 21:52 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

Tests on macOS Mac Catalina (10.15) failed for unknown reasons.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6429605&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [99e6a9e84fbdd01cc70e1828cd1b3cbfd8c7e423](https://github.com/xamarin/xamarin-macios/pull/15538/commits/99e6a9e84fbdd01cc70e1828cd1b3cbfd8c7e423)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-18 21:52 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Tests on macOS M1 - Mac Big Sur (11.5) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6429605&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [99e6a9e84fbdd01cc70e1828cd1b3cbfd8c7e423](https://github.com/xamarin/xamarin-macios/pull/15538/commits/99e6a9e84fbdd01cc70e1828cd1b3cbfd8c7e423)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-18 23:02 UTC, mandel-macaque commented on src/vision.cs
> +		[TV (16,0), Mac (13,0), iOS (16,0)]
```suggestion
		[TV (16,0), Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
```

2022-07-18 23:03 UTC, mandel-macaque commented on src/vision.cs
> +		ScaleFitRotate90Ccw = 256 + ScaleFit,
```suggestion
		[TV (16,0), Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
		ScaleFitRotate90Ccw = 256 + ScaleFit,
```

2022-07-18 23:03 UTC, mandel-macaque commented on src/vision.cs
> +		ScaleFillRotate90Ccw = 256 + ScaleFill,
```suggestion
		[TV (16,0), Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
		ScaleFillRotate90Ccw = 256 + ScaleFill,
```

2022-07-19 03:49 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6431800&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4d0ca6f25ca35b213a1c60147479bcdabee06ff4](https://github.com/xamarin/xamarin-macios/pull/15538/commits/4d0ca6f25ca35b213a1c60147479bcdabee06ff4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-19 03:49 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.200-ci.pr.gh15538.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Bundle.16.0.200-ci.pr.gh15538.pkg)
* [Microsoft.iOS.Ref.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Ref.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Runtime.ios-arm.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Runtime.ios-arm64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Sdk.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Sdk.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Templates.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Templates.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.iOS.Windows.Sdk.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.200-ci.pr.gh15538.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.MacCatalyst.Bundle.16.0.200-ci.pr.gh15538.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.MacCatalyst.Ref.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.MacCatalyst.Sdk.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.MacCatalyst.Templates.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.macOS.Bundle.13.0.200-ci.pr.gh15538.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.macOS.Bundle.13.0.200-ci.pr.gh15538.pkg)
* [Microsoft.macOS.Ref.13.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.macOS.Ref.13.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.macOS.Runtime.osx-arm64.13.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.macOS.Runtime.osx-x64.13.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.macOS.Sdk.13.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.macOS.Sdk.13.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.macOS.Templates.13.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.macOS.Templates.13.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.200-ci.pr.gh15538.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.NET.Workload.iOS.16.0.200-ci.pr.gh15538.msi)
* [Microsoft.tvOS.Bundle.16.0.200-ci.pr.gh15538.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.tvOS.Bundle.16.0.200-ci.pr.gh15538.pkg)
* [Microsoft.tvOS.Ref.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.tvOS.Ref.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620ec57e/6431800/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.200-ci.pr.gh15538.nupkg)
* [Microsoft.tvOS.Sdk.16.0.200-ci.pr.gh15538.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/38365b5ffca459b09b2140e9fb5f1594620e [...]

2022-07-19 03:57 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/8937ec30fb864928b1676aec6b7dff8c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/0eb2379c518957692fd3c915f7e52a8b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/765d32b97127280be1844f49f43cd742) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/67da7a1e19e0f13f97e76530fbcb9805) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/1d6422d57fdd2291cb8bac7c8c4d9668) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/8c1ceaccca1a163a79890ea76a62738f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/9962c48536d3c70dd8a5daf80e8872e2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/180c25e6f6fc6aeb855e529fa451f03a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/b7aeb1ddb10193087eff68864b9cd9ff)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/7660732484142bd6b9d692727e636767)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/7b73931ab4048acd915f43cd09c74c9d)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/b5414fec164c1f58cb93380976fcc748)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220719.2/6431800/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/f03ca77ced50b3307555bb42c62f9ac8) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6431800&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4d0ca6f25ca35b213a1c60147479bcdabee06ff4](https://github.com/xamarin/xamarin-macios/pull/15538/commits/4d0ca6f25ca35b213a1c60147479bcdabee06ff4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-19 04:15 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6431800&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4d0ca6f25ca35b213a1c60147479bcdabee06ff4](https://github.com/xamarin/xamarin-macios/pull/15538/commits/4d0ca6f25ca35b213a1c60147479bcdabee06ff4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-19 07:00 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 226 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: BuildFailure
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220719.2/6431800//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6431800/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6431800&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15538/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-07-19 18:44 UTC, mandel-macaque commented
xtro tests failures are due to a mismatch with xcode14, which is an issue in the CI, landing and I'll be working on thet later.

2022-07-19 18:44 UTC, merged