[MetricKit] Added support for Xcode 14 beta 1 & 3
xamarin/xamarin-macios pull request #15629
Opened 2022-08-04 17:12 UTC by SotoiGhost

2022-08-04 17:27 UTC, mandel-macaque approved these changes
Small nit.

2022-08-04 17:27 UTC, mandel-macaque commented on src/MetricKit/MXEnums.cs
> +		InternalFailure
```suggestion
		InternalFailure,
```

2022-08-04 17:46 UTC, SotoiGhost commented on src/MetricKit/MXEnums.cs
> +		InternalFailure
![](https://media.giphy.com/media/ka6M66Z58QEcXadCd4/giphy.gif)

2022-08-05 00:47 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/affee705845f2ca5adaf10a5fc330b4b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/359c629a9b6f6a4565d90bcca6ebeee8) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/0b46ebfdfeb639e617730583e8db9a46) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/255c4076542dc556a0c662f0b3578d2d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/194b9df85944265f06d463f7e0e44b72) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/b376be44f0903f2563a3cb5d1264944a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/3e3afbf4c1992bdea8484945ed2ed261) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/9bfe93d3ade6447b2d0d097824cf62e4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/3b0e18f71fc1b9dad695971e472c5b21)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/138432130c49525d02c21a0d75651d91)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/e6d0d9656d9c1585fc1554d7fe9ee62a)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220804.23/6515535/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/6dcc1f7dc2415507df2ee413910ecb51)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6515535&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f8228e3a5516be4553806076310475c306a60a2e](https://github.com/xamarin/xamarin-macios/pull/15629/commits/f8228e3a5516be4553806076310475c306a60a2e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-05 01:01 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6515535&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f8228e3a5516be4553806076310475c306a60a2e](https://github.com/xamarin/xamarin-macios/pull/15629/commits/f8228e3a5516be4553806076310475c306a60a2e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-05 01:01 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.280-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Bundle.16.0.280-ci.pr.gh15629.pkg)
* [Microsoft.iOS.Ref.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Ref.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Runtime.ios-arm.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Runtime.ios-arm64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Sdk.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Sdk.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Templates.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Templates.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.iOS.Windows.Sdk.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.280-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.MacCatalyst.Bundle.16.0.280-ci.pr.gh15629.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.MacCatalyst.Ref.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.MacCatalyst.Sdk.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.MacCatalyst.Templates.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Bundle.13.0.280-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.macOS.Bundle.13.0.280-ci.pr.gh15629.pkg)
* [Microsoft.macOS.Ref.13.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.macOS.Ref.13.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.macOS.Runtime.osx-arm64.13.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.macOS.Runtime.osx-x64.13.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Sdk.13.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.macOS.Sdk.13.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Templates.13.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.macOS.Templates.13.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.280-ci.pr.gh15629.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.NET.Workload.iOS.16.0.280-ci.pr.gh15629.msi)
* [Microsoft.tvOS.Bundle.16.0.280-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.tvOS.Bundle.16.0.280-ci.pr.gh15629.pkg)
* [Microsoft.tvOS.Ref.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.tvOS.Ref.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a914b32/6515535/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.280-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Sdk.16.0.280-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/068c712b43f8ef4b46949d78ce4793f45a91 [...]

2022-08-05 01:15 UTC, dalexsoto requested changes

2022-08-05 01:15 UTC, dalexsoto commented on src/metrickit.cs
> +		NSString ErrorDomain { get; }
This is not needed. It is already generated as part of the enum since you added `[ErrorDomain ("MXErrorDomain")]`

```suggestion
```

2022-08-05 01:17 UTC, dalexsoto approved these changes

2022-08-05 01:17 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Tests timed out

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6515535&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f8228e3a5516be4553806076310475c306a60a2e](https://github.com/xamarin/xamarin-macios/pull/15629/commits/f8228e3a5516be4553806076310475c306a60a2e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-05 01:17 UTC, dalexsoto commented on src/metrickit.cs
> +		NSString ErrorDomain { get; }
Easy fix, committed so we do not wait on this little thing.

2022-08-05 07:19 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/834e7a245b9a9a927e42dff711a9285d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/083bb35c7f8409b1f305b65f9f9abcb2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/7ca00272d7bb600169e600143134790c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~macOS~: (empty diff detected)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/e709746e6fdf87c837689763b5272465) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/46f76191a09be6cbeb298a480c9ad775) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/a687e7fdb2781a1d229e181c751a53ab) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/b304478c9bcabc0b3a8b24de2c3981d2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/753be776371922f07bfacf68e207f2c3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/95c4dec6ea0a38072ec8622141079499) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/f36455e6b15be9adb42dc0fac7106f86) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/c394e67ca7266cc2b9f663ad4e6a7663) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/dcf8bbd1f222ec8d29b5a606d8430484)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/837e0136586b3d749a09278da0db5a29)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/26646908795a55bb038a4bc09b73af28)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/fbb893554f7b4b3da3595f693b17b828)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220805.5/6518641/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/13f2f199fe3092b8d484502578384f69) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6518641&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9acf0874143b65c718afbb50f6c8e58bdc75b07f](https://github.com/xamarin/xamarin-macios/pull/15629/commits/9acf0874143b65c718afbb50f6c8e58bdc75b07f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-05 07:26 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Ref.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Ref.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Runtime.ios-arm.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Runtime.ios-arm64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Sdk.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Sdk.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Templates.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Templates.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.iOS.Windows.Sdk.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Ref.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.MacCatalyst.Ref.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.MacCatalyst.Sdk.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.MacCatalyst.Templates.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Ref.13.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.macOS.Ref.13.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.macOS.Runtime.osx-arm64.13.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.macOS.Runtime.osx-x64.13.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Sdk.13.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.macOS.Sdk.13.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Templates.13.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.macOS.Templates.13.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Ref.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.tvOS.Ref.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Sdk.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.tvOS.Sdk.16.0.281-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Templates.16.0.281-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/Microsoft.tvOS.Templates.16.0.281-ci.pr.gh15629.nupkg)
* [xamarin.ios-15.99.0.281.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/xamarin.ios-15.99.0.281.pkg)
* [xamarin.mac-8.99.0.281.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9017e56e9bb7074294ae18c51eaac375c8b3bd2a/6518641/package/xamarin.mac-8.99.0.281.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6518641&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1183.Monterey'
Hash: [9acf0874143b65c718afbb50f6c8e58bdc75b07f](https://github.com/xamarin/xamarin-macios/pull/15629/commits/9acf0874143b65c718afbb50f6c8e58bdc75b07f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-05 07:30 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6518641&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9acf0874143b65c718afbb50f6c8e58bdc75b07f](https://github.com/xamarin/xamarin-macios/pull/15629/commits/9acf0874143b65c718afbb50f6c8e58bdc75b07f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-05 07:51 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6518641&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9acf0874143b65c718afbb50f6c8e58bdc75b07f](https://github.com/xamarin/xamarin-macios/pull/15629/commits/9acf0874143b65c718afbb50f6c8e58bdc75b07f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-05 13:27 UTC, tj-devel709 approved these changes
Tiny nit thing but otherwise looks good to me!

2022-08-05 13:27 UTC, tj-devel709 commented on src/metrickit.cs
> +	[BaseType (typeof(MXDiagnostic))]
```suggestion
	[BaseType (typeof (MXDiagnostic))]
```
nit

2022-08-05 14:46 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 14 tests failed, 214 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 6)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220805.5/6518641//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6518641/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>2 tests failed, 5 tests passed.</summary>
<details>

 * fsharp/tvOS - simulator/Debug [dotnet]: HarnessException (Harness exception for 'fsharp': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted () [0x00000] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:79 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x002d9] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:639 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
)
 * fsharp/tvOS - simulator/Debug: HarnessException (Harness exception for 'fsharp': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted () [0x00000] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:79 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x002d9] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:639 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220805.5/6518641//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6518641/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220805.5/6518641//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6518641/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>8 tests failed, 15 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220805.5/6518641//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6518641/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
 * Xtro/.NET: BuildFailure
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220805.5/6518641//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6518641/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220805.5/6518641//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6518641/artifacts?artifactName=HtmlReport-simulator [...]

2022-08-06 08:59 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.282-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Bundle.16.0.282-ci.pr.gh15629.pkg)
* [Microsoft.iOS.Ref.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Ref.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Runtime.ios-arm.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Runtime.ios-arm64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Sdk.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Sdk.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Templates.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Templates.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.iOS.Windows.Sdk.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.282-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.MacCatalyst.Bundle.16.0.282-ci.pr.gh15629.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.MacCatalyst.Ref.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.MacCatalyst.Sdk.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.MacCatalyst.Templates.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Bundle.13.0.282-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.macOS.Bundle.13.0.282-ci.pr.gh15629.pkg)
* [Microsoft.macOS.Ref.13.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.macOS.Ref.13.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.macOS.Runtime.osx-arm64.13.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.macOS.Runtime.osx-x64.13.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Sdk.13.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.macOS.Sdk.13.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Templates.13.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.macOS.Templates.13.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.282-ci.pr.gh15629.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.NET.Workload.iOS.16.0.282-ci.pr.gh15629.msi)
* [Microsoft.tvOS.Bundle.16.0.282-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.tvOS.Bundle.16.0.282-ci.pr.gh15629.pkg)
* [Microsoft.tvOS.Ref.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.tvOS.Ref.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992ca0dc/6524555/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.282-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Sdk.16.0.282-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c591cf65f908d9ab46b609b760a21a32992c [...]

2022-08-06 09:05 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/5dd3571f32df850d637559e6a3ad3410) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/0a23f83d3175575ba5874cb6dd995d0c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/39bdb05d04737ac4b82c8e38fb194f0f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/66f8d85a864e64c911b403a83a8a3276) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/9b5a78647473ae9bc4b6ed0b9c87c76d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/ff02f58e888c2fb4d3e8755211921bee) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/9f5b32393a8c77da2eba5565ed93b848) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/653a21548094e812f96c749edbdba838) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/8e057864ad079da6409a3abbbcc23005)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/52ba766efec1e0690f35d74b58f86cb1)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/9849ab9ae88c6857ee456d9fcbf84658)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.3/6524555/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/97a9b2267842e0a8667fa3ab51406df3)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6524555&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8f79333a9d698cea706914edcf0f41b26c23f50d](https://github.com/xamarin/xamarin-macios/pull/15629/commits/8f79333a9d698cea706914edcf0f41b26c23f50d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-06 09:07 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6524555&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8f79333a9d698cea706914edcf0f41b26c23f50d](https://github.com/xamarin/xamarin-macios/pull/15629/commits/8f79333a9d698cea706914edcf0f41b26c23f50d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-06 09:23 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6524555&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8f79333a9d698cea706914edcf0f41b26c23f50d](https://github.com/xamarin/xamarin-macios/pull/15629/commits/8f79333a9d698cea706914edcf0f41b26c23f50d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-06 12:09 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 7 tests failed, 221 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * mscorlib Part 3/tvOS - simulator/Debug: Crashed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.3/6524555//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6524555/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 6)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.3/6524555//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6524555/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.3/6524555//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6524555/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: mononative tests

<summary>2 tests failed, 10 tests passed.</summary>
<details>

 * mono-native-compat/tvOS - simulator/Debug: HarnessException (Harness exception for 'mono-native-compat': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted () [0x00000] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:79 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x002d9] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:639 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
)
 * mono-native-unified/tvOS - simulator/Debug: HarnessException (Harness exception for 'mono-native-unified': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted () [0x00000] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:79 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x002d9] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:639 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.3/6524555//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6524555/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
 * Xtro/.NET: BuildFailure
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.3/6524555//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6524555/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.3/6524555//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6524555/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.3/6524555//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6524555/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/202208 [...]

2022-08-08 15:28 UTC, chamons approved these changes

2022-08-18 13:51 UTC, rolfbjarne approved these changes
Please make sure to update the PR to the latest beta if need be before merging!

2022-08-18 20:50 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/4286d998d6f765f252ba5a9a79361b3e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/9b0e38b576e1269ce3e6c7a915c9f216) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/ae24bdb23e342d29a6cd1bcae610d7ae) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/2d9c5851335b7fb9fe501b96cb5de403) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/b818746a1234fa629b6270796a58ba73) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/fff52bde9199e483465298369f65af96) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/1b96efae87004896abef1b1ffcefacd4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/55eaebeb68cbda8fa543c8240d0e0954) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/e3c66c8bbe16e6a78e4529f22ba505c5)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/371fdba9d1d280dc4fb58b1e2d2e7555)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/67a63d4a53cf3007277bf97c1373b6a0)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.20/6578014/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/aa3a4b3e6dd65c3b40336f23dd179854)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578014&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c005062e25edd05fcef507af3209c0fd76f330b9](https://github.com/xamarin/xamarin-macios/pull/15629/commits/c005062e25edd05fcef507af3209c0fd76f330b9)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-18 20:55 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578014&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c005062e25edd05fcef507af3209c0fd76f330b9](https://github.com/xamarin/xamarin-macios/pull/15629/commits/c005062e25edd05fcef507af3209c0fd76f330b9)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-18 21:04 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.308-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Bundle.16.0.308-ci.pr.gh15629.pkg)
* [Microsoft.iOS.Ref.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Ref.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Runtime.ios-arm.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Runtime.ios-arm64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Sdk.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Sdk.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Templates.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Templates.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.iOS.Windows.Sdk.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.308-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.MacCatalyst.Bundle.16.0.308-ci.pr.gh15629.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.MacCatalyst.Ref.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.MacCatalyst.Sdk.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.MacCatalyst.Templates.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Bundle.13.0.308-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.macOS.Bundle.13.0.308-ci.pr.gh15629.pkg)
* [Microsoft.macOS.Ref.13.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.macOS.Ref.13.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.macOS.Runtime.osx-arm64.13.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.macOS.Runtime.osx-x64.13.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Sdk.13.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.macOS.Sdk.13.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Templates.13.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.macOS.Templates.13.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.308-ci.pr.gh15629.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.NET.Workload.iOS.16.0.308-ci.pr.gh15629.msi)
* [Microsoft.tvOS.Bundle.16.0.308-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.tvOS.Bundle.16.0.308-ci.pr.gh15629.pkg)
* [Microsoft.tvOS.Ref.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.tvOS.Ref.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da05ff8/6578014/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.308-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Sdk.16.0.308-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/539887fd3f115dcf3e62978770403ab16da0 [...]

2022-08-18 21:12 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6578014&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c005062e25edd05fcef507af3209c0fd76f330b9](https://github.com/xamarin/xamarin-macios/pull/15629/commits/c005062e25edd05fcef507af3209c0fd76f330b9)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 00:29 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 8 tests failed, 220 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

<summary>6 tests failed, 59 tests passed.</summary>
<details>

 * dont link/watchOS 32-bits - simulator/Debug: TimedOut
 * dont link/watchOS 32-bits - simulator/Release: TimedOut
 * link all/watchOS 32-bits - simulator/Debug: TimedOut
 * link all/watchOS 32-bits - simulator/Release: TimedOut
 * link sdk/watchOS 32-bits - simulator/Debug: HarnessException (Harness exception for 'link sdk': System.InvalidOperationException: The Writer is closed or in error state.
  at System.Xml.XmlWellFormedWriter.AdvanceState (System.Xml.XmlWellFormedWriter+Token token) [0x001f6] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:1712 
  at System.Xml.XmlWellFormedWriter.WriteCData (System.String text) [0x00029] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:771 
  at Microsoft.DotNet.XHarness.iOS.Shared.Utilities.Extensions.WriteCDataSafe (System.Xml.XmlWriter writer, System.String text) [0x0001b] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Extensions.cs:130 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.TestReportGenerator.WriteFailure (System.Xml.XmlWriter writer, System.String message, System.IO.TextReader stderr) [0x00031] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/TestReportGenerator.cs:43 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.NUnitV3TestReportGenerator.GenerateFailure (System.Xml.XmlWriter writer, System.String title, System.String message, System.IO.TextReader stderr) [0x0030e] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/NUnitV3TestReportGenerator.cs:124 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailureXml (System.String destination, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00033] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:226 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x000a4] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:248 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.String stderrPath, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00008] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:236 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.GenerateXmlFailures (System.String failure, System.Boolean crashed, System.String crashReason) [0x00247] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:575 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x0056f] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:713 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 )
 * link sdk/watchOS 32-bits - simulator/Release: TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/tvOS - simulator/Release (all optimizations) [dotnet]: TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.20/6578014//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578014/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdepend [...]

2022-08-22 21:14 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6590574&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1170.Monterey'
Hash: [a7d201082316e716391cad7817fc4375386cb364](https://github.com/xamarin/xamarin-macios/pull/15629/commits/a7d201082316e716391cad7817fc4375386cb364)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-22 21:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6590574&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a7d201082316e716391cad7817fc4375386cb364](https://github.com/xamarin/xamarin-macios/pull/15629/commits/a7d201082316e716391cad7817fc4375386cb364)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-22 21:33 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/7491cb63e4e178cfe862e0593900fcb6) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/1837f999453f960e7f561a712e32156f) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/0181b84a60c78e3e13713f8c8a2e54a4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/de803a447db9e3ac78c40f705d05ade8) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/66fc6f4d792941d1e67edb852264e295) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/3c0b20efe2134cfcab43ee6923bec5f9) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/e9ac74cff1138f24b76fb0bee83b1e0e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/3d4bd297499b2e92c81e8113ea4d7f2c) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/ac090f5bf096a9cac2048a66762518ef) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/40429c5172bfc6c773f212618cad169e) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/bb79b1ebcc7ef1b1c599e3088eab8bfb) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/274719b1c4653f3825ebeb8f8ee1e580) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/67075f9570cc679a0a6955b0a58d2f00) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/cf9d9ad89fb7c714a74eb656f7451c34) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/1f247ef438b6c442dd7690c6dfa87fa0) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/a5569274fe4e79c5df45f057414a9d01)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/e261b54df97486ae6b4017a2898a458f)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/3cae0f21e30cdfe24a788bfcd1a584ae)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/af48f30a73560a7a09ca59d904f78c92)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220822.11/6590574/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/5772a598c2fe8762163ec5510f64a5b9) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6590574&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a7d201082316e716391cad7817fc4375386cb364](https://github.com/xamarin/xamarin-macios/pull/15629/commits/a7d201082316e716391cad7817fc4375386cb364)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-22 21:40 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6590574&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a7d201082316e716391cad7817fc4375386cb364](https://github.com/xamarin/xamarin-macios/pull/15629/commits/a7d201082316e716391cad7817fc4375386cb364)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-23 00:12 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

4 tests crashed, 1 tests failed, 141 tests passed.

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: framework tests

:fire: Failed catastrophically on VSTS: simulator tests - framework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220822.11/6590574//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6590574/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6590574&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15629/commits/)  [PR build]

[comment]: <> [...]

2022-08-25 21:37 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/5d3b721cd357a00b6e447d9f152fe616) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/ec1791d389e4de100407bcab1f739ac1) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/2c8858b0ee5c242e46dbd3191ab90ea5) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/6936598b11ee110db43ff19acf5ef66c) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/626233385b9e0d08c75c2fa613473872) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/2acf5af33242831be6aad0a37a31001a) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/9447b72665b47a7a3974b06d1f26be9f) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/0a2514eacde9f7e03125dd5feb9ee9c9) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/2cd07baf1118859f3dd809f29a87367b) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/8eee15b60e9042ebaf86ffd30b8dc8cb) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/2ccbc63b357937f3e9038658b0f0b7e2) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/e7e858d54c535f89f72554798f513c3a)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/35c5460ccb53e84c7904187961186ffa)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/525b1730ac30f71d614e7196347e63a5)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/49e1528e1a92fdfc3fbde3a6dfa60a8a)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.32/6607644/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/c6019e16a53a1f0c3d0b6a545e39fe18) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6607644&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1ffe3cbd2f86554252f63d6d15794ae91fa8d81a](https://github.com/xamarin/xamarin-macios/pull/15629/commits/1ffe3cbd2f86554252f63d6d15794ae91fa8d81a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-25 21:52 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.347-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Bundle.16.0.347-ci.pr.gh15629.pkg)
* [Microsoft.iOS.Ref.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Ref.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Runtime.ios-arm.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Runtime.ios-arm64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Sdk.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Sdk.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Templates.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Templates.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.iOS.Windows.Sdk.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.347-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.MacCatalyst.Bundle.16.0.347-ci.pr.gh15629.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.MacCatalyst.Ref.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.MacCatalyst.Sdk.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.MacCatalyst.Templates.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Bundle.13.0.347-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.macOS.Bundle.13.0.347-ci.pr.gh15629.pkg)
* [Microsoft.macOS.Ref.13.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.macOS.Ref.13.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.macOS.Runtime.osx-arm64.13.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.macOS.Runtime.osx-x64.13.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Sdk.13.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.macOS.Sdk.13.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.macOS.Templates.13.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.macOS.Templates.13.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.347-ci.pr.gh15629.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.NET.Workload.iOS.16.0.347-ci.pr.gh15629.msi)
* [Microsoft.tvOS.Bundle.16.0.347-ci.pr.gh15629.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.tvOS.Bundle.16.0.347-ci.pr.gh15629.pkg)
* [Microsoft.tvOS.Ref.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.tvOS.Ref.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c13771b72/6607644/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.347-ci.pr.gh15629.nupkg)
* [Microsoft.tvOS.Sdk.16.0.347-ci.pr.gh15629.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1b48f1b7f87844e78b3be233bbc37c9c1377 [...]

2022-08-25 21:59 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6607644&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1ffe3cbd2f86554252f63d6d15794ae91fa8d81a](https://github.com/xamarin/xamarin-macios/pull/15629/commits/1ffe3cbd2f86554252f63d6d15794ae91fa8d81a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 04:51 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 226 tests passed.

## Failures

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/watchOS 32-bits - simulator/Debug: TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.32/6607644//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6607644/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6607644&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15629/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 22:25 UTC, merged