[Mediaplayer] Add support for xcode14 bet 4.
xamarin/xamarin-macios pull request #15654
Opened 2022-08-06 19:39 UTC by mandel-macaque

2022-08-06 20:01 UTC, dalexsoto requested changes
just two small things

2022-08-06 20:01 UTC, dalexsoto commented on src/avfoundation.cs
> +		NSDictionary<NSString, NSObject> NowPlayingInfo { get; set; }
Looks like there is a way to make a smart dictionary from the MPNowPlayingInfoCenter properties, that said you can do something like and file an issue for this so we can have a look at this later

```suggestion
		NSDictionary WeakNowPlayingInfo { get; set; }
```

2022-08-06 21:11 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6525090&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e1b7ec3b2e9ae9fdf682875aab0a7ff6590cfa92](https://github.com/xamarin/xamarin-macios/pull/15654/commits/e1b7ec3b2e9ae9fdf682875aab0a7ff6590cfa92)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-06 21:13 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.286-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Bundle.16.0.286-ci.pr.gh15654.pkg)
* [Microsoft.iOS.Ref.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Ref.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Runtime.ios-arm.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Runtime.ios-arm64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Sdk.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Sdk.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Templates.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Templates.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.iOS.Windows.Sdk.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.286-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.MacCatalyst.Bundle.16.0.286-ci.pr.gh15654.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.MacCatalyst.Ref.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.MacCatalyst.Sdk.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.MacCatalyst.Templates.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Bundle.13.0.286-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.macOS.Bundle.13.0.286-ci.pr.gh15654.pkg)
* [Microsoft.macOS.Ref.13.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.macOS.Ref.13.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.macOS.Runtime.osx-arm64.13.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.macOS.Runtime.osx-x64.13.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Sdk.13.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.macOS.Sdk.13.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Templates.13.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.macOS.Templates.13.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.286-ci.pr.gh15654.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.NET.Workload.iOS.16.0.286-ci.pr.gh15654.msi)
* [Microsoft.tvOS.Bundle.16.0.286-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.tvOS.Bundle.16.0.286-ci.pr.gh15654.pkg)
* [Microsoft.tvOS.Ref.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.tvOS.Ref.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409301f/6525090/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.286-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Sdk.16.0.286-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/815a9f34ff79fd3169725f6b7e2fe4a61409 [...]

2022-08-06 21:18 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/1d1ea14b858d3e94cdacaee0560692ab) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/89a7d64c51e0fba587e12d453dcf7da5) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/cb5096620c534052e52f3656e07d2491) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/1ce0ca95130183210283d0a1d9cc103d) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/07dbe2a592f8b8947964ff80062e7f3c) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/6ff102ee6113e0d7143b8cff64392414) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/92deccc37b13b65f4280a138a8dd954e) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/f9c7e34fad6c2b7c3c67260e415141af) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/4d05b673f9008aa75fd524617ac8625c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/7e2a41ef66eaa14ac168056cd6fd9178) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/bb486723aa107d36341284811cb42e99) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/f297e2933e1abce70cbebd94ce3cb64d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/46223f3428932e5039f3c3d9cb91c901) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/fc8e346f91254d6dc7b32761eeec5608) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/1c8b34c52ef68638b2ac957ee5a26a05) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/461b876bd10ebeee0b0ab25e721b1877) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/704d11e2f351d0f1dd239625a6dfe3a2)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/98a66a3731961577bd2a9b6cdc6534ee)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/71c7581ac60b31c081a22ac3ab758c4b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/801498653a079a2286113ac424ddb823)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220806.5/6525090/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/546b360c06e0785f076a726a7a8f9e3a) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6525090&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e1b7ec3b2e9ae9fdf682875aab0a7ff6590cfa92](https://github.com/xamarin/xamarin-macios/pull/15654/commits/e1b7ec3b2e9ae9fdf682875aab0a7ff6590cfa92)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-06 21:37 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6525090&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e1b7ec3b2e9ae9fdf682875aab0a7ff6590cfa92](https://github.com/xamarin/xamarin-macios/pull/15654/commits/e1b7ec3b2e9ae9fdf682875aab0a7ff6590cfa92)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-06 23:38 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 5 tests failed, 223 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>2 tests failed, 11 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
 * Xtro/.NET: BuildFailure
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220806.5/6525090//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6525090/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6525090&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https [...]

2022-08-07 19:44 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.292-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Bundle.16.0.292-ci.pr.gh15654.pkg)
* [Microsoft.iOS.Ref.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Ref.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Runtime.ios-arm.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Runtime.ios-arm64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Sdk.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Sdk.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Templates.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Templates.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.iOS.Windows.Sdk.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.292-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.MacCatalyst.Bundle.16.0.292-ci.pr.gh15654.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.MacCatalyst.Ref.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.MacCatalyst.Sdk.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.MacCatalyst.Templates.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Bundle.13.0.292-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.macOS.Bundle.13.0.292-ci.pr.gh15654.pkg)
* [Microsoft.macOS.Ref.13.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.macOS.Ref.13.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.macOS.Runtime.osx-arm64.13.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.macOS.Runtime.osx-x64.13.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Sdk.13.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.macOS.Sdk.13.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Templates.13.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.macOS.Templates.13.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.292-ci.pr.gh15654.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.NET.Workload.iOS.16.0.292-ci.pr.gh15654.msi)
* [Microsoft.tvOS.Bundle.16.0.292-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.tvOS.Bundle.16.0.292-ci.pr.gh15654.pkg)
* [Microsoft.tvOS.Ref.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.tvOS.Ref.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040aa64/6526050/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.292-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Sdk.16.0.292-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd3f359966754306fd2ee27a721e77214040 [...]

2022-08-07 19:49 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6526050&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d0ed56d8ac707f0d1af62273518b60f9d0437091](https://github.com/xamarin/xamarin-macios/pull/15654/commits/d0ed56d8ac707f0d1af62273518b60f9d0437091)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-07 19:56 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/ea5f081dd224d07094c3c06a53b79a87) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/c7d553c0b25745b1c6741fb5b559ee94) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/94388ef217835bfdfe8efb0cc16ea2fd) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/324714716ace3b83e8e49266849c170d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/306f5aef072d7e5bf31f24c5f93675cc) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/adc181374f4d6ff219d8b763754af277) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/544d2bc513fbe8062f829f79ef944414) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/ee047591929cc725d0b26eba437343ec) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/8953c92f4e9697acb394eb6196cc8085) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/3cd068c4b7b406c1250e1f60098a40f9)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/68297397c5d10be420d5f8dffc6c482f)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/3f3b4f6e3015f4922b754b6805926a14)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/f54c6590d2298a5c9f86146cb71c2492)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220807.9/6526050/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/13a7f02d0145117811b1e5b6affaf587) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6526050&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d0ed56d8ac707f0d1af62273518b60f9d0437091](https://github.com/xamarin/xamarin-macios/pull/15654/commits/d0ed56d8ac707f0d1af62273518b60f9d0437091)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-07 20:00 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6526050&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d0ed56d8ac707f0d1af62273518b60f9d0437091](https://github.com/xamarin/xamarin-macios/pull/15654/commits/d0ed56d8ac707f0d1af62273518b60f9d0437091)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-07 23:16 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 217 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220807.9/6526050//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6526050/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>2 tests failed, 11 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220807.9/6526050//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6526050/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>8 tests failed, 15 tests passed.</summary>
<details>

 * monotouch-test/tvOS - simulator/Debug [dotnet]: HarnessException (Harness exception for 'monotouch-test': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted () [0x00000] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:79 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x002d9] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:639 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
)
 * monotouch-test/tvOS - simulator/Debug: HarnessException (Harness exception for 'monotouch-test': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted () [0x00000] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:79 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x002d9] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:639 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
)
 * monotouch-test/tvOS - simulator/Debug (LinkSdk) [dotnet]: HarnessException (Harness exception for 'monotouch-test': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted () [0x00000] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:79 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x002d9] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:639 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<-- [...]

2022-08-08 15:02 UTC, tj-devel709 approved these changes

2022-08-08 15:20 UTC, dalexsoto approved these changes

2022-08-08 15:20 UTC, chamons approved these changes

2022-08-08 18:45 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6527941&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f7a880eb5de4a9a8d294a402fd40928b26ac63cd](https://github.com/xamarin/xamarin-macios/pull/15654/commits/f7a880eb5de4a9a8d294a402fd40928b26ac63cd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-08 18:46 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/66b7f6f9178f1868566101ce33a2f2ab) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/ff2865fe59499a68ba6d587f176bba7e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/cb29cc3acaa8a1be7108b4b308b8be0f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/019c6905bb174a7dbe436dd3e2ec5800) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/acbc5a5d1c51435a749c7067c790caf0) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/3fd94c0a6ee4efbe3d98107e8ae71b58) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/1f5b2e9cf525aa4a8415690152a03139) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/bddd5b2afb030b2ab9e9a67f4d6e0b3e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/753b532cefdeb594a3f36e3636a75199)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/059ea73ad9d0303b5cfddd8e9038f059)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/d6578e151ff0a4ab5a2aabde8a627761)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220808.10/6527941/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/abb960ce1abd70d838d0715ddb1b3b2e)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6527941&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f7a880eb5de4a9a8d294a402fd40928b26ac63cd](https://github.com/xamarin/xamarin-macios/pull/15654/commits/f7a880eb5de4a9a8d294a402fd40928b26ac63cd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-08 18:55 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.300-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Bundle.16.0.300-ci.pr.gh15654.pkg)
* [Microsoft.iOS.Ref.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Ref.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Runtime.ios-arm.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Runtime.ios-arm64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Sdk.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Sdk.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Templates.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Templates.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.iOS.Windows.Sdk.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.300-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.MacCatalyst.Bundle.16.0.300-ci.pr.gh15654.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.MacCatalyst.Ref.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.MacCatalyst.Sdk.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.MacCatalyst.Templates.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Bundle.13.0.300-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.macOS.Bundle.13.0.300-ci.pr.gh15654.pkg)
* [Microsoft.macOS.Ref.13.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.macOS.Ref.13.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.macOS.Runtime.osx-arm64.13.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.macOS.Runtime.osx-x64.13.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Sdk.13.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.macOS.Sdk.13.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Templates.13.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.macOS.Templates.13.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.300.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.300.13.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.300.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.300-ci.pr.gh15654.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.NET.Workload.iOS.16.0.300-ci.pr.gh15654.msi)
* [Microsoft.tvOS.Bundle.16.0.300-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.tvOS.Bundle.16.0.300-ci.pr.gh15654.pkg)
* [Microsoft.tvOS.Ref.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.tvOS.Ref.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902ccea/6527941/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.300-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Sdk.16.0.300-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ad752c3f379116e51f76bc2a0c1127e78902 [...]

2022-08-08 19:00 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6527941&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f7a880eb5de4a9a8d294a402fd40928b26ac63cd](https://github.com/xamarin/xamarin-macios/pull/15654/commits/f7a880eb5de4a9a8d294a402fd40928b26ac63cd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-09 02:28 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 226 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

<summary>1 tests failed, 64 tests passed.</summary>
<details>

 * link sdk/tvOS - simulator/Debug [dotnet]: Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220808.10/6527941//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6527941/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6527941&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15654/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-10 19:12 UTC, stephen-hawley approved these changes

2022-08-18 13:53 UTC, rolfbjarne approved these changes

2022-08-18 23:21 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578754&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4e3c8388ec9568d0ca6dbc3e80c2c9902a6fc3de](https://github.com/xamarin/xamarin-macios/pull/15654/commits/4e3c8388ec9568d0ca6dbc3e80c2c9902a6fc3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-18 23:29 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.312-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Bundle.16.0.312-ci.pr.gh15654.pkg)
* [Microsoft.iOS.Ref.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Ref.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Runtime.ios-arm.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Runtime.ios-arm64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Sdk.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Sdk.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Templates.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Templates.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.iOS.Windows.Sdk.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.312-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.MacCatalyst.Bundle.16.0.312-ci.pr.gh15654.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.MacCatalyst.Ref.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.MacCatalyst.Sdk.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.MacCatalyst.Templates.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Bundle.13.0.312-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.macOS.Bundle.13.0.312-ci.pr.gh15654.pkg)
* [Microsoft.macOS.Ref.13.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.macOS.Ref.13.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.macOS.Runtime.osx-arm64.13.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.macOS.Runtime.osx-x64.13.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Sdk.13.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.macOS.Sdk.13.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Templates.13.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.macOS.Templates.13.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.312-ci.pr.gh15654.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.NET.Workload.iOS.16.0.312-ci.pr.gh15654.msi)
* [Microsoft.tvOS.Bundle.16.0.312-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.tvOS.Bundle.16.0.312-ci.pr.gh15654.pkg)
* [Microsoft.tvOS.Ref.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.tvOS.Ref.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5c859/6578754/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.312-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Sdk.16.0.312-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ae2d9f46abddbcecfc6b1b416f6daee6b5a5 [...]

2022-08-18 23:30 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/16a1703dc0a6e8a70dc9a7cdd030f97a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/e1bd5420f366b61e04070d4e7a57482b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/d40c77d14518346a85e4137fdb5b596f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/037a992c6bddaa4ff994620822d0c037) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/cb93bb2cc3e7e9889975b12ea54aae81) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/37337a69fe6428f9ecb285bf20bc5df2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/61d3887f5274aba5eaab09a1c41a62d6) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/db4ac3e95529aa1883980db3968f149a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/2b0303ef3ef1548ae46bfa42612f728f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/bf6be39eda15b4c0737f48279d8ccf04) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/a5af566eeec14266bb1c669b1ae64243) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/14335835871c8cc723b778c41381df46) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/25eb5c50f437412e86749426c14ca78a)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/58ad902f52f329d2e9637337880ea6d5)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/35772fc3844058445d1b52c7d789ce9c)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/27af976fc0e8459e240998f62287bffc)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.27/6578754/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/5240f866d2573ed492c792a6d3cce890) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578754&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4e3c8388ec9568d0ca6dbc3e80c2c9902a6fc3de](https://github.com/xamarin/xamarin-macios/pull/15654/commits/4e3c8388ec9568d0ca6dbc3e80c2c9902a6fc3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-18 23:44 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6578754&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4e3c8388ec9568d0ca6dbc3e80c2c9902a6fc3de](https://github.com/xamarin/xamarin-macios/pull/15654/commits/4e3c8388ec9568d0ca6dbc3e80c2c9902a6fc3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 04:52 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 226 tests passed.

## Failures

### :x: introspection tests

<summary>2 tests failed, 11 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug: TimedOut
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.27/6578754//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578754/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578754&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15654/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 09:32 UTC, rolfbjarne approved these changes

2022-08-25 18:31 UTC, vs-mobiletools-engineering-service2 commented
:fire: Failed to compare API and create generator diff :fire:

Error: 'make' failed for the hash 85f662502c22375f3838c1354ba5dfb3aee4b212.


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6606932&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a1ee895334cb74de42647c7fd63bff11000d29bb](https://github.com/xamarin/xamarin-macios/pull/15654/commits/a1ee895334cb74de42647c7fd63bff11000d29bb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-25 19:03 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.348-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Bundle.16.0.348-ci.pr.gh15654.pkg)
* [Microsoft.iOS.Ref.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Ref.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Runtime.ios-arm.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Runtime.ios-arm64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Sdk.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Sdk.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Templates.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Templates.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.iOS.Windows.Sdk.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.348-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.MacCatalyst.Bundle.16.0.348-ci.pr.gh15654.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.MacCatalyst.Ref.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.MacCatalyst.Sdk.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.MacCatalyst.Templates.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Bundle.13.0.348-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.macOS.Bundle.13.0.348-ci.pr.gh15654.pkg)
* [Microsoft.macOS.Ref.13.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.macOS.Ref.13.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.macOS.Runtime.osx-arm64.13.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.macOS.Runtime.osx-x64.13.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Sdk.13.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.macOS.Sdk.13.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.macOS.Templates.13.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.macOS.Templates.13.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.348-ci.pr.gh15654.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.NET.Workload.iOS.16.0.348-ci.pr.gh15654.msi)
* [Microsoft.tvOS.Bundle.16.0.348-ci.pr.gh15654.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.tvOS.Bundle.16.0.348-ci.pr.gh15654.pkg)
* [Microsoft.tvOS.Ref.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.tvOS.Ref.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4ca356/6606932/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.348-ci.pr.gh15654.nupkg)
* [Microsoft.tvOS.Sdk.16.0.348-ci.pr.gh15654.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/ceeddc523e16aaebb8067f16a619ece6de4c [...]

2022-08-25 19:11 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6606932&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a1ee895334cb74de42647c7fd63bff11000d29bb](https://github.com/xamarin/xamarin-macios/pull/15654/commits/a1ee895334cb74de42647c7fd63bff11000d29bb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 00:51 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 7 tests failed, 221 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

<summary>6 tests failed, 59 tests passed.</summary>
<details>

 * dont link/watchOS 32-bits - simulator/Debug: TimedOut
 * dont link/watchOS 32-bits - simulator/Release: TimedOut
 * link all/watchOS 32-bits - simulator/Debug: TimedOut
 * link all/watchOS 32-bits - simulator/Release: TimedOut
 * link sdk/watchOS 32-bits - simulator/Debug: TimedOut
 * link sdk/watchOS 32-bits - simulator/Release: TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.29/6606932//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6606932/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index [...]

2022-08-26 14:38 UTC, dalexsoto commented
Unrelated test failures
* https://github.com/xamarin/maccore/issues/2595
* https://github.com/xamarin/maccore/issues/581

2022-08-26 14:38 UTC, merged