[WebKit] Add support for Xcode 14 beta 5.
xamarin/xamarin-macios pull request #15700
Opened 2022-08-18 20:42 UTC by mandel-macaque

2022-08-18 21:58 UTC, tj-devel709 approved these changes

2022-08-18 22:24 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/ca2286c131caff0e9692743dd23c5f17) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/33f9994d661b2babb3ce6fd6d4d5c272) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/d31011106489f846adb241a0be854712) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/4ecde56eeb922e01180d2df89960f9ef) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/70248bf4ee67a7e0e62f1aecc4fb509e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a23fe85e9eeb5d0511da81f430ec3142) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/1e8161ddfb8a0e833bddc873f740be86) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/1384e8bd0a155c2ad13665345159efa4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/36c913e2838e04e364483ba4053e046e)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/6eab792b48d2d058ddf926f5efdd0ea5)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/f5d8ade266f62f9d277b1b98e714076c)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220818.24/6578654/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/996c3baad256976f61ceb50f3b497213)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578654&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [048b6991b9dca2867fe7a2fbf85916060ec78936](https://github.com/xamarin/xamarin-macios/pull/15700/commits/048b6991b9dca2867fe7a2fbf85916060ec78936)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-18 22:25 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578654&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [048b6991b9dca2867fe7a2fbf85916060ec78936](https://github.com/xamarin/xamarin-macios/pull/15700/commits/048b6991b9dca2867fe7a2fbf85916060ec78936)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-18 22:33 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.306-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Bundle.16.0.306-ci.pr.gh15700.pkg)
* [Microsoft.iOS.Ref.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Ref.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Runtime.ios-arm.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Runtime.ios-arm64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Sdk.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Sdk.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Templates.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Templates.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.iOS.Windows.Sdk.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.306-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.MacCatalyst.Bundle.16.0.306-ci.pr.gh15700.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.MacCatalyst.Ref.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.MacCatalyst.Sdk.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.MacCatalyst.Templates.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Bundle.13.0.306-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.macOS.Bundle.13.0.306-ci.pr.gh15700.pkg)
* [Microsoft.macOS.Ref.13.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.macOS.Ref.13.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.macOS.Runtime.osx-arm64.13.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.macOS.Runtime.osx-x64.13.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Sdk.13.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.macOS.Sdk.13.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Templates.13.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.macOS.Templates.13.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.306-ci.pr.gh15700.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.NET.Workload.iOS.16.0.306-ci.pr.gh15700.msi)
* [Microsoft.tvOS.Bundle.16.0.306-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.tvOS.Bundle.16.0.306-ci.pr.gh15700.pkg)
* [Microsoft.tvOS.Ref.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.tvOS.Ref.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e925ee2/6578654/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.306-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Sdk.16.0.306-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/8c223d1a692cc12eae6b6a65cddc9ab17e92 [...]

2022-08-18 22:54 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6578654&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [048b6991b9dca2867fe7a2fbf85916060ec78936](https://github.com/xamarin/xamarin-macios/pull/15700/commits/048b6991b9dca2867fe7a2fbf85916060ec78936)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 03:05 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 226 tests passed.

## Failures

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/watchOS 32-bits - simulator/Debug: TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220818.24/6578654//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6578654/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6578654&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15700/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 09:22 UTC, rolfbjarne requested changes

2022-08-19 09:22 UTC, rolfbjarne commented on src/wkwebkit.cs
> +		void WebView (WKWebView webView, string message, Action<WKDialogResult> completionHandler);
```suggestion
		void ShowLockDownMode (WKWebView webView, string firstUseMessage, Action<WKDialogResult> completionHandler);
```

2022-08-19 13:03 UTC, dalexsoto approved these changes

2022-08-19 13:35 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6582051&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [66b7bb0ade3bc91ac35999843c1cb359a038443d](https://github.com/xamarin/xamarin-macios/pull/15700/commits/66b7bb0ade3bc91ac35999843c1cb359a038443d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 13:42 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.307-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Bundle.16.0.307-ci.pr.gh15700.pkg)
* [Microsoft.iOS.Ref.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Ref.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Runtime.ios-arm.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Runtime.ios-arm64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Sdk.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Sdk.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Templates.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Templates.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.iOS.Windows.Sdk.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.307-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.MacCatalyst.Bundle.16.0.307-ci.pr.gh15700.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.MacCatalyst.Ref.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.MacCatalyst.Sdk.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.MacCatalyst.Templates.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Bundle.13.0.307-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.macOS.Bundle.13.0.307-ci.pr.gh15700.pkg)
* [Microsoft.macOS.Ref.13.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.macOS.Ref.13.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.macOS.Runtime.osx-arm64.13.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.macOS.Runtime.osx-x64.13.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Sdk.13.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.macOS.Sdk.13.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.macOS.Templates.13.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.macOS.Templates.13.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.307-ci.pr.gh15700.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.NET.Workload.iOS.16.0.307-ci.pr.gh15700.msi)
* [Microsoft.tvOS.Bundle.16.0.307-ci.pr.gh15700.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.tvOS.Bundle.16.0.307-ci.pr.gh15700.pkg)
* [Microsoft.tvOS.Ref.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.tvOS.Ref.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0e868/6582051/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.307-ci.pr.gh15700.nupkg)
* [Microsoft.tvOS.Sdk.16.0.307-ci.pr.gh15700.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f33cac2eae7ba28e3cb9f7ab3a308e8e63c0 [...]

2022-08-19 13:53 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/33029b992794918c406ae28b3ac0ee7b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/c2e7c4b23acb8aa67d1b8eb9ca2f2fbb) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/dea5714b832a0ca648f26d5d1c9bae7e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~macOS~: (empty diff detected)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/5da34351f59508e3263e47d0ce7f1e77) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/3b7bd5e9973a0919f18220960663eb5b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/d47f6e871f3a967e8888605a3d5ed8b1) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/a6a4230c3df328ef9708c6b3c37bea9b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/79445635db7a653539d7c772fc54a104) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a6e0e2c73bd449be843ecaa9857686c1) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/4efb0e56c414a9db5299430932d10eb4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/9229062ee6ff23bbcf10d7eba011172d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/7ef7a9c2d71ee51d4d76d675309c9abe)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/c0aa5c3bddd6dd1a3475ea99694bcef4)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a926a9ae496090333a567e222cb91832)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/cbd87b768fb329fe12246b2688b63784)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220819.3/6582051/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/530c702f453b99319a3be9217f535887) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6582051&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [66b7bb0ade3bc91ac35999843c1cb359a038443d](https://github.com/xamarin/xamarin-macios/pull/15700/commits/66b7bb0ade3bc91ac35999843c1cb359a038443d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 14:04 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6582051&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [66b7bb0ade3bc91ac35999843c1cb359a038443d](https://github.com/xamarin/xamarin-macios/pull/15700/commits/66b7bb0ade3bc91ac35999843c1cb359a038443d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 16:09 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 228 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 13 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220819.3/6582051//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6582051/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6582051&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15700/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-19 16:21 UTC, stephen-hawley approved these changes

2022-08-22 16:17 UTC, chamons approved these changes

2022-08-24 00:30 UTC, merged