[AppKit] Xcode 14 Beta 1-5
xamarin/xamarin-macios pull request #15778
Opened 2022-08-25 22:12 UTC by chamons

2022-08-26 03:36 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/c02e46c2c8ccf8d8abb0a3c6b24d71aa) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/31324147c371ea7db73e1c5870e38e0c) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/4eacb6c551a26b3c779b03a0e2f4be42) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/bd4790b85d99102bb40b34e0d8e8bb47) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/38f2d09fe73ba6405ca3e64a8a27191e) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/689aad565c67d724eddd352e390b4d86) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/1249dcdcd63dce9e51fd50ca86c8f29a) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/d82f6672ad9ccb3c0e772f932fca124f) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/54853eb62f6e473756874f4720244b70) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/37ca38fe657f0d0972cccf938f2fcb4c) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/5a6be09899096e9c602449c273af684a) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/8022f23ddeca67447e87d601ee5f5354) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/cc2f72e062db20bdec9ba48ca66ea610) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/ea1375b84f2b0fb74f304aaa3c6048b0) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/7afdba835ad4edd15280ea30216d2abe) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/81d41db114fc697c9149de7e9fe1559c)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/4696ea8e67e736c24f69e5db28dd48ca)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/527c3f33c078abfacf17cd1deee81c15)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/d4f49946028e4a599e9989ce10e409f5)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220825.36/6609179/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/da4cc9284e7eef9a45e537cb19371438) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6609179&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6375185967d3a64ffbe7469ca84dfe37835e3a12](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6375185967d3a64ffbe7469ca84dfe37835e3a12)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 03:37 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.336-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Bundle.16.0.336-ci.pr.gh15778.pkg)
* [Microsoft.iOS.Ref.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Ref.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Runtime.ios-arm.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Runtime.ios-arm64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Sdk.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Sdk.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Templates.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Templates.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.iOS.Windows.Sdk.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.336-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.MacCatalyst.Bundle.16.0.336-ci.pr.gh15778.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.MacCatalyst.Ref.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.MacCatalyst.Sdk.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.MacCatalyst.Templates.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Bundle.13.0.336-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.macOS.Bundle.13.0.336-ci.pr.gh15778.pkg)
* [Microsoft.macOS.Ref.13.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.macOS.Ref.13.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.macOS.Runtime.osx-arm64.13.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.macOS.Runtime.osx-x64.13.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Sdk.13.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.macOS.Sdk.13.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Templates.13.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.macOS.Templates.13.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.336-ci.pr.gh15778.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.NET.Workload.iOS.16.0.336-ci.pr.gh15778.msi)
* [Microsoft.tvOS.Bundle.16.0.336-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.tvOS.Bundle.16.0.336-ci.pr.gh15778.pkg)
* [Microsoft.tvOS.Ref.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.tvOS.Ref.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef289ff/6609179/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.336-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Sdk.16.0.336-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bd676adfaba71acdc2636f660e6f2c78bef2 [...]

2022-08-26 03:42 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6609179&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6375185967d3a64ffbe7469ca84dfe37835e3a12](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6375185967d3a64ffbe7469ca84dfe37835e3a12)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 03:42 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6609179&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6375185967d3a64ffbe7469ca84dfe37835e3a12](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6375185967d3a64ffbe7469ca84dfe37835e3a12)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 06:16 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 226 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * mscorlib Part 3/tvOS - simulator/Debug: Crashed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220825.36/6609179//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6609179/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6609179&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15778/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 13:19 UTC, dalexsoto requested changes

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSFont SystemFontOfSize (nfloat fontSize, double weight, double width);
```suggestion
		NSFont GetSystemFontOfSize (nfloat fontSize, double weight, double width);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		nfloat Compressed { get; }
the only nfloat? looks funny...

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSImage ImageWithSymbolName (string name, double value);
```suggestion
		NSImage GetImage (string symbolName, double variableValue);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSImage ImageWithSystemSymbolName (string name, double value, [NullAllowed] string description);
```suggestion
		NSImage GetImage (string systemSymbolName, double variableValue, [NullAllowed] string accessibilityDescription);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSSet<NSString> ToolbarImmovableItemIdentifiers (NSToolbar toolbar);
```suggestion
		NSSet<NSString> GetToolbarImmovableItemIdentifiers (NSToolbar toolbar);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		bool ItemCanBeInsertedAt (NSToolbar toolbar, string itemIdentifier, nint index);
```suggestion
		bool GetItemCanBeInsertedAt (NSToolbar toolbar, string itemIdentifier, nint index);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSImageSymbolConfiguration ConfigurationPreferringMonochrome ();
```suggestion
		NSImageSymbolConfiguration GetConfigurationPreferringMonochrome ();
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSImageSymbolConfiguration ConfigurationPreferringHierarchical ();
```suggestion
		NSImageSymbolConfiguration GetConfigurationPreferringHierarchical ();
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSComboButton CreateWithTitle (string title, [NullAllowed] NSMenu menu, [NullAllowed] NSObject target, [NullAllowed] Selector action);
```suggestion
		NSComboButton Create (string title, [NullAllowed] NSMenu menu, [NullAllowed] NSObject target, [NullAllowed] Selector action);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSComboButton CreateWithImage (NSImage image, [NullAllowed] NSMenu menu, [NullAllowed] NSObject target, [NullAllowed] Selector action);
```suggestion
		NSComboButton Create (NSImage image, [NullAllowed] NSMenu menu, [NullAllowed] NSObject target, [NullAllowed] Selector action);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +		NSComboButton CreateWithTitle (string title, NSImage image, [NullAllowed] NSMenu menu, [NullAllowed] NSObject target, [NullAllowed] Selector action);
```suggestion
		NSComboButton Create (string title, NSImage image, [NullAllowed] NSMenu menu, [NullAllowed] NSObject target, [NullAllowed] Selector action);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/appkit.cs
> +	[BaseType (typeof(NSObject))]
This needs to be removed or the ModelAttribute, I think the former is the right choice 
```suggestion
```

2022-08-26 13:19 UTC, dalexsoto commented on src/xkit.cs
> +		NSTextListElement CreateWithContents (NSAttributedString contents, [NullAllowed] NSDictionary<NSString, NSObject> markerAttributes, NSTextList textList, [NullAllowed] NSTextListElement[] children);
```suggestion
		NSTextListElement Create (NSAttributedString contents, [NullAllowed] NSDictionary markerAttributes, NSTextList textList, [NullAllowed] NSTextListElement[] children);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/xkit.cs
> +		NSTextListElement CreateWithChildElements (NSTextListElement[] children, NSTextList textList, nint nestingLevel);
```suggestion
		NSTextListElement Create (NSTextListElement[] children, NSTextList textList, nint nestingLevel);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/xkit.cs
> +		NativeHandle Constructor ([NullAllowed] NSTextListElement parent, NSTextList textList, [NullAllowed] NSAttributedString contents, [NullAllowed] NSDictionary<NSString, NSObject> markerAttributes, [N
I would probably not use the generic dictionary here so we can create a better API in the future

```suggestion
		NativeHandle Constructor ([NullAllowed] NSTextListElement parent, NSTextList textList, [NullAllowed] NSAttributedString contents, [NullAllowed] NSDictionary markerAttributes, [NullAllowed] NSTextListElement[] children);
```

2022-08-26 13:19 UTC, dalexsoto commented on src/xkit.cs
> +		NSDictionary<NSString, NSObject> MarkerAttributes { get; }
Probably we can create a strong dictionary in the future

```suggestion
		NSDictionary WeakMarkerAttributes { get; }
```

2022-08-26 15:11 UTC, chamons commented on src/appkit.cs
> +		nfloat Compressed { get; }
That does seem wrong, looking.

2022-08-26 16:14 UTC, rolfbjarne requested changes

2022-08-26 16:14 UTC, rolfbjarne commented on src/xkit.cs
> +		PrependEnclosingMarker = 1
```suggestion
		PrependEnclosingMarker = 1,
```

2022-08-26 16:14 UTC, rolfbjarne commented on src/xkit.cs
> +	[TV (16,0), NoWatch, Mac (10,10), iOS (16,0)]
MacCatalyst?

2022-08-26 16:14 UTC, rolfbjarne commented on tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
> +!deprecated-attribute-missing! NSWindow::showsToolbarButton missing a [Deprecated] attribute
👀

2022-08-26 16:14 UTC, rolfbjarne commented on tests/xtro-sharpie/macOS-AppKit.ignore
> +!deprecated-attribute-missing! NSWindow::showsToolbarButton missing a [Deprecated] attribute
👀

2022-08-26 16:14 UTC, rolfbjarne commented on src/appkit.cs
> +		NSFont GetSystemFontOfSize (nfloat fontSize, double weight, double width);
Fonts need some custom treatment (look at the UIKit PR for the same selector): 

https://github.com/xamarin/xamarin-macios/pull/15694/files#diff-97d65d3ebcf51cbd79386a15db035a4a338cc9bf0fdcb2cd653d6b015ecd1770R6226

2022-08-26 16:14 UTC, rolfbjarne commented on src/appkit.cs
> +		NSImageSymbolConfiguration GetConfigurationPreferringMonochrome ();
All the other methods in this class seem to use Create:

```suggestion
		NSImageSymbolConfiguration CreateConfigurationPreferringMonochrome ();
```

2022-08-26 16:14 UTC, rolfbjarne commented on src/appkit.cs
> +		NSImageSymbolConfiguration GetConfigurationPreferringHierarchical ();
Same:

```suggestion
		NSImageSymbolConfiguration CreateConfigurationPreferringHierarchical ();
```

2022-08-26 17:29 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Bundle.16.0.351-ci.pr.gh15778.pkg)
* [Microsoft.iOS.Ref.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Ref.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Runtime.ios-arm.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Runtime.ios-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Sdk.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Templates.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Templates.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.iOS.Windows.Sdk.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.MacCatalyst.Bundle.16.0.351-ci.pr.gh15778.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.MacCatalyst.Ref.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.MacCatalyst.Sdk.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.MacCatalyst.Templates.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Bundle.13.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.macOS.Bundle.13.0.351-ci.pr.gh15778.pkg)
* [Microsoft.macOS.Ref.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.macOS.Ref.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.macOS.Runtime.osx-arm64.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.macOS.Runtime.osx-x64.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Sdk.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.macOS.Sdk.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Templates.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.macOS.Templates.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.351-ci.pr.gh15778.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.NET.Workload.iOS.16.0.351-ci.pr.gh15778.msi)
* [Microsoft.tvOS.Bundle.16.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.tvOS.Bundle.16.0.351-ci.pr.gh15778.pkg)
* [Microsoft.tvOS.Ref.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.tvOS.Ref.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa384d/6612380/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f178856467836ce0edd3ef4039a7c01259aa [...]

2022-08-26 17:31 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/afe2528db8f447a4cbfc81e5c9647883) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/98525f78fb0540d61673659bf7ed1ae0) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/13e233392ed651e4f5d4e9fa6947c3c7) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/78288d85f25f9e5c3e876bde24c10008) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/1529aade4ba1036ae5a8412ab479ce26) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/962d7cd4078b36ccc05ecd34f2e4bb75) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/a86657cad4e3908980fe331c94656860) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/480d738077645f65637011c1980d9098) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/fff8f3ef0e748fc5cfce8d549d1572c7) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/95107d3a3f59f508a78dd2f814963e97) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/6a7838c2d599d05603f8bb8052521222) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/5a41a7cf4a3c72bbed293a83dd036fef) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/fb4f058a04675de932c99eb25389ff90) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/7d2356b2f34ca501519bca5e452f6e0d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/0fe9dc991b3e3949f3234123cc5972f1) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/dcd60aaf830318dc597fcc7e77747710)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/f9cd2923f878ad57383b8dcb1672df05)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/8c2e1005768826ee72d66bff483b4d5d)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/e145e24205e6043f3b42d77d8192dbb8)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.21/6612381/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/7a198905b494bb6671406879ad7c60d7) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6612381&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6a134f80f3823377cbeac7628ed50d6183af4f48](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6a134f80f3823377cbeac7628ed50d6183af4f48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 17:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6612381&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6a134f80f3823377cbeac7628ed50d6183af4f48](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6a134f80f3823377cbeac7628ed50d6183af4f48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 17:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6612380&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6a134f80f3823377cbeac7628ed50d6183af4f48](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6a134f80f3823377cbeac7628ed50d6183af4f48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 17:38 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/c89bb0bff55d84e96bdc256260a9c7c6) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/cf4b566edea0ed836258589e1d0c08ae) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/731e89854c615c49bde4d6dc72d34f89) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/2076e204bf7a4c015d4e0a5e3afab641) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/db5e730e25ff53a865eaba6a0196c45f) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a313926f1977a201be8f7fdf379fc3a1) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/f8e8e97ee659c123ade7574fe0cf68f8) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/bdde2690a7a7bbd7b524d02f59b36a2f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/6047de79cf54bce80b71700469307053) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/9985b1f87eee16474af46993db8d9b05) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/1b25209ac9bbdc270502f3f246c8e9c5) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/ebc50e4e0d70922bbef8784457c007a4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/5760178b3b3e16127a0a11274dd75960) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/40f9c19ab84833a5a2ef2a6f854b4e4f) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/1dad3b1b31a04e6a363baf13204247f4) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/d5ccbe1d127d5c698d9a3845b1f3ece4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/012e15aec50b22538fb2d22f29e3f886)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/42709d4faec8887a82dac2ea227fb01f)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/d7a9c02e4fac03246f8bf2e0ad155dd2)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/442e32b99a09e5467e0f868d78254834)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220826.20/6612380/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/cbec04e99cee4336146985c9fb8ede81) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6612380&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6a134f80f3823377cbeac7628ed50d6183af4f48](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6a134f80f3823377cbeac7628ed50d6183af4f48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 17:39 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Bundle.16.0.351-ci.pr.gh15778.pkg)
* [Microsoft.iOS.Ref.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Ref.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Runtime.ios-arm.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Runtime.ios-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Sdk.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Templates.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Templates.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.iOS.Windows.Sdk.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.MacCatalyst.Bundle.16.0.351-ci.pr.gh15778.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.MacCatalyst.Ref.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.MacCatalyst.Sdk.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.MacCatalyst.Templates.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Bundle.13.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.macOS.Bundle.13.0.351-ci.pr.gh15778.pkg)
* [Microsoft.macOS.Ref.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.macOS.Ref.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.macOS.Runtime.osx-arm64.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.macOS.Runtime.osx-x64.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Sdk.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.macOS.Sdk.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Templates.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.macOS.Templates.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.351-ci.pr.gh15778.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.NET.Workload.iOS.16.0.351-ci.pr.gh15778.msi)
* [Microsoft.tvOS.Bundle.16.0.351-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.tvOS.Bundle.16.0.351-ci.pr.gh15778.pkg)
* [Microsoft.tvOS.Ref.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.tvOS.Ref.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53d77b/6612381/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.351-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Sdk.16.0.351-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fae8ec7bb2e532b62fbee3d794e0192cfc53 [...]

2022-08-26 17:51 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* dontlink
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6612381&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6a134f80f3823377cbeac7628ed50d6183af4f48](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6a134f80f3823377cbeac7628ed50d6183af4f48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 17:53 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6612380&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6a134f80f3823377cbeac7628ed50d6183af4f48](https://github.com/xamarin/xamarin-macios/pull/15778/commits/6a134f80f3823377cbeac7628ed50d6183af4f48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 21:00 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 3 tests failed, 225 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: mononative tests

<summary>2 tests failed, 10 tests passed.</summary>
<details>

 * mono-native-compat/watchOS 32-bits - simulator/Debug: TimedOut
 * mono-native-unified/watchOS 32-bits - simulator/Debug: TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220826.20/6612380//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6612380/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6612380&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15778/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-26 21:59 UTC, tj-devel709 commented on src/appkit.cs
> +
```suggestion
```
nit: extra new lines

2022-08-26 22:09 UTC, tj-devel709 approved these changes
Aside from the small nit things I mentioned and others' suggestions, LGTM!

2022-08-26 22:09 UTC, tj-devel709 commented on src/appkit.cs
> +	[BaseType (typeof(NSControl))]
```suggestion
	[BaseType (typeof (NSControl))]
```
nit

2022-08-26 22:09 UTC, tj-devel709 commented on src/appkit.cs
> +	[BaseType (typeof(NSObject))]
```suggestion
	[BaseType (typeof (NSObject))]
```

2022-08-27 07:43 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 38 tests failed, 190 tests passed.

## Failures

### :x: bcl tests

<summary>37 tests failed, 32 tests passed.</summary>
<details>

 * [NUnit] Mono SystemCoreTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemNumericsTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemRuntimeSerializationTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemTransactionsTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemXmlTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemXmlLinqTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemComponentModelDataAnnotationsTests/watchOS 32-bits - simulator/Debug: HarnessException (Harness exception for '[NUnit] Mono SystemComponentModelDataAnnotationsTests': System.InvalidOperationException: The Writer is closed or in error state.
  at System.Xml.XmlWellFormedWriter.AdvanceState (System.Xml.XmlWellFormedWriter+Token token) [0x001f6] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:1712 
  at System.Xml.XmlWellFormedWriter.WriteCData (System.String text) [0x00029] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:771 
  at Microsoft.DotNet.XHarness.iOS.Shared.Utilities.Extensions.WriteCDataSafe (System.Xml.XmlWriter writer, System.String text) [0x0001b] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Extensions.cs:130 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.TestReportGenerator.WriteFailure (System.Xml.XmlWriter writer, System.String message, System.IO.TextReader stderr) [0x00031] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/TestReportGenerator.cs:43 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.NUnitV3TestReportGenerator.GenerateFailure (System.Xml.XmlWriter writer, System.String title, System.String message, System.IO.TextReader stderr) [0x0030e] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/NUnitV3TestReportGenerator.cs:124 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailureXml (System.String destination, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00033] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:226 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x000a4] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:248 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.String stderrPath, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00008] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:236 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.GenerateXmlFailures (System.String failure, System.Boolean crashed, System.String crashReason) [0x00247] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:575 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x0056f] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:713 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/2/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 )
 * [NUnit] Mono SystemJsonTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemServiceModelWebTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemIOCompressionTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemIOCompressionFileSystemTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono MonoCSharpTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono SystemSecurityTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono MonoDataSqliteTests/watchOS 32-bits - simulator/Debug: TimedOut
 * [NUnit] Mono MonoRuntimeTests/watchOS 32-bits - simulator/Debug: HarnessException (Harness exception for '[NUnit] Mono MonoRuntimeTests': System.InvalidOperationException: The Writer is closed or in error state.
  at System.Xml.XmlWellFormedWriter.AdvanceState (System.Xml.XmlWellFormedWriter+Token token) [0x001f6] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:1712 
  at System.Xml.XmlWellFormedWriter.WriteCData (System.String text) [0x00029] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:771 
  at Microsoft.DotNet.XHarness.iOS.Shared.Utilities.Extensions.WriteCDataSafe (System.Xml.XmlWriter writer, System.String text) [0x0001b] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Extensions.cs:130 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.TestReportGenerator.WriteFailure (System.Xml.XmlWriter writer, System.String message, System.IO.TextReader stderr) [0x00031] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/TestReportGenerator.cs:43 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.NUnitV3TestReportGenerator.GenerateFailure (System.Xml.XmlWriter writer, System.String title, System.String message, System.IO.TextReader stderr) [0x0030e] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/NUnitV3TestReportGenerator.cs:124 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailureXml (System.String destination, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00033] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:226 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x000a4] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:248 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.String stderrPath, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00008] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:236 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.GenerateXmlFailures (System.String failure, System.Boo [...]

2022-08-28 02:36 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6617333&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15778/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-28 02:41 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6617333&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f6d9f075cee05aceb307c90947bd8ad4ba27e0da](https://github.com/xamarin/xamarin-macios/pull/15778/commits/f6d9f075cee05aceb307c90947bd8ad4ba27e0da)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-28 03:47 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.378-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Bundle.16.0.378-ci.pr.gh15778.pkg)
* [Microsoft.iOS.Ref.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Ref.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Runtime.ios-arm.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Runtime.ios-arm64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Sdk.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Sdk.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Templates.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Templates.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.iOS.Windows.Sdk.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.378-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.MacCatalyst.Bundle.16.0.378-ci.pr.gh15778.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.MacCatalyst.Ref.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.MacCatalyst.Sdk.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.MacCatalyst.Templates.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Bundle.13.0.378-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.macOS.Bundle.13.0.378-ci.pr.gh15778.pkg)
* [Microsoft.macOS.Ref.13.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.macOS.Ref.13.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.macOS.Runtime.osx-arm64.13.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.macOS.Runtime.osx-x64.13.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Sdk.13.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.macOS.Sdk.13.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Templates.13.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.macOS.Templates.13.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.378-ci.pr.gh15778.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.NET.Workload.iOS.16.0.378-ci.pr.gh15778.msi)
* [Microsoft.tvOS.Bundle.16.0.378-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.tvOS.Bundle.16.0.378-ci.pr.gh15778.pkg)
* [Microsoft.tvOS.Ref.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.tvOS.Ref.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838ddea0/6617333/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.378-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Sdk.16.0.378-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/eb0b1973312c2ed54d142c7c807fd2c0838d [...]

2022-08-28 03:51 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6617333&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f6d9f075cee05aceb307c90947bd8ad4ba27e0da](https://github.com/xamarin/xamarin-macios/pull/15778/commits/f6d9f075cee05aceb307c90947bd8ad4ba27e0da)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-28 04:10 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6617333&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f6d9f075cee05aceb307c90947bd8ad4ba27e0da](https://github.com/xamarin/xamarin-macios/pull/15778/commits/f6d9f075cee05aceb307c90947bd8ad4ba27e0da)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-28 06:58 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 3 tests failed, 225 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * MSBuild tests/Integration: Failed (Execution failed with exit code 6)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.3/6617333//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617333/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6617333&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15778/co [...]

2022-08-28 19:42 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.379-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Bundle.16.0.379-ci.pr.gh15778.pkg)
* [Microsoft.iOS.Ref.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Ref.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Runtime.ios-arm.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Runtime.ios-arm64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Sdk.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Sdk.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Templates.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Templates.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.iOS.Windows.Sdk.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.379-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.MacCatalyst.Bundle.16.0.379-ci.pr.gh15778.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.MacCatalyst.Ref.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.MacCatalyst.Sdk.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.MacCatalyst.Templates.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Bundle.13.0.379-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.macOS.Bundle.13.0.379-ci.pr.gh15778.pkg)
* [Microsoft.macOS.Ref.13.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.macOS.Ref.13.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.macOS.Runtime.osx-arm64.13.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.macOS.Runtime.osx-x64.13.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Sdk.13.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.macOS.Sdk.13.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Templates.13.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.macOS.Templates.13.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.379-ci.pr.gh15778.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.NET.Workload.iOS.16.0.379-ci.pr.gh15778.msi)
* [Microsoft.tvOS.Bundle.16.0.379-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.tvOS.Bundle.16.0.379-ci.pr.gh15778.pkg)
* [Microsoft.tvOS.Ref.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.tvOS.Ref.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560cbcd8/6617956/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.379-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Sdk.16.0.379-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/507b76170bd3d47431df64d23778c40e560c [...]

2022-08-28 19:46 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/b47c2ab105ef7bf8c6f4608325001b4a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/77b1bd4ce2fbe4ce67a3ab846ac43d50) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/d1f26e00d49f9a534e329a78ab34f86f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/3d4653cf551220aab9382f3be2cc4726) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/6f3fa43abcffc9fd7160ccf619f99539) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/246c4f12915c5d30fa0fc132463e525b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/62d9c358bad5503db96234529470ad33) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/86ea528599416cec8fefa1df5bd0dab3) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/5f8df4eea7c47ed51e71667c7f4a951e) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/8101ab922b66b7d6713b227243f7c64a) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/84da10a5d4d6b570d1d454fb6da0716e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/648cf734910b75315682c38fbd542ceb) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/b5f5b208d3885d4c607d5992c2cdcbbc) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/56a91d104e784909fe12beae667f40ec) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/a384599f6cae5fdf661b09d26c0ff8fd) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/e9caf79329569a1eb350b4c96f746502)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/1890ee76c9d11cdfcbfcdd702c45658d)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/00b0d73f8737cb069a80fceddb50879b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/c12b1c9b2066b8575c0d6e4abb0093ed)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220828.4/6617956/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/4e809bd7944a91f4a03ef3f3f2fcfd6d) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6617956&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [147d3c4882f8513989fbbb8535673fe7885b10df](https://github.com/xamarin/xamarin-macios/pull/15778/commits/147d3c4882f8513989fbbb8535673fe7885b10df)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-28 19:46 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6617956&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [147d3c4882f8513989fbbb8535673fe7885b10df](https://github.com/xamarin/xamarin-macios/pull/15778/commits/147d3c4882f8513989fbbb8535673fe7885b10df)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-28 20:15 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6617956&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [147d3c4882f8513989fbbb8535673fe7885b10df](https://github.com/xamarin/xamarin-macios/pull/15778/commits/147d3c4882f8513989fbbb8535673fe7885b10df)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-28 22:48 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 5 tests failed, 223 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>4 tests failed, 19 tests passed.</summary>
<details>

 * monotouch-test/watchOS 32-bits - simulator/Debug: TimedOut
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): TimedOut
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): TimedOut
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): TimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220828.4/6617956//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6617956/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6617956&view=ms.vss-test-web.test-result-details) on Ag [...]

2022-08-29 10:19 UTC, rolfbjarne approved these changes

2022-08-29 10:19 UTC, rolfbjarne commented on src/appkit.cs
> +		[Advice ("Use constants from 'NSFontWeight' and 'NSFontWidth'.")]
I believe [Advice] is useless on an [Internal] method.

```suggestion
		[Advice ("Use constants from 'NSFontWeight' and 'NSFontWidth'.")]
```

2022-08-29 11:59 UTC, dalexsoto approved these changes

2022-08-29 13:45 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.380-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Bundle.16.0.380-ci.pr.gh15778.pkg)
* [Microsoft.iOS.Ref.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Ref.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Runtime.ios-arm.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Runtime.ios-arm64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Sdk.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Sdk.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Templates.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Templates.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.iOS.Windows.Sdk.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.380-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.MacCatalyst.Bundle.16.0.380-ci.pr.gh15778.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.MacCatalyst.Ref.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.MacCatalyst.Sdk.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.MacCatalyst.Templates.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Bundle.13.0.380-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.macOS.Bundle.13.0.380-ci.pr.gh15778.pkg)
* [Microsoft.macOS.Ref.13.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.macOS.Ref.13.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.macOS.Runtime.osx-arm64.13.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.macOS.Runtime.osx-x64.13.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Sdk.13.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.macOS.Sdk.13.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.macOS.Templates.13.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.macOS.Templates.13.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.380-ci.pr.gh15778.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.NET.Workload.iOS.16.0.380-ci.pr.gh15778.msi)
* [Microsoft.tvOS.Bundle.16.0.380-ci.pr.gh15778.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.tvOS.Bundle.16.0.380-ci.pr.gh15778.pkg)
* [Microsoft.tvOS.Ref.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.tvOS.Ref.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec637304166/6619539/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.380-ci.pr.gh15778.nupkg)
* [Microsoft.tvOS.Sdk.16.0.380-ci.pr.gh15778.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/01f69f906706761f0a68b56c53ddeec63730 [...]

2022-08-29 13:47 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/b5e472498c9f3379de1fbb26cb7631b2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/bb0161d5d0c2192fceccdc75c53be438) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/15aeb8963b85108e1fd0b2f693f0416a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/6b937a88674ea6e8f023083cb7188324) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/49020a9713b36b2304fefabfe79f4d04) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/c25c4d1ee9aab80231aef336f63b9904) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/103aa645624263e5cdf11a9a6ba06ac3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/ca8cd31dcadf2d45c6b1c463f9282234) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/b91c46617f9b611d68c08ee06dd16fc5) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/6af4515f075c2d2443466eb64405671b) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/4c6ca187fd47572f6e604d6a6d4672d3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/0a5056c5fe7a4311d9ada5c2a72ac8c7) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/548e7d3032d2f699d20dc39f7f91695d) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/da495b5c102369e9a0b64cd6a7a69810) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/9bca3af9a02963aada3187fab7941d25) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/277f8f2fc46856608e7227c97f88badf)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/82f5966a0f6b15b26ca2ecfca1e69098)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/1921600a565b3307bb78f916705ae029)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/c82678a2d20c3e9cc1b7252dfc99dc69)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220829.6/6619539/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/a8a35bc693dc579ff4a8b6802611f14e) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6619539&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c53a60dbc0be330f7d71e6d74433e08872d95e57](https://github.com/xamarin/xamarin-macios/pull/15778/commits/c53a60dbc0be330f7d71e6d74433e08872d95e57)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-29 13:49 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6619539&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c53a60dbc0be330f7d71e6d74433e08872d95e57](https://github.com/xamarin/xamarin-macios/pull/15778/commits/c53a60dbc0be330f7d71e6d74433e08872d95e57)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-29 14:17 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6619539&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c53a60dbc0be330f7d71e6d74433e08872d95e57](https://github.com/xamarin/xamarin-macios/pull/15778/commits/c53a60dbc0be330f7d71e6d74433e08872d95e57)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-08-29 17:12 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 9 tests failed, 219 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>8 tests failed, 15 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220829.6/6619539//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6619539/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xa [...]

2022-08-31 20:08 UTC, merged