[AudioToolbox] Add support for xcode 14 beta6.
xamarin/xamarin-macios pull request #15877
Opened 2022-09-06 16:18 UTC by mandel-macaque

2022-09-06 18:24 UTC, vs-mobiletools-engineering-service2 commented
:fire: Failed to compare API and create generator diff :fire:

Error: 'make' failed for the hash ae42d556fedd7e65f67ed31829e0af40b87cfe39.


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6651507&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [00949481ba6e1be875b3efd40ed750c99d3691ca](https://github.com/xamarin/xamarin-macios/pull/15877/commits/00949481ba6e1be875b3efd40ed750c99d3691ca)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 18:52 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6651507&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [00949481ba6e1be875b3efd40ed750c99d3691ca](https://github.com/xamarin/xamarin-macios/pull/15877/commits/00949481ba6e1be875b3efd40ed750c99d3691ca)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 18:59 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.398-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Bundle.16.0.398-ci.pr.gh15877.pkg)
* [Microsoft.iOS.Ref.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Ref.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Runtime.ios-arm.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Runtime.ios-arm64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Sdk.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Sdk.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Templates.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Templates.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.iOS.Windows.Sdk.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.398-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.MacCatalyst.Bundle.16.0.398-ci.pr.gh15877.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.MacCatalyst.Ref.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.MacCatalyst.Sdk.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.MacCatalyst.Templates.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Bundle.13.0.398-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.macOS.Bundle.13.0.398-ci.pr.gh15877.pkg)
* [Microsoft.macOS.Ref.13.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.macOS.Ref.13.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.macOS.Runtime.osx-arm64.13.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.macOS.Runtime.osx-x64.13.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Sdk.13.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.macOS.Sdk.13.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Templates.13.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.macOS.Templates.13.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.398-ci.pr.gh15877.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.NET.Workload.iOS.16.0.398-ci.pr.gh15877.msi)
* [Microsoft.tvOS.Bundle.16.0.398-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.tvOS.Bundle.16.0.398-ci.pr.gh15877.pkg)
* [Microsoft.tvOS.Ref.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.tvOS.Ref.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14537c/6651507/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.398-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Sdk.16.0.398-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/09efb4c18444770887ef02b9b3557b6a5a14 [...]

2022-09-06 19:21 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6651507&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [00949481ba6e1be875b3efd40ed750c99d3691ca](https://github.com/xamarin/xamarin-macios/pull/15877/commits/00949481ba6e1be875b3efd40ed750c99d3691ca)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 20:13 UTC, dalexsoto approved these changes

2022-09-06 23:38 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 4 tests failed, 224 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

<summary>1 tests failed, 64 tests passed.</summary>
<details>

 * link sdk/iOS Unified 64-bits - simulator/Release [dotnet]: Failed
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: mmp tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 2)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.21/6651507//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651507/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=665 [...]

2022-09-07 08:53 UTC, rolfbjarne requested changes
Manual bindings need manual tests too :)

2022-09-07 08:53 UTC, rolfbjarne commented on src/AudioUnit/AudioComponent.cs
> +			var success = AudioComponentValidate (GetCheckedHandle (), validationParameters.GetNonNullHandle (nameof (validationParameters)), out var result);
The header says `validationParameters` can be null.

2022-09-07 08:53 UTC, rolfbjarne commented on src/AudioUnit/AudioComponent.cs
> +				AudioComponentValidateWithResults (GetCheckedHandle (), validationParameters.GetNonNullHandle (nameof (validationParameters)), ref block_handler);
Same, headers say `validationParameters` can be null.

2022-09-07 08:53 UTC, rolfbjarne commented on src/AudioUnit/AudioComponent.cs
> +			return AudioComponentValidationResult.Unknown;
Your managed bindings have one thing in common: they don't expose the returned OSStatus from the native functions. This return value can be valuable when trying to diagnose why calls to these methods fail, so we often provide another overload that users can use to get this value. In this particular case that could be something like:

```cs
public AudioComponentValidationResult Validate (NSDictionary validationParameters, out int resultCode)
{
    ...
}
```

This goes for all the new API.

2022-09-07 16:19 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6656712&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15877/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-07 16:23 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6656712&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15877/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-07 16:25 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6656712&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f35420de065fa62a31cd4099b904aac0a7ad9e7f](https://github.com/xamarin/xamarin-macios/pull/15877/commits/f35420de065fa62a31cd4099b904aac0a7ad9e7f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-07 16:34 UTC, tj-devel709 reviewed
Other than this, LGTM

2022-09-07 16:34 UTC, tj-devel709 commented on src/AudioToolbox/Enums.cs
> +	}
Hmm why add tv and ios support if none of the enums support it?

2022-09-07 19:16 UTC, rolfbjarne requested changes

2022-09-07 19:16 UTC, rolfbjarne commented on src/AudioUnit/AudioComponent.cs
> +				var success = AudioComponentCopyConfigurationInfo (GetCheckedHandle (), out var dictPtr);
This one is also needs an overload (or really a method, since this is a property)

2022-09-08 19:09 UTC, stephen-hawley commented on tests/monotouch-test/AudioToolbox/AudioComponentTest.cs
> +			componentInfo.Subtype =  "XMPL";
nit: extra space before `"XMPL"`

2022-09-08 19:10 UTC, stephen-hawley commented on tests/monotouch-test/AudioToolbox/AudioComponentTest.cs
> +			componentInfo.Subtype =  "XMPL";
same

2022-09-08 19:10 UTC, stephen-hawley commented on tests/monotouch-test/AudioToolbox/AudioComponentTest.cs
> +			componentInfo.Subtype =  "XMPL";
same

2022-09-08 19:10 UTC, stephen-hawley approved these changes

2022-09-08 19:34 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/784ff4735b73695749350a0f87b5fe81) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/39af04618ae243149b352407182283e2) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/d983dada2c7a4b37f9ab48adb205e70e) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/2d7192a81605d5dcdc97bc777d12b65b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/3b4219e110b4154f86a2b1f894d6f99e) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/aaacc0fed3405e2ce67f0f440f1ff520) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/5d4b72299bbdfab592c4e5aa1d55e6e2) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/1fe1b65db057d40ba6b60ecd334a76e2) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/764e16ef35d766ad6a78ef03c98cf429) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/967d7509a70a9040a601b8492b60d2fb) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/8b09b70ddadd3433601ffbddb6ecca5c) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/9b0653d5ded7e6b14a781ac276e5877d) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/7bd0f31cd417152ff42620c4a3b46e64) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/a703463eb5d0ec70903e241d51c82495) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/ec63257fd1331c8a2547da5e1b8bbe4c) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/f4c14d30629aff4c7aa92d903a7b2aa8)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/cb8b8edab91484f885b866f90e460963)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/b800f38077dca8acbf4db5209cdd3add)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/18ef79a07e286888e01036f0f124535c)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220908.20/6662804/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/4dbf1a7eb23f693c3fa70612260c3e34) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6662804&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c9ff13fbb7e6747e1f4df74ccf9207ccf324baab](https://github.com/xamarin/xamarin-macios/pull/15877/commits/c9ff13fbb7e6747e1f4df74ccf9207ccf324baab)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-08 19:45 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.437-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Bundle.16.0.437-ci.pr.gh15877.pkg)
* [Microsoft.iOS.Ref.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Ref.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Runtime.ios-arm.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Runtime.ios-arm64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Sdk.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Sdk.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Templates.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Templates.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.iOS.Windows.Sdk.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.437-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.MacCatalyst.Bundle.16.0.437-ci.pr.gh15877.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.MacCatalyst.Ref.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.MacCatalyst.Sdk.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.MacCatalyst.Templates.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Bundle.13.0.437-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.macOS.Bundle.13.0.437-ci.pr.gh15877.pkg)
* [Microsoft.macOS.Ref.13.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.macOS.Ref.13.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.macOS.Runtime.osx-arm64.13.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.macOS.Runtime.osx-x64.13.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Sdk.13.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.macOS.Sdk.13.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Templates.13.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.macOS.Templates.13.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.437-ci.pr.gh15877.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.NET.Workload.iOS.16.0.437-ci.pr.gh15877.msi)
* [Microsoft.tvOS.Bundle.16.0.437-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.tvOS.Bundle.16.0.437-ci.pr.gh15877.pkg)
* [Microsoft.tvOS.Ref.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.tvOS.Ref.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e6445b37/6662804/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.437-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Sdk.16.0.437-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e547957081d6cab96dc07bfaeb818407e644 [...]

2022-09-08 20:00 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6662804&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c9ff13fbb7e6747e1f4df74ccf9207ccf324baab](https://github.com/xamarin/xamarin-macios/pull/15877/commits/c9ff13fbb7e6747e1f4df74ccf9207ccf324baab)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-08 21:50 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 12 tests failed, 215 tests passed.

## Failures

### :x: introspection tests

<summary>2 tests failed, 11 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug: TimedOut
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: mmp tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 2)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>8 tests failed, 15 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): LaunchTimedOut
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.20/6662804//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6662804/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220908.2 [...]

2022-09-09 08:24 UTC, rolfbjarne approved these changes

2022-09-09 18:36 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6668031&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15877/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 19:52 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/1a2dc9ca47bae583f229654392846c67) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/f8b99a4f60c0ebdaaa5366fe82163696) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/be153a3ec42df171aa8498040d4a9717) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/2aae8b3d547eb71a9b8dfef149951b89) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a270bed3996c35e0378981c214241723) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/0a70c630d04fa2808117d4cc0e774e51) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/f8d01acbf9f0d1af412a9bf4d6acd13d) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/feb0cefb2000e1426c6d7846e214605b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/5db66ba73e6e6d7779b37cf6668d5f8a) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/bcf062f27fa6abe362bf7f0d124cba32) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/36a958c38bd2c8777b84fa88694ae838) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/3c0024b463f0c4c4ef7cf3da9fb906b8) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/efdab97bcdc0d0d75df21bf61b8a9745) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/cd706d305c93f93a0ce75eb4bc1329f6) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/c0033c2a10e4de9224bbfec51b920a1e) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/3dd266c8514e09086a5c541f8c642d11)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/b2a865da4eca9eb8aa8fbee650cc29f7)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/91e60308fe78deed05beca49f58da24f)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/b8b018534dd5b59138fddd9ca1195854)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.24/6668031/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/0f48fe28d4e67d53924dc0482ba067da) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6668031&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d38d6e46d4bc868cc769f607c101e5529ad2a387](https://github.com/xamarin/xamarin-macios/pull/15877/commits/d38d6e46d4bc868cc769f607c101e5529ad2a387)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-10 00:45 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6669707&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [501c2e1b47d297a57ce7102e139ae2171068242a](https://github.com/xamarin/xamarin-macios/pull/15877/commits/501c2e1b47d297a57ce7102e139ae2171068242a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-10 00:56 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.439-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Bundle.16.0.439-ci.pr.gh15877.pkg)
* [Microsoft.iOS.Ref.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Ref.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Runtime.ios-arm.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Runtime.ios-arm64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Sdk.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Sdk.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Templates.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Templates.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.iOS.Windows.Sdk.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.439-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.MacCatalyst.Bundle.16.0.439-ci.pr.gh15877.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.MacCatalyst.Ref.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.MacCatalyst.Sdk.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.MacCatalyst.Templates.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Bundle.13.0.439-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.macOS.Bundle.13.0.439-ci.pr.gh15877.pkg)
* [Microsoft.macOS.Ref.13.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.macOS.Ref.13.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.macOS.Runtime.osx-arm64.13.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.macOS.Runtime.osx-x64.13.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Sdk.13.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.macOS.Sdk.13.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.macOS.Templates.13.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.macOS.Templates.13.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.439-ci.pr.gh15877.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.NET.Workload.iOS.16.0.439-ci.pr.gh15877.msi)
* [Microsoft.tvOS.Bundle.16.0.439-ci.pr.gh15877.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.tvOS.Bundle.16.0.439-ci.pr.gh15877.pkg)
* [Microsoft.tvOS.Ref.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.tvOS.Ref.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c0c40/6669707/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.439-ci.pr.gh15877.nupkg)
* [Microsoft.tvOS.Sdk.16.0.439-ci.pr.gh15877.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/c6b4703fdc01dc2581cfec36cf103752450c [...]

2022-09-10 01:02 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/e4d39719f8e1c8561da59a5a76fb72be) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/5b2295e9d4c91138b1df9416dba32286) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/d8d6f0494d60635a46c16b44998efa7f) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/6795169af1ac2fc2bfa004daad24d65b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/6ef02655bd9512eec926f9af98a04745) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/0602af57ecae559de563f777611cae01) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/f361c2648423cc22acd3541f18b587a8) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/933931e2f460d2d1d23caa75d0fe75b1) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/dc466504c5b20df61d1a00153296e210) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/a9e648c3f0734f4658a7abf879b886d7) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/b3a7c54d0fc3d0cf63e7b007c1c85540) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/5f845c5a30fc9d2eba58f7f0c5b6434c) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/09393639e3197d2d6b70f64971e2e8d6) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/1d3ff828785a51a0dec1f0a738095789) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/3f0388ba034913d082c9cb644ceec3a7) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/99beb98a2e8aa32110710a8482a2ef18)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/d24543ca0a294b0fa44439e3d9837cea)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/8bde3f7c4d822733755bc3a00ff8be02)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/8ba7a702c869c5f2090610c874274fe3)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220909.31/6669707/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/c807a4269232fcf7bdbe0af7797e68a0) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6669707&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [501c2e1b47d297a57ce7102e139ae2171068242a](https://github.com/xamarin/xamarin-macios/pull/15877/commits/501c2e1b47d297a57ce7102e139ae2171068242a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-10 01:11 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6669707&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [501c2e1b47d297a57ce7102e139ae2171068242a](https://github.com/xamarin/xamarin-macios/pull/15877/commits/501c2e1b47d297a57ce7102e139ae2171068242a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-10 02:48 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 1 tests failed, 119 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220909.31/6669707//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6669707/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6669707&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15877/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 14:34 UTC, merged