[LocalAuthentication] Add support for Xcode 14 b1-3
xamarin/xamarin-macios pull request #15873
Opened 2022-09-05 22:12 UTC by SotoiGhost

2022-09-05 23:52 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6649712&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1166.Monterey
Hash: [8e9f94c781de59d454153dbb29d21509d9312999](https://github.com/xamarin/xamarin-macios/pull/15873/commits/8e9f94c781de59d454153dbb29d21509d9312999)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-05 23:59 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6649712&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8e9f94c781de59d454153dbb29d21509d9312999](https://github.com/xamarin/xamarin-macios/pull/15873/commits/8e9f94c781de59d454153dbb29d21509d9312999)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 00:03 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/d75d5ce2f062ed5dd1fe758a14b339f2) (No breaking changes)
* ~tvOS~ (no change detected)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/71258bd47806e5f695cfb8381b52617b) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/f51efa64de71b29246c2899f12e1e0e7) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/36fde8db4355729713482a8979ca63bd) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/e6b1d1399845326d08812bdec512fda3) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/f70d7d052ae407fb54ecc3e35cacd2ad) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/534aa7b2382169d3e08fafe1d6f10cd1) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/887c55f149097f465cf7e2996888b288) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/6d9aaab75d834df5e4019d08f2275085) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/3fd37a01595a59028dd02d260c80e53b) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/3e308446c717bda1280efd56da1d66d1) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/7787cff8428046732f98f8449306c827) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/5be3b6c21ebd259f0af3494f8c0d2b09) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/6ad95372dc13cadad45c2c6f28bd254c) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/c41b1bb8dc1999cd02b29e5d21831e5c)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/b0ecb8c71631bc44724590e5ddfda3f6)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/1c49d86c27ec14d96d543d639285365d)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/903448e4ed7d413e2d5f5bcb6cbbcf6d)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220905.21/6649712/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/eecc05deb6ce546181e2e4bb37b36d9b) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6649712&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8e9f94c781de59d454153dbb29d21509d9312999](https://github.com/xamarin/xamarin-macios/pull/15873/commits/8e9f94c781de59d454153dbb29d21509d9312999)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 00:24 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6649712&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8e9f94c781de59d454153dbb29d21509d9312999](https://github.com/xamarin/xamarin-macios/pull/15873/commits/8e9f94c781de59d454153dbb29d21509d9312999)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 03:43 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 1 tests failed, 227 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220905.21/6649712//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6649712/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6649712&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15873/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 07:23 UTC, rolfbjarne requested changes

2022-09-06 07:23 UTC, rolfbjarne commented on src/LocalAuthentication/LAEnums.cs
> +		OwnerAuthenticationWithBiometricsOrWatch = DeviceOwnerAuthenticationWithBiometricsOrWatch,
Shouldn't this one be [NoWatch] as well (because the Obsolete attribute on this value tells you to use another enum value which is obsolete)?

2022-09-06 13:31 UTC, mandel-macaque commented on src/localauthentication.cs
> +		void RemoveAllRights (LARightStoreRemoveRightCompletionHandler handler);
It is a Right store and all methods have the Right word. Should we remove that since it seems redundant.

2022-09-06 19:52 UTC, mandel-macaque approved these changes

2022-09-06 20:01 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6651859&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e0d42499077aec93b72909d911341613f95460d3](https://github.com/xamarin/xamarin-macios/pull/15873/commits/e0d42499077aec93b72909d911341613f95460d3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 20:08 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/0d43b0a823754c80f02283b7c886af94) (No breaking changes)
* ~tvOS~ (no change detected)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/92387ab1e2d1671e19d3e589bea4f177) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/f8cd0d8cc41c6132b20bbbd62ab17242) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/a865d5725eb4ea68a5485996607192b8) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/e4ddb3e48d4a97ac7fcd317c2e3eee41) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/56db3de98de094d2859498d652b3e35c) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/9ae53a8ceea0f1847e601ff33e56c5eb) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/99af16edb3e00eb0c2cbdee6cb31a2dd) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/d46d5ca1b31d60a059e5e867729c1636) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/63ea12e06b4caebff1609bb94154ea07) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/4641a3765332af61972770549ca610fa) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/51ec4235199ed6de9b925950fe5e26f8) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/213773c4b1b74c27b9b76adbf0533beb) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/6c8d6feb3f2efd6bdec9301baf4c922e) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/cf5bcd8d84852ed5be6058b7d2b69d1b)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/3cc5607441c7776778f14ee65b83b0e8)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/be3e3e0d023dfd266ea135e2eb2d9c72)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/843faf9cc2a18bbe67ef03e2829b067d)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220906.26/6651859/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/84c0f2572b5ec11f6c89e8aceb104eee) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6651859&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e0d42499077aec93b72909d911341613f95460d3](https://github.com/xamarin/xamarin-macios/pull/15873/commits/e0d42499077aec93b72909d911341613f95460d3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-06 20:11 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.407-ci.pr.gh15873.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Bundle.16.0.407-ci.pr.gh15873.pkg)
* [Microsoft.iOS.Ref.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Ref.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Runtime.ios-arm.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Runtime.ios-arm64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Sdk.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Sdk.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Templates.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Templates.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.iOS.Windows.Sdk.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.407-ci.pr.gh15873.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.MacCatalyst.Bundle.16.0.407-ci.pr.gh15873.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.MacCatalyst.Ref.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.MacCatalyst.Sdk.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.MacCatalyst.Templates.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.macOS.Bundle.13.0.407-ci.pr.gh15873.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.macOS.Bundle.13.0.407-ci.pr.gh15873.pkg)
* [Microsoft.macOS.Ref.13.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.macOS.Ref.13.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.macOS.Runtime.osx-arm64.13.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.macOS.Runtime.osx-x64.13.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.macOS.Sdk.13.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.macOS.Sdk.13.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.macOS.Templates.13.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.macOS.Templates.13.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.407-ci.pr.gh15873.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.NET.Workload.iOS.16.0.407-ci.pr.gh15873.msi)
* [Microsoft.tvOS.Bundle.16.0.407-ci.pr.gh15873.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.tvOS.Bundle.16.0.407-ci.pr.gh15873.pkg)
* [Microsoft.tvOS.Ref.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.tvOS.Ref.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df86bac/6651859/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.407-ci.pr.gh15873.nupkg)
* [Microsoft.tvOS.Sdk.16.0.407-ci.pr.gh15873.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9fef71d83d42cedf58c731e74fd3ab133df8 [...]

2022-09-06 20:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6651859&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e0d42499077aec93b72909d911341613f95460d3](https://github.com/xamarin/xamarin-macios/pull/15873/commits/e0d42499077aec93b72909d911341613f95460d3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-07 02:47 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 1 tests failed, 227 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220906.26/6651859//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6651859/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6651859&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15873/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-07 09:54 UTC, rolfbjarne approved these changes

2022-09-07 17:06 UTC, tj-devel709 approved these changes

2022-09-08 19:16 UTC, merged