[xcode14] Bump to Xcode 14 RC
xamarin/xamarin-macios pull request #15898
Opened 2022-09-08 04:55 UTC by dalexsoto

We should probably consider a merge commit for this PR so we can revert the revert in the future for revert BackgroundAssets

* Apple removed BackgroundAssets 
* Apple removed macOS 13.0 SDK
* Apple Removed MacCat 16.0 SDK

2022-09-08 05:51 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6660939&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-08 05:53 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6660939&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-08 06:02 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6660939&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [66fbeefa2a0a70ef8e247296db16b5e14e7efe0d](https://github.com/xamarin/xamarin-macios/pull/15898/commits/66fbeefa2a0a70ef8e247296db16b5e14e7efe0d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-08 08:20 UTC, rolfbjarne approved these changes

2022-09-08 14:12 UTC, chamons approved these changes

2022-09-08 14:55 UTC, mandel-macaque requested changes

2022-09-08 14:55 UTC, mandel-macaque commented on tests/xtro-sharpie/api-annotations-dotnet/macOS-BackgroundAssets.todo
> +!missing-enum! BADownloadState not bound
So we are adding a macOS todo yet removing the binding that were there, why is that? Can't we just simply add it to mac os x and remove the todo or clean the todo accordingly?

2022-09-08 14:55 UTC, mandel-macaque commented on tools/common/Frameworks.cs
> -					{ "BackgroundAssets", "BackgroundAssets", 13,0 },
Leave it for macOS, not for the other platforms. Looks to me we are doing a step fwd and 2 steps back with this.

2022-09-08 15:59 UTC, tj-devel709 approved these changes

2022-09-09 01:52 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6665275&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4](https://github.com/xamarin/xamarin-macios/pull/15898/commits/c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 02:08 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6665275&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4](https://github.com/xamarin/xamarin-macios/pull/15898/commits/c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 02:09 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6665275&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4](https://github.com/xamarin/xamarin-macios/pull/15898/commits/c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 02:34 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.442-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Bundle.16.0.442-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Ref.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Runtime.ios-arm.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Runtime.ios-arm64.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Sdk.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Templates.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.iOS.Windows.Sdk.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.442-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.NET.Workload.iOS.16.0.442-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.442-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.tvOS.Bundle.16.0.442-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.tvOS.Ref.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.tvOS.Sdk.16.0.442-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.442-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/Microsoft.tvOS.Templates.16.0.442-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.7.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6ec5ee7ee9f6dc461fc17845f5a6b8b0eef6cd43/6665275/package/xamarin.ios-16.0.0.7.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6665275&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1166.Monterey'
Hash: [c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4](https://github.com/xamarin/xamarin-macios/pull/15898/commits/c7c2ed0cad071953e07d68e22ab04ac5a6ad6af4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 03:10 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 0 tests passed :tada:

## Tests counts

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6665275&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 12:10 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6666884&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 12:14 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6666884&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 12:15 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6666884&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1102c780e9c40803df30b5163007e815f96d32ff](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1102c780e9c40803df30b5163007e815f96d32ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 13:35 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6666884&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1102c780e9c40803df30b5163007e815f96d32ff](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1102c780e9c40803df30b5163007e815f96d32ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 13:35 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6666884&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1102c780e9c40803df30b5163007e815f96d32ff](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1102c780e9c40803df30b5163007e815f96d32ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 13:50 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.443-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Bundle.16.0.443-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Ref.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Runtime.ios-arm.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Runtime.ios-arm64.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Sdk.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Templates.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.iOS.Windows.Sdk.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.443-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.NET.Workload.iOS.16.0.443-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.443-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.tvOS.Bundle.16.0.443-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.tvOS.Ref.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.tvOS.Sdk.16.0.443-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.443-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/Microsoft.tvOS.Templates.16.0.443-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.8.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fa8e45878509284affeb64dd5b03be05b40aab6d/6666884/package/xamarin.ios-16.0.0.8.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6666884&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1165.Monterey
Hash: [1102c780e9c40803df30b5163007e815f96d32ff](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1102c780e9c40803df30b5163007e815f96d32ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 16:12 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6667172&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [031410fa241e0ef22ed57e2debfd38a1b312a1ee](https://github.com/xamarin/xamarin-macios/pull/15898/commits/031410fa241e0ef22ed57e2debfd38a1b312a1ee)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 16:21 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.444-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Bundle.16.0.444-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Ref.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Runtime.ios-arm.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Runtime.ios-arm64.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Sdk.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Templates.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.iOS.Windows.Sdk.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.444-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.NET.Workload.iOS.16.0.444-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.444-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.tvOS.Bundle.16.0.444-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.tvOS.Ref.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.tvOS.Sdk.16.0.444-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.444-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/Microsoft.tvOS.Templates.16.0.444-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.9.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9e0077e251075a4ee9eb0f7e6154e7eefd0725d2/6667172/package/xamarin.ios-16.0.0.9.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6667172&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1165.Monterey'
Hash: [031410fa241e0ef22ed57e2debfd38a1b312a1ee](https://github.com/xamarin/xamarin-macios/pull/15898/commits/031410fa241e0ef22ed57e2debfd38a1b312a1ee)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 16:29 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 0 tests passed :tada:

## Tests counts

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6667172&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 18:06 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6667716&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e70d077ae16dfdcdb0ec5326cb61f0f539520b3b](https://github.com/xamarin/xamarin-macios/pull/15898/commits/e70d077ae16dfdcdb0ec5326cb61f0f539520b3b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 18:27 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.445-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Bundle.16.0.445-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Ref.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Runtime.ios-arm.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Runtime.ios-arm64.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Sdk.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Templates.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.iOS.Windows.Sdk.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.445-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.NET.Workload.iOS.16.0.445-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.445-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.tvOS.Bundle.16.0.445-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.tvOS.Ref.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.tvOS.Sdk.16.0.445-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.445-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/Microsoft.tvOS.Templates.16.0.445-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.10.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/cd60101508dcfaece849f8c0705f37ceba7f9fb9/6667716/package/xamarin.ios-16.0.0.10.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6667716&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1171.Monterey'
Hash: [e70d077ae16dfdcdb0ec5326cb61f0f539520b3b](https://github.com/xamarin/xamarin-macios/pull/15898/commits/e70d077ae16dfdcdb0ec5326cb61f0f539520b3b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 18:38 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6667716&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e70d077ae16dfdcdb0ec5326cb61f0f539520b3b](https://github.com/xamarin/xamarin-macios/pull/15898/commits/e70d077ae16dfdcdb0ec5326cb61f0f539520b3b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 19:04 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6668435&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 19:04 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6668435&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-09 19:09 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6668435&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [eba95448328ff686758964332b981fc168c54cbb](https://github.com/xamarin/xamarin-macios/pull/15898/commits/eba95448328ff686758964332b981fc168c54cbb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 09:48 UTC, rolfbjarne commented
/azp run

2022-09-12 11:30 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6673847&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [eba95448328ff686758964332b981fc168c54cbb](https://github.com/xamarin/xamarin-macios/pull/15898/commits/eba95448328ff686758964332b981fc168c54cbb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 11:31 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6673847&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [eba95448328ff686758964332b981fc168c54cbb](https://github.com/xamarin/xamarin-macios/pull/15898/commits/eba95448328ff686758964332b981fc168c54cbb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 11:47 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.446-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Bundle.16.0.446-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Ref.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Runtime.ios-arm.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Runtime.ios-arm64.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Sdk.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Templates.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.iOS.Windows.Sdk.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.446-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.NET.Workload.iOS.16.0.446-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.446-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.tvOS.Bundle.16.0.446-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.tvOS.Ref.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.tvOS.Sdk.16.0.446-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.446-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/Microsoft.tvOS.Templates.16.0.446-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.11.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/bb30b14f87ae6054121b5d3f49d57ef07d1f43d7/6673847/package/xamarin.ios-16.0.0.11.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6673847&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1166.Monterey'
Hash: [eba95448328ff686758964332b981fc168c54cbb](https://github.com/xamarin/xamarin-macios/pull/15898/commits/eba95448328ff686758964332b981fc168c54cbb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 12:04 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6673847&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [eba95448328ff686758964332b981fc168c54cbb](https://github.com/xamarin/xamarin-macios/pull/15898/commits/eba95448328ff686758964332b981fc168c54cbb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 12:32 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 0 tests passed :tada:

## Tests counts

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6673847&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/15898/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 13:42 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6674172&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [77dd98cc1f1a62e0b0276e7db947580e4be41b3e](https://github.com/xamarin/xamarin-macios/pull/15898/commits/77dd98cc1f1a62e0b0276e7db947580e4be41b3e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 13:43 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6674172&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [77dd98cc1f1a62e0b0276e7db947580e4be41b3e](https://github.com/xamarin/xamarin-macios/pull/15898/commits/77dd98cc1f1a62e0b0276e7db947580e4be41b3e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 13:59 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.468-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Bundle.16.0.468-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Ref.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Runtime.ios-arm.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Runtime.ios-arm64.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Sdk.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Templates.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.iOS.Windows.Sdk.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.468-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.NET.Workload.iOS.16.0.468-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.468-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.tvOS.Bundle.16.0.468-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.tvOS.Ref.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.tvOS.Sdk.16.0.468-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.468-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/Microsoft.tvOS.Templates.16.0.468-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.33.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/9890c87a3d65848e3e14a556a8844dc395dc1b24/6674172/package/xamarin.ios-16.0.0.33.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6674172&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1164.Monterey'
Hash: [77dd98cc1f1a62e0b0276e7db947580e4be41b3e](https://github.com/xamarin/xamarin-macios/pull/15898/commits/77dd98cc1f1a62e0b0276e7db947580e4be41b3e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 14:15 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6674172&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [77dd98cc1f1a62e0b0276e7db947580e4be41b3e](https://github.com/xamarin/xamarin-macios/pull/15898/commits/77dd98cc1f1a62e0b0276e7db947580e4be41b3e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-12 18:59 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

19 tests crashed, 0 tests failed, 0 tests passed.

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

:fire: Failed catastrophically on VSTS: simulator tests - cecil (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: framework tests

:fire: Failed catastrophically on VSTS: simulator tests - framework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

:fire: Failed catastrophically on VSTS: simulator tests - interdependent_binding_projects (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)

### :x: install_source tests

:fire: Failed catastrophically on VSTS: simulator tests - install_source (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

:fire: Failed catastrophically on VSTS: simulator tests - linker (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6674172/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220912.14/6674172-2//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https [...]

2022-09-13 03:47 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6678484&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4c90a7f33cc1b58624843acef34004509388d12c](https://github.com/xamarin/xamarin-macios/pull/15898/commits/4c90a7f33cc1b58624843acef34004509388d12c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 03:47 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6678484&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4c90a7f33cc1b58624843acef34004509388d12c](https://github.com/xamarin/xamarin-macios/pull/15898/commits/4c90a7f33cc1b58624843acef34004509388d12c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 04:04 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.471-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Bundle.16.0.471-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Ref.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Runtime.ios-arm.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Runtime.ios-arm64.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Sdk.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Templates.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.iOS.Windows.Sdk.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.471-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.NET.Workload.iOS.16.0.471-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.471-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.tvOS.Bundle.16.0.471-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.tvOS.Ref.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.tvOS.Sdk.16.0.471-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.471-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/Microsoft.tvOS.Templates.16.0.471-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.36.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e6b795d9e62c8ab7e69561ea34aa84221e4c00cc/6678484/package/xamarin.ios-16.0.0.36.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6678484&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1164.Monterey'
Hash: [4c90a7f33cc1b58624843acef34004509388d12c](https://github.com/xamarin/xamarin-macios/pull/15898/commits/4c90a7f33cc1b58624843acef34004509388d12c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 04:23 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6678484&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4c90a7f33cc1b58624843acef34004509388d12c](https://github.com/xamarin/xamarin-macios/pull/15898/commits/4c90a7f33cc1b58624843acef34004509388d12c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 05:03 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

19 tests crashed, 0 tests failed, 0 tests passed.

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

:fire: Failed catastrophically on VSTS: simulator tests - cecil (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: framework tests

:fire: Failed catastrophically on VSTS: simulator tests - framework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

:fire: Failed catastrophically on VSTS: simulator tests - interdependent_binding_projects (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)

### :x: install_source tests

:fire: Failed catastrophically on VSTS: simulator tests - install_source (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

:fire: Failed catastrophically on VSTS: simulator tests - linker (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6678484/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.2/6678484-1//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualst [...]

2022-09-13 07:34 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6679259&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1d38f9477a7ce7decd97308814d22579c55cc6bf](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1d38f9477a7ce7decd97308814d22579c55cc6bf)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 07:35 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6679259&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1d38f9477a7ce7decd97308814d22579c55cc6bf](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1d38f9477a7ce7decd97308814d22579c55cc6bf)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 07:53 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.472-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Bundle.16.0.472-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Ref.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Runtime.ios-arm.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Runtime.ios-arm64.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Sdk.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Templates.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.iOS.Windows.Sdk.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.472-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.NET.Workload.iOS.16.0.472-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.472-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.tvOS.Bundle.16.0.472-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.tvOS.Ref.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.tvOS.Sdk.16.0.472-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.472-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/Microsoft.tvOS.Templates.16.0.472-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.37.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f0f4338495b8e5bdb9bdf3f80b8025f20827699e/6679259/package/xamarin.ios-16.0.0.37.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6679259&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1168.Monterey'
Hash: [1d38f9477a7ce7decd97308814d22579c55cc6bf](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1d38f9477a7ce7decd97308814d22579c55cc6bf)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 08:09 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6679259&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1d38f9477a7ce7decd97308814d22579c55cc6bf](https://github.com/xamarin/xamarin-macios/pull/15898/commits/1d38f9477a7ce7decd97308814d22579c55cc6bf)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 08:16 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

19 tests crashed, 0 tests failed, 0 tests passed.

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)

### :x: cecil tests

:fire: Failed catastrophically on VSTS: simulator tests - cecil (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)

### :x: framework tests

:fire: Failed catastrophically on VSTS: simulator tests - framework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

:fire: Failed catastrophically on VSTS: simulator tests - interdependent_binding_projects (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)

### :x: install_source tests

:fire: Failed catastrophically on VSTS: simulator tests - install_source (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

:fire: Failed catastrophically on VSTS: simulator tests - linker (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679259/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.3/6679259-1//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualst [...]

2022-09-13 09:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6679549&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6f8d821dc3f0e5acefc01802b0f8705a0a8e53c8](https://github.com/xamarin/xamarin-macios/pull/15898/commits/6f8d821dc3f0e5acefc01802b0f8705a0a8e53c8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 09:20 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6679549&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6f8d821dc3f0e5acefc01802b0f8705a0a8e53c8](https://github.com/xamarin/xamarin-macios/pull/15898/commits/6f8d821dc3f0e5acefc01802b0f8705a0a8e53c8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 09:57 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6679549&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [6f8d821dc3f0e5acefc01802b0f8705a0a8e53c8](https://github.com/xamarin/xamarin-macios/pull/15898/commits/6f8d821dc3f0e5acefc01802b0f8705a0a8e53c8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 11:02 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

6 tests crashed, 5 tests failed, 119 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: generator tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Generator tests/NUnit: Failed (Execution failed with exit code 39)
 * Generator tests/.NET: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 59 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)
:white_check_mark: linker: All 38 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:warning: mac_binding_project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.8/6679549-1//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6679549/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1 [...]

2022-09-13 16:49 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6680519&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [bb9eb0a56f16b231340736410ae5360a3e555ca6](https://github.com/xamarin/xamarin-macios/pull/15898/commits/bb9eb0a56f16b231340736410ae5360a3e555ca6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 16:51 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6680519&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [bb9eb0a56f16b231340736410ae5360a3e555ca6](https://github.com/xamarin/xamarin-macios/pull/15898/commits/bb9eb0a56f16b231340736410ae5360a3e555ca6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 17:08 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.474-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Bundle.16.0.474-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Ref.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Runtime.ios-arm.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Runtime.ios-arm64.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Sdk.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Templates.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.iOS.Windows.Sdk.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.474-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.NET.Workload.iOS.16.0.474-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.474-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.tvOS.Bundle.16.0.474-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.tvOS.Ref.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.tvOS.Sdk.16.0.474-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.474-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/Microsoft.tvOS.Templates.16.0.474-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.39.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/f7615745f3b6b2862b03602be31079f900ea3c8d/6680519/package/xamarin.ios-16.0.0.39.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6680519&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1164.Monterey'
Hash: [bb9eb0a56f16b231340736410ae5360a3e555ca6](https://github.com/xamarin/xamarin-macios/pull/15898/commits/bb9eb0a56f16b231340736410ae5360a3e555ca6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 17:26 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6680519&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [bb9eb0a56f16b231340736410ae5360a3e555ca6](https://github.com/xamarin/xamarin-macios/pull/15898/commits/bb9eb0a56f16b231340736410ae5360a3e555ca6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-13 20:05 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 15 tests failed, 145 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)

### :x: generator tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Generator tests/NUnit: Failed (Execution failed with exit code 39)
 * Generator tests/.NET: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>8 tests failed, 12 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug (LinkSdk) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Release (all optimizations) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * MSBuild tests/Tasks: Failed (Execution failed with exit code 2)
 * MSBuild tests/Integration: Failed (Execution failed with exit code 25)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: mtouch tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * MTouch tests/NUnit: Failed (Execution failed with exit code 4)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 59 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)
:white_check_mark: linker: All 38 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:warning: mac_binding_project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6680519/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:warning: xammac: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220913.22/6680519-1//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/668 [...]

2022-09-15 08:21 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS Mac Catalina (10.15) failed :x:

No test package could be found for tests on macOS Mac Catalina (10.15)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6690805&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a2f89bd0936af6dec37e43806b203d5d0bbbf897](https://github.com/xamarin/xamarin-macios/pull/15898/commits/a2f89bd0936af6dec37e43806b203d5d0bbbf897)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-15 08:36 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.495-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Bundle.16.0.495-ci.pr.gh15898.pkg)
* [Microsoft.iOS.Ref.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Ref.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Runtime.ios-arm.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Runtime.ios-arm64.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Sdk.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Sdk.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Templates.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Templates.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.iOS.Windows.Sdk.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.495-ci.pr.gh15898.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.NET.Workload.iOS.16.0.495-ci.pr.gh15898.msi)
* [Microsoft.tvOS.Bundle.16.0.495-ci.pr.gh15898.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.tvOS.Bundle.16.0.495-ci.pr.gh15898.pkg)
* [Microsoft.tvOS.Ref.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.tvOS.Ref.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Sdk.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.tvOS.Sdk.16.0.495-ci.pr.gh15898.nupkg)
* [Microsoft.tvOS.Templates.16.0.495-ci.pr.gh15898.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/Microsoft.tvOS.Templates.16.0.495-ci.pr.gh15898.nupkg)
* [xamarin.ios-16.0.0.60.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/78b48911942d94e8fe6a3f60b18047b5fdbbfa58/6690805/package/xamarin.ios-16.0.0.60.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6690805&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1164.Monterey'
Hash: [a2f89bd0936af6dec37e43806b203d5d0bbbf897](https://github.com/xamarin/xamarin-macios/pull/15898/commits/a2f89bd0936af6dec37e43806b203d5d0bbbf897)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-15 08:53 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6690805&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a2f89bd0936af6dec37e43806b203d5d0bbbf897](https://github.com/xamarin/xamarin-macios/pull/15898/commits/a2f89bd0936af6dec37e43806b203d5d0bbbf897)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-15 10:43 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 12 tests failed, 148 tests passed.

## Failures

### :x: monotouch tests

<summary>12 tests failed, 8 tests passed.</summary>
<details>

 * monotouch-test/tvOS - simulator/Debug [dotnet]: Failed
 * monotouch-test/tvOS - simulator/Debug: Failed
 * monotouch-test/tvOS - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/tvOS - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/tvOS - simulator/Debug (LinkSdk): Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar): Failed
 * monotouch-test/tvOS - simulator/Release (all optimizations): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 59 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_cecil&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_dotnettests/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_dotnettests&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_fsharp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_fsharp&api-version=6.0&$format=zip)
:white_check_mark: framework: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_generator/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_generator&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_interdependent_binding_projects/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_install_source/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_install_source&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)
:white_check_mark: linker: All 38 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)
:warning: mac_binding_project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_mac_binding_project/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_mac_binding_project&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_mmp/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_mmp&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_mononative/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_mononative&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_mtouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_mtouch&api-version=6.0&$format=zip)
:warning: xammac: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_xammac/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_xammac&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_xcframework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6690805/artifacts?artifactName=HtmlReport-simulator_xcframework&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220915.1/6690805-1//simulator_xtro/;/tests/vs [...]

2022-09-15 11:52 UTC, rolfbjarne commented
Test failures are unrelated (#15939).

2022-09-15 14:35 UTC, merged