[StoreKit] Added support for Xcode 14.1 b1
xamarin/xamarin-macios pull request #16026
Opened 2022-09-20 05:11 UTC by SotoiGhost

2022-09-20 05:37 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6711311&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-20 05:37 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6711311&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-20 05:43 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6711311&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4d920d410321f9ffd91261d58b276b410a52c719](https://github.com/xamarin/xamarin-macios/pull/16026/commits/4d920d410321f9ffd91261d58b276b410a52c719)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-21 18:58 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6719949&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-21 18:59 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6719949&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-21 19:04 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6719949&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [110537ac687170f3c1163984c414a0c226d4586b](https://github.com/xamarin/xamarin-macios/pull/16026/commits/110537ac687170f3c1163984c414a0c226d4586b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-28 00:53 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6749831&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-28 00:53 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6749831&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-28 00:59 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6749831&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f1af4c6fef3f3f0c75a9ea476562c42402922ae5](https://github.com/xamarin/xamarin-macios/pull/16026/commits/f1af4c6fef3f3f0c75a9ea476562c42402922ae5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-03 16:36 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6772984&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-03 16:47 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6772984&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16026/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-03 16:53 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6772984&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f16fc20b9aaa993a3360fdb735dad2923f8d6a57](https://github.com/xamarin/xamarin-macios/pull/16026/commits/f16fc20b9aaa993a3360fdb735dad2923f8d6a57)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-03 21:29 UTC, stephen-hawley approved these changes

2022-10-03 22:15 UTC, tj-devel709 approved these changes

2022-10-04 01:28 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/8047efb07bb8088282296ea7ff37195b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/73d5de714f5dc70cdac07d3682c8cec9) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/e7410844be8459fbfef00a560a41b27e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~macOS~: (empty diff detected)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/2320d6dcd5d0b19c1b7852881e427664) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/85a807d59c40f08825109de00cf603de) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/3b6a0242b2d0b5d402a55530a734eae1) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/336b6706cfbf4c53559607063d7a0931) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/39da1654fe58e196784b629ca03cde14) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/d41e24fbe6ee683cda04efe204f76941) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/25f8ff90836b8bcda9526154cb7ac8f3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/2c37ea85a794e8f34df4f0b3d35ec0be) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/9fe205845006cde64621e56d87818fa5)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/cb6cde3cea12f198069a2b8d02e5d599)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/5c3f2be990526cc67c5cff57415957ec)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/071ee269a8a82441552188584ca8af18)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221003.26/6775176-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/f463f4bdfc3dcaa7845ded3758e136af) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6775176&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [22d857764e22eac0a4dd8acedc61d31e633fc95c](https://github.com/xamarin/xamarin-macios/pull/16026/commits/22d857764e22eac0a4dd8acedc61d31e633fc95c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 01:30 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.6-ci.pr.gh16026.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Bundle.16.1.6-ci.pr.gh16026.pkg)
* [Microsoft.iOS.Ref.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Ref.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Runtime.ios-arm.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Runtime.ios-arm64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Sdk.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Sdk.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Templates.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Templates.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.iOS.Windows.Sdk.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.6-ci.pr.gh16026.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.MacCatalyst.Bundle.16.1.6-ci.pr.gh16026.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.MacCatalyst.Ref.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.MacCatalyst.Sdk.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.MacCatalyst.Templates.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.macOS.Bundle.13.0.561-ci.pr.gh16026.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.macOS.Bundle.13.0.561-ci.pr.gh16026.pkg)
* [Microsoft.macOS.Ref.13.0.561-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.macOS.Ref.13.0.561-ci.pr.gh16026.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.561-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.macOS.Runtime.osx-arm64.13.0.561-ci.pr.gh16026.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.561-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.macOS.Runtime.osx-x64.13.0.561-ci.pr.gh16026.nupkg)
* [Microsoft.macOS.Sdk.13.0.561-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.macOS.Sdk.13.0.561-ci.pr.gh16026.nupkg)
* [Microsoft.macOS.Templates.13.0.561-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.macOS.Templates.13.0.561-ci.pr.gh16026.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.561-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.561-ci.pr.gh16026.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.6-ci.pr.gh16026.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.NET.Workload.iOS.16.1.6-ci.pr.gh16026.msi)
* [Microsoft.tvOS.Bundle.16.1.6-ci.pr.gh16026.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.tvOS.Bundle.16.1.6-ci.pr.gh16026.pkg)
* [Microsoft.tvOS.Ref.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.tvOS.Ref.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.tvOS.Sdk.16.1.6-ci.pr.gh16026.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/71fd2c4aea31f01dbe5a69c290c9a64f5ed31352/6775176/package/Microsoft.tvOS.Sdk.16.1.6-ci.pr.gh16026.nupkg)
* [Microsoft.tvOS.Templates.16.1.6 [...]

2022-10-04 01:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6775176&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [22d857764e22eac0a4dd8acedc61d31e633fc95c](https://github.com/xamarin/xamarin-macios/pull/16026/commits/22d857764e22eac0a4dd8acedc61d31e633fc95c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 01:37 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6775176&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [22d857764e22eac0a4dd8acedc61d31e633fc95c](https://github.com/xamarin/xamarin-macios/pull/16026/commits/22d857764e22eac0a4dd8acedc61d31e633fc95c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 04:25 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 8 tests failed, 220 tests passed.

## Failures

### :x: bcl tests

<summary>2 tests failed, 67 tests passed.</summary>
<details>

 * mscorlib Part 3/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemCoreXunit Part 2/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>3 tests failed, 62 tests passed.</summary>
<details>

 * link all/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * link all/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
 * dont link/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>2 tests failed, 21 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221003.26/6775176//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6775176/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mar [...]

2022-10-04 13:12 UTC, rolfbjarne requested changes

2022-10-04 13:12 UTC, rolfbjarne commented on src/storekit.cs
> +		void StartImpression (SKAdImpression impression, [NullAllowed] SKAdNetworkCompletionHandler completion);
This is a breaking change, you can only add a new overload, not change existing parameter types.

2022-10-04 13:12 UTC, rolfbjarne commented on src/storekit.cs
> +		void EndImpression (SKAdImpression impression, [NullAllowed] SKAdNetworkCompletionHandler completion);
Same

2022-10-04 13:12 UTC, rolfbjarne commented on src/storekit.cs
> +		void UpdatePostback (nint conversionValue, [NullAllowed] SKAdNetworkCompletionHandler completion);
Same

2022-10-04 13:12 UTC, rolfbjarne commented on src/storekit.cs
> +		void UpdatePostbackConversionValue (nint fineValue, [BindAs (typeof (SKAdNetworkCoarseConversionValue))] NSString coarseValue, [NullAllowed] SKAdNetworkCompletionHandler completion);
It's better to name it like the existing method:

```suggestion
		void UpdatePostback (nint conversionValue, [BindAs (typeof (SKAdNetworkCoarseConversionValue))] NSString coarseValue, [NullAllowed] SKAdNetworkCompletionHandler completion);
```

2022-10-04 13:12 UTC, rolfbjarne commented on src/storekit.cs
> +		void UpdatePostbackConversionValue (nint fineValue, [BindAs (typeof (SKAdNetworkCoarseConversionValue))] NSString coarseValue, bool lockWindow, [NullAllowed] SKAdNetworkCompletionHandler completion
```suggestion
		void UpdatePostback (nint conversionValue, [BindAs (typeof (SKAdNetworkCoarseConversionValue))] NSString coarseValue, bool lockWindow, [NullAllowed] SKAdNetworkCompletionHandler completion);
```

2022-10-04 16:31 UTC, mandel-macaque approved these changes

2022-10-04 16:33 UTC, chamons approved these changes

2022-10-04 17:01 UTC, dalexsoto approved these changes

2022-10-04 18:59 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/7926f1ec75425f8f1cf5d9cc8234779b) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/b3f1385e8c5614266b6c2a0bc0df87e5) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/b0496550be2fb45e6b184b768ef26581) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/59c12320ccff3b3e4a96c716ec28d59b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/e82e31edb73f12be788f769eb9c7266e) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/fabbd36f6e4307f170ac8e656637503e) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/ca35475e34aa46186e6fd299558339d1) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/c14e6f2d2296a889adc62f5ffb5ab96b) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/e63591544f005aef49cb3ac904d004cc) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/23e03077a931c923e7867a8482c81f6f) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/8592c55ba78554a971df70927755e0b7) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/041c599b950fd522b74ab278bc6da9c1)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/60baae0dd4cd0adb1aabd096b4a70b34)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a5c457eba095b72f53545bf980f7b6f4)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/4fef34d68c84e2d6819f9c020b7b7b23)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.15/6778762-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/44b32095ca94ec544065bc3cb4f32f7a) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6778762&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ebf27ef80748b676134a4157e16e129f1d2e84f3](https://github.com/xamarin/xamarin-macios/pull/16026/commits/ebf27ef80748b676134a4157e16e129f1d2e84f3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 19:18 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* linksdk
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6778762&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ebf27ef80748b676134a4157e16e129f1d2e84f3](https://github.com/xamarin/xamarin-macios/pull/16026/commits/ebf27ef80748b676134a4157e16e129f1d2e84f3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 22:01 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 19 tests failed, 209 tests passed.

## Failures

### :x: bcl tests

<summary>10 tests failed, 59 tests passed.</summary>
<details>

 * [NUnit] Mono Mac OS X BCL tests group 3/Mac Modern/Debug: Failed (Test run failed.
Tests run: 8755 Passed: 8174 Inconclusive: 0 Failed: 1 Ignored: 46)
 * [NUnit] Mono BCL tests group 1/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 3/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 4/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 5/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * mscorlib Part 1/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * mscorlib Part 2/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * mscorlib Part 3/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 1/iOS Unified 64-bits - simulator/Debug: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>5 tests failed, 60 tests passed.</summary>
<details>

 * dont link/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
 * dont link/iOS Unified 64-bits - simulator/Release: LaunchTimedOut
 * trimmode copy/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
 * trimmode link/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * link all/iOS Unified 64-bits - simulator/Release: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>3 tests failed, 20 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): LaunchTimedOut
 * monotouch-test/watchOS 32-bits - simulator/Debug: TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6778762/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.15/6778762//simulator_mtouch-1/;/tests/vs [...]

2022-10-05 06:35 UTC, rolfbjarne approved these changes

2022-10-05 15:36 UTC, mandel-macaque commented
Failures are unrelated.

2022-10-05 15:37 UTC, merged