[HomeKit] Added support to Xcode 14.1 b1
xamarin/xamarin-macios pull request #16069
Opened 2022-09-22 00:21 UTC by SotoiGhost

* Matter properties are still missing

2022-09-22 01:59 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/214e281fc548da4f1b8dbdbc87d6616c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/a004a8e9447d15b3e1b2a6748c002319) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/3d8beb6c10187ff0ba48b82cc0252014) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/7b4210853f0d63ef5d9c4c0a426b7f7a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/a2e03705599988eec8a58930f385adef) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/c493c0fdf8614fae511cd3ef67a9166e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~macOS~: (empty diff detected)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/a8a8d31f6137bcd9a8f4df021a2a0881) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/e7c96dc90be5d06587aa74dc12bc789d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/e3eedc13c08e2ef67d6d3e400c83c9cb) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/31db15bed5bb25b262e7445b5f724777) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/06a460a6b333585241ef9bd735ff52be) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/192d3e1421b2fe8b669a4715ba4bbac0) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/2de23553475a086d85918a2cf9141688) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/fa58712894d065903ab963668971cab5) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/914c0042651f13dbe52c3a2e2bd700af)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/b34b503c460a2264a27110e2fea047cc)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/189f2c4bf7d718ff94355b7033809dc2)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/fb92e049b315f1d0f70f5714bc526230)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20220922.1/6722442-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/d4541e0b3afeedb980c2e8d064759ab7) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6722442&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f06afb7638a07773f5b82e40b3fc110ed68d247f](https://github.com/xamarin/xamarin-macios/pull/16069/commits/f06afb7638a07773f5b82e40b3fc110ed68d247f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-22 02:01 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.0.514-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Bundle.16.0.514-ci.pr.gh16069.pkg)
* [Microsoft.iOS.Ref.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Ref.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Runtime.ios-arm.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Runtime.ios-arm64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Runtime.iossimulator-x64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Runtime.iossimulator-x86.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Sdk.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Sdk.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Templates.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Templates.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.iOS.Windows.Sdk.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.0.514-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.MacCatalyst.Bundle.16.0.514-ci.pr.gh16069.pkg)
* [Microsoft.MacCatalyst.Ref.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.MacCatalyst.Ref.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.MacCatalyst.Sdk.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Templates.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.MacCatalyst.Templates.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Bundle.13.0.514-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.macOS.Bundle.13.0.514-ci.pr.gh16069.pkg)
* [Microsoft.macOS.Ref.13.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.macOS.Ref.13.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.macOS.Runtime.osx-arm64.13.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.macOS.Runtime.osx-x64.13.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Sdk.13.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.macOS.Sdk.13.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Templates.13.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.macOS.Templates.13.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Workload.iOS.16.0.514-ci.pr.gh16069.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.NET.Workload.iOS.16.0.514-ci.pr.gh16069.msi)
* [Microsoft.tvOS.Bundle.16.0.514-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.tvOS.Bundle.16.0.514-ci.pr.gh16069.pkg)
* [Microsoft.tvOS.Ref.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.tvOS.Ref.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.tvOS.Runtime.tvos-arm64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f26975/6722442/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.0.514-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Sdk.16.0.514-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/e85452964c56739ca6f5773d631780e269f2 [...]

2022-09-22 02:03 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS Mac Catalina (10.15) passed :computer:

:white_check_mark: **All** tests on macOS Mac Catalina (10.15) passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6722442&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f06afb7638a07773f5b82e40b3fc110ed68d247f](https://github.com/xamarin/xamarin-macios/pull/16069/commits/f06afb7638a07773f5b82e40b3fc110ed68d247f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-22 02:11 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6722442&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f06afb7638a07773f5b82e40b3fc110ed68d247f](https://github.com/xamarin/xamarin-macios/pull/16069/commits/f06afb7638a07773f5b82e40b3fc110ed68d247f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-22 05:12 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 12 tests failed, 216 tests passed.

## Failures

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/watchOS 32-bits - simulator/Debug: TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_framework/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_framework&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_introspection/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_introspection&api-version=6.0&$format=zip)

### :x: linker tests

<summary>6 tests failed, 59 tests passed.</summary>
<details>

 * dont link/watchOS 32-bits - simulator/Debug: TimedOut
 * dont link/watchOS 32-bits - simulator/Release: TimedOut
 * link all/watchOS 32-bits - simulator/Debug: TimedOut
 * link all/watchOS 32-bits - simulator/Release: TimedOut
 * link sdk/watchOS 32-bits - simulator/Debug: TimedOut
 * link sdk/watchOS 32-bits - simulator/Release: HarnessException (Harness exception for 'link sdk': System.InvalidOperationException: The Writer is closed or in error state.
  at System.Xml.XmlWellFormedWriter.AdvanceState (System.Xml.XmlWellFormedWriter+Token token) [0x001f6] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:1712 
  at System.Xml.XmlWellFormedWriter.WriteCData (System.String text) [0x00029] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlWellFormedWriter.cs:771 
  at Microsoft.DotNet.XHarness.iOS.Shared.Utilities.Extensions.WriteCDataSafe (System.Xml.XmlWriter writer, System.String text) [0x0001b] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Extensions.cs:130 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.TestReportGenerator.WriteFailure (System.Xml.XmlWriter writer, System.String message, System.IO.TextReader stderr) [0x00031] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/TestReportGenerator.cs:43 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.NUnitV3TestReportGenerator.GenerateFailure (System.Xml.XmlWriter writer, System.String title, System.String message, System.IO.TextReader stderr) [0x0030e] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/NUnitV3TestReportGenerator.cs:124 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailureXml (System.String destination, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00033] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:226 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.IO.TextReader stderrReader, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x000a4] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:248 
  at Microsoft.DotNet.XHarness.iOS.Shared.XmlResults.XmlResultParser.GenerateFailure (Microsoft.DotNet.XHarness.iOS.Shared.Logging.ILogs logs, System.String source, System.String appName, System.String variation, System.String title, System.String message, System.String stderrPath, Microsoft.DotNet.XHarness.Common.XmlResultJargon jargon) [0x00008] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/XmlResultParser.cs:236 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.GenerateXmlFailures (System.String failure, System.Boolean crashed, System.String crashReason) [0x00247] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:575 
  at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult () [0x0056f] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs:713 
  at Xharness.AppRunner.RunAsync () [0x01b78] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/AppRunner.cs:453 
  at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync () [0x002b1] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:128 
  at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync () [0x001b9] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:113 
  at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:269 )
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_linker/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_linker&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2788 Passed: 2657 Inconclusive: 9 Failed: 1 Ignored: 130)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_monotouch/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_monotouch&api-version=6.0&$format=zip)

### :x: msbuild tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * MSBuild tests/Integration: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_msbuild/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_msbuild&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
 * Xtro/.NET: Failed (Test run failed.)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_xtro/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_xtro&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_bcl/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_bcl&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20220922.1/6722442-1//simulator_cecil/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6722442/artifacts?artifactName=HtmlReport-simulator_cecil&a [...]

2022-09-28 01:37 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6750170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-28 01:38 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6750170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-09-28 01:47 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6750170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [035f82639e09f67eae73ba32aa1914ebde53d42d](https://github.com/xamarin/xamarin-macios/pull/16069/commits/035f82639e09f67eae73ba32aa1914ebde53d42d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-03 16:36 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6772981&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-03 16:36 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6772981&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-03 16:41 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6772981&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8126dea2fb4b0711251d5b86e13b4518ffecd674](https://github.com/xamarin/xamarin-macios/pull/16069/commits/8126dea2fb4b0711251d5b86e13b4518ffecd674)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 13:19 UTC, rolfbjarne requested changes

2022-10-04 17:07 UTC, mandel-macaque commented on src/homekit.cs
> -	interface HMMatterHome : NSCopying, NSSecureCoding
I don't think so, since it won't compile without them.

2022-10-04 20:46 UTC, chamons approved these changes
Approved assuming apidiff comes back clean now.

2022-10-04 22:23 UTC, SotoiGhost reviewed
LGTM! 👍🏼

2022-10-04 23:16 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/e37ebfdf49290846394370a27bab694e) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/2d0eed740c9e954dd43a1d3f88a3eb4d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/f48bf7ccedf3044f1a8919430da9c95f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/634e9abbc0a93912018b67cafaab8ef2) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/ba482d7d8c4b3e72df91cdcd20ca830c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/768d3c7cdab1de8fa24d4d64803df689) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* ~macOS~: (empty diff detected)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/60ffdc7a4c0b58ae7bde5279b0f7b953) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/834dd1f482064baeba159f0f66008efd) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/b75d9f599bea03eb5be877894b05c665) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/1395f9f2d05ed41ee03fc4ab242b5f39) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/7dfd2b812d9956e4aa8cdba78f5b2f49) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/fe37d1dcb3ce64cedfcd95b66ab043c7) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/44ab0a4faf6f549272f5a44437965862) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/9d629bfbcfaf76227f7f6a8af14e52ae) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/829b8c3fa4521930023e26038a373b84)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/4502738966bf05fcf049ac1739e61884)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/0ff88eaf1db394950d172d14c26f0c77)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/1ef2ab13e99051d392e6b1badd7fa0fe)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221004.23/6780522-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/27f56099cfa830f379c3751931b6ac9b) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6780522&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9a7f2777df863db2eae8de47eda1cba37b0abad9](https://github.com/xamarin/xamarin-macios/pull/16069/commits/9a7f2777df863db2eae8de47eda1cba37b0abad9)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 23:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6780522&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9a7f2777df863db2eae8de47eda1cba37b0abad9](https://github.com/xamarin/xamarin-macios/pull/16069/commits/9a7f2777df863db2eae8de47eda1cba37b0abad9)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-04 23:24 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.4-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Bundle.16.1.4-ci.pr.gh16069.pkg)
* [Microsoft.iOS.Ref.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Ref.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Runtime.ios-arm.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Runtime.ios-arm64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Sdk.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Sdk.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Templates.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Templates.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.iOS.Windows.Sdk.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.4-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.MacCatalyst.Bundle.16.1.4-ci.pr.gh16069.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.MacCatalyst.Ref.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.MacCatalyst.Sdk.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.MacCatalyst.Templates.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Bundle.13.0.559-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.macOS.Bundle.13.0.559-ci.pr.gh16069.pkg)
* [Microsoft.macOS.Ref.13.0.559-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.macOS.Ref.13.0.559-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.559-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.macOS.Runtime.osx-arm64.13.0.559-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.559-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.macOS.Runtime.osx-x64.13.0.559-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Sdk.13.0.559-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.macOS.Sdk.13.0.559-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Templates.13.0.559-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.macOS.Templates.13.0.559-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.559-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.559-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.4-ci.pr.gh16069.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.NET.Workload.iOS.16.1.4-ci.pr.gh16069.msi)
* [Microsoft.tvOS.Bundle.16.1.4-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.tvOS.Bundle.16.1.4-ci.pr.gh16069.pkg)
* [Microsoft.tvOS.Ref.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.tvOS.Ref.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Sdk.16.1.4-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/4a8b610f1ec3330f4a7ea02efd84355bcc0d252b/6780522/package/Microsoft.tvOS.Sdk.16.1.4-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Templates.16.1.4 [...]

2022-10-05 02:57 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 217 tests passed.

## Failures

### :x: bcl tests

<summary>2 tests failed, 67 tests passed.</summary>
<details>

 * mscorlib Part 3/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemXunit/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>4 tests failed, 9 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug (iOS 12.4) [dotnet]: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug (iOS 12.4): Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * link sdk/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * link sdk/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * link all/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
 * dont link/iOS Unified 64-bits - simulator/Release: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6780522/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221004.23/6780522//simulator_xcframework-1/;/tests/vsdrops_index. [...]

2022-10-05 06:39 UTC, rolfbjarne requested changes
Looks mostly good, but the api diff is still red on tvOS, Mac Catalyst and watchOS:

```
Removed Type HomeKit.HMFetchRoomHandler
Removed Type HomeKit.HMMatterHome
Removed Type HomeKit.HMMatterRequestHandler
Removed Type HomeKit.HMMatterRoom
Removed Type HomeKit.HMMatterTopology
```

2022-10-06 16:46 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6789741&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-06 16:51 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6789741&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e9d7466735158160b5099924c77f7f5c58f865e9](https://github.com/xamarin/xamarin-macios/pull/16069/commits/e9d7466735158160b5099924c77f7f5c58f865e9)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-06 16:55 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6789741&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-06 19:18 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/6baffcb72e98aa6da603987bbd1d021b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/622c00eb09576f2f9196f009f7322e78) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/6e2d49f4a1e016ddfc7e41a79a07b4ee) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/b86e640b8616f31da76c8d3c0f75e53f) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/bbd2fb4607d78192cce7de45e72991f1) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/b0288ea87d863ab179f752c1bd2f6e12) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/ec575d5ec2dfa69cbc64e30720bd0576) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/b244268143e2282c8889bf1db6b21ad7) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/c29719177f07c5a9ad619583e7f94869) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/998749e4fcffadb97534489aa7fba442) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/8e8966531155bfecdcc51b0252ae1c3f) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/f22631e9c989f3bd664d9dface21866b) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/d13f41db5ec968ab096f0d56c541d6e1) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/d128d9fc7ac56737951d3c2c9e8d9f6f) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/4462411f8b98d4205804a73451ea2f6f)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/5e4b8bdcfdd5f9b5b13a5fbf9233f19d)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/5ff459c0a3c8a0c81ff5bd86ff148cc7)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/e41f647ceeb46d308007c6a747e38727)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221006.23/6790224-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/b629b851f8fec35bffaa438f570be318) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6790224&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b7488225a1be8ca1d89db1bc5cf3162074ac1fbd](https://github.com/xamarin/xamarin-macios/pull/16069/commits/b7488225a1be8ca1d89db1bc5cf3162074ac1fbd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-06 22:00 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6790224&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-07 17:56 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/387d315f2a14c373cc9907120cc8b4cf) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/c03884c44a2ea769aec68e60f2864e41) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/2c3318d62c2d6378f3d8b8f0aba593d1) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/0bb5baedbd46c767a8a6385a79dd4c0e) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/763d3c7b86e3df3fb97fbefc95975890) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/5dda16683603fae11d0a08b65c201b8e) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/8ac56039e8e0c8ba8b028f8e6dbb2a36) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/2abf984005d0e9f3cbd18edbb1392fa0) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/1f7922cd9b36114071611cf1b0a57a36) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/bc85a9a41b805a415d48c14dbfef829b) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/f13c724accf4311ea7e0e0e95375a83e) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/7ecc3536bbaedb008637d5f02aa7b601) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/73a005c2f9adc234f26e4ab6bc7bd58d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/8cc533592a60132385c24f1fe1433b36) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/75b6bf241454547ef8ccbda9df219d6e)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/f94b59142dcb8ddd68dbc7bc40759998)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/eca0d729f7d5a84daad56c33c0fd8a58)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/dcdd7ddd76dd3f535a3a4992401f93bf)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221007.19/6794941-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/5ffb8b944138c50489087a5029c71313) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6794941&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b7488225a1be8ca1d89db1bc5cf3162074ac1fbd](https://github.com/xamarin/xamarin-macios/pull/16069/commits/b7488225a1be8ca1d89db1bc5cf3162074ac1fbd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-07 18:05 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6794941&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b7488225a1be8ca1d89db1bc5cf3162074ac1fbd](https://github.com/xamarin/xamarin-macios/pull/16069/commits/b7488225a1be8ca1d89db1bc5cf3162074ac1fbd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-07 18:05 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.37-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Bundle.16.1.37-ci.pr.gh16069.pkg)
* [Microsoft.iOS.Ref.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Ref.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Runtime.ios-arm.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Runtime.ios-arm64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Sdk.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Sdk.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Templates.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Templates.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.iOS.Windows.Sdk.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.37-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.MacCatalyst.Bundle.16.1.37-ci.pr.gh16069.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.MacCatalyst.Ref.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.MacCatalyst.Sdk.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.MacCatalyst.Templates.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Bundle.13.0.592-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.macOS.Bundle.13.0.592-ci.pr.gh16069.pkg)
* [Microsoft.macOS.Ref.13.0.592-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.macOS.Ref.13.0.592-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.592-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.macOS.Runtime.osx-arm64.13.0.592-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.592-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.macOS.Runtime.osx-x64.13.0.592-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Sdk.13.0.592-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.macOS.Sdk.13.0.592-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Templates.13.0.592-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.macOS.Templates.13.0.592-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.592-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.592-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.37-ci.pr.gh16069.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.NET.Workload.iOS.16.1.37-ci.pr.gh16069.msi)
* [Microsoft.tvOS.Bundle.16.1.37-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.tvOS.Bundle.16.1.37-ci.pr.gh16069.pkg)
* [Microsoft.tvOS.Ref.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.tvOS.Ref.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.37-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Sdk.16.1.37-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/0e0fdaec55b17c7cdf9f4902e6635b422e630e1d/6794941/package/Microsoft.tvOS.Sdk.16.1.37-ci. [...]

2022-10-07 23:39 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 18 tests failed, 210 tests passed.

## Failures

### :x: bcl tests

<summary>2 tests failed, 67 tests passed.</summary>
<details>

 * [NUnit] Mono BCL tests group 1/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemCoreXunit Part 2/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>2 tests failed, 6 tests passed.</summary>
<details>

 * framework-test/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * framework-test/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>9 tests failed, 4 tests passed.</summary>
<details>

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 44 Passed: 40 Inconclusive: 0 Failed: 2 Ignored: 2)
 * introspection/iOS Unified 64-bits - simulator/Debug: Failed
 * introspection/tvOS - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug (iOS 12.4) [dotnet]: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug (iOS 12.4): Failed
 * introspection/tvOS - simulator/Debug (tvOS 12.4) [dotnet]: Failed
 * introspection/tvOS - simulator/Debug (tvOS 12.4): Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>3 tests failed, 62 tests passed.</summary>
<details>

 * dont link/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
 * link all/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * link sdk/iOS Unified 64-bits - simulator/Release: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: mtouch tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * MTouch tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221007.19/6794941//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6794941/artifacts?artifactName= [...]

2022-10-10 16:52 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/75e7fbd038a013d27927c0985ca548c4) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/5bac097722af8d463a46082e0a5d1a04) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/51149f52b635f0ac250d3709b9718da0) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/2f8093862fdd88e856381eab136b8a99) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/ca824f4aee0e070e27d9f39ea7c88d3a) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/fceac76d407a85bc41ed311a0c2fdb85) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/a249484c770d1ab451f77743ca3c3987) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/d87b558d01246435f80321cfee9e1b61) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/9c9872911c4fc3c773e03663aa9a4f69) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/a0cab25e74f9f58372bf207995fbce1c) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/e14e40d81a94267c37a02f7e61f7e2c3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/855a3351154fa076316b149391994da4) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/1e5d5a85a873ffffeb5ccb5735a1ea25) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/7f1b30cba992b477218d74661a04a5fd) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/c45477376b0dcebed95ee3376c1343ef)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/6e8db475457b86b3e414a49b5bdb4d0c)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/20cb2d35fd13114074724ad7b249a875)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/2a4c3c0aaa4c4906cac66e7ed1e4ea22)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221010.16/6802582-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/4e582c267834cb377957a06fb52ac84b) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6802582&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [affa08b64b7f8d6379f920c05aaba56d7a040e48](https://github.com/xamarin/xamarin-macios/pull/16069/commits/affa08b64b7f8d6379f920c05aaba56d7a040e48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-10 16:54 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.55-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Bundle.16.1.55-ci.pr.gh16069.pkg)
* [Microsoft.iOS.Ref.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Ref.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Runtime.ios-arm.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Runtime.ios-arm64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Sdk.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Sdk.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Templates.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Templates.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.iOS.Windows.Sdk.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.55-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.MacCatalyst.Bundle.16.1.55-ci.pr.gh16069.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.MacCatalyst.Ref.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.MacCatalyst.Sdk.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.MacCatalyst.Templates.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Bundle.13.0.610-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.macOS.Bundle.13.0.610-ci.pr.gh16069.pkg)
* [Microsoft.macOS.Ref.13.0.610-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.macOS.Ref.13.0.610-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.610-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.macOS.Runtime.osx-arm64.13.0.610-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.610-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.macOS.Runtime.osx-x64.13.0.610-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Sdk.13.0.610-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.macOS.Sdk.13.0.610-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Templates.13.0.610-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.macOS.Templates.13.0.610-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.610-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.610-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.55-ci.pr.gh16069.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.NET.Workload.iOS.16.1.55-ci.pr.gh16069.msi)
* [Microsoft.tvOS.Bundle.16.1.55-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.tvOS.Bundle.16.1.55-ci.pr.gh16069.pkg)
* [Microsoft.tvOS.Ref.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.tvOS.Ref.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.55-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Sdk.16.1.55-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/1db06b1cc892fd3c009fbd745822bc66cab353a0/6802582/package/Microsoft.tvOS.Sdk.16.1.55-ci. [...]

2022-10-10 16:58 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* introspection
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6802582&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [affa08b64b7f8d6379f920c05aaba56d7a040e48](https://github.com/xamarin/xamarin-macios/pull/16069/commits/affa08b64b7f8d6379f920c05aaba56d7a040e48)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-10 20:26 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 14 tests failed, 214 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * [xUnit] Mono BCL tests group 4/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>2 tests failed, 6 tests passed.</summary>
<details>

 * framework-test/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * framework-test/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>4 tests failed, 9 tests passed.</summary>
<details>

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 44 Passed: 41 Inconclusive: 0 Failed: 1 Ignored: 2)
 * introspection/iOS Unified 64-bits - simulator/Debug (iOS 12.4) [dotnet]: Failed
 * introspection/tvOS - simulator/Debug (tvOS 12.4) [dotnet]: Failed
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>3 tests failed, 62 tests passed.</summary>
<details>

 * trimmode copy/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * dont link/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * link sdk/iOS Unified 64-bits - simulator/Release: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>3 tests failed, 20 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: LaunchTimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: mtouch tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * MTouch tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221010.16/6802582//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6802582/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/ [...]

2022-10-11 20:48 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6809543&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16069/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-11 20:54 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6809543&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2abaf1fa85afb6c1b99f891dbb9a75994dacb9e0](https://github.com/xamarin/xamarin-macios/pull/16069/commits/2abaf1fa85afb6c1b99f891dbb9a75994dacb9e0)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-11 20:55 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6809543&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2abaf1fa85afb6c1b99f891dbb9a75994dacb9e0](https://github.com/xamarin/xamarin-macios/pull/16069/commits/2abaf1fa85afb6c1b99f891dbb9a75994dacb9e0)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-11 21:29 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.56-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Bundle.16.1.56-ci.pr.gh16069.pkg)
* [Microsoft.iOS.Ref.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Ref.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Runtime.ios-arm.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Runtime.ios-arm64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Sdk.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Sdk.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Templates.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Templates.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.iOS.Windows.Sdk.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.56-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.MacCatalyst.Bundle.16.1.56-ci.pr.gh16069.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.MacCatalyst.Ref.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.MacCatalyst.Sdk.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.MacCatalyst.Templates.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Bundle.13.0.611-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.macOS.Bundle.13.0.611-ci.pr.gh16069.pkg)
* [Microsoft.macOS.Ref.13.0.611-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.macOS.Ref.13.0.611-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.611-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.macOS.Runtime.osx-arm64.13.0.611-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.611-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.macOS.Runtime.osx-x64.13.0.611-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Sdk.13.0.611-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.macOS.Sdk.13.0.611-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Templates.13.0.611-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.macOS.Templates.13.0.611-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.611-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.611-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.56-ci.pr.gh16069.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.NET.Workload.iOS.16.1.56-ci.pr.gh16069.msi)
* [Microsoft.tvOS.Bundle.16.1.56-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.tvOS.Bundle.16.1.56-ci.pr.gh16069.pkg)
* [Microsoft.tvOS.Ref.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.tvOS.Ref.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.56-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Sdk.16.1.56-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/03bacabe99c80646c8dc34aba10180ddfcebacb2/6809543/package/Microsoft.tvOS.Sdk.16.1.56-ci. [...]

2022-10-12 00:53 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 217 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * [xUnit] Mono SystemXunit/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>2 tests failed, 5 tests passed.</summary>
<details>

 * interdependent-binding-projects/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * interdependent-binding-projects/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>2 tests failed, 11 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>1 tests failed, 64 tests passed.</summary>
<details>

 * trimmode link/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: mtouch tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * MTouch tests/NUnit: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

### :x: xammac tests

<summary>1 tests failed, 2 tests passed.</summary>
<details>

 * xammac tests/Mac Modern/Release (all optimizations): TimedOut (Execution timed out after 1200 seconds.
Test run crashed)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6809543/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221011.12/6809543//simulator_mononative-1/;/tests/ [...]

2022-10-12 16:19 UTC, tj-devel709 commented on src/homekit.cs
> -	interface HMMatterHome : NSCopying, NSSecureCoding
Was this addressed?

2022-10-12 16:21 UTC, tj-devel709 commented on src/homekit.cs
> -	interface HMMatterHome : NSCopying, NSSecureCoding
Oh nevermind! I see that's what those added classes are there for!

2022-10-12 18:38 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/aef288786786456a9ddee36bd394e4b8) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/3ba4acf09501e45a05467b42a7d14681) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/e6994dd0160271feb4343d5cff394d95) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/08485ece7b79dcd1dbcdb67eaec389e7) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/3aa58d8c748675ec41b5a1c603720f70) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/7054a9652df44b7c6fc1adaf032370e4) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/6659089cde6eb989e659f1c6769e4885) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/8b8888775bd9ddb0e85e9a3a73bd682a) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/96d7dcc97c948e711d87df6dd227f0d5) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/9281da1b79eeb7423a8c41c1d6bd4cdc) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/cef8fedb8a0beca41570c88c840fdbbd) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/f7296ad5abb72e84f92e9190111939d5) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/7efe894082acb6ae4d00c3e5c1081207) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/fd948c237f965b36261b43c3e65e5c3e) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/77de2757c9f6cf8e30c5a15897debabb)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/31b398acc6d83c7bf07cbf30d12a3859)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/0107e53d3f3132efab31bfbc290cfca0)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/928dd1b6dea35f9c9999b10f311c48bd)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.4/6814868-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/b8e66ced33527c599b69ffedf5986b2b) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6814868&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b406637acd4762308e2bae5ce2931f6b51e6cb5b](https://github.com/xamarin/xamarin-macios/pull/16069/commits/b406637acd4762308e2bae5ce2931f6b51e6cb5b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-12 18:42 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6814868&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b406637acd4762308e2bae5ce2931f6b51e6cb5b](https://github.com/xamarin/xamarin-macios/pull/16069/commits/b406637acd4762308e2bae5ce2931f6b51e6cb5b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-12 18:51 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.63-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Bundle.16.1.63-ci.pr.gh16069.pkg)
* [Microsoft.iOS.Ref.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Ref.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Runtime.ios-arm.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Runtime.ios-arm64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Sdk.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Sdk.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Templates.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Templates.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.iOS.Windows.Sdk.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.63-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.MacCatalyst.Bundle.16.1.63-ci.pr.gh16069.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.MacCatalyst.Ref.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.MacCatalyst.Sdk.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.MacCatalyst.Templates.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Bundle.13.0.618-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.macOS.Bundle.13.0.618-ci.pr.gh16069.pkg)
* [Microsoft.macOS.Ref.13.0.618-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.macOS.Ref.13.0.618-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.618-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.macOS.Runtime.osx-arm64.13.0.618-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.618-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.macOS.Runtime.osx-x64.13.0.618-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Sdk.13.0.618-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.macOS.Sdk.13.0.618-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Templates.13.0.618-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.macOS.Templates.13.0.618-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.618-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.618-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.63-ci.pr.gh16069.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.NET.Workload.iOS.16.1.63-ci.pr.gh16069.msi)
* [Microsoft.tvOS.Bundle.16.1.63-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.tvOS.Bundle.16.1.63-ci.pr.gh16069.pkg)
* [Microsoft.tvOS.Ref.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.tvOS.Ref.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.63-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Sdk.16.1.63-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/fffe801c9310460ebdc48cc4f7d2851dfb333257/6814868/package/Microsoft.tvOS.Sdk.16.1.63-ci. [...]

2022-10-12 23:38 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/29ccf3d7d27d46e039cec7750ecded11) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/eeb3368d16fe802edbc475ea16ab167f) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/51d28606a321e8161d85638e236f544c) (No breaking changes)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/f68315d83c65869e0d4fbe3cdb6d315e) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/8dff610c6ea5c1e9cc608138be7b61f5) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/0599bcd7900b0665d23bf536e638e66e) (No breaking changes)
* ~macOS~: (empty diff detected)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/2491244000d5e393de443b6832bb8401) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/f95e85003a0e154df4c1c0649f25c9ee) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/cd9fb49b399eb1a1547dd207a9a3d097) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/0f1436037ff44d90b6b3d4076e91debe) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/6b32ed5435c6ba3529b63de92b07e70a) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/ea75769ae8053721fb87208615f80a75) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net6.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/81d5d40f84e7730af3e3a46087dbd72d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/87a750ea631d9c34d5daec3ce98e8842) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/da59efdaab7401c50dfd2734360e211f)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net6.0/Microsoft.iOS.html) [gist](https://gist.github.com/ecea5a7ada65cea3fe71ca057c7c543e)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net6.0/Microsoft.tvOS.html) [gist](https://gist.github.com/285ae727a950000bc6b7f9957177e989)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net6.0/Microsoft.macOS.html) [gist](https://gist.github.com/ebbf25b60b0077611e7efc250c61a7b5)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221012.10/6816798-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/a929f7863f51c7d85d7985d1781287dc) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6816798&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8d8745c0aad5f3051cfcabbdc82b7f5fea17ae61](https://github.com/xamarin/xamarin-macios/pull/16069/commits/8d8745c0aad5f3051cfcabbdc82b7f5fea17ae61)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-12 23:44 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6816798&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8d8745c0aad5f3051cfcabbdc82b7f5fea17ae61](https://github.com/xamarin/xamarin-macios/pull/16069/commits/8d8745c0aad5f3051cfcabbdc82b7f5fea17ae61)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-10-12 23:44 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.65-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Bundle.16.1.65-ci.pr.gh16069.pkg)
* [Microsoft.iOS.Ref.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Ref.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Runtime.ios-arm.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Runtime.ios-arm64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Sdk.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Sdk.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Templates.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Templates.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.iOS.Windows.Sdk.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.65-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.MacCatalyst.Bundle.16.1.65-ci.pr.gh16069.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.MacCatalyst.Ref.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.MacCatalyst.Sdk.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.MacCatalyst.Templates.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Bundle.13.0.620-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.macOS.Bundle.13.0.620-ci.pr.gh16069.pkg)
* [Microsoft.macOS.Ref.13.0.620-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.macOS.Ref.13.0.620-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.620-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.macOS.Runtime.osx-arm64.13.0.620-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.620-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.macOS.Runtime.osx-x64.13.0.620-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Sdk.13.0.620-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.macOS.Sdk.13.0.620-ci.pr.gh16069.nupkg)
* [Microsoft.macOS.Templates.13.0.620-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.macOS.Templates.13.0.620-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.NET.Sdk.iOS.Manifest-6.0.400.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.620-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.NET.Sdk.macOS.Manifest-6.0.400.13.0.620-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.65-ci.pr.gh16069.msi](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.NET.Workload.iOS.16.1.65-ci.pr.gh16069.msi)
* [Microsoft.tvOS.Bundle.16.1.65-ci.pr.gh16069.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.tvOS.Bundle.16.1.65-ci.pr.gh16069.pkg)
* [Microsoft.tvOS.Ref.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.tvOS.Ref.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.65-ci.pr.gh16069.nupkg)
* [Microsoft.tvOS.Sdk.16.1.65-ci.pr.gh16069.nupkg](https://bosstoragemirror.blob.core.windows.net/wrench/merge/6f1619b885a5d6b05cac342ffdab2e6d591ca89d/6816798/package/Microsoft.tvOS.Sdk.16.1.65-ci. [...]

2022-10-13 03:23 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 217 tests passed.

## Failures

### :x: bcl tests

<summary>4 tests failed, 65 tests passed.</summary>
<details>

 * mscorlib Part 1/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * mscorlib Part 2/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * mscorlib Part 3/tvOS - simulator/Debug: Crashed
 * [xUnit] Mono SystemCoreXunit Part 1/tvOS - simulator/Debug: Crashed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>2 tests failed, 63 tests passed.</summary>
<details>

 * link all/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * trimmode copy/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All [...]

2022-10-13 06:36 UTC, rolfbjarne approved these changes

2022-10-13 09:10 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 8 tests failed, 220 tests passed.

## Failures

### :x: bcl tests [attempt 2]

<summary>3 tests failed, 66 tests passed.</summary>
<details>

 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemCoreXunit Part 2/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemXunit/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_bcl-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_bcl-2&api-version=6.0&$format=zip)

### :x: framework tests [attempt 2]

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_framework-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_framework-2&api-version=6.0&$format=zip)

### :x: introspection tests [attempt 2]

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_introspection-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_introspection-2&api-version=6.0&$format=zip)

### :x: linker tests [attempt 2]

<summary>2 tests failed, 63 tests passed.</summary>
<details>

 * link all/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
 * trimmode link/iOS Unified 64-bits - simulator/Release [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_linker-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_linker-2&api-version=6.0&$format=zip)

### :x: monotouch tests [attempt 2]

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_monotouch-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_monotouch-2&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_interdependent_binding_projects-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-2&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_xcframework-2/;/tests/vsdrops_index.html) [Download](https://devdiv.vis [...]

2022-10-13 12:31 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 7 tests failed, 221 tests passed.

## Failures

### :x: bcl tests [attempt 3]

<summary>2 tests failed, 67 tests passed.</summary>
<details>

 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemXunit/iOS Unified 64-bits - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_bcl-3/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_bcl-3&api-version=6.0&$format=zip)

### :x: introspection tests [attempt 3]

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/watchOS 32-bits - simulator/Debug (watchOS 6.0): Crashed Known issue: [HE0038](https://github.com/xamarin/maccore/issues/581))
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_introspection-3/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_introspection-3&api-version=6.0&$format=zip)

### :x: linker tests [attempt 3]

<summary>3 tests failed, 62 tests passed.</summary>
<details>

 * trimmode copy/iOS Unified 64-bits - simulator/Debug [dotnet]: LaunchTimedOut
 * dont link/iOS Unified 64-bits - simulator/Release: LaunchTimedOut
 * link all/iOS Unified 64-bits - simulator/Release: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_linker-3/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_linker-3&api-version=6.0&$format=zip)

### :x: monotouch tests [attempt 3]

<summary>1 tests failed, 22 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_monotouch-3/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_monotouch-3&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [attempt 3] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_framework-3/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_framework-3&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_interdependent_binding_projects-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-2&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221012.10/6816798//simulator_xcframework-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6816798/artifacts?artifactName=HtmlReport-simulator_xcframework-2&api-version=6.0&$format=zip)
:white_check_mark: xt [...]

2022-10-13 15:35 UTC, merged