[DevOps] Fix missed variables format.
xamarin/xamarin-macios pull request #16634
Opened 2022-11-08 00:30 UTC by mandel-macaque

2022-11-08 00:30 UTC, mandel-macaque commented
/sudo backport xcode14.1

2022-11-08 00:30 UTC, mandel-macaque commented
/sudo backport release/6.0.4xx-xcode14.1

2022-11-08 00:30 UTC, mandel-macaque commented
/sudo backport release/7.0.1xx

2022-11-08 00:31 UTC, dalexsoto approved these changes

2022-11-08 00:31 UTC, vs-mobiletools-engineering-service2 commented
Backport Job to branch **xcode14.1** Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=6932590)

2022-11-08 00:32 UTC, vs-mobiletools-engineering-service2 commented
Backport Job to branch **release/6.0.4xx-xcode14.1** Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=6932592)

2022-11-08 00:33 UTC, vs-mobiletools-engineering-service2 commented
Backport Job to branch **release/7.0.1xx** Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=6932599)

2022-11-08 00:33 UTC, vs-mobiletools-engineering-service2 commented
Oh no! Backport failed! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6932592 for more details.

2022-11-08 05:10 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/67822c95ded2880b57d39e7a57144d89) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/b780cf027c05d0ca405a9341abb76715) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/a71ddcb8bd952b47d2ef382549993879) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/e11545de6b6121f6762ff94371a9ce14) (No breaking changes)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/e2a6a6c55051aebff46c004fe928413c) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/471eddb491e266c2c85ca2dd7a0b7d69) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/206a25ac1a2588bc3c36a7a055337fab) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/f0bdc4e93445c46184c87d129deb8017) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/837f586e91a290dbd34ca4a2780a95c4) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/749ec7e64b0e5be7577b07ff745c3274) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/a207a52c0d8983ce3f08a972d1d062d0) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/c1cc56cace9c556282712e86c282edcc) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/6f2f8b91c5977810aa559ae0010fb7f6)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/2a0183f09e98114fff5c94f6c59e22c3)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/bdbfffb5eb84889489ea801c87ea1f35)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.2/6932586-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/5757b0f3ea3ab044e6937dc6a6f204fc)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6932586&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [38fbd6ae29ce3ad37fd5ede06045d2117cfc79ed](https://github.com/xamarin/xamarin-macios/pull/16634/commits/38fbd6ae29ce3ad37fd5ede06045d2117cfc79ed)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-11-08 05:15 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6932586&view=ms.vss-test-web.test-result-details) on Agent XAMBOT-1178.Monterey'
Hash: [38fbd6ae29ce3ad37fd5ede06045d2117cfc79ed](https://github.com/xamarin/xamarin-macios/pull/16634/commits/38fbd6ae29ce3ad37fd5ede06045d2117cfc79ed)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-11-08 05:19 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6932586&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [38fbd6ae29ce3ad37fd5ede06045d2117cfc79ed](https://github.com/xamarin/xamarin-macios/pull/16634/commits/38fbd6ae29ce3ad37fd5ede06045d2117cfc79ed)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-11-08 06:58 UTC, rolfbjarne requested changes
I'm assuming this is trying to fix the broken package upload:

> Artifacts were not provided.

but it didn't...

2022-11-08 09:53 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 5 tests failed, 218 tests passed.

## Failures

### :x: bcl tests

<summary>5 tests failed, 64 tests passed.</summary>
<details>

 * [NUnit] Mono Mac OS X BCL tests group 3/Mac Full/Debug: Failed (Test run failed.
Tests run: 11328 Passed: 10552 Inconclusive: 0 Failed: 1 Ignored: 98)
 * [NUnit] Mono Mac OS X BCL tests group 3/Mac Modern/Debug: Failed (Test run failed.
Tests run: 8755 Passed: 8174 Inconclusive: 0 Failed: 1 Ignored: 46)
 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: Failed
 * [NUnit] Mono BCL tests group 2/tvOS - simulator/Debug: Failed
 * [NUnit] Mono CorlibTests/watchOS 32-bits - simulator/Debug: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.2/6932586//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6932586/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azu [...]

2022-11-08 16:30 UTC, tj-devel709 approved these changes

2022-11-08 16:37 UTC, rolfbjarne commented on tools/devops/automation/templates/main-stage.yml
> +      azureContainer: ${{ parameters..azureContainer }}
Typo?

```suggestion
      azureContainer: ${{ parameters.azureContainer }}
```

2022-11-08 16:38 UTC, rolfbjarne commented on tools/devops/automation/templates/main-stage.yml
> +      azureStorage:  ${{ paramenters.azureStorage }}
Typo?

```suggestion
      azureStorage:  ${{ parameters.azureStorage }}
```

2022-11-08 21:41 UTC, mandel-macaque commented on tools/devops/automation/templates/main-stage.yml
> +      azureContainer: ${{ variables.azureContainer }}
```suggestion
      azureStorage:  ${{ parameters.azureStorage }}
      azureContainer: ${{ parameters.azureContainer }}
```

2022-11-09 04:12 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.1.539-ci.pr.gh16634.pkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Bundle.16.1.539-ci.pr.gh16634.pkg)
* [Microsoft.iOS.Ref.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Ref.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Runtime.ios-arm.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Runtime.ios-arm64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Runtime.iossimulator-x64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Runtime.iossimulator-x86.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Sdk.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Sdk.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Templates.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Templates.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.iOS.Windows.Sdk.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.1.539-ci.pr.gh16634.pkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.MacCatalyst.Bundle.16.1.539-ci.pr.gh16634.pkg)
* [Microsoft.MacCatalyst.Ref.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.MacCatalyst.Ref.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.MacCatalyst.Sdk.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.MacCatalyst.Templates.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.MacCatalyst.Templates.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.macOS.Bundle.13.0.1094-ci.pr.gh16634.pkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.macOS.Bundle.13.0.1094-ci.pr.gh16634.pkg)
* [Microsoft.macOS.Ref.13.0.1094-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.macOS.Ref.13.0.1094-ci.pr.gh16634.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.0.1094-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.macOS.Runtime.osx-arm64.13.0.1094-ci.pr.gh16634.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.0.1094-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.macOS.Runtime.osx-x64.13.0.1094-ci.pr.gh16634.nupkg)
* [Microsoft.macOS.Sdk.13.0.1094-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.macOS.Sdk.13.0.1094-ci.pr.gh16634.nupkg)
* [Microsoft.macOS.Templates.13.0.1094-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.macOS.Templates.13.0.1094-ci.pr.gh16634.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.0.1094-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.0.1094-ci.pr.gh16634.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.NET.Workload.iOS.16.1.539-ci.pr.gh16634.msi](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.NET.Workload.iOS.16.1.539-ci.pr.gh16634.msi)
* [Microsoft.tvOS.Bundle.16.1.539-ci.pr.gh16634.pkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.tvOS.Bundle.16.1.539-ci.pr.gh16634.pkg)
* [Microsoft.tvOS.Ref.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.tvOS.Ref.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.tvOS.Sdk.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.tvOS.Sdk.16.1.539-ci.pr.gh16634.nupkg)
* [Microsoft.tvOS.Templates.16.1.539-ci.pr.gh16634.nupkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/Microsoft.tvOS.Templates.16.1.539-ci.pr.gh16634.nupkg)
* [xamarin.ios-16.1.1.412.pkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/xamarin.ios-16.1.1.412.pkg)
* [xamarin.mac-9.0.0.412.pkg](https://dl.internalx.com/wrench/merge/4307843ee5a221ecbeed8d05814d997737777304/6937181/package/xamarin.mac-9.0.0.412.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6937181&view=ms.vss-test-web.test-result-deta [...]

2022-11-09 04:18 UTC, vs-mobiletools-engineering-service2 commented
## :heavy_exclamation_mark: API diff for current PR / commit (Breaking changes)

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/68548c658997e1909e558c018f227e04) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/97123957ea681587245a00565d7a3eea) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/89740e43e992fb39cb9ee7ca2ca8f401) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/7e63f6d5206419409e2badf9450fc115) (No breaking changes)

</details>


<!-- BreakingChangesDetected -->


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/016c29c90d19b9ab486e1da8922c1a08) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/5953fa69c2c7b08bd55bb342ecd9e704) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/4c76833372b80bdac5b7334ed58875bb) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/86c5808ce78d52e44c0c3b905aadd8f5) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/788db043824f566b358c2a9f29df36f2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/c69475f72d6874a879fcee264978f953) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/4fd8845aac366bb9f599dd357999c8c6) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/b21bc2915acdb1d47e532e68fcaa4329) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/63b2d63ce4ce0974676a0b00b1e2cd44)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/b4659048cac123391e272afb5e082a9c)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/2e80057d20b67564d7d860fd8d3b0dd7)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221108.40/6937181-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/c1dfc39bad6f718143b3449d2488358b)

</details>


<!-- BreakingChangesDetected -->


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6937181&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [132ef258a4f149a5fa85e48d5d82fb9a7a740309](https://github.com/xamarin/xamarin-macios/pull/16634/commits/132ef258a4f149a5fa85e48d5d82fb9a7a740309)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-11-09 04:20 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=6937181&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [132ef258a4f149a5fa85e48d5d82fb9a7a740309](https://github.com/xamarin/xamarin-macios/pull/16634/commits/132ef258a4f149a5fa85e48d5d82fb9a7a740309)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-11-09 06:44 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

1 tests crashed, 0 tests failed, 216 tests passed.

## Failures

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221108.40/6937181//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/6937181/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6937181&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/16634/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-11-09 07:27 UTC, vs-mobiletools-engineering-service2 commented
### :fire: Failed to compute test summaries on VSTS: simulator tests :fire:

Failed to compute test summaries: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host...

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=6937181&view=ms.vss-test-web.test-result-details) on Agent 
Merge 132ef258a4f149a5fa85e48d5d82fb9a7a740309 into 968ebbf4d37bc816b5b09b633eb646a5197e9aba

2022-11-09 12:13 UTC, rolfbjarne approved these changes

2022-11-09 13:52 UTC, merged