[dotnet] security string pinvokes
xamarin/xamarin-macios pull request #17054
Opened 2022-12-14 20:33 UTC by stephen-hawley

- Renamed NativeString.cs -> TransientString.cs
- Added an encoding parameter for available Marshal methods
- Added encoding in the ctor
- Handled security strings

2022-12-14 20:43 UTC, rolfbjarne requested changes

2022-12-14 21:07 UTC, stephen-hawley commented on src/ObjCRuntime/TransientString.cs
> +			ptr = (Encode (encoding)) (str);
I was being clever.

2022-12-14 21:10 UTC, dalexsoto approved these changes
After Rolf's comment is addressed.

2022-12-14 21:35 UTC, rolfbjarne approved these changes

2022-12-14 23:24 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/21ca853e40bbd0c4fd0ffd9ef6e51bff) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/d829d2139910e4dcd351103ca847e3b2) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/00f462972860a8dfd999aa1b2442d0e0) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/af4c0a9dc1fd72b09f39d0c3351336e4) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/1fd5d6905c07977f74cef3419eb4871b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/53a95b5b43814a9adeea235421774f35) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/905594787ecec0b8c2c97590a173b6e3) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/dd699ceccdb0a407861b970cdd8258b7) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/279213926d46250b04d359b136bbb7c6)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/6e1babd3cdd7d8ae9d12b5e22c5a3ec4)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/c67c80d33d0badd0baab5394ec31497a)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/4a7e61d0db8d297260c9753c401d6fdf)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20221214.32/7097143-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/84595010068298a82385740c466d6112) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7097143&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [729e56f5be7efd435f908592616e97265810a4f5](https://github.com/xamarin/xamarin-macios/pull/17054/commits/729e56f5be7efd435f908592616e97265810a4f5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-12-14 23:36 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7097143&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [729e56f5be7efd435f908592616e97265810a4f5](https://github.com/xamarin/xamarin-macios/pull/17054/commits/729e56f5be7efd435f908592616e97265810a4f5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-12-15 02:37 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 1 tests failed, 222 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * [xUnit] Mono SystemXunit/tvOS - simulator/Debug: Crashed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 23 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20221214.32/7097143//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7097143/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7097143&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [729e56f5be7efd435f908592616e97265810a4f5](https://github.com/xamarin/xamarin-macios/pull/17054/commits/729e56f5be7efd435f908592616e97265810a4f5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2022-12-15 14:20 UTC, merged