[tools] Add diagnostics when a native library turns off -dead_link support.
xamarin/xamarin-macios pull request #17361
Opened 2023-01-24 15:40 UTC by rolfbjarne

2023-01-24 16:23 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7232325&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [$(GIT_HASH)](https://github.com/xamarin/xamarin-macios/pull/17361/commits/$(GIT_HASH))  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-24 18:15 UTC, mandel-macaque requested changes
; missing

2023-01-24 18:15 UTC, mandel-macaque commented on tools/common/Assembly.cs
> +				Driver.Log (3, $"The library '{metadata.LibraryName}', shipped with the assembly '{FullName}', sets SmartLink=false, which will disable passing -dead_strip to the native linker (and make the app
```suggestion
				Driver.Log (3, $"The library '{metadata.LibraryName}', shipped with the assembly '{FullName}', sets SmartLink=false, which will disable passing -dead_strip to the native linker (and make the app bigger).");
```

2023-01-24 18:39 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7232325&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [$(GIT_HASH)](https://github.com/xamarin/xamarin-macios/pull/17361/commits/$(GIT_HASH))  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-24 18:55 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7232325&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [5e4acb7957c31bcbd5c602ca3f78f42b704ba598](https://github.com/xamarin/xamarin-macios/pull/17361/commits/5e4acb7957c31bcbd5c602ca3f78f42b704ba598)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-25 12:20 UTC, mandel-macaque approved these changes

2023-01-26 04:15 UTC, dalexsoto approved these changes

2023-01-26 07:25 UTC, rolfbjarne commented
/azp run

2023-01-26 08:02 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7243075&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [$(GIT_HASH)](https://github.com/xamarin/xamarin-macios/pull/17361/commits/$(GIT_HASH))  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-26 08:03 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7243075&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [$(GIT_HASH)](https://github.com/xamarin/xamarin-macios/pull/17361/commits/$(GIT_HASH))  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-26 08:08 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7243075&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4b913cadf16d0597dff77d666296839959dce74b](https://github.com/xamarin/xamarin-macios/pull/17361/commits/4b913cadf16d0597dff77d666296839959dce74b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-26 10:57 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/c326f860fc40036e54263078e9816b1d) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/68d659c8658f239c97dcfb7102ecd301) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/c56c8aa75bab740e3331115baa41d54c) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/dff0b4dfd566a886a616ae025d1ad196) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/68964b3b6f0abfdbb6c29d8e7eae0208) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/236f2ee171dcd45a94e09e59af805bf8) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/d3b85c131e61352d269cd1c3226decab) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/55ae1a90ac3449864031a8cb66aaff04) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/13852147dc68d8acf8a37405e0b52bd6)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/d6cb9e3fb03929cd81193e295fa6887a)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/0386e3983e0d87eb49239bcf4b224b1b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230126.4/7243330-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/8adae4d103d0661adf555ece0cacd246)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7243330&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4d1ba37e7184bb390f958051e1f4d93968b345e6](https://github.com/xamarin/xamarin-macios/pull/17361/commits/4d1ba37e7184bb390f958051e1f4d93968b345e6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-26 11:08 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7243330&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4d1ba37e7184bb390f958051e1f4d93968b345e6](https://github.com/xamarin/xamarin-macios/pull/17361/commits/4d1ba37e7184bb390f958051e1f4d93968b345e6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-26 11:11 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.105-ci.pr.gh17361.pkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Bundle.16.2.105-ci.pr.gh17361.pkg)
* [Microsoft.iOS.Ref.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Ref.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Runtime.ios-arm.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Runtime.ios-arm64.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Sdk.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Sdk.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Templates.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Templates.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.iOS.Windows.Sdk.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.105-ci.pr.gh17361.pkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.MacCatalyst.Bundle.16.2.105-ci.pr.gh17361.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.MacCatalyst.Ref.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.MacCatalyst.Sdk.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.MacCatalyst.Templates.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.macOS.Bundle.13.1.105-ci.pr.gh17361.pkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.macOS.Bundle.13.1.105-ci.pr.gh17361.pkg)
* [Microsoft.macOS.Ref.13.1.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.macOS.Ref.13.1.105-ci.pr.gh17361.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.macOS.Runtime.osx-arm64.13.1.105-ci.pr.gh17361.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.macOS.Runtime.osx-x64.13.1.105-ci.pr.gh17361.nupkg)
* [Microsoft.macOS.Sdk.13.1.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.macOS.Sdk.13.1.105-ci.pr.gh17361.nupkg)
* [Microsoft.macOS.Templates.13.1.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.macOS.Templates.13.1.105-ci.pr.gh17361.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.105-ci.pr.gh17361.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.105-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.105-ci.pr.gh17361.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.893-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.893-ci.pr.gh17361.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.105-ci.pr.gh17361.msi](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.NET.Workload.iOS.16.2.105-ci.pr.gh17361.msi)
* [Microsoft.tvOS.Bundle.16.1.893-ci.pr.gh17361.pkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.tvOS.Bundle.16.1.893-ci.pr.gh17361.pkg)
* [Microsoft.tvOS.Ref.16.1.893-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.tvOS.Ref.16.1.893-ci.pr.gh17361.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.893-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.893-ci.pr.gh17361.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.893-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.893-ci.pr.gh17361.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.893-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.893-ci.pr.gh17361.nupkg)
* [Microsoft.tvOS.Sdk.16.1.893-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.tvOS.Sdk.16.1.893-ci.pr.gh17361.nupkg)
* [Microsoft.tvOS.Templates.16.1.893-ci.pr.gh17361.nupkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/Microsoft.tvOS.Templates.16.1.893-ci.pr.gh17361.nupkg)
* [xamarin.ios-16.2.1.105.pkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/xamarin.ios-16.2.1.105.pkg)
* [xamarin.mac-9.1.1.105.pkg](https://dl.internalx.com/wrench/merge/e1358c2a3da75f8d1c7de7d271dde1aac9562be4/7243330/package/xamarin.mac-9.1.1.105.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7243330&view=ms.vss-test-web.test-result-details) on Agent  [...]

2023-01-26 15:06 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 11 tests failed, 214 tests passed.

## Failures

### :x: bcl tests

<summary>11 tests failed, 58 tests passed.</summary>
<details>

 * [NUnit] Mono BCL tests group 1/tvOS - simulator/Debug: LaunchTimedOut
 * [NUnit] Mono BCL tests group 2/tvOS - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono BCL tests group 3/tvOS - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono BCL tests group 4/tvOS - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono BCL tests group 5/tvOS - simulator/Debug: LaunchTimedOut
 * mscorlib Part 1/tvOS - simulator/Debug: LaunchTimedOut
 * mscorlib Part 2/tvOS - simulator/Debug: LaunchTimedOut
 * mscorlib Part 3/tvOS - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemCoreXunit Part 1/tvOS - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemCoreXunit Part 2/tvOS - simulator/Debug: LaunchTimedOut
 * [xUnit] Mono SystemXunit/tvOS - simulator/Debug: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7243330/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230126.4/7243330//simulator_xtro-1/; [...]

2023-01-26 15:15 UTC, rolfbjarne commented
Test failures are unrelated (https://github.com/xamarin/maccore/issues/2450).

2023-01-26 15:16 UTC, merged