Merge main to xcode14.2
xamarin/xamarin-macios pull request #17390
Opened 2023-01-28 02:45 UTC by mandel-macaque

We are behind and this was going to be a problem moving fwd. Had to fix a small number of merge issues.

2023-01-28 04:14 UTC, vs-mobiletools-engineering-service2 commented
:fire: Failed to compare API and create generator diff :fire:

Failed to update apidiff references


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7253327&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d4027535b4ac766d310104397954313e82ca6c6c](https://github.com/xamarin/xamarin-macios/pull/17390/commits/d4027535b4ac766d310104397954313e82ca6c6c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-28 04:28 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.768-ci.pr.gh17390.pkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Bundle.16.2.768-ci.pr.gh17390.pkg)
* [Microsoft.iOS.Ref.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Ref.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Runtime.ios-arm.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Runtime.ios-arm64.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Sdk.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Sdk.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Templates.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Templates.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.iOS.Windows.Sdk.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.768-ci.pr.gh17390.pkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.MacCatalyst.Bundle.16.2.768-ci.pr.gh17390.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.MacCatalyst.Ref.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.MacCatalyst.Sdk.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.MacCatalyst.Templates.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.macOS.Bundle.13.1.768-ci.pr.gh17390.pkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.macOS.Bundle.13.1.768-ci.pr.gh17390.pkg)
* [Microsoft.macOS.Ref.13.1.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.macOS.Ref.13.1.768-ci.pr.gh17390.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.macOS.Runtime.osx-arm64.13.1.768-ci.pr.gh17390.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.macOS.Runtime.osx-x64.13.1.768-ci.pr.gh17390.nupkg)
* [Microsoft.macOS.Sdk.13.1.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.macOS.Sdk.13.1.768-ci.pr.gh17390.nupkg)
* [Microsoft.macOS.Templates.13.1.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.macOS.Templates.13.1.768-ci.pr.gh17390.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.768-ci.pr.gh17390.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.768-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.768-ci.pr.gh17390.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.928-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.928-ci.pr.gh17390.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.768-ci.pr.gh17390.msi](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.NET.Workload.iOS.16.2.768-ci.pr.gh17390.msi)
* [Microsoft.tvOS.Bundle.16.1.928-ci.pr.gh17390.pkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.tvOS.Bundle.16.1.928-ci.pr.gh17390.pkg)
* [Microsoft.tvOS.Ref.16.1.928-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.tvOS.Ref.16.1.928-ci.pr.gh17390.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.928-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.928-ci.pr.gh17390.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.928-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.928-ci.pr.gh17390.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.928-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.928-ci.pr.gh17390.nupkg)
* [Microsoft.tvOS.Sdk.16.1.928-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.tvOS.Sdk.16.1.928-ci.pr.gh17390.nupkg)
* [Microsoft.tvOS.Templates.16.1.928-ci.pr.gh17390.nupkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/Microsoft.tvOS.Templates.16.1.928-ci.pr.gh17390.nupkg)
* [xamarin.ios-16.2.0.768.pkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/xamarin.ios-16.2.0.768.pkg)
* [xamarin.mac-9.1.0.768.pkg](https://dl.internalx.com/wrench/merge/522cc90dca13ed5b64f7703d8a1b07fd1aea3245/7253327/package/xamarin.mac-9.1.0.768.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7253327&view=ms.vss-test-web.test-result-details) on Agent  [...]

2023-01-28 04:30 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7253327&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d4027535b4ac766d310104397954313e82ca6c6c](https://github.com/xamarin/xamarin-macios/pull/17390/commits/d4027535b4ac766d310104397954313e82ca6c6c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-28 08:19 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 1 tests failed, 224 tests passed.

## Failures

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230128.1/7253327//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7253327/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7253327&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d4027535b4ac766d310104397954313e82ca6c6c](https://github.com/xamarin/xamarin-macios/pull/17390/commits/d4027535b4ac766d310104397954313e82ca6c6c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-01-30 07:21 UTC, rolfbjarne requested changes
We branched xcode14.2 from xcode14.1, so it's expected that xcode14.2 is behind main. Which scenarios are going to be a problem?

2023-01-30 15:33 UTC, mandel-macaque commented
@Rolf we have a number of merge issues do to the dotnet format. But those are solvable, we can talk about it in a standup. Perse I do not see any "logical" issues.

2023-01-30 15:35 UTC, Rolf commented
@mandel-macaque pls check username. not rolf. u need @rolfbjarne

2023-01-30 21:47 UTC, closed without merging