[dotnet] UIMain changes
xamarin/xamarin-macios pull request #17611
Opened 2023-02-23 21:33 UTC by stephen-hawley

handling of string array for args

2023-02-23 23:03 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* dontlink
* introspection
* linksdk
* linkall
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7375126&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [133605cb3a0b30935f16362539add1ae60a5491d](https://github.com/xamarin/xamarin-macios/pull/17611/commits/133605cb3a0b30935f16362539add1ae60a5491d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-23 23:06 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* dontlink
* introspection
* linksdk
* linkall
* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7375126&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [133605cb3a0b30935f16362539add1ae60a5491d](https://github.com/xamarin/xamarin-macios/pull/17611/commits/133605cb3a0b30935f16362539add1ae60a5491d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-23 23:09 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/bc8ad4db9f78190afc0c5258d416a19f) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/1c328730522c4d74920fa9783aeff317) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/3bc65cbdc8949ad83f6c7f05e308268f) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/5236a39c78c5f8872c4e11e5459d59e1) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/fd692bbe74efeb9b36eba7d112055d88) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/90cdddee06362c64d5421211f538227a) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/7b9f72cd8d1cad6c9fd62997327f2dda) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/aed865cf0cd90e3901b780de254a98cc) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/1e56ab3fe49baa3a1c2bee6caf8428e3)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/c43ddb2c9b83b9fbb64bb348b2d08921)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/5a70716db6c1e7de9ffcac906f5e1386)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230223.24/7375126-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/a9dc3a5e340e48b8d954b75c89df5e0f)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7375126&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [133605cb3a0b30935f16362539add1ae60a5491d](https://github.com/xamarin/xamarin-macios/pull/17611/commits/133605cb3a0b30935f16362539add1ae60a5491d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-23 23:27 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.220-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Bundle.16.2.220-ci.pr.gh17611.pkg)
* [Microsoft.iOS.Ref.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Ref.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Runtime.ios-arm.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Runtime.ios-arm64.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Sdk.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Sdk.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Templates.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Templates.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.iOS.Windows.Sdk.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.220-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.MacCatalyst.Bundle.16.2.220-ci.pr.gh17611.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.MacCatalyst.Ref.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.MacCatalyst.Sdk.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.MacCatalyst.Templates.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Bundle.13.1.220-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.macOS.Bundle.13.1.220-ci.pr.gh17611.pkg)
* [Microsoft.macOS.Ref.13.1.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.macOS.Ref.13.1.220-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.macOS.Runtime.osx-arm64.13.1.220-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.macOS.Runtime.osx-x64.13.1.220-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Sdk.13.1.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.macOS.Sdk.13.1.220-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Templates.13.1.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.macOS.Templates.13.1.220-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.220-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.220-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.220-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1008-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1008-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.220-ci.pr.gh17611.msi](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.NET.Workload.iOS.16.2.220-ci.pr.gh17611.msi)
* [Microsoft.tvOS.Bundle.16.1.1008-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.tvOS.Bundle.16.1.1008-ci.pr.gh17611.pkg)
* [Microsoft.tvOS.Ref.16.1.1008-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.tvOS.Ref.16.1.1008-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.1008-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.1008-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1008-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1008-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1008-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1008-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Sdk.16.1.1008-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.tvOS.Sdk.16.1.1008-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Templates.16.1.1008-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/Microsoft.tvOS.Templates.16.1.1008-ci.pr.gh17611.nupkg)
* [xamarin.ios-16.2.1.220.pkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/xamarin.ios-16.2.1.220.pkg)
* [xamarin.mac-9.1.1.220.pkg](https://dl.internalx.com/wrench/merge/c34e0b8b175a891917a01ab24219ba87f2a3a26a/7375126/package/xamarin.mac-9.1.1.220.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7375126&view=ms.vss-test-web.test-result-de [...]

2023-02-24 02:34 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

1 tests crashed, 74 tests failed, 149 tests passed.

## Failures

### :x: fsharp tests

<summary>3 tests failed, 4 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * fsharp/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * fsharp/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230223.24/7375126//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7375126/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>3 tests failed, 5 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * framework-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * framework-test/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230223.24/7375126//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7375126/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>3 tests failed, 4 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * interdependent-binding-projects/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * interdependent-binding-projects/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230223.24/7375126//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7375126/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>3 tests failed, 5 tests passed.</summary>
<details>

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * introspection/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230223.24/7375126//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7375126/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>30 tests failed, 35 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * dont link/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * dont link/iOS Unified 64-bits - simulator/Release [dotnet]: Crashed
 * dont link/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
 * dont link/tvOS - simulator/Release [dotnet]: LaunchTimedOut
 * link sdk/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * link sdk/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * link sdk/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * link sdk/iOS Unified 64-bits - simulator/Release [dotnet]: Crashed
 * link sdk/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
 * link sdk/tvOS - simulator/Release [dotnet]: LaunchTimedOut
 * link all/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * link all/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * link all/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * link all/iOS Unified 64-bits - simulator/Release [dotnet]: Crashed
 * link all/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
 * link all/tvOS - simulator/Release [dotnet]: LaunchTimedOut
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * trimmode copy/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * trimmode copy/iOS Unified 64-bits - simulator/Release [dotnet]: Crashed
 * trimmode copy/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
 * trimmode copy/tvOS - simulator/Release [dotnet]: LaunchTimedOut
 * trimmode link/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * trimmode link/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * trimmode link/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * trimmode link/iOS Unified 64-bits - simulator/Release [dotnet]: Crashed
 * trimmode link/tvOS - simulator/Debug [dotnet]: LaunchTimedOut
 * trimmode link/tvOS - simulator/Release [dotnet]: LaunchTimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230223.24/7375126//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7375126/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: mmp tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * mmptest/macOS/Debug: Failed (Execution failed with exit code 2)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230223.24/7375126//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7375126/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>25 tests failed, 0 tests passed.</summary>
<details>

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 139).
Test run crashed)
 * monotouch-test/Mac [dotnet]/Debug (static registrar) [dotnet]: Failed (Test run crashed (exit code: 139).
Test run crashed)
 * monotouch-test/Mac [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 139).
Test run crashed)
 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * monotouch-test/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 255).
No test log file was produced)
 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Crashed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Crashed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Crashed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Crashed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
 * monotouch-test/tvO [...]

2023-02-24 08:54 UTC, rolfbjarne requested changes

2023-02-24 08:54 UTC, rolfbjarne commented on src/ObjCRuntime/TransientString.cs
> +				Marshal.WriteIntPtr (ptrArr + 4 * i, new TransientString (arr [i], encoding));
```suggestion
				Marshal.WriteIntPtr (ptrArr + IntPtr.Size * i, new TransientString (arr [i], encoding));
```

2023-02-24 08:54 UTC, rolfbjarne commented on src/ObjCRuntime/TransientString.cs
> +				Marshal.FreeHGlobal (Marshal.ReadIntPtr (ptrArr + 4 * i));
```suggestion
				Marshal.FreeHGlobal (Marshal.ReadIntPtr (ptrArr + IntPtr.Size * i));
```

2023-02-24 08:54 UTC, rolfbjarne commented on src/UIKit/UIApplication.cs
> +			TransientString.FreeStringArray (strArr, argc);
This makes sure we don't crash if `argc` is wrong:

```suggestion
			TransientString.FreeStringArray (strArr, argv?.Length ?? 0);
```

2023-02-24 08:54 UTC, rolfbjarne commented on src/UIKit/UIApplication.cs
> +		extern static int xamarin_UIApplicationMain (int argc, /* char[]* */ IntPtr argv, /* NSString* */ IntPtr principalClassName, /* NSString* */ IntPtr delegateClassName, out IntPtr gchandle);
Is there any reason we can't always use the new code (i.e. don't check for NET)?

2023-02-24 15:40 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Tests timed out

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7379628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [85a0daf3de93f4db4315380ec9b65f967736fa76](https://github.com/xamarin/xamarin-macios/pull/17611/commits/85a0daf3de93f4db4315380ec9b65f967736fa76)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-24 15:41 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Tests timed out

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7379628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [85a0daf3de93f4db4315380ec9b65f967736fa76](https://github.com/xamarin/xamarin-macios/pull/17611/commits/85a0daf3de93f4db4315380ec9b65f967736fa76)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-24 15:41 UTC, rolfbjarne approved these changes

2023-02-24 17:20 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7379813&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e74ecb396306736ee0dfd18dfb710a6ac204bec1](https://github.com/xamarin/xamarin-macios/pull/17611/commits/e74ecb396306736ee0dfd18dfb710a6ac204bec1)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-24 17:26 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.222-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Bundle.16.2.222-ci.pr.gh17611.pkg)
* [Microsoft.iOS.Ref.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Ref.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Runtime.ios-arm.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Runtime.ios-arm64.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Sdk.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Sdk.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Templates.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Templates.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.iOS.Windows.Sdk.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.222-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.MacCatalyst.Bundle.16.2.222-ci.pr.gh17611.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.MacCatalyst.Ref.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.MacCatalyst.Sdk.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.MacCatalyst.Templates.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Bundle.13.1.222-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.macOS.Bundle.13.1.222-ci.pr.gh17611.pkg)
* [Microsoft.macOS.Ref.13.1.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.macOS.Ref.13.1.222-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.macOS.Runtime.osx-arm64.13.1.222-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.macOS.Runtime.osx-x64.13.1.222-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Sdk.13.1.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.macOS.Sdk.13.1.222-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Templates.13.1.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.macOS.Templates.13.1.222-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.222-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.222-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.222-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1010-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1010-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.222-ci.pr.gh17611.msi](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.NET.Workload.iOS.16.2.222-ci.pr.gh17611.msi)
* [Microsoft.tvOS.Bundle.16.1.1010-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.tvOS.Bundle.16.1.1010-ci.pr.gh17611.pkg)
* [Microsoft.tvOS.Ref.16.1.1010-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.tvOS.Ref.16.1.1010-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.1010-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.1010-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1010-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1010-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1010-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1010-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Sdk.16.1.1010-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.tvOS.Sdk.16.1.1010-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Templates.16.1.1010-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/Microsoft.tvOS.Templates.16.1.1010-ci.pr.gh17611.nupkg)
* [xamarin.ios-16.2.1.222.pkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/xamarin.ios-16.2.1.222.pkg)
* [xamarin.mac-9.1.1.222.pkg](https://dl.internalx.com/wrench/merge/89bbdee4044bf67869115b459e77132d1a1fe778/7379813/package/xamarin.mac-9.1.1.222.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7379813&view=ms.vss-test-web.test-result-de [...]

2023-02-24 17:29 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* xammac_tests
* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7379813&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e74ecb396306736ee0dfd18dfb710a6ac204bec1](https://github.com/xamarin/xamarin-macios/pull/17611/commits/e74ecb396306736ee0dfd18dfb710a6ac204bec1)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-24 20:55 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/193a07d16f6c5436a6dae5cfda24a02e) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/86ffcbc5abaa00fe450ea83f96208a0e) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/dbbe44f9b44a9b75830fb7f812023c0d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/f9dcbe1ddbde39372cec901a2f272bce) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/9fd93c78ff543e950802aa856b7bdef1) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/78641c50ceaa00e6b185654404257bdf) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/764c276c5437e4b81eb2d54be0939af4) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/5bb923f76823465efc6bec0096f3be9c) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/dde83fcae03ea4c85714f40840de748c)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/6d3f4c2224e0f73eea18112df81dfbce)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/36522c8202332b04118b689b29fa0f06)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230224.19/7380904-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/5aa15e9143ce93606d9d3ccbaa7a8804)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7380904&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7](https://github.com/xamarin/xamarin-macios/pull/17611/commits/d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-24 20:57 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7380904&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7](https://github.com/xamarin/xamarin-macios/pull/17611/commits/d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-24 20:57 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* xammac_tests


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7380904&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7](https://github.com/xamarin/xamarin-macios/pull/17611/commits/d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-24 21:07 UTC, dalexsoto approved these changes

2023-02-24 21:22 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.226-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Bundle.16.2.226-ci.pr.gh17611.pkg)
* [Microsoft.iOS.Ref.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Ref.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Runtime.ios-arm.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Runtime.ios-arm64.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Sdk.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Sdk.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Templates.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Templates.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.iOS.Windows.Sdk.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.226-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.MacCatalyst.Bundle.16.2.226-ci.pr.gh17611.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.MacCatalyst.Ref.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.MacCatalyst.Sdk.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.MacCatalyst.Templates.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Bundle.13.1.226-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.macOS.Bundle.13.1.226-ci.pr.gh17611.pkg)
* [Microsoft.macOS.Ref.13.1.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.macOS.Ref.13.1.226-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.macOS.Runtime.osx-arm64.13.1.226-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.macOS.Runtime.osx-x64.13.1.226-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Sdk.13.1.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.macOS.Sdk.13.1.226-ci.pr.gh17611.nupkg)
* [Microsoft.macOS.Templates.13.1.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.macOS.Templates.13.1.226-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.226-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.226-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.226-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1014-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1014-ci.pr.gh17611.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.226-ci.pr.gh17611.msi](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.NET.Workload.iOS.16.2.226-ci.pr.gh17611.msi)
* [Microsoft.tvOS.Bundle.16.1.1014-ci.pr.gh17611.pkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.tvOS.Bundle.16.1.1014-ci.pr.gh17611.pkg)
* [Microsoft.tvOS.Ref.16.1.1014-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.tvOS.Ref.16.1.1014-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.1014-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.1014-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1014-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1014-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1014-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1014-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Sdk.16.1.1014-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.tvOS.Sdk.16.1.1014-ci.pr.gh17611.nupkg)
* [Microsoft.tvOS.Templates.16.1.1014-ci.pr.gh17611.nupkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/Microsoft.tvOS.Templates.16.1.1014-ci.pr.gh17611.nupkg)
* [xamarin.ios-16.2.1.226.pkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/xamarin.ios-16.2.1.226.pkg)
* [xamarin.mac-9.1.1.226.pkg](https://dl.internalx.com/wrench/merge/f55340e030d7613afeb831e842e71ad628567be6/7380904/package/xamarin.mac-9.1.1.226.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7380904&view=ms.vss-test-web.test-result-de [...]

2023-02-24 22:43 UTC, haritha-mohan approved these changes

2023-02-24 23:20 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

2 tests crashed, 0 tests failed, 216 tests passed.

## Failures

### :x: fsharp tests

:fire: Failed catastrophically on VSTS: simulator tests - fsharp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7380904&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7](https://github.com/xamarin/xamarin-macios/pull/17611/commits/d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-27 09:45 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 225 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_fsharp-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_fsharp-2&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_generator-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_generator-2&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230224.19/7380904//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7380904/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7380904&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7](https://github.com/xamarin/xamarin-macios/pull/17611/commits/d9b9e9af9ddba59fc43a7e2a2d137c374024a8b7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-27 15:23 UTC, merged