[dotnet] AppKit pinvokes
xamarin/xamarin-macios pull request #17644
Opened 2023-02-28 21:01 UTC by stephen-hawley

2023-02-28 21:15 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7397704&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/17644/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-28 22:44 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7397704&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9aba3baaf52e6029433f6e44e851eed29e36a4d4](https://github.com/xamarin/xamarin-macios/pull/17644/commits/9aba3baaf52e6029433f6e44e851eed29e36a4d4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-28 22:47 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* xammac_tests


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7397704&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9aba3baaf52e6029433f6e44e851eed29e36a4d4](https://github.com/xamarin/xamarin-macios/pull/17644/commits/9aba3baaf52e6029433f6e44e851eed29e36a4d4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-02-28 22:53 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.228-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Bundle.16.2.228-ci.pr.gh17644.pkg)
* [Microsoft.iOS.Ref.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Ref.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Runtime.ios-arm.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Runtime.ios-arm64.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Sdk.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Sdk.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Templates.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Templates.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.iOS.Windows.Sdk.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.228-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.MacCatalyst.Bundle.16.2.228-ci.pr.gh17644.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.MacCatalyst.Ref.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.MacCatalyst.Sdk.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.MacCatalyst.Templates.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Bundle.13.1.228-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.macOS.Bundle.13.1.228-ci.pr.gh17644.pkg)
* [Microsoft.macOS.Ref.13.1.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.macOS.Ref.13.1.228-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.macOS.Runtime.osx-arm64.13.1.228-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.macOS.Runtime.osx-x64.13.1.228-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Sdk.13.1.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.macOS.Sdk.13.1.228-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Templates.13.1.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.macOS.Templates.13.1.228-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.228-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.228-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.228-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1016-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1016-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.228-ci.pr.gh17644.msi](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.NET.Workload.iOS.16.2.228-ci.pr.gh17644.msi)
* [Microsoft.tvOS.Bundle.16.1.1016-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.tvOS.Bundle.16.1.1016-ci.pr.gh17644.pkg)
* [Microsoft.tvOS.Ref.16.1.1016-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.tvOS.Ref.16.1.1016-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.1016-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.1016-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1016-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1016-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1016-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1016-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Sdk.16.1.1016-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.tvOS.Sdk.16.1.1016-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Templates.16.1.1016-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/Microsoft.tvOS.Templates.16.1.1016-ci.pr.gh17644.nupkg)
* [xamarin.ios-16.2.1.228.pkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/xamarin.ios-16.2.1.228.pkg)
* [xamarin.mac-9.1.1.228.pkg](https://dl.internalx.com/wrench/merge/8fd53903378cd713b581bd7f9d7ce49f7570b046/7397704/package/xamarin.mac-9.1.1.228.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7397704&view=ms.vss-test-web.test-result-de [...]

2023-03-01 02:02 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 1 tests failed, 224 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * [xUnit] Mono SystemXunit/tvOS - simulator/Debug: Crashed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230228.16/7397704//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7397704/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7397704&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9aba3baaf52e6029433f6e44e851eed29e36a4d4](https://github.com/xamarin/xamarin-macios/pull/17644/commits/9aba3baaf52e6029433f6e44e851eed29e36a4d4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-01 06:57 UTC, rolfbjarne requested changes

2023-03-01 06:57 UTC, rolfbjarne commented on src/AppKit/NSApplication.cs
> +				TransientString.FreeStringArray (argsPtr, args.Length);
Can we use this code path for !NET as well?

2023-03-01 06:57 UTC, rolfbjarne commented on src/AppKit/NSAccessibility.cs
> +			return NSAccessibilityFrameInView (parentView.Handle, frame);
This avoids a potential NullReferenceException:

```suggestion
			return NSAccessibilityFrameInView (parentView.GetHandle (), frame);
```

2023-03-01 06:57 UTC, rolfbjarne commented on src/AppKit/NSAccessibility.cs
> +			return NSAccessibilityPointInView (parentView.Handle, point);
This avoids a potential NullReferenceException:

```suggestion
			return NSAccessibilityPointInView (parentView.GetHandle (), point);
```

2023-03-01 06:57 UTC, rolfbjarne commented on src/AppKit/NSGraphics.cs
> +			NSShowAnimationEffect ((nuint) (ulong) animationEffect, centerLocation, size, animationDelegate.Handle, didEndSelector.Handle, contextInfo);
This avoids potential NullReferenceExceptions:

```suggestion
			NSShowAnimationEffect ((nuint) (ulong) animationEffect, centerLocation, size, animationDelegate.GetHandle (), didEndSelector.GetHandle (), contextInfo);
```

2023-03-01 14:57 UTC, dalexsoto approved these changes

2023-03-01 16:29 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/fde317ac7ce609639bfecc0ce62d038b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/e49a395cecf9a46ddb32397937e784cd) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/805fe2e565618c9dca89bd1325bfa8cc) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/f1a53933e6a10b7932fa0c22c6f79e56) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/dcc0459d36b9d4554729f9886445d7ff) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/3f75ad5894414d0ea7c8a28fcd0dac72) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/61887017c6517f516e300b2d6850e381) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/796c7a7a61300444087e29f9ab9bddaf) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/be84007cf74c79b43fffb583a2165d66)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/f8dd5db804de11179f5d628eb0ee0fc5)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/8cfd9e796927a1af57542731c3214a06)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230301.18/7402719-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/a6fb015a90e74d3ad77227e847d01501)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7402719&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fb8f1ea61516408d738a661f9c714df2dbfa74a6](https://github.com/xamarin/xamarin-macios/pull/17644/commits/fb8f1ea61516408d738a661f9c714df2dbfa74a6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-01 16:33 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* xammac_tests


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7402719&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fb8f1ea61516408d738a661f9c714df2dbfa74a6](https://github.com/xamarin/xamarin-macios/pull/17644/commits/fb8f1ea61516408d738a661f9c714df2dbfa74a6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-01 16:40 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.229-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Bundle.16.2.229-ci.pr.gh17644.pkg)
* [Microsoft.iOS.Ref.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Ref.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Runtime.ios-arm.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Runtime.ios-arm64.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Sdk.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Sdk.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Templates.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Templates.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.iOS.Windows.Sdk.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.229-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.MacCatalyst.Bundle.16.2.229-ci.pr.gh17644.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.MacCatalyst.Ref.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.MacCatalyst.Sdk.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.MacCatalyst.Templates.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Bundle.13.1.229-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.macOS.Bundle.13.1.229-ci.pr.gh17644.pkg)
* [Microsoft.macOS.Ref.13.1.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.macOS.Ref.13.1.229-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.macOS.Runtime.osx-arm64.13.1.229-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.macOS.Runtime.osx-x64.13.1.229-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Sdk.13.1.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.macOS.Sdk.13.1.229-ci.pr.gh17644.nupkg)
* [Microsoft.macOS.Templates.13.1.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.macOS.Templates.13.1.229-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.229-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.229-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.229-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1017-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.1017-ci.pr.gh17644.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.229-ci.pr.gh17644.msi](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.NET.Workload.iOS.16.2.229-ci.pr.gh17644.msi)
* [Microsoft.tvOS.Bundle.16.1.1017-ci.pr.gh17644.pkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.tvOS.Bundle.16.1.1017-ci.pr.gh17644.pkg)
* [Microsoft.tvOS.Ref.16.1.1017-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.tvOS.Ref.16.1.1017-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.1017-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.1017-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1017-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.1017-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1017-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.1017-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Sdk.16.1.1017-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.tvOS.Sdk.16.1.1017-ci.pr.gh17644.nupkg)
* [Microsoft.tvOS.Templates.16.1.1017-ci.pr.gh17644.nupkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/Microsoft.tvOS.Templates.16.1.1017-ci.pr.gh17644.nupkg)
* [xamarin.ios-16.2.1.229.pkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/xamarin.ios-16.2.1.229.pkg)
* [xamarin.mac-9.1.1.229.pkg](https://dl.internalx.com/wrench/merge/68ad6c9f6b73767ff941ca4004da8f15667dfd1d/7402719/package/xamarin.mac-9.1.1.229.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7402719&view=ms.vss-test-web.test-result-de [...]

2023-03-01 16:40 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7402719&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fb8f1ea61516408d738a661f9c714df2dbfa74a6](https://github.com/xamarin/xamarin-macios/pull/17644/commits/fb8f1ea61516408d738a661f9c714df2dbfa74a6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-01 19:22 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

6 tests crashed, 1 tests failed, 146 tests passed.

## Failures

### :x: bcl tests

:fire: Failed catastrophically on VSTS: simulator tests - bcl (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: dotnettests tests

:fire: Failed catastrophically on VSTS: simulator tests - dotnettests (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: simulator tests - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 24 tests passed.</summary>
<details>

 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)

### :x: xtro tests

:fire: Failed catastrophically on VSTS: simulator tests - xtro (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio. [...]

2023-03-02 09:18 UTC, haritha-mohan approved these changes

2023-03-02 11:22 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 225 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_bcl-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_bcl-2&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_dotnettests-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_dotnettests-2&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_generator-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_generator-2&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mmp-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mmp-2&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_monotouch-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_monotouch-2&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_msbuild-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_msbuild-2&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230301.18/7402719//simulator_xtro-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7402719/artifacts?artifactName=HtmlReport-simulator_xtro-2&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7402719&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fb8f1ea61516408d738a661f9c714df2dbfa74a6](https://github.com/xamarin/xamarin-macios/pull/17644/commits/fb8f1ea61516408d738a661f9c714df2dbfa74a6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-03 15:59 UTC, rolfbjarne approved these changes

2023-03-03 16:10 UTC, merged