[CI] Backport all commits that fixed the CI in order to have the release/7.0.2xx branch work with the unified pipeline.
xamarin/xamarin-macios pull request #17687
Opened 2023-03-03 00:02 UTC by mandel-macaque

All of the commits have been cherry-picked and just a small number of them needed fixes due to the auto format tool.

2023-03-03 04:13 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

No test package could be found for tests on macOS M1 - Mac Big Sur (11.5)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7414036&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2a48990e1e23d41f84a5b1fd6cea67bc20cba3a3](https://github.com/xamarin/xamarin-macios/pull/17687/commits/2a48990e1e23d41f84a5b1fd6cea67bc20cba3a3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-03 04:15 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

No test package could be found for tests on macOS M1 - Mac Ventura (13.0)

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7414036&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2a48990e1e23d41f84a5b1fd6cea67bc20cba3a3](https://github.com/xamarin/xamarin-macios/pull/17687/commits/2a48990e1e23d41f84a5b1fd6cea67bc20cba3a3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-03 04:39 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.2.2082-ci.pr.gh17687.pkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Bundle.16.2.2082-ci.pr.gh17687.pkg)
* [Microsoft.iOS.Ref.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Ref.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Runtime.ios-arm.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Runtime.ios-arm64.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Runtime.iossimulator-x64.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Runtime.iossimulator-x86.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Sdk.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Sdk.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Templates.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Templates.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.iOS.Windows.Sdk.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.2.2082-ci.pr.gh17687.pkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.MacCatalyst.Bundle.16.2.2082-ci.pr.gh17687.pkg)
* [Microsoft.MacCatalyst.Ref.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.MacCatalyst.Ref.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.MacCatalyst.Sdk.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.MacCatalyst.Templates.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.MacCatalyst.Templates.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.macOS.Bundle.13.1.2082-ci.pr.gh17687.pkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.macOS.Bundle.13.1.2082-ci.pr.gh17687.pkg)
* [Microsoft.macOS.Ref.13.1.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.macOS.Ref.13.1.2082-ci.pr.gh17687.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.1.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.macOS.Runtime.osx-arm64.13.1.2082-ci.pr.gh17687.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.1.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.macOS.Runtime.osx-x64.13.1.2082-ci.pr.gh17687.nupkg)
* [Microsoft.macOS.Sdk.13.1.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.macOS.Sdk.13.1.2082-ci.pr.gh17687.nupkg)
* [Microsoft.macOS.Templates.13.1.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.macOS.Templates.13.1.2082-ci.pr.gh17687.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.2.2082-ci.pr.gh17687.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.2082-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.1.2082-ci.pr.gh17687.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.2579-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.1.2579-ci.pr.gh17687.nupkg)
* [Microsoft.NET.Workload.iOS.16.2.2082-ci.pr.gh17687.msi](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.NET.Workload.iOS.16.2.2082-ci.pr.gh17687.msi)
* [Microsoft.tvOS.Bundle.16.1.2579-ci.pr.gh17687.pkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.tvOS.Bundle.16.1.2579-ci.pr.gh17687.pkg)
* [Microsoft.tvOS.Ref.16.1.2579-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.tvOS.Ref.16.1.2579-ci.pr.gh17687.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.1.2579-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.tvOS.Runtime.tvos-arm64.16.1.2579-ci.pr.gh17687.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.2579-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.1.2579-ci.pr.gh17687.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.2579-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.1.2579-ci.pr.gh17687.nupkg)
* [Microsoft.tvOS.Sdk.16.1.2579-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.tvOS.Sdk.16.1.2579-ci.pr.gh17687.nupkg)
* [Microsoft.tvOS.Templates.16.1.2579-ci.pr.gh17687.nupkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/Microsoft.tvOS.Templates.16.1.2579-ci.pr.gh17687.nupkg)
* [xamarin.ios-16.1.1.452.pkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/xamarin.ios-16.1.1.452.pkg)
* [xamarin.mac-9.0.0.452.pkg](https://dl.internalx.com/wrench/merge/efd556893a8d0f0735d4fed0a4b996b2f71dc248/7414036/package/xamarin.mac-9.0.0.452.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index [...]

2023-03-03 04:39 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230303.2/7414036-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/f37e0ab181953349e53768ef4bf4c3b9) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230303.2/7414036-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/a1e150ed88769f17215c34d16f23aded) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230303.2/7414036-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/b9c6f5075d604c0de73043b05635f4d6) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230303.2/7414036-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) (could not create gist: file 'D:\a\1\s\change-detection\results\stable-api-comparison\diff\dotnet\iOS-MacCatalyst-diff\Microsoft.iOS.Ref\ref\net7.0\Microsoft.iOS.MacCatalyst.md' does not exist)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230303.2/7414036-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230303.2/7414036-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/6eb811783a93f32fa7c9792c99ee67ff) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7414036&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2a48990e1e23d41f84a5b1fd6cea67bc20cba3a3](https://github.com/xamarin/xamarin-macios/pull/17687/commits/2a48990e1e23d41f84a5b1fd6cea67bc20cba3a3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-03-03 07:48 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 12 tests failed, 65 tests passed.

## Failures

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>11 tests failed, 0 tests passed.</summary>
<details>

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac [dotnet]/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2808 Passed: 2662 Inconclusive: 10 Failed: 3 Ignored: 143)
 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug (LinkSdk) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Release (all optimizations) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

## Successes

:warning: bcl: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:warning: install_source: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:warning: mac_binding_project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:warning: mtouch: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:warning: xammac: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artif [...]

2023-03-03 10:44 UTC, rolfbjarne approved these changes
Looks good, but there are test failures.

2023-03-03 15:38 UTC, haritha-mohan approved these changes

2023-03-06 16:09 UTC, tj-devel709 approved these changes

2023-03-07 02:10 UTC, dalexsoto requested changes
Until tests are ✅

2023-03-08 10:05 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 12 tests failed, 65 tests passed.

## Failures

### :x: dotnettests tests [attempt 2]

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_dotnettests-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_dotnettests-2&api-version=6.0&$format=zip)

### :x: monotouch tests [attempt 2]

<summary>11 tests failed, 0 tests passed.</summary>
<details>

 * monotouch-test/Mac [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac [dotnet]/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 2808 Passed: 2663 Inconclusive: 9 Failed: 3 Ignored: 142)
 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug (LinkSdk) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Debug (static registrar) [dotnet]: BuildFailure
 * monotouch-test/tvOS - simulator/Release (all optimizations) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_monotouch-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_monotouch-2&api-version=6.0&$format=zip)

## Successes

:warning: bcl: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:warning: install_source: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:warning: mac_binding_project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:warning: mtouch: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:warning: xammac: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7414036/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230303.2/7414036//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/ [...]

2023-06-27 16:40 UTC, dalexsoto commented
@mandel-macaque this PR got stale and needs to switch branch now to [release/7.0.3xx](https://github.com/xamarin/xamarin-macios/tree/release/7.0.3xx)

2023-08-28 21:09 UTC, closed without merging