[dotnet] Added tests, fixed bugs
xamarin/xamarin-macios pull request #17979
Opened 2023-04-05 20:05 UTC by stephen-hawley

Stunt testing!

What happens is this: we write a string of C# to a file. This C# acts as a mock of the ObjCRuntime namespace it also includes a one or more classes that act internally like NSObject descendants at least as far as the `class_ptr` field is concerned.

The test compiles this code, runs the rewriter, then executes the final code collecting the output.
The tests include the following:

1. tool not run, code works as expected
2. tool run, `ClassHandle` now returns a different value
3. tool run, a class not listed for changing stays the same
4. tool run on a more authentic cctor, the cctor gets removed entirely

The code to run a process and collect its output was taken from the binding-tools-for-swift tests.

All tests pass.

2023-04-05 21:52 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0ccb9b8c6b421893fd6cee7c3512f4aa) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/da71e67004ba6229c172fcca2d06c177) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/78077c2c5c0b82f4b90861a6c5508ffc) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ce26a74cee69c9dd485fbb3ec3af84d0) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/17ecaf90ca88d267780f56058bed951a) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c0f4ede76ead454d7356c96e68dfcf4e) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6f177d1d07070e72de03402b0f8e88b3) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f4a64763c503c10f0d8532d82a6c67f8) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0bef2bdd5e1c122ee02affda1bfb1820)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ce5b0526d1e993f4669d5465a5235ad6)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ca205babea02cdfc32890d7727081fb1)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230405.3/7585776-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a3bd4b574d29dc7a948e9d2fec95b4f6)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7585776&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d728b8a9b2083b1c516195d03846f3b881d3cdcc](https://github.com/xamarin/xamarin-macios/pull/17979/commits/d728b8a9b2083b1c516195d03846f3b881d3cdcc)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-05 21:53 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7585776&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d728b8a9b2083b1c516195d03846f3b881d3cdcc](https://github.com/xamarin/xamarin-macios/pull/17979/commits/d728b8a9b2083b1c516195d03846f3b881d3cdcc)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-05 21:58 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7585776&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d728b8a9b2083b1c516195d03846f3b881d3cdcc](https://github.com/xamarin/xamarin-macios/pull/17979/commits/d728b8a9b2083b1c516195d03846f3b881d3cdcc)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-05 21:59 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7585776&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d728b8a9b2083b1c516195d03846f3b881d3cdcc](https://github.com/xamarin/xamarin-macios/pull/17979/commits/d728b8a9b2083b1c516195d03846f3b881d3cdcc)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-05 22:04 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.4.7052-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Bundle.16.4.7052-ci.pr.gh17979.pkg)
* [Microsoft.iOS.Ref.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Ref.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Runtime.ios-arm.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Runtime.ios-arm64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Runtime.iossimulator-x64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Runtime.iossimulator-x86.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Sdk.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Sdk.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Templates.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Templates.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.iOS.Windows.Sdk.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.4.7052-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.MacCatalyst.Bundle.16.4.7052-ci.pr.gh17979.pkg)
* [Microsoft.MacCatalyst.Ref.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.MacCatalyst.Ref.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.MacCatalyst.Sdk.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Templates.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.MacCatalyst.Templates.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Bundle.13.3.7052-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.macOS.Bundle.13.3.7052-ci.pr.gh17979.pkg)
* [Microsoft.macOS.Ref.13.3.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.macOS.Ref.13.3.7052-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.3.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.macOS.Runtime.osx-arm64.13.3.7052-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.3.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.macOS.Runtime.osx-x64.13.3.7052-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Sdk.13.3.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.macOS.Sdk.13.3.7052-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Templates.13.3.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.macOS.Templates.13.3.7052-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7052-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Workload.iOS.16.4.7052-ci.pr.gh17979.msi](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.NET.Workload.iOS.16.4.7052-ci.pr.gh17979.msi)
* [Microsoft.tvOS.Bundle.16.4.7052-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.tvOS.Bundle.16.4.7052-ci.pr.gh17979.pkg)
* [Microsoft.tvOS.Ref.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.tvOS.Ref.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.tvOS.Runtime.tvos-arm64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Sdk.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.tvOS.Sdk.16.4.7052-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Templates.16.4.7052-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/Microsoft.tvOS.Templates.16.4.7052-ci.pr.gh17979.nupkg)
* [xamarin.ios-16.5.0.18.pkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/xamarin.ios-16.5.0.18.pkg)
* [xamarin.mac-9.4.0.18.pkg](https://dl.internalx.com/wrench/merge/ca91a8c1d07f7b451af27dc2c53f977c6a567a1d/7585776/package/xamarin.mac-9.4.0.18.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?bui [...]

2023-04-06 01:21 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 225 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230405.3/7585776//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7585776/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7585776&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d728b8a9b2083b1c516195d03846f3b881d3cdcc](https://github.com/xamarin/xamarin-macios/pull/17979/commits/d728b8a9b2083b1c516195d03846f3b881d3cdcc)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-06 21:00 UTC, tj-devel709 reviewed
Few very small things, but otherwise LGTM :)

2023-04-06 21:00 UTC, tj-devel709 commented on tools/class-redirector/class-redirector-tests/Compiler.cs
> +
```suggestion
```
nit: reformatter may grab this :)

2023-04-06 21:00 UTC, tj-devel709 commented on tools/class-redirector/class-redirector-tests/Compiler.cs
> +		if (output == null)
```suggestion
		if (output is null)
```

2023-04-06 21:00 UTC, tj-devel709 commented on tools/class-redirector/class-redirector-tests/Compiler.cs
> +		if (workingDirectory != null)
```suggestion
		if (workingDirectory is not null)
```

2023-04-06 21:00 UTC, tj-devel709 commented on tools/class-redirector/class-redirector-tests/Compiler.cs
> +		if (env != null) {
```suggestion
		if (env is not null) {
```

2023-04-06 21:00 UTC, tj-devel709 commented on tools/class-redirector/class-redirector-tests/Compiler.cs
> +				if (kvp.Value == null) {
```suggestion
				if (kvp.Value is null) {
```

2023-04-10 15:09 UTC, rolfbjarne requested changes

2023-04-10 16:02 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7605523&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3dbeb0833b5bf531f85f2330624e0b246b068e27](https://github.com/xamarin/xamarin-macios/pull/17979/commits/3dbeb0833b5bf531f85f2330624e0b246b068e27)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-10 16:04 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/29450eb2b309f90211ea0f997c979060) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/76d846f7164a2882a8c5ba5b7c10679c) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/abd81a240b372dafdb98a2bb9b0ee83d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2480e6aaebddd14fd69506884350aaf7) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fd583e0ee6a4c49c04cd430aa827fca6) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7bf4b05a46c53c83b162c90bd7b21ea0) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/68ec4245cb008c0c8b0521878431fd37) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/077d96b4673754c5edd1e65a030c2a2b) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a7b991347585505652e9a165f937a890)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f6a69e20f7a64d1bfcd6c5c3b634cd91)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f4323cd8ae968561f2ceccc790c6980f)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230410.11/7605523-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/74d2d92681ca864e03465258c02cad7d)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7605523&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3dbeb0833b5bf531f85f2330624e0b246b068e27](https://github.com/xamarin/xamarin-macios/pull/17979/commits/3dbeb0833b5bf531f85f2330624e0b246b068e27)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-10 16:10 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7605523&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3dbeb0833b5bf531f85f2330624e0b246b068e27](https://github.com/xamarin/xamarin-macios/pull/17979/commits/3dbeb0833b5bf531f85f2330624e0b246b068e27)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-10 16:10 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.4.7054-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Bundle.16.4.7054-ci.pr.gh17979.pkg)
* [Microsoft.iOS.Ref.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Ref.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Runtime.ios-arm.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Runtime.ios-arm64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Runtime.iossimulator-x64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Runtime.iossimulator-x86.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Sdk.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Sdk.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Templates.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Templates.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.iOS.Windows.Sdk.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.4.7054-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.MacCatalyst.Bundle.16.4.7054-ci.pr.gh17979.pkg)
* [Microsoft.MacCatalyst.Ref.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.MacCatalyst.Ref.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.MacCatalyst.Sdk.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Templates.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.MacCatalyst.Templates.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Bundle.13.3.7054-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.macOS.Bundle.13.3.7054-ci.pr.gh17979.pkg)
* [Microsoft.macOS.Ref.13.3.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.macOS.Ref.13.3.7054-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.3.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.macOS.Runtime.osx-arm64.13.3.7054-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.3.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.macOS.Runtime.osx-x64.13.3.7054-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Sdk.13.3.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.macOS.Sdk.13.3.7054-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Templates.13.3.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.macOS.Templates.13.3.7054-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7054-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Workload.iOS.16.4.7054-ci.pr.gh17979.msi](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.NET.Workload.iOS.16.4.7054-ci.pr.gh17979.msi)
* [Microsoft.tvOS.Bundle.16.4.7054-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.tvOS.Bundle.16.4.7054-ci.pr.gh17979.pkg)
* [Microsoft.tvOS.Ref.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.tvOS.Ref.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.tvOS.Runtime.tvos-arm64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Sdk.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.tvOS.Sdk.16.4.7054-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Templates.16.4.7054-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/Microsoft.tvOS.Templates.16.4.7054-ci.pr.gh17979.nupkg)
* [xamarin.ios-16.5.0.20.pkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/xamarin.ios-16.5.0.20.pkg)
* [xamarin.mac-9.4.0.20.pkg](https://dl.internalx.com/wrench/merge/4cea5585d8cc3ac069361d07f11ff9138c252d22/7605523/package/xamarin.mac-9.4.0.20.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?bui [...]

2023-04-10 19:36 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 225 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230410.11/7605523//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7605523/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7605523&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3dbeb0833b5bf531f85f2330624e0b246b068e27](https://github.com/xamarin/xamarin-macios/pull/17979/commits/3dbeb0833b5bf531f85f2330624e0b246b068e27)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-11 19:26 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7613514&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e64db85807a10d86fa3cbae0e54cd63e2aed8f2a](https://github.com/xamarin/xamarin-macios/pull/17979/commits/e64db85807a10d86fa3cbae0e54cd63e2aed8f2a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-11 19:29 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7613514&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e64db85807a10d86fa3cbae0e54cd63e2aed8f2a](https://github.com/xamarin/xamarin-macios/pull/17979/commits/e64db85807a10d86fa3cbae0e54cd63e2aed8f2a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-13 14:19 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7613514&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e64db85807a10d86fa3cbae0e54cd63e2aed8f2a](https://github.com/xamarin/xamarin-macios/pull/17979/commits/e64db85807a10d86fa3cbae0e54cd63e2aed8f2a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-13 16:29 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9d75f7eff33480540d324b042948e095) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c119c7f6d231621bfc86d3938e73a9e8) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/848f512bd3b4f325819444b21c1cb9e7) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2349bb11bafa38cae322052f9f3b31a7) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/86bcf82a7bbca0e1d84b405714be5bdd) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7c062b01f815b489b98577ade997265b) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ca579455831e2f500dc9afe76a5517fb) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/526914fa4fe451d83c1bbfa7bf617979) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3bc4bd3949351bb59e595d8bf90a7338)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/945a343eced303c060767f1e3e22c7fc)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6edcecb4cb4896e01d0c9b68658c9ff4)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230411.13/7613514-2/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/37d4ee73f55582ee3404df69aa293398)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7613514&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [e64db85807a10d86fa3cbae0e54cd63e2aed8f2a](https://github.com/xamarin/xamarin-macios/pull/17979/commits/e64db85807a10d86fa3cbae0e54cd63e2aed8f2a)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-13 18:34 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/040beace1627fa09e0b577d625ee320a) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a16c67d2a8c7fe0809d74b254ff22ec9) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d9ba7e24821d4d4f6d6ae0e9fcc517c3) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/49e3f4890c7ebe5d1bd06a5cd59614cd) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fbaa22f3a5946682296352f586f08f39) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/24b66a38bdb90cde48496c522981ee3f) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f429da5c0f10a4be76dd499ab89db09e) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ce9fe72afbe6a1306dc16e6ed26768a9) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/62362a9e04f1a27e634f03d9fc6dcd25)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/de3d9d4644930c599acc01f0abcb6453)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/480be98def76278a05130c3e457e85fb)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230413.25/7624946-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5891ec6b4929afc1903db148bab42fdc)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7624946&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa](https://github.com/xamarin/xamarin-macios/pull/17979/commits/73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-13 19:44 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7624946&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa](https://github.com/xamarin/xamarin-macios/pull/17979/commits/73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-13 19:46 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7624946&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa](https://github.com/xamarin/xamarin-macios/pull/17979/commits/73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-13 19:52 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.4.7087-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Bundle.16.4.7087-ci.pr.gh17979.pkg)
* [Microsoft.iOS.Ref.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Ref.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Runtime.ios-arm.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Runtime.ios-arm64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Runtime.iossimulator-x64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Runtime.iossimulator-x86.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Sdk.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Sdk.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Templates.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Templates.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.iOS.Windows.Sdk.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.4.7087-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.MacCatalyst.Bundle.16.4.7087-ci.pr.gh17979.pkg)
* [Microsoft.MacCatalyst.Ref.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.MacCatalyst.Ref.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.MacCatalyst.Sdk.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.MacCatalyst.Templates.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.MacCatalyst.Templates.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Bundle.13.3.7087-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.macOS.Bundle.13.3.7087-ci.pr.gh17979.pkg)
* [Microsoft.macOS.Ref.13.3.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.macOS.Ref.13.3.7087-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.3.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.macOS.Runtime.osx-arm64.13.3.7087-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.3.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.macOS.Runtime.osx-x64.13.3.7087-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Sdk.13.3.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.macOS.Sdk.13.3.7087-ci.pr.gh17979.nupkg)
* [Microsoft.macOS.Templates.13.3.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.macOS.Templates.13.3.7087-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7087-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.NET.Workload.iOS.16.4.7087-ci.pr.gh17979.msi](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.NET.Workload.iOS.16.4.7087-ci.pr.gh17979.msi)
* [Microsoft.tvOS.Bundle.16.4.7087-ci.pr.gh17979.pkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.tvOS.Bundle.16.4.7087-ci.pr.gh17979.pkg)
* [Microsoft.tvOS.Ref.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.tvOS.Ref.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.tvOS.Runtime.tvos-arm64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Sdk.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.tvOS.Sdk.16.4.7087-ci.pr.gh17979.nupkg)
* [Microsoft.tvOS.Templates.16.4.7087-ci.pr.gh17979.nupkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/Microsoft.tvOS.Templates.16.4.7087-ci.pr.gh17979.nupkg)
* [xamarin.ios-16.5.0.53.pkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/xamarin.ios-16.5.0.53.pkg)
* [xamarin.mac-9.4.0.53.pkg](https://dl.internalx.com/wrench/merge/352befccc5c7330c05d45ede22a6d9dfe0112f87/7624946/package/xamarin.mac-9.4.0.53.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?bui [...]

2023-04-13 19:52 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7624946&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa](https://github.com/xamarin/xamarin-macios/pull/17979/commits/73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-13 23:45 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

1 tests crashed, 0 tests failed, 223 tests passed.

## Failures

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230413.25/7624946//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7624946/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7624946&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa](https://github.com/xamarin/xamarin-macios/pull/17979/commits/73ddc1b1d46391b9d6610f33fb4d393ce4d1fcaa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-14 09:05 UTC, rolfbjarne approved these changes

2023-04-14 14:16 UTC, merged