[Localization] Use xamarin-release-manager to create PRs
xamarin/xamarin-macios pull request #18122
Opened 2023-04-24 15:17 UTC by tj-devel709

Pull requests created from pipelines that bring over Localization strings created by `vs-mobiletools-engineering-service2` were automatically closed a few hours after creation such as [this](https://github.com/xamarin/xamarin-macios/pull/18051). Michael Bond suggested using the `xamarin-release-manager` account since it also has access to the repo. 

The email for the account is the one I found on Github and am not totally sure if this has changed since then or not.

2023-04-24 16:37 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7672942&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [0f92a62edc90fbbac3568472a927e6c468d9ebeb](https://github.com/xamarin/xamarin-macios/pull/18122/commits/0f92a62edc90fbbac3568472a927e6c468d9ebeb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-24 16:47 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [Microsoft.iOS.Bundle.16.4.7107-ci.pr.gh18122.pkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Bundle.16.4.7107-ci.pr.gh18122.pkg)
* [Microsoft.iOS.Ref.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Ref.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Runtime.ios-arm.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Runtime.ios-arm.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Runtime.ios-arm64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Runtime.ios-arm64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Runtime.iossimulator-arm64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Runtime.iossimulator-x64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Runtime.iossimulator-x86.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Runtime.iossimulator-x86.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Sdk.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Sdk.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Templates.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Templates.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.iOS.Windows.Sdk.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.iOS.Windows.Sdk.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.MacCatalyst.Bundle.16.4.7107-ci.pr.gh18122.pkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.MacCatalyst.Bundle.16.4.7107-ci.pr.gh18122.pkg)
* [Microsoft.MacCatalyst.Ref.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.MacCatalyst.Ref.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.MacCatalyst.Sdk.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.MacCatalyst.Sdk.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.MacCatalyst.Templates.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.MacCatalyst.Templates.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.macOS.Bundle.13.3.7107-ci.pr.gh18122.pkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.macOS.Bundle.13.3.7107-ci.pr.gh18122.pkg)
* [Microsoft.macOS.Ref.13.3.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.macOS.Ref.13.3.7107-ci.pr.gh18122.nupkg)
* [Microsoft.macOS.Runtime.osx-arm64.13.3.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.macOS.Runtime.osx-arm64.13.3.7107-ci.pr.gh18122.nupkg)
* [Microsoft.macOS.Runtime.osx-x64.13.3.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.macOS.Runtime.osx-x64.13.3.7107-ci.pr.gh18122.nupkg)
* [Microsoft.macOS.Sdk.13.3.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.macOS.Sdk.13.3.7107-ci.pr.gh18122.nupkg)
* [Microsoft.macOS.Templates.13.3.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.macOS.Templates.13.3.7107-ci.pr.gh18122.nupkg)
* [Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.NET.Sdk.iOS.Manifest-7.0.100.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.NET.Sdk.macOS.Manifest-7.0.100.13.3.7107-ci.pr.gh18122.nupkg)
* [Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.NET.Sdk.tvOS.Manifest-7.0.100.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.NET.Workload.iOS.16.4.7107-ci.pr.gh18122.msi](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.NET.Workload.iOS.16.4.7107-ci.pr.gh18122.msi)
* [Microsoft.tvOS.Bundle.16.4.7107-ci.pr.gh18122.pkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.tvOS.Bundle.16.4.7107-ci.pr.gh18122.pkg)
* [Microsoft.tvOS.Ref.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.tvOS.Ref.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.tvOS.Runtime.tvos-arm64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.tvOS.Runtime.tvos-arm64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.tvOS.Runtime.tvossimulator-arm64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.tvOS.Runtime.tvossimulator-x64.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.tvOS.Sdk.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.tvOS.Sdk.16.4.7107-ci.pr.gh18122.nupkg)
* [Microsoft.tvOS.Templates.16.4.7107-ci.pr.gh18122.nupkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/Microsoft.tvOS.Templates.16.4.7107-ci.pr.gh18122.nupkg)
* [xamarin.ios-16.5.0.73.pkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/xamarin.ios-16.5.0.73.pkg)
* [xamarin.mac-9.4.0.73.pkg](https://dl.internalx.com/wrench/merge/387f543fbf1c8cd98c04ad43a2cea351e96a0bc2/7672942/package/xamarin.mac-9.4.0.73.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?bui [...]

2023-04-24 16:48 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6ce8f9a228da2ec0774a30e3bc714c21) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c5b593f9fcb4509958882bba19f4efd3) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1278e76939a3bf9b2faf46e1c2ab439b) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c2ea9335d4a28d60c200cb56923146af) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/be62288bed79e726aa5efb02e4506404) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3c361ffb5417eff4e205463878a2bf08) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0393e76aa0a77a3e7cab2668cc7e4bf2) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f016b3b9b74b1325ce634402d7d66d85) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/797cfd60fb7c24ea2efed36965e3d801)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ca421a0fded960617c11d3eac6e15ef2)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c8b0a5ce33ed737fd3f5cb0b4771fc7e)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230424.13/7672942-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/61ff3908a5f3ecfdb6053c4744a1c3ce)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7672942&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [0f92a62edc90fbbac3568472a927e6c468d9ebeb](https://github.com/xamarin/xamarin-macios/pull/18122/commits/0f92a62edc90fbbac3568472a927e6c468d9ebeb)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-24 17:00 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7672942&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18122/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-24 17:01 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7672942&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18122/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-24 20:42 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

2 tests crashed, 2 tests failed, 213 tests passed.

## Failures

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>2 tests failed, 23 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: TimedOut (Execution timed out after 1200 seconds.
Test run crashed)
 * monotouch-test/Mac Catalyst [dotnet]/Release [dotnet]: TimedOut (Execution timed out after 1200 seconds.
Test run crashed)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230424.13/7672942//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7672942/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7672942&view=ms.vss-test-web.test-resul [...]

2023-04-25 05:34 UTC, rolfbjarne requested changes
This won't change the user used to create the PR. In order to do that, you need to change the $(GitHub.Token)/GITHUB_TOKEN value to a PAT for the account you want to use.

2023-04-25 23:08 UTC, tj-devel709 commented
> This won't change the user used to create the PR. In order to do that, you need to change the $(GitHub.Token)/GITHUB_TOKEN value to a PAT for the account you want to use.

Thanks for catching this, @rolfbjarne! I talked to Manuel and am trying to test using my own PAT: the PR was created, but I want to confirm that it does not close itself and I do not want to interact with it in any way to try to control variables haha. The PR number is 18143 for reference.

2023-06-06 18:03 UTC, closed without merging