Change all null checking expressions to use 'is' and 'is not'.
xamarin/xamarin-macios pull request #18176
Opened 2023-04-28 08:42 UTC by rolfbjarne

Change all null checking expressions to use 'is null' and 'is not null'
instead of '== null' and '!= null'.

This was mostly done with sed, so code can probably be improved in many other
ways with manual inspection, but that will come over time.

2023-04-28 09:58 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Canceled :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7698458&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [92e59921367bf59059ff7927e233c54082815b4b](https://github.com/xamarin/xamarin-macios/pull/18176/commits/92e59921367bf59059ff7927e233c54082815b4b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 10:18 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.86.pkg](https://dl.internalx.com/wrench/merge/7065fd08d75f0702baec6c9c1532ae4336868e49/7698458/package/xamarin.ios-16.5.0.86.pkg)
* [xamarin.mac-9.4.0.86.pkg](https://dl.internalx.com/wrench/merge/7065fd08d75f0702baec6c9c1532ae4336868e49/7698458/package/xamarin.mac-9.4.0.86.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7698458&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 11:06 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7698621&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9c60806473d1f4b7aa493a98d09956ea343ad922](https://github.com/xamarin/xamarin-macios/pull/18176/commits/9c60806473d1f4b7aa493a98d09956ea343ad922)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 11:25 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.87.pkg](https://dl.internalx.com/wrench/merge/1b0f9c954d4af3043f7bcc5cfb7ca2305e81be38/7698621/package/xamarin.ios-16.5.0.87.pkg)
* [xamarin.mac-9.4.0.87.pkg](https://dl.internalx.com/wrench/merge/1b0f9c954d4af3043f7bcc5cfb7ca2305e81be38/7698621/package/xamarin.mac-9.4.0.87.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7698621&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 11:37 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7698621&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [9c60806473d1f4b7aa493a98d09956ea343ad922](https://github.com/xamarin/xamarin-macios/pull/18176/commits/9c60806473d1f4b7aa493a98d09956ea343ad922)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 13:12 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7698621&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 13:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7698621&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 14:48 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7699012&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [609f81577917d4b32fa1eac994f004fde1c53e9e](https://github.com/xamarin/xamarin-macios/pull/18176/commits/609f81577917d4b32fa1eac994f004fde1c53e9e)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 15:07 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.92.pkg](https://dl.internalx.com/wrench/merge/56858032c31c791da27cda6464759cd0e861b947/7699012/package/xamarin.ios-16.5.0.92.pkg)
* [xamarin.mac-9.4.0.92.pkg](https://dl.internalx.com/wrench/merge/56858032c31c791da27cda6464759cd0e861b947/7699012/package/xamarin.mac-9.4.0.92.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7699012&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 19:56 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7699012&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 19:59 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7699012&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-04-28 23:17 UTC, haritha-mohan approved these changes

2023-04-29 00:59 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 72 tests failed, 153 tests passed.

## Failures

### :x: bcl tests

<summary>69 tests failed, 0 tests passed.</summary>
<details>

 * [NUnit] Mono Mac OS X BCL tests group 1/Mac Full/Debug: BuildFailure
 * [NUnit] Mono Mac OS X BCL tests group 1/Mac Modern/Debug: BuildFailure
 * [NUnit] Mono Mac OS X BCL tests group 2/Mac Full/Debug: BuildFailure
 * [NUnit] Mono Mac OS X BCL tests group 2/Mac Modern/Debug: BuildFailure
 * [NUnit] Mono Mac OS X BCL tests group 3/Mac Full/Debug: BuildFailure
 * [NUnit] Mono Mac OS X BCL tests group 3/Mac Modern/Debug: BuildFailure
 * [xUnit] Mono Mac OS X BCL tests group 4/Mac Full/Debug: BuildFailure
 * [xUnit] Mono Mac OS X BCL tests group 4/Mac Modern/Debug: BuildFailure
 * mscorlib/Mac Full/Debug: BuildFailure
 * mscorlib/Mac Modern/Debug: BuildFailure
 * [NUnit] Mono BCL tests group 1/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono BCL tests group 1/tvOS - simulator/Debug: BuildFailure
 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono BCL tests group 2/tvOS - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 3/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 3/tvOS - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 4/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 4/tvOS - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 5/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono BCL tests group 5/tvOS - simulator/Debug: BuildFailure
 * mscorlib Part 1/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * mscorlib Part 1/tvOS - simulator/Debug: BuildFailure
 * mscorlib Part 1/watchOS 32-bits - simulator/Debug: BuildFailure
 * mscorlib Part 2/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * mscorlib Part 2/tvOS - simulator/Debug: BuildFailure
 * mscorlib Part 2/watchOS 32-bits - simulator/Debug: BuildFailure
 * mscorlib Part 3/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * mscorlib Part 3/tvOS - simulator/Debug: BuildFailure
 * mscorlib Part 3/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 1/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 1/tvOS - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 1/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 2/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 2/tvOS - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 2/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemXunit/iOS Unified 64-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemXunit/tvOS - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemCoreTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemNumericsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemRuntimeSerializationTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemTransactionsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemXmlTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemXmlLinqTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemComponentModelDataAnnotationsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemJsonTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemServiceModelWebTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemIOCompressionTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemIOCompressionFileSystemTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono MonoCSharpTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemSecurityTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono MonoDataSqliteTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono MonoRuntimeTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemDataTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemDataDataSetExtensionsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemNetHttpTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemServiceModelTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono CorlibTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemWebServicesTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemDataXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemJsonXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemSecurityXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemLinqXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemXmlXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemRuntimeCompilerServicesUnsafeXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemNumericsXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono MicrosoftCSharpXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemNetHttpUnitTestsXunit/watchOS 32-bits - simulator/Debug: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230428.18/7699012//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7699012/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: mmp tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * MMP Regression Tests/Mac: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230428.18/7699012//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7699012/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

### :x: msbuild tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * MSBuild tests/Integration: Failed (Execution failed with exit code 28)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230428.18/7699012//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7699012/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)

### :x: mtouch tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * MTouch tests/NUnit: Failed (Execution failed with exit code 3)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230428.18/7699012//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7699012/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230428.18/7699012//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7699012/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230428. [...]

2023-05-01 17:30 UTC, tj-devel709 commented on tools/common/Driver.execution.cs
> +			var error_received = error is null ? null : new Action<string> ((v) => { if (v is not null) error.AppendLine (v); });
```suggestion
			var output_received = output ?? new Action<string> ((v) => { if (v is not null) output.AppendLine (v); });
			var error_received = error ?? new Action<string> ((v) => { if (v is not null) error.AppendLine (v); });
```

2023-05-01 17:34 UTC, tj-devel709 approved these changes

2023-05-02 18:54 UTC, dalexsoto approved these changes

2023-05-03 14:10 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7718443&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f617fc915f21a748aafc453b8186976e6797a3a4](https://github.com/xamarin/xamarin-macios/pull/18176/commits/f617fc915f21a748aafc453b8186976e6797a3a4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-03 14:26 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7a54a6543bb1e8b98ab2a7b1d2e8fa2d) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fd119e75a2c3b285fc40b824d8d32566) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b05a7cefcc882399bd619282ccdf4139) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d5c343127e0731d9a1c1c0a411c09b94) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d174786cf4dba43e516a1f69fa95910f) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b53912f407f3909453caba58cd6bd806) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f40b1e63087628e2eda9a4cbe019b80e) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ebc08575a50edfabfec3ce1948e5a993) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bc700528976bb70de48d1969a0fd8e9f)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9e283ec978569c803c98a5e5381bff25)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/537a52d5ea864b617f00c750283caadf)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c849d01f2aa364b1c099bdc606e4986d)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230503.4/7718443-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/064b61b9ce05e2006e5db10cd776209b) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7718443&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f617fc915f21a748aafc453b8186976e6797a3a4](https://github.com/xamarin/xamarin-macios/pull/18176/commits/f617fc915f21a748aafc453b8186976e6797a3a4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-03 14:40 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7718443&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-03 14:56 UTC, mauroa approved these changes

2023-05-03 18:32 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 225 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230503.4/7718443//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7718443/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7718443&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [f617fc915f21a748aafc453b8186976e6797a3a4](https://github.com/xamarin/xamarin-macios/pull/18176/commits/f617fc915f21a748aafc453b8186976e6797a3a4)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-03 22:12 UTC, emaf approved these changes

2023-05-04 06:58 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7723936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3fea4f2a015aafc071884964984f11b743c4e2b7](https://github.com/xamarin/xamarin-macios/pull/18176/commits/3fea4f2a015aafc071884964984f11b743c4e2b7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 07:04 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7723936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 07:06 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7723936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 07:14 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.125.pkg](https://dl.internalx.com/wrench/merge/b19e369a38e68aa1b42d3bd4d63540dd44bf0641/7723936/package/xamarin.ios-16.5.0.125.pkg)
* [xamarin.mac-9.4.0.125.pkg](https://dl.internalx.com/wrench/merge/b19e369a38e68aa1b42d3bd4d63540dd44bf0641/7723936/package/xamarin.mac-9.4.0.125.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7723936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 07:21 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/cfebc09ed0be0a863742e821b870ccc8) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7b3317eba767bd2e78964a4e9a71623e) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/36d76b9188d3c765e2e255da927f482d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/cc3d282cf316a57d4f37629852c19722) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/16d18fdc19a73934b467f79012b8665b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3f7e1b1f57a65f4986ea8d97821ee0b0) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1007ea5d0a9eb3dcfdbdeb12df1bb6fd) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/10daecb8f850dfe34dc11442deeac678) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1a68a1d12dd67454694348b07e907609)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8671c3aef02225e548398947de88cf03)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/43fbf438e84cdf4ef1475b10a6c3fe92)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/04565484eb2235c6fb22e03f64433de9)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.3/7723936-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/519b9996d8e60ef4827e422458df650a) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7723936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3fea4f2a015aafc071884964984f11b743c4e2b7](https://github.com/xamarin/xamarin-macios/pull/18176/commits/3fea4f2a015aafc071884964984f11b743c4e2b7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 10:57 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 4 tests failed, 221 tests passed.

## Failures

### :x: bcl tests

<summary>1 tests failed, 68 tests passed.</summary>
<details>

 * [NUnit] Mono CorlibTests/watchOS 32-bits - simulator/Debug: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>1 tests failed, 24 tests passed.</summary>
<details>

 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: xammac tests

<summary>1 tests failed, 2 tests passed.</summary>
<details>

 * xammac tests/Mac Modern/Release: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.3/7723936//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7723936/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/ [...]

2023-05-04 15:07 UTC, stephen-hawley reviewed
This is a big PR - taking it in pieces.

2023-05-04 15:15 UTC, stephen-hawley requested changes
I know this is a pain, but since it looks like we're committed to nullable, I'd like to see a test that greps through all the source code for `== null`, `!= null`, `null ==`, and `null !=` just so that we keep ourselves honest.

2023-05-04 22:26 UTC, rolfbjarne commented
@stephen-hawley 

> I know this is a pain, but since it looks like we're committed to nullable, I'd like to see a test that greps through all the source code for `== null`, `!= null`, `null ==`, and `null !=` just so that we keep ourselves honest.

I made it better than a test: automatically fix it (using autoformat): [xamarin/xamarin-macios@`2f91cd0` (#18176)](https://github.com/xamarin/xamarin-macios/pull/18176/commits/2f91cd0875e4b062e2a32e7e55bd0b0ebf6667cd)

Note I only handle the two first cases (null as the second operator), because:

* It's much more complex to handle null as the first operator, because you have to switch the order (`null == x` => `x is null`)
* It's a very rare thing to do in our code base (I found it in two files: one is fixed, and the other is actually correct because it's a test testing equality operators and the code shouldn't be changed).

2023-05-04 23:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7728211&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2f91cd0875e4b062e2a32e7e55bd0b0ebf6667cd](https://github.com/xamarin/xamarin-macios/pull/18176/commits/2f91cd0875e4b062e2a32e7e55bd0b0ebf6667cd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 23:46 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7728211&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 23:53 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7728211&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 23:54 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.128.pkg](https://dl.internalx.com/wrench/merge/bacb7824fc11de42c4e4bb28de2763f2cf051358/7728211/package/xamarin.ios-16.5.0.128.pkg)
* [xamarin.mac-9.4.0.128.pkg](https://dl.internalx.com/wrench/merge/bacb7824fc11de42c4e4bb28de2763f2cf051358/7728211/package/xamarin.mac-9.4.0.128.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7728211&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18176/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-04 23:59 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/36ab541d0d6ea840484137d5afc09ca4) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ed26dbba0950002b27152fd8bcf1d158) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b07dc02133df221b64a0ca6a856b516e) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/16d98fe3495312c3495e901b7f39dd04) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/eacbcf6746cc60f5e60e5847793b4f76) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7c72a4e6a55a7ba242ec6997c5e0c851) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8911efbcba87c84278960292b708780c) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/dd4bea29482903b47838dda1f8adc538) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7b9475d258d5449a7f7e39abae4b2f9b)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/56807097f581d05f64e40a702a53969e)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b37e921e1cf4e969cca40ed3c79335b1)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/61a92ac1510ebbf04b689aa59f6ed588)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230504.21/7728211-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/78b1805267b242f28e95a313102e1ab7) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7728211&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2f91cd0875e4b062e2a32e7e55bd0b0ebf6667cd](https://github.com/xamarin/xamarin-macios/pull/18176/commits/2f91cd0875e4b062e2a32e7e55bd0b0ebf6667cd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-05 05:36 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 225 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 25 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230504.21/7728211//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7728211/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7728211&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2f91cd0875e4b062e2a32e7e55bd0b0ebf6667cd](https://github.com/xamarin/xamarin-macios/pull/18176/commits/2f91cd0875e4b062e2a32e7e55bd0b0ebf6667cd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-05-05 15:49 UTC, stephen-hawley approved these changes

2023-05-05 15:52 UTC, merged