NSUrlSessionHandler should propagate network exceptions
xamarin/xamarin-macios pull request #18459
Opened 2023-06-16 11:03 UTC by EmilienDup

fixes #18458

2023-06-16 11:08 UTC, EmilienDup commented
@microsoft-github-policy-service agree company="SnagR Ltd."

2023-06-16 11:24 UTC, rolfbjarne requested changes

2023-06-16 11:24 UTC, rolfbjarne commented on tests/monotouch-test/System.Net.Http/MessageHandlers.cs
> +			IPEndPoint localEndPoint = new IPEndPoint (IPAddress.Any, 8080);
Could the test use a dynamic port instead? In some cases we might end up executing the tests simulaneously on the same machine, and having a fixed port could cause conflicts if the same test executes in two different processes at thes ame time.

2023-06-16 11:24 UTC, rolfbjarne commented on tests/monotouch-test/System.Net.Http/MessageHandlers.cs
> +				Assert.Inconclusive ("Failed to produce a timeout. The response content was streamed completly.");
```suggestion
				Assert.Inconclusive ("Failed to produce a timeout. The response content was streamed completely.");
```

2023-06-16 11:24 UTC, rolfbjarne commented on tests/monotouch-test/System.Net.Http/MessageHandlers.cs
> +			}, out var ex);
You're not doing anything with `ex`, maybe also add an assert that no exception was thrown:

```cs
Assert.NotNull (ex, "Exception");
```

2023-06-16 12:00 UTC, rolfbjarne commented
/azp run

2023-06-16 13:06 UTC, rolfbjarne commented
/azp run

2023-06-16 14:46 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7929576&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [160290eae143031abe6856cb19ba9f1b90428827](https://github.com/xamarin/xamarin-macios/pull/18459/commits/160290eae143031abe6856cb19ba9f1b90428827)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-16 14:55 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8596b38376404e096f896cf5b3e52444) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/05abd4eecead9c1ea2027300006b2a68) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/dfcf71d6645ac73e2c2f68e758fc2ccc) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1d6ffa3314ebaf72440c82f58e83229a) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bc54918d894bc70f1c8200d280e60975) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5758bfcf71e0f9c17febe35a43a3cbb4) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7687170b2e5962e191fca3c8740d6688) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/15283626e88a72dcd42d58521c8a09f3) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f3f2d1a7325c3e8f98514225abef31cf)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0906a16f4bea56f5af6290a94ff0900c)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c794fa0939a5ef112341e1d89435d5f3)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230616.2/7929576-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/660e323fc86ffa81e78a82508633a74f)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7929576&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [160290eae143031abe6856cb19ba9f1b90428827](https://github.com/xamarin/xamarin-macios/pull/18459/commits/160290eae143031abe6856cb19ba9f1b90428827)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-16 15:02 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.291.pkg](https://dl.internalx.com/wrench/merge/c5fb239069db9ad1555d1cddfc08d5f29ab3c719/7929576/package/xamarin.ios-16.5.0.291.pkg)
* [xamarin.mac-9.4.0.291.pkg](https://dl.internalx.com/wrench/merge/c5fb239069db9ad1555d1cddfc08d5f29ab3c719/7929576/package/xamarin.mac-9.4.0.291.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7929576&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18459/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-16 15:03 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7929576&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18459/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-16 15:05 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7929576&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18459/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-16 18:14 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 235 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 35 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230616.2/7929576//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7929576/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7929576&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [160290eae143031abe6856cb19ba9f1b90428827](https://github.com/xamarin/xamarin-macios/pull/18459/commits/160290eae143031abe6856cb19ba9f1b90428827)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-16 21:57 UTC, mandel-macaque approved these changes

2023-06-19 15:18 UTC, mandel-macaque commented
@rolfbjarne @dalexsoto I believe the is a valid change and the failures in the CI are not related to this commit, but due to an update on the allowed words by Microsoft in the source code, specially in the mon source code:
```
 Tool: PoliCheck: Rule: 80034 (Term: nuke. TermClass: Cultural. Action: Action : Context = In all other contexts.; ActionRecommendation = <b>REMOVE</b>; Context = When used an an abbreviation of nuclear weapon.; ActionRecommendation = <b>Replace</b> with "nuclear weapon" or "nuclear armament"; ). 
  Term: 'nuke'. Term class: Cultural. Term table: English-9. Position: Line: 137. Context(term at 16): '  displayName: 'Nuke Provisionator Tool Cache''
```
And some nonsense related to the Mac APIs:
```
Tool: PoliCheck: Rule: 203588 (Term: Orient. TermClass: Geopolitical. Action: Action : Context = When used in other contexts, such as to refer to positioning.; ActionRecommendation = <b>Leave term unchanged</b>; Context = When used to refer to the geographic region of East Asia.; ActionRecommendation = <b>Replace</b> with "East Asia" or "Asia"; Context = When used to refer to the Microsoft sales region.; ActionRecommendation = <b>Replace</b> with "Asia"; ). 
  Term: 'Orient'. Term class: Geopolitical. Term table: English-9. Position: Line: 261626. Context(term at 34): 'P:MonoMac.WebKit.DomOverflowEvent.Orient'.
```

2023-06-19 15:31 UTC, rolfbjarne approved these changes

2023-06-19 15:31 UTC, rolfbjarne commented
/azp run

2023-06-19 16:58 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7939913&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6](https://github.com/xamarin/xamarin-macios/pull/18459/commits/2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-19 17:11 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7939913&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18459/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-19 17:12 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=7939913&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18459/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-19 17:40 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/997186cf9befb0d21bb3829b946ecb1d) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d914b59966084715e61aa9106a9607d2) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/094e5b57eb3bb75021a77e1eb13f2391) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9063ade13a37c631f240eddac9498b20) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/593c4fb8d4c74bbe12d56387be97c123) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/36af2080f216ecb8be5cbbe52afe418c) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c9138a30713f02a2932228ecf1a9ba23) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7b2f8f7225482fe4ea4f44e0ad9f7a18) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c95be98608787f2c87946f2e00d25406)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a17a5e04d37b6619cd5aa612f3b6e579)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/91d3629c34f7689e829d3553aaa8aee4)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230619.7/7939913-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/72c0680cd4e1d8cfebd1a1e5d0ce137f)

</details>


## :white_check_mark: Generator diff

Generator diff is empty


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7939913&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6](https://github.com/xamarin/xamarin-macios/pull/18459/commits/2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-19 20:33 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 1 tests failed, 234 tests passed.

## Failures

### :x: mmp tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * mmptest/macOS/Debug: TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 35 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7939913&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6](https://github.com/xamarin/xamarin-macios/pull/18459/commits/2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-19 22:29 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 235 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mmp-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mmp-2&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 12 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 35 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230619.7/7939913//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/7939913/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=7939913&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6](https://github.com/xamarin/xamarin-macios/pull/18459/commits/2ed73a4e6cd620b71b373bf617b2b6a4fe3cf3c6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-06-20 05:27 UTC, merged