[Cinematic] Add support for Xcode 15 beta 5.
xamarin/xamarin-macios pull request #18686
Opened 2023-08-09 21:45 UTC by mandel-macaque

2023-08-09 22:04 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8229573&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ad994e7ea9090058d43c2cdd6254132a6d105ae5](https://github.com/xamarin/xamarin-macios/pull/18686/commits/ad994e7ea9090058d43c2cdd6254132a6d105ae5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-09 22:05 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8229573&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ad994e7ea9090058d43c2cdd6254132a6d105ae5](https://github.com/xamarin/xamarin-macios/pull/18686/commits/ad994e7ea9090058d43c2cdd6254132a6d105ae5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-09 22:06 UTC, mandel-macaque commented on src/rsp/dotnet/ios-defines-dotnet.rsp
> +-d:HAS_CINEMATICS
```suggestion
-d:HAS_CINEMATIC
```

2023-08-09 22:06 UTC, mandel-macaque commented on src/rsp/dotnet/maccatalyst-defines-dotnet.rsp
> +-d:HAS_CINEMATICS
```suggestion
-d:HAS_CINEMATIC
```

2023-08-09 22:07 UTC, mandel-macaque commented on src/rsp/dotnet/macos-defines-dotnet.rsp
> +-d:HAS_CINEMATICS
```suggestion
-d:HAS_CINEMATIC
```

2023-08-09 22:07 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8229573&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ad994e7ea9090058d43c2cdd6254132a6d105ae5](https://github.com/xamarin/xamarin-macios/pull/18686/commits/ad994e7ea9090058d43c2cdd6254132a6d105ae5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-09 22:07 UTC, mandel-macaque commented on src/rsp/dotnet/tvos-defines-dotnet.rsp
> +-d:HAS_CINEMATICS
```suggestion
-d:HAS_CINEMATIC
```

2023-08-09 22:07 UTC, mandel-macaque commented on src/rsp/ios-defines.rsp
> +-d:HAS_CINEMATICS
```suggestion
-d:HAS_CINEMATIC
```

2023-08-09 22:07 UTC, mandel-macaque commented on src/rsp/macos-defines.rsp
> +-d:HAS_CINEMATICS
```suggestion
-d:HAS_CINEMATIC
```

2023-08-09 22:07 UTC, mandel-macaque commented on src/rsp/tvos-defines.rsp
> +-d:HAS_CINEMATICS
```suggestion
-d:HAS_CINEMATIC
```

2023-08-09 22:10 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8229573&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ad994e7ea9090058d43c2cdd6254132a6d105ae5](https://github.com/xamarin/xamarin-macios/pull/18686/commits/ad994e7ea9090058d43c2cdd6254132a6d105ae5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 17:03 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8234004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [39f6fdd8b2c74a17504933bb4ab2eac139b6dae6](https://github.com/xamarin/xamarin-macios/pull/18686/commits/39f6fdd8b2c74a17504933bb4ab2eac139b6dae6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 17:03 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8234004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [39f6fdd8b2c74a17504933bb4ab2eac139b6dae6](https://github.com/xamarin/xamarin-macios/pull/18686/commits/39f6fdd8b2c74a17504933bb4ab2eac139b6dae6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 17:04 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8234004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [39f6fdd8b2c74a17504933bb4ab2eac139b6dae6](https://github.com/xamarin/xamarin-macios/pull/18686/commits/39f6fdd8b2c74a17504933bb4ab2eac139b6dae6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 17:09 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8234004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [39f6fdd8b2c74a17504933bb4ab2eac139b6dae6](https://github.com/xamarin/xamarin-macios/pull/18686/commits/39f6fdd8b2c74a17504933bb4ab2eac139b6dae6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 17:50 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8234248&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [089f339137ede5627853121d29b58684797afcd3](https://github.com/xamarin/xamarin-macios/pull/18686/commits/089f339137ede5627853121d29b58684797afcd3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 17:51 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8234248&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [089f339137ede5627853121d29b58684797afcd3](https://github.com/xamarin/xamarin-macios/pull/18686/commits/089f339137ede5627853121d29b58684797afcd3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 17:58 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8234248&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [089f339137ede5627853121d29b58684797afcd3](https://github.com/xamarin/xamarin-macios/pull/18686/commits/089f339137ede5627853121d29b58684797afcd3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-10 18:04 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8234248&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [089f339137ede5627853121d29b58684797afcd3](https://github.com/xamarin/xamarin-macios/pull/18686/commits/089f339137ede5627853121d29b58684797afcd3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 17:34 UTC, mandel-macaque commented on src/Cinematic/CNDecision.cs
> +		public CNDecision (CMTime time, long detectionID, bool isStrong, CNDecisionIdentifierType identifierType)
No need for attr using the default ones from the class.

2023-08-17 17:43 UTC, mandel-macaque commented on src/Cinematic/CNDecision.cs
> +	[UnsupportedOSPlatform ("tvos17.0")]
```suggestion
	[SupportedOSPlatform ("tvos17.0")]
```

2023-08-17 18:24 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8268790&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b791d02f71fd27bba612e1ee71b6921f32863609](https://github.com/xamarin/xamarin-macios/pull/18686/commits/b791d02f71fd27bba612e1ee71b6921f32863609)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 18:34 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8268865&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [743d1d72bb564c56d8970fe1da78979cb0dffbde](https://github.com/xamarin/xamarin-macios/pull/18686/commits/743d1d72bb564c56d8970fe1da78979cb0dffbde)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 19:07 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8268865&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [743d1d72bb564c56d8970fe1da78979cb0dffbde](https://github.com/xamarin/xamarin-macios/pull/18686/commits/743d1d72bb564c56d8970fe1da78979cb0dffbde)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 19:13 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.109.pkg](https://dl.internalx.com/wrench/merge/31660daf7d970f34c7c434c58d739ea77749cf78/8268865/package/xamarin.ios-16.99.0.109.pkg)
* [xamarin.mac-9.99.0.109.pkg](https://dl.internalx.com/wrench/merge/31660daf7d970f34c7c434c58d739ea77749cf78/8268865/package/xamarin.mac-9.99.0.109.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8268865&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 19:24 UTC, mandel-macaque commented
/azp run

2023-08-17 20:35 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8269510&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [743d1d72bb564c56d8970fe1da78979cb0dffbde](https://github.com/xamarin/xamarin-macios/pull/18686/commits/743d1d72bb564c56d8970fe1da78979cb0dffbde)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 20:52 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.109.pkg](https://dl.internalx.com/wrench/merge/31660daf7d970f34c7c434c58d739ea77749cf78/8269510/package/xamarin.ios-16.99.0.109.pkg)
* [xamarin.mac-9.99.0.109.pkg](https://dl.internalx.com/wrench/merge/31660daf7d970f34c7c434c58d739ea77749cf78/8269510/package/xamarin.mac-9.99.0.109.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8269510&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 21:13 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8269510&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [743d1d72bb564c56d8970fe1da78979cb0dffbde](https://github.com/xamarin/xamarin-macios/pull/18686/commits/743d1d72bb564c56d8970fe1da78979cb0dffbde)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-17 21:14 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/74a2f0d549e04895998e99dcb03c299f) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d7d6bde40953a7f49fb056ca38659944) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8d8f19e8993a17a0df96ddbea4d9d292) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/88899bc1e7749fb57d969b81a805cbdc) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8db7628f83861d0310893110d179cce0) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ff523c868c11df2164ca29f4addc3191) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1b2682f98778e1b9f3fd7d9f8bc5b8b9) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e6ffc23a2d9872ba47f1b50e11bd8d3d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e9e30f07c258fdc268c8e338917e6a31) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/98ab98248fbf26cfeef65d183ba24d5c) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d2fe1ae77e8262e5dc4fd57502b48fc4) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bfdafda90f4c34e279519d69823c690d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/40b39d776fbe34bef7c8efb56d17f29a) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bda498657f0720bfdebd297a86f14b0a) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/47c8bd46b585b2817e2333404dea5b9a) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/15fdd83a5304aeef514d4076ca78a2b7)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0138d1f16ba78a9c058b5c2e62400929)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c01b9e0429e33ba786f3d104505f6e7b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1aec74b3e02b55757fd389c77d3ac0d2)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230817.16/8269510-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/51ad4847d833ad7b9720a90a093defca) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8269510&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [743d1d72bb564c56d8970fe1da78979cb0dffbde](https://github.com/xamarin/xamarin-macios/pull/18686/commits/743d1d72bb564c56d8970fe1da78979cb0dffbde)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 01:02 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

4 tests crashed, 17 tests failed, 207 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>5 tests failed, 8 tests passed.</summary>
<details>

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug: Failed
 * introspection/tvOS - simulator/Debug [dotnet]: Failed
 * introspection/tvOS - simulator/Debug: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>2 tests failed, 36 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 2 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

### :x: xtro tests

:fire: Failed catastrophically on VSTS: simulator tests - xtro (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8269510/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230817.16/8269510//simulator_install_source-1/;/tests/vsdrop [...]

2023-08-18 01:58 UTC, dalexsoto approved these changes

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		long DetectionID { get; }
Not an acronym 
```suggestion
		long DetectionId { get; }
```

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		long DetectionGroupID { get; }
```suggestion
		long DetectionGroupId { get; }
```

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		bool IsValidDetectionID (long detectionID);
```suggestion
		bool IsValidDetectionId (long detectionId);
```

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		bool IsValidDetectionGroupID (long detectionGroupID);
```suggestion
		bool IsValidDetectionGroupId (long detectionGroupId);
```

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		long DetectionID { get; }
```suggestion
		long DetectionId { get; }
```

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		long DetectionGroupID { get; }
```suggestion
		long DetectionGroupId { get; }
```

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		CNDetection GetDetectionForID (long detectionID);
```suggestion
		CNDetection GetDetectionForId (long detectionId);
```

2023-08-18 01:58 UTC, dalexsoto commented on src/cinematic.cs
> +		CNDetection GetBestDetectionForGroupID (long detectionGroupID);
```suggestion
		CNDetection GetBestDetectionForGroupId (long detectionGroupId);
```

2023-08-18 15:02 UTC, rolfbjarne requested changes

2023-08-18 15:02 UTC, rolfbjarne commented on src/cinematic.cs
> +		CNDetectionTrack GetDetectionTrackForID (long detectionID);
```suggestion
		CNDetectionTrack GetDetectionTrackForId (long detectionId);
```

2023-08-18 15:02 UTC, rolfbjarne commented on src/cinematic.cs
> +		bool StartTrackingAt (CMTime time, CGRect normalizedBounds, CVPixelBuffer sourceImage, CVPixelBuffer sourceDisparity);
```suggestion
		bool StartTracking (CMTime atTime, CGRect normalizedBounds, CVPixelBuffer sourceImage, CVPixelBuffer sourceDisparity);
```

2023-08-18 15:02 UTC, rolfbjarne commented on src/cinematic.cs
> +		CNBoundsPrediction ContinueTrackingAt (CMTime time, CVPixelBuffer sourceImage, CVPixelBuffer sourceDisparity);
```suggestion
		CNBoundsPrediction ContinueTracking (CMTime atTime, CVPixelBuffer sourceImage, CVPixelBuffer sourceDisparity);
```

2023-08-18 17:02 UTC, mandel-macaque commented on src/cinematic.cs
> +		long DetectionID { get; }
Dotnet uses ID: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions and we have more frameworks using ID than Id in our source.

2023-08-18 17:02 UTC, mandel-macaque commented on src/cinematic.cs
> +		long DetectionGroupID { get; }
Same.

2023-08-18 17:31 UTC, mandel-macaque commented on src/cinematic.cs
> +		bool IsValidDetectionID (long detectionID);
Same.

2023-08-18 17:31 UTC, mandel-macaque commented on src/cinematic.cs
> +		bool IsValidDetectionGroupID (long detectionGroupID);
Same

2023-08-18 17:31 UTC, mandel-macaque commented on src/cinematic.cs
> +		long DetectionGroupID { get; }
Same

2023-08-18 17:31 UTC, mandel-macaque commented on src/cinematic.cs
> +		long DetectionID { get; }
Same.

2023-08-18 17:31 UTC, mandel-macaque commented on src/cinematic.cs
> +		long DetectionGroupID { get; }
Same.

2023-08-18 17:32 UTC, mandel-macaque commented on src/cinematic.cs
> +		CNDetectionTrack GetDetectionTrackForID (long detectionID);
Same.

2023-08-18 17:32 UTC, mandel-macaque commented on src/cinematic.cs
> +		CNDetection GetDetectionForID (long detectionID);
Same.

2023-08-18 17:32 UTC, mandel-macaque commented on src/cinematic.cs
> +		CNDetection GetBestDetectionForGroupID (long detectionGroupID);
Same.

2023-08-18 17:32 UTC, mandel-macaque commented on src/cinematic.cs
> +		long DetectionID { get; }
Same.

2023-08-18 17:58 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8275400&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [55b444be41213daa1a498feed5caa9c45e9945fe](https://github.com/xamarin/xamarin-macios/pull/18686/commits/55b444be41213daa1a498feed5caa9c45e9945fe)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 18:00 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8275400&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [55b444be41213daa1a498feed5caa9c45e9945fe](https://github.com/xamarin/xamarin-macios/pull/18686/commits/55b444be41213daa1a498feed5caa9c45e9945fe)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 18:01 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8275400&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [55b444be41213daa1a498feed5caa9c45e9945fe](https://github.com/xamarin/xamarin-macios/pull/18686/commits/55b444be41213daa1a498feed5caa9c45e9945fe)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 18:11 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8275400&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [55b444be41213daa1a498feed5caa9c45e9945fe](https://github.com/xamarin/xamarin-macios/pull/18686/commits/55b444be41213daa1a498feed5caa9c45e9945fe)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 20:58 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8276533&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fc7022c6aa95a1035ca77121f992e534ebaf3850](https://github.com/xamarin/xamarin-macios/pull/18686/commits/fc7022c6aa95a1035ca77121f992e534ebaf3850)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 21:33 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8276533&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fc7022c6aa95a1035ca77121f992e534ebaf3850](https://github.com/xamarin/xamarin-macios/pull/18686/commits/fc7022c6aa95a1035ca77121f992e534ebaf3850)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 21:45 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.112.pkg](https://dl.internalx.com/wrench/merge/e809dc2b2db67eebd21597853c14d05d6dc44b62/8276533/package/xamarin.ios-16.99.0.112.pkg)
* [xamarin.mac-9.99.0.112.pkg](https://dl.internalx.com/wrench/merge/e809dc2b2db67eebd21597853c14d05d6dc44b62/8276533/package/xamarin.mac-9.99.0.112.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8276533&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 21:50 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/effa690bc12246da5b41d5895ec81bab) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bd3bb1983c52543bc5977177fe47b19b) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3e69385417eb3db3e3c2f8a819fd6185) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/90c294527c8b21e99033d52918a66a21) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/19589d5f68ca6387cf40f3123bb81aa0) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f67187ab4dce134122942cf90a4e8aba) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2133ec0e58f41ed1af3fede476894411) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e6451ad1bc748b047e60d34d7b7fb204) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6a0c736d358ed2c870d11e5bba4fbc31) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/aef9e167fdb22d5bf1f185e0dd5b2c9b) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d9ca47aac33cebae4f1fbe0221b25b97) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/07e8e8d1283517600b9f3301b4e7a7ab) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fb03b9fdf6abdae356a08cd939d16baa) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/cd709118b0f68b807e7c5c08066d5b4b) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d111a9d571ace8a0f054415e09f69e52) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f79a2a48143d45068b3dcaf0de99d626)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6f1d46c2046cb704a7fc6e02147219ee)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4c87fa08b074e91d83d371e510fe5025)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6d892965d805391d35a63cfdfc3b1c2c)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230818.15/8276533-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1e30dee4e30d2199bbdb5023c55fc0f9) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8276533&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [fc7022c6aa95a1035ca77121f992e534ebaf3850](https://github.com/xamarin/xamarin-macios/pull/18686/commits/fc7022c6aa95a1035ca77121f992e534ebaf3850)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-18 23:44 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 17 tests failed, 220 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>5 tests failed, 8 tests passed.</summary>
<details>

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug: Failed
 * introspection/tvOS - simulator/Debug [dotnet]: Failed
 * introspection/tvOS - simulator/Debug: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>2 tests failed, 36 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230818.15/8276533//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8276533/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: [...]

2023-08-22 19:13 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8291252&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8d077968ac51880d2ba5abc4540047ef55e048aa](https://github.com/xamarin/xamarin-macios/pull/18686/commits/8d077968ac51880d2ba5abc4540047ef55e048aa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-22 19:48 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8291252&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8d077968ac51880d2ba5abc4540047ef55e048aa](https://github.com/xamarin/xamarin-macios/pull/18686/commits/8d077968ac51880d2ba5abc4540047ef55e048aa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-22 20:01 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.115.pkg](https://dl.internalx.com/wrench/merge/d65056ac68066fd2f2f7f2708dd698598c6080e0/8291252/package/xamarin.ios-16.99.0.115.pkg)
* [xamarin.mac-9.99.0.115.pkg](https://dl.internalx.com/wrench/merge/d65056ac68066fd2f2f7f2708dd698598c6080e0/8291252/package/xamarin.mac-9.99.0.115.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8291252&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-22 20:10 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c20eb5f246f48260d85a300ab2f6b8b7) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5a602d0a9d2b18ba671e6400ab7ad9c0) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/cb5fdf1f78e0d1532a002a00c9f25512) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/03b6ef2bdf8dbf37ed434b25367388df) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b7c02bfb5eb23173a42cdff2ca0ed440) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/db945a964947490485fb44736cebd048) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3f5cb1dcff42dfa7d13f6ef83e72ebb2) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b72d72e0ff1b872d2015ad881ed87e47) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fc7e1f83f8872cc0729bcc59622aa80e) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/62191e1623961a59960aceccbeca6864) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6fb446f2e929f1ef89d2786fb5397b51) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9a2523615b2ccd2d408813ebdb5d35a2) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1d10ac12afc58f2178ade9dac252b745) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ae9e4e67f12b69ef7e6f802e44eb50ad) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e6c2a2867e41cd66ccce9ee97e2cece8) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/352878a56443911e48b105b33f5259ce)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3ccd927d586bc7d2c1198c13c38ca6db)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6812c9287ae9e81def40a90ca4985fc4)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/353cb85d55d64b7fcb87bc939f0002a1)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230822.13/8291252-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ff32b9985eae3062b0ddd9adbd3d8267) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8291252&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8d077968ac51880d2ba5abc4540047ef55e048aa](https://github.com/xamarin/xamarin-macios/pull/18686/commits/8d077968ac51880d2ba5abc4540047ef55e048aa)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-22 21:36 UTC, tj-devel709 commented on src/cinematic.cs
> +		bool EncodeRender (IMTLCommandBuffer commandBuffer, CNRenderingSessionFrameAttributes frameAttributes, CVPixelBuffer sourceImage, CVPixelBuffer sourceDisparity, IMTLTexture destinationRGBA);
```suggestion
		bool EncodeRender (IMTLCommandBuffer commandBuffer, CNRenderingSessionFrameAttributes frameAttributes, CVPixelBuffer sourceImage, CVPixelBuffer sourceDisparity, IMTLTexture destinationRgba);
```
not quite sure if I remember the rule, but should this be as such?

2023-08-22 21:38 UTC, tj-devel709 approved these changes
Left a small thing to check, but other than that, LGTM

2023-08-22 23:58 UTC, haritha-mohan approved these changes

2023-08-23 00:05 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

9 tests crashed, 5 tests failed, 101 tests passed.

## Failures

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

:fire: Failed catastrophically on VSTS: simulator tests - introspection (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

:fire: Failed catastrophically on VSTS: simulator tests - linker (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: simulator tests - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230822.13/8291252//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8291252/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-t [...]

2023-08-23 05:37 UTC, rolfbjarne requested changes

2023-08-23 05:37 UTC, rolfbjarne commented on src/Cinematic/CNDecision.cs
> +		{
I believe you should call base with NSObjectFlag.Empty here:

```suggestion
		public CNDecision (CMTime time, long detectionId, bool isStrong, CNDecisionIdentifierType identifierType)
			: base (NSObjectFlag.Empty)
		{
```

2023-08-23 15:47 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8296738&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3c1c2d483a22e88eae0ff6eedeb5396813fca936](https://github.com/xamarin/xamarin-macios/pull/18686/commits/3c1c2d483a22e88eae0ff6eedeb5396813fca936)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-23 17:14 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8296826&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c00102c5794c5db489f85295a9efebea5ad99995](https://github.com/xamarin/xamarin-macios/pull/18686/commits/c00102c5794c5db489f85295a9efebea5ad99995)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-23 17:20 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/88beae2bfccb829a50241b9b51888eaa) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1e18d1ff15f591c3012d20b9836ea91f) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5530808abad166fe854a2ad93158ba77) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/247c757167a0d657faef606651026573) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9decad017652df066299a3464f831cc3) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8fea3b3871cca9f1feaf768c5129cf4c) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/254394281317eca4fb4e5712ed37c8ad) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/434c59cbe9d59123affe636ed6200ce3) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b9a4903e385c557a25f6a6ecd764f730) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2d5520fd644a14f7f52b740074a6a473) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9046274d2cd1300e95b5159008a312e6) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a164b350bc5832479888318c98b51433) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/962bb3eeace78fdc90c543340ac599b3) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c732cae99b7f79d3bca1bd39c2b10092) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/01735e57a6c568be371f45185acd3714) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8f5e6149098cffc1aff1f2e9c724e64c)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/09bf80bd261d9d6e4118c1fa7173cff6)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6420204ed8912c3232092f2c079f622b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/395166b84316da18a803fd8d0ec46538)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230823.16/8296826-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/dcd6daf99e16e4c24f1af1591365e2d9) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8296826&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c00102c5794c5db489f85295a9efebea5ad99995](https://github.com/xamarin/xamarin-macios/pull/18686/commits/c00102c5794c5db489f85295a9efebea5ad99995)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-23 17:30 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.121.pkg](https://dl.internalx.com/wrench/merge/3d2b852bb4c943cd7c3a851c87426b55066001e5/8296826/package/xamarin.ios-16.99.0.121.pkg)
* [xamarin.mac-9.99.0.121.pkg](https://dl.internalx.com/wrench/merge/3d2b852bb4c943cd7c3a851c87426b55066001e5/8296826/package/xamarin.mac-9.99.0.121.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8296826&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-23 22:07 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 13 tests failed, 224 tests passed.

## Failures

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 12 tests passed.</summary>
<details>

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>3 tests failed, 35 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Release [dotnet]: Failed (Test run crashed (exit code: 255).
Test run crashed)
 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8296826/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230823.16/8296826//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis [...]

2023-08-24 16:47 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8303030&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3ea1786b131dd29e237c2b3678d15b881129e633](https://github.com/xamarin/xamarin-macios/pull/18686/commits/3ea1786b131dd29e237c2b3678d15b881129e633)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-24 16:50 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.122.pkg](https://dl.internalx.com/wrench/merge/e3613b32974436e1240150329315dcdb9164970d/8303030/package/xamarin.ios-16.99.0.122.pkg)
* [xamarin.mac-9.99.0.122.pkg](https://dl.internalx.com/wrench/merge/e3613b32974436e1240150329315dcdb9164970d/8303030/package/xamarin.mac-9.99.0.122.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8303030&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-24 16:57 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8303030&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-24 17:05 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f031f1a00fcdbcc4a215a1c6af1a0946) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f0c1bbf107a32f9154893ada1fca23f3) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2094d0977e99a5268d55e2b26caf19a3) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1cc8f13fe081e3ea2c8e38e50a25ce26) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4134e4ce9200e47a6330c51fa1be2b79) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/11372106c8b8319276bdd3a7a7677e12) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a5992e2b76fb9a081189e7e481c47e8d) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7239c61026e3bd25c916e912df87aa91) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3248b90d98d80dbab0daad0f31ecfbe5) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ae768310e98ffe271837ba3d08183d1d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fa87effc0ca17d0919c717a8e316835d) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/eb843830fcbf778785b0abcd1b9f9802) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0803ddecec378b752c656d6e2a53584a) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/126ab768ebd32d01af71e9aaa040bcac) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/cd9a601755e9bce3e059a046eea996f6) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/15d39d0371a88f6e5ede4930bc974ff2)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ec06f6dffc87387efa7551a464d7abab)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d771bfc7bf8b19721f163676f9698748)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7351f978ec3cab210ac99025cd8e31f0)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230824.9/8303030-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/88198940ed5127ca5249e625e0575a10) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8303030&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3ea1786b131dd29e237c2b3678d15b881129e633](https://github.com/xamarin/xamarin-macios/pull/18686/commits/3ea1786b131dd29e237c2b3678d15b881129e633)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-24 20:55 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

6 tests crashed, 1 tests failed, 184 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)

### :x: mac_binding_project tests

:fire: Failed catastrophically on VSTS: simulator tests - mac_binding_project (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

### :x: xcframework tests

:fire: Failed catastrophically on VSTS: simulator tests - xcframework (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

### :x: xtro tests

:fire: Failed catastrophically on VSTS: simulator tests - xtro (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 13 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230824.9/8303030//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8303030/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/in [...]

2023-08-25 18:21 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8309936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-25 18:23 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8309936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [dee710f8d08f77009b11298a38be3ba201f78f0f](https://github.com/xamarin/xamarin-macios/pull/18686/commits/dee710f8d08f77009b11298a38be3ba201f78f0f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-25 18:27 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8309936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-25 18:38 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4e5790059b896c71284396e7e7380c8a) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8811b66e2c4574fc3478505283efb2b0) (No breaking changes)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fe608e850bfff58d0e89bb2eeb06488b) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6f1dfd6897444ada9333296e2040a239) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c861209147217e5e4fb437fca984c6f2) (No breaking changes)
* ~MacCatalyst~: (empty diff detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bd12ac1cba5670c83d2142cabd21fdc3) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a3014cc0b76008db760ef1e1d5d591de) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/adf47ac4bc4f3c0a87a3e98c73cc47fd) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3feaa9b06357c05c52a98004ef8178e1) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6d174ad0d92095b85820b32f3edf8abd) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/14e13aa80929e26cd556a4c98b57e691) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7722f9fec794b640466f5b154c7becbd) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bda6b1b2e7406eb9e7734dd1350c4a3a) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6beed291642478a7deb895960d6d935b) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/33a4aba92c395bc22d19923698e24fcb)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/73b46bb3b78f988a1b8fd15143eae380)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/291a78292ef786dce097f16ca7e8d351)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/23df407ad4874eedf1b9a529a4ee2910)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230825.25/8309936-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b10e758717de1be174002c642d85591f) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8309936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [dee710f8d08f77009b11298a38be3ba201f78f0f](https://github.com/xamarin/xamarin-macios/pull/18686/commits/dee710f8d08f77009b11298a38be3ba201f78f0f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-25 18:48 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.123.pkg](https://dl.internalx.com/wrench/merge/31f9f23c3c82e899c35185c9b2d9f63038e10444/8309936/package/xamarin.ios-16.99.0.123.pkg)
* [xamarin.mac-9.99.0.123.pkg](https://dl.internalx.com/wrench/merge/31f9f23c3c82e899c35185c9b2d9f63038e10444/8309936/package/xamarin.mac-9.99.0.123.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8309936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18686/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-25 22:31 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

5 tests crashed, 0 tests failed, 188 tests passed.

## Failures

### :x: mmp tests

:fire: Failed catastrophically on VSTS: simulator tests - mmp (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)

### :x: monotouch tests

:fire: Failed catastrophically on VSTS: simulator tests - monotouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: msbuild tests

:fire: Failed catastrophically on VSTS: simulator tests - msbuild (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: simulator tests - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 13 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8309936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [dee710f8d08f77009b11298a38be3ba201f78f0f](https://github.com/xamarin/xamarin-macios/pull/18686/commit [...]

2023-08-28 11:35 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 237 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 13 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mmp-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mmp-2&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mononative-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mononative-2&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 38 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_monotouch-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_monotouch-2&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_msbuild-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_msbuild-2&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_mtouch-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_mtouch-2&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230825.25/8309936//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8309936/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8309936&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [dee710f8d08f77009b11298a38be3ba201f78f0f](https://github.com/xamarin/xamarin-macios/pull/18686/commits/dee710f8d08f77009b11298a38be3ba201f78f0f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-28 18:59 UTC, merged