[MapKit] Add support for Xcode 15 beta 7
xamarin/xamarin-macios pull request #18877
Opened 2023-08-30 18:02 UTC by haritha-mohan

2023-08-30 18:09 UTC, mandel-macaque requested changes

2023-08-30 18:09 UTC, mandel-macaque commented on src/mapkit.cs
> +		[Deprecated (PlatformName.TvOS, 17, 0, message: "Use preferredConfiguration.")]
```suggestion
		[Deprecated (PlatformName.MacOSX, 14, 0, message: "Use 'PreferredConfiguration' instead.")]
		[Deprecated (PlatformName.iOS, 17, 0, message: "Use 'PreferredConfiguration' instead.")]
		[Deprecated (PlatformName.MacCatalyst, 17, 0, message: "Use 'PreferredConfiguration' instead.")]
		[Deprecated (PlatformName.TvOS, 17, 0, message: "Use 'PreferredConfiguration' instead.")]
```

2023-08-30 20:22 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/952c636e4212a7f02f5c6e41e33e8194) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/313cef6afaa1fc63a7e06f3f839c6e85) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fb7e4f1552fe2a65116c63bbe4796ab2) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/52e5f5d20b109e613ba064cc78d30c91) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a41002ba5d82faf16ce25b8bf3d0b8eb) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c1f828a8f029b52da09f60df86a37b20) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b69d3ee37799740ef7aec8dc4af18280) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/964791ebf871bf5db7d3bc5794d698ef) (No breaking changes)

</details>


## :heavy_exclamation_mark: API diff vs stable (Breaking changes)

<details><summary>Legacy Xamarin (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/086111aeac739b14036b8fc1587f1e1d) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2e76f8248e245b7ca92f20e31bb67c91) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e3813dd322c16a8bfb53e28784694295) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ae6f150abe8b8ea71488c926767d0488) (No breaking changes)

</details>

<details><summary>.NET (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/40e0af81383bb602a145943aa3904447) (:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4ded05613f41d17a003a9dd9d36d4386) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4411b67367ba883c4038474c39396867) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/588016ff46ee3004da600c6b38b04457) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e3078f3e8e3c27b61796967774d42e93)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/38d6edda505bcf33f5bd007f239e46aa)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/08d59cd3a4ccc0532a8092f998fb0d5f)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/760de4694a4d10dcdcb3283aa3ba8af0)

</details>


<!-- BreakingChangesDetected -->


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230830.24/8333472-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6384c66e06d2a2c6a6bd6077f911f99c) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8333472&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7](https://github.com/xamarin/xamarin-macios/pull/18877/commits/5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-31 06:15 UTC, rolfbjarne approved these changes

2023-08-31 19:31 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8333472&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7](https://github.com/xamarin/xamarin-macios/pull/18877/commits/5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-31 19:37 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8333472&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18877/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-31 19:37 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8333472&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18877/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-31 19:38 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.99.0.162.pkg](https://dl.internalx.com/wrench/merge/c8baedfcc6e4bb696452e3bdd96d4c5d6e9e30f4/8333472/package/xamarin.ios-16.99.0.162.pkg)
* [xamarin.mac-9.99.0.162.pkg](https://dl.internalx.com/wrench/merge/c8baedfcc6e4bb696452e3bdd96d4c5d6e9e30f4/8333472/package/xamarin.mac-9.99.0.162.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8333472&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18877/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-08-31 19:44 UTC, mandel-macaque approved these changes

2023-08-31 23:39 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

1 tests crashed, 0 tests failed, 231 tests passed.

## Failures

### :x: mononative tests

:fire: Failed catastrophically on VSTS: simulator tests - mononative (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 13 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 38 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8333472&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7](https://github.com/xamarin/xamarin-macios/pull/18877/commits/5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-01 20:48 UTC, dalexsoto approved these changes

2023-09-01 21:52 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 237 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 13 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mononative-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mononative-2&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 38 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230830.24/8333472//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8333472/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8333472&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7](https://github.com/xamarin/xamarin-macios/pull/18877/commits/5d6bdb5d3001bf83ddbc2fef8eb2302b2aa1cbf7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-05 12:22 UTC, merged