[AppKit] Add missing NSView.ClipsToBounds. Fixes #18916.
xamarin/xamarin-macios pull request #18924
Opened 2023-09-05 06:50 UTC by rolfbjarne

Fixes https://github.com/xamarin/xamarin-macios/issues/18916.

2023-09-05 08:20 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8352818&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18924/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-05 08:20 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8352818&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18924/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-05 08:58 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8352818&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [bcab92f7a6c5a2cbfd1046d06a26dd54188cb284](https://github.com/xamarin/xamarin-macios/pull/18924/commits/bcab92f7a6c5a2cbfd1046d06a26dd54188cb284)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-05 09:05 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.408.pkg](https://dl.internalx.com/wrench/merge/ac3dbb061e76fa4841cbffadd25d8aca75091ea5/8352818/package/xamarin.ios-16.5.0.408.pkg)
* [xamarin.mac-9.4.0.408.pkg](https://dl.internalx.com/wrench/merge/ac3dbb061e76fa4841cbffadd25d8aca75091ea5/8352818/package/xamarin.mac-9.4.0.408.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8352818&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/18924/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-05 09:07 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3957b36c9336da0c0cdb3e19629e48b1) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0f0df4f4e7968fc80a110b870a53402d) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/97baeb139847164d80f00d2ab92e080c) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0c8720fdaa8d9a274cc0090e96510288) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/56c64b2d65ab13a692902af50c4245da) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/85ff2dc8a40bfebd3d22a00650fc5906) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f18b4b449eb1089ece9faf8383b8fec4) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b6730b379fa6e4680992ad7e3425c57a) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net7.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1541a12be7c238e8fa5421512014ab76) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/05879509ccdbb9d3a2d9545430d39d7c) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4de9f4078730d57f13362e4b5a389e75)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net7.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5cc4ebe4fdeb6207a1e10cf10c6212d0)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net7.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6de7c68d7dd327ff8507b48cb8fe1666)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net7.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/58a031a7d4e640796b071b568209e687)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230905.4/8352818-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/43e9554fc934cc9aa1968dfe5adc09ed) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8352818&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [bcab92f7a6c5a2cbfd1046d06a26dd54188cb284](https://github.com/xamarin/xamarin-macios/pull/18924/commits/bcab92f7a6c5a2cbfd1046d06a26dd54188cb284)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-05 21:04 UTC, dalexsoto approved these changes

2023-09-05 23:02 UTC, haritha-mohan requested changes
there's a few todos to be addressed

- api-annotations-dotnet/macOS-AppKit.todo:!missing-selector! NSView::clipsToBounds not bound
- macOS-AppKit.todo:!missing-selector! NSView::clipsToBounds not bound

2023-09-06 10:20 UTC, rolfbjarne commented
> there's a few todos to be addressed
> 
> * api-annotations-dotnet/macOS-AppKit.todo:!missing-selector! NSView::clipsToBounds not bound
> * macOS-AppKit.todo:!missing-selector! NSView::clipsToBounds not bound

@haritha-mohan it looks like Apple only added this selector to their headers in Xcode 15 (although their documentation says the selector is available since macOS 10.9, and all the tests pass), so these xtro entries only show up in the `net8.0-xcode15` branch (and not `main`, which this PR is targeting). This means that the xtro todos will only have to be fixed once `main` is merged into `net8.0-xcode15`.

2023-09-06 14:33 UTC, haritha-mohan commented
@rolfbjarne ah, didn't realize this was going into main. sounds good!

2023-09-06 14:42 UTC, merged