Implementing Feature Switch for CFNetworkHandler and NSUrlSessionHandler
xamarin/xamarin-macios pull request #19003
Opened 2023-09-12 15:17 UTC by Agnik7

This PR is with respect to Issue #14298 . 

Changes made:
- Added the `UseCFNetworkHandler` and `UseNSUrlSessionHandler` properties.
- Computed the values for the aforementioned properties.
- Added two new RuntimeHostConfigurationOption entries.
- Updated the `RuntimeOptions.cs` to use the two new Runtime properties.

2023-09-12 15:18 UTC, Agnik7 commented
@rolfbjarne I have made the changes you requested. Kindly review.

2023-09-13 09:26 UTC, rolfbjarne commented
/azp run

2023-09-13 10:09 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Detect API changes'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8390455&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ee19d849f6be570f0ffebea2ea6cb6245f815e85](https://github.com/xamarin/xamarin-macios/pull/19003/commits/ee19d849f6be570f0ffebea2ea6cb6245f815e85)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-13 10:10 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8390455&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ee19d849f6be570f0ffebea2ea6cb6245f815e85](https://github.com/xamarin/xamarin-macios/pull/19003/commits/ee19d849f6be570f0ffebea2ea6cb6245f815e85)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-13 10:15 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8390455&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ee19d849f6be570f0ffebea2ea6cb6245f815e85](https://github.com/xamarin/xamarin-macios/pull/19003/commits/ee19d849f6be570f0ffebea2ea6cb6245f815e85)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-13 10:33 UTC, Agnik7 commented
> The changes don't compile:
> 
> ```
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(41,16): error CS1061: 'RuntimeOptions' does not contain a definition for 'UseCFNetworkHandler' and no accessible extension method 'UseCFNetworkHandler' accepting a first argument of type 'RuntimeOptions' could be found (are you missing a using directive or an assembly reference?) [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(41,38): error CS0103: The name '_IsCFNetworkHandlerFeature' does not exist in the current context [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(42,16): error CS1061: 'RuntimeOptions' does not contain a definition for 'UseNSUrlSessionHandler' and no accessible extension method 'UseNSUrlSessionHandler' accepting a first argument of type 'RuntimeOptions' could be found (are you missing a using directive or an assembly reference?) [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(42,41): error CS0103: The name '_IsNSUrlSessionHandlerFeature' does not exist in the current context [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(108,9): error CS0103: The name 'UseCFNetworkHandler' does not exist in the current context [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(109,23): error CS0246: The type or namespace name 'CFNetworkHandler' could not be found (are you missing a using directive or an assembly reference?) [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(112,16): error CS0103: The name 'handler_name' does not exist in the current context [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(112,44): error CS0103: The name 'handler_name' does not exist in the current context [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(113,16): error CS0103: The name 'Runtime' does not exist in the current context [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(113,34): error CS0103: The name 'handler_name' does not exist in the current context [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
>          /Users/builder/azdo/_work/2/s/xamarin-macios/src/ObjCRuntime/RuntimeOptions.cs(114,23): error CS0246: The type or namespace name 'NSUrlSessionHandler' could not be found (are you missing a using directive or an assembly reference?) [/Users/builder/azdo/_work/2/s/xamarin-macios/tools/dotnet-linker/dotnet-linker.csproj]
> ```
> 
> did you try to [build locally](https://github.com/xamarin/xamarin-macios/wiki/Build-&-Run)?

@rolfbjarne  I wasn't able to build it locally since I have a Windows system, so I just wrote the code. Is it possible for you to build locally and suggest the required changes?

2023-09-13 17:08 UTC, rolfbjarne commented
> @rolfbjarne I wasn't able to build it locally since I have a Windows system, so I just wrote the code. Is it possible for you to build locally and suggest the required changes?

At that point I'll end up doing more work than if I were to do it myself...

To work on this project you really need a Mac to be able to build and test your changes.

2023-09-13 17:13 UTC, Agnik7 commented
So....what should I do now?? Do you have any ideas?? Really sorry for the inconvinience caused

2023-09-14 00:35 UTC, dalexsoto commented
@Agnik7 Thank you for your contribution, we are a bit busy right now but we will try to get back to you as soon as possible, as @rolfbjarne mentioned you do need a Mac in order to build this project and do appreciate the intent so give us some time in order to move forward.

2023-09-14 00:37 UTC, Agnik7 commented
Ok

2023-09-18 01:56 UTC, dalexsoto commented
/azp run

2023-09-18 03:26 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8408023&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19003/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-18 03:28 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8408023&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19003/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-18 03:29 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.906.pkg](https://dl.internalx.com/wrench/merge/d963b96c4d22c6eccdb79f327fef5dc2d1f1ea9c/8408023/package/xamarin.ios-16.5.0.906.pkg)
* [xamarin.mac-9.4.0.906.pkg](https://dl.internalx.com/wrench/merge/d963b96c4d22c6eccdb79f327fef5dc2d1f1ea9c/8408023/package/xamarin.mac-9.4.0.906.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8408023&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19003/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-18 03:34 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8408023&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d9902b86e2559a7a20f9f86903bed356946d9c36](https://github.com/xamarin/xamarin-macios/pull/19003/commits/d9902b86e2559a7a20f9f86903bed356946d9c36)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-18 03:46 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/93007c407ef1a926422ec5f8f5de6983) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/704c53d1f8792be8341c8012b369e1bb) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5210768d59a6bfd08a09355dfb588e99) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6aa8d75b99504349bc2b05d130b6f48e) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4aa7207a876dee8d930fbf3bb009c4a9) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e738bc1ad66fe1d59a8f629b880167e4) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c506d18412e1e999b7b1a01e6ffbf194) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/67262cbdfb0454ddf3c4256670bdadad) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/64b5f17598a5ac73d808f4e23bbda413)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4a14e516d18eeb9fc3ed9772e013d80f)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5c80ddc19c2e707ec8a6ad0e11b25d1d)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/be2c5134bd846663a246c6ec4a0c0fba)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230918.1/8408023-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c06fe76aca336125975ccc772feef2b4) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8408023&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d9902b86e2559a7a20f9f86903bed356946d9c36](https://github.com/xamarin/xamarin-macios/pull/19003/commits/d9902b86e2559a7a20f9f86903bed356946d9c36)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-18 05:50 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 5 tests failed, 222 tests passed.

## Failures

### :x: cecil tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * Cecil-based tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>4 tests failed, 35 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Release (NativeAOT, x64) [dotnet]: Failed (Test run failed.
Tests run: 2884 Passed: 2671 Inconclusive: 10 Failed: 1 Ignored: 212)
 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (NativeAOT, x64) [dotnet]: Failed
 * monotouch-test/tvOS - simulator/Release (NativeAOT, x64) [dotnet]: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:warning: mtouch: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230918.1/8408023//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8408023/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added  [...]

2023-09-19 04:46 UTC, dustin-wojciechowski commented
/azp run

2023-09-19 06:20 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8414745&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [88b97031d8d398cb2b350f72aed36e0eae8922de](https://github.com/xamarin/xamarin-macios/pull/19003/commits/88b97031d8d398cb2b350f72aed36e0eae8922de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-19 06:21 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8414745&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19003/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-19 06:23 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8414745&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19003/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-19 06:26 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-16.5.0.908.pkg](https://dl.internalx.com/wrench/merge/914bcfd37f970949bb4d82978b6156efd47ae45f/8414745/package/xamarin.ios-16.5.0.908.pkg)
* [xamarin.mac-9.4.0.908.pkg](https://dl.internalx.com/wrench/merge/914bcfd37f970949bb4d82978b6156efd47ae45f/8414745/package/xamarin.mac-9.4.0.908.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8414745&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19003/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-19 06:33 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fa24798b96e8e3e7f8f8e17b018b78af) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9d395434f2b4dcfd0f6ab12e2586b6cd) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/65939eef414c0734656e970ad608cf69) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/19fe2bd220ea0ceff82d0f5bee546a31) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3f752ce04f1952ef3d0ac170f4b7e55e) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2becff63134c8ee288531deec2f36bae) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/11264a674aff66b7419e35d608054366) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fb2d8dc62f5176091e87a463db65c176) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/dbe94046b18afdc1fd25e9d23c0cc3db)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3eaf75d40cbfc033f68a21624fbe06fc)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2a6d4fb9cd345650377b9893148f761a)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d973e681efa5a9c921aeea7da0902040)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230919.7/8414745-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e5f6b56bd36199daa5890a733e5854e4) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8414745&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [88b97031d8d398cb2b350f72aed36e0eae8922de](https://github.com/xamarin/xamarin-macios/pull/19003/commits/88b97031d8d398cb2b350f72aed36e0eae8922de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-19 09:36 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 232 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 39 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:warning: mtouch: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230919.7/8414745//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8414745/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8414745&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [88b97031d8d398cb2b350f72aed36e0eae8922de](https://github.com/xamarin/xamarin-macios/pull/19003/commits/88b97031d8d398cb2b350f72aed36e0eae8922de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-19 16:03 UTC, rolfbjarne requested changes
It would be nice to have some numbers to see if the linker really is able to change the app size depending on this behavior.

This can probably be done by editing the size-comparison project here:

https://github.com/xamarin/xamarin-macios/blob/main/tests/dotnet/size-comparison/MySingleView/dotnet/MySingleView.csproj

And check if there's any app size difference between:

1. No change
2. Setting `UseNativeHttpHandler=false`:

```xml
<PropertyGroup>
    <UseNativeHttpHandler>false</UseNativeHttpHandler>
</PropertyGroup>
```

3. Using NSUrlSessionHandler:

```xml
<PropertyGroup>
    <MtouchHttpClientHandler>NSUrlSessionHandler</MtouchHttpClientHandler>
</PropertyGroup>
```

3. Using CFNetworkHandler:

```xml
<PropertyGroup>
    <MtouchHttpClientHandler>CFNetworkHandler</MtouchHttpClientHandler>
</PropertyGroup>
```

Then running `make compare` in the tests/ subdirectory for each case should result in a comparison:

https://github.com/xamarin/xamarin-macios/blob/5f3c312b6ce6eb3cc0011c152bc528de19c806c9/tests/dotnet/Makefile#L17-L18

2023-09-19 16:03 UTC, rolfbjarne commented on src/ObjCRuntime/Runtime.cs
> +		static bool useNSUrlSessionHandler = false;
The assignment to the default value is unnecessary, except that the default is to use NSUrlSessionHandler:

```suggestion
		static bool useCFNetworkHandler;
		static bool useNSUrlSessionHandler = true;
```

2024-05-13 11:41 UTC, closed without merging