[MetalFX] Add the framework (whihc was added in Xcode 14) and add xcode 15 support.
xamarin/xamarin-macios pull request #19107
Opened 2023-09-27 14:42 UTC by mandel-macaque

2023-09-27 15:41 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8458119&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [81823a22c142ee78c49e312d7f8d154c6808bd84](https://github.com/xamarin/xamarin-macios/pull/19107/commits/81823a22c142ee78c49e312d7f8d154c6808bd84)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-27 16:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8458119&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [81823a22c142ee78c49e312d7f8d154c6808bd84](https://github.com/xamarin/xamarin-macios/pull/19107/commits/81823a22c142ee78c49e312d7f8d154c6808bd84)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-27 16:32 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.0.0.41.pkg](https://dl.internalx.com/wrench/merge/e33226619ba03cb4e71a039220666376e1e3cf78/8458119/package/xamarin.ios-17.0.0.41.pkg)
* [xamarin.mac-9.0.0.41.pkg](https://dl.internalx.com/wrench/merge/e33226619ba03cb4e71a039220666376e1e3cf78/8458119/package/xamarin.mac-9.0.0.41.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8458119&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-27 16:45 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e3d50cd8d6b0563e1e507430bb2e4272) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/78ac394a3676cb745d5599c39f7a6f4b) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4801a240fd36c734908145f9f6ae8ad6) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/aaee9d88b2c7dddc6a8160f0ab31ab0a) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/374d5acea65c0272b14cddc3891d9b09) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/43c309399b56f8b82b5161886489305c) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bcfc278539b9fd6f97ee23cced77d1e3) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1f6920c562ffa1829825f77acafdca74) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/481a1602d31c41aedb2c0c8d98e45b6f) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ac86f8b645c96c00a94ab4fbbb0c830d) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/072b81d4f9dd1e54b7865f57c58d9a62) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e728f926f04adb909b4f0cc48df75bd9) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8a181474bdf1fe41e6d4f2fd65015d79) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b151b414f5025eb13db384487fc3da47)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5ae7e761f45742c7cb353f74aa8b99df)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c7ba214e22769a940ce5fed12744504d)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/03a7c18e6bb799659e2b50c71c93f924)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20230927.6/8458119-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/99f5eff52d28e39f524aaedda006d615) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8458119&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [81823a22c142ee78c49e312d7f8d154c6808bd84](https://github.com/xamarin/xamarin-macios/pull/19107/commits/81823a22c142ee78c49e312d7f8d154c6808bd84)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-09-27 18:33 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 14 tests failed, 219 tests passed.

## Failures

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>3 tests failed, 5 tests passed.</summary>
<details>

 * introspection/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 33 Passed: 31 Inconclusive: 0 Failed: 1 Ignored: 1)
 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>2 tests failed, 37 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20230927.6/8458119//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8458119/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20 [...]

2023-09-27 21:39 UTC, haritha-mohan approved these changes

2023-09-28 11:10 UTC, dalexsoto approved these changes

2023-10-04 17:54 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8489461&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [61222b218ba3c7cd0e1c3d7fb9007d43e4c63238](https://github.com/xamarin/xamarin-macios/pull/19107/commits/61222b218ba3c7cd0e1c3d7fb9007d43e4c63238)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-04 18:50 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.0.0.48.pkg](https://dl.internalx.com/wrench/merge/2b82169bfff5e90395e41954345a8dfc32959e96/8489461/package/xamarin.ios-17.0.0.48.pkg)
* [xamarin.mac-9.0.0.48.pkg](https://dl.internalx.com/wrench/merge/2b82169bfff5e90395e41954345a8dfc32959e96/8489461/package/xamarin.mac-9.0.0.48.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8489461&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-04 18:56 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/60f37a8c5f062a93625d3be7398963fd) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6636af2217206c2b686e7371946274ba) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9eb48e0a1cdcfa63598338df26986f05) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/444ce8bea1842a6e1580cb543b7c5c78) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fb6d56244b1babc759c3426e3b3c2208) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/07e43f38abad751edd52d08e3075689b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/af38a2adda570d1ae71ee44d3c615244) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/21f78fc74e0d7da6db677fa9013a966a) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5cdf68bb47d6db9b8df3f775fa321aea) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0576d70a56d939f9510b0a8a91a941ea) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/98edcada99f358d2d39cd8211d6ef573) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4651f55ebc40b51af65cf71fd2522701) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/53b8831dfef6ffeec47f405c1a0dc5bb) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f459ec473f076dbfecffd88d8e2257a6)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/72cb2323b3dd5cea0578f01894ea36f2)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/63f33fae28a73e6fed3183559e808b90)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/33a81e27fb84326f259e75d82c7016b7)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231004.4/8489461-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/006d2f3dba2c537cef924723edcac14b) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8489461&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [61222b218ba3c7cd0e1c3d7fb9007d43e4c63238](https://github.com/xamarin/xamarin-macios/pull/19107/commits/61222b218ba3c7cd0e1c3d7fb9007d43e4c63238)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-04 20:47 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 15 tests failed, 218 tests passed.

## Failures

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>3 tests failed, 5 tests passed.</summary>
<details>

 * introspection/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 33 Passed: 31 Inconclusive: 0 Failed: 1 Ignored: 1)
 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>3 tests failed, 36 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: BuildFailure
 * monotouch-test/watchOS 32-bits - simulator/Debug: TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231004.4/8489461//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8489461/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vs [...]

2023-10-06 18:48 UTC, tj-devel709 approved these changes

2023-10-09 20:53 UTC, rolfbjarne requested changes

2023-10-09 20:53 UTC, rolfbjarne commented on src/metalfx.cs
> +		float SupportedInputContentMinScale (IMTLDevice device);
```suggestion
		float GetSupportedInputContentMinScale (IMTLDevice device);
```

2023-10-09 20:53 UTC, rolfbjarne commented on src/metalfx.cs
> +		float SupportedInputContentMaxScale (IMTLDevice device);
```suggestion
		float GetSupportedInputContentMaxScale (IMTLDevice device);
```

2023-10-16 21:39 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8545142&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [99469041276368dec61ba820d1a5771fd07a2a18](https://github.com/xamarin/xamarin-macios/pull/19107/commits/99469041276368dec61ba820d1a5771fd07a2a18)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-16 22:16 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8545349&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7](https://github.com/xamarin/xamarin-macios/pull/19107/commits/7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-16 22:46 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8545349&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7](https://github.com/xamarin/xamarin-macios/pull/19107/commits/7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-16 23:02 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.1.0.25.pkg](https://dl.internalx.com/wrench/merge/3fa216fd0164bec8062cee801eeaf8bb1f2eb809/8545349/package/xamarin.ios-17.1.0.25.pkg)
* [xamarin.mac-9.1.0.25.pkg](https://dl.internalx.com/wrench/merge/3fa216fd0164bec8062cee801eeaf8bb1f2eb809/8545349/package/xamarin.mac-9.1.0.25.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8545349&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-16 23:15 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/483b0c408fb90fbe1bd9b2cf74d7ab0c) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9a121e4f782e204d821f6f7b9b1b8b7a) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5e537101c193cc3d12d7d43a09e66cb1) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a1a056db3660c30cbb8509ebea8e7696) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7a3d1ced6b9eefe3e31d14865ccc852f) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e6c28f06131605c9666823a81e94b3ea) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/19314d7cf3aac472a7d0d821e276c984) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bb44f7170e0309722db2d4e858e1e89c) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4fe9c3fe5552d6d3a0d667b9249714af) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/89e88d84dce568928059b2e82de52ca7) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d398e516499c2abd561b7702f423612c) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ab1fbd8f9f24a3f5b994496a96a869bb) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/db10aef0fae7cc39a32309ebe6a79375) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bbb740d20737dea0e69376a2c81d40d5)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8cef5150b9882690dd266096cc8a1e56)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/eb2ce26ca42564d3d6ff5e6740deb4cb)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2b6e43be5ade746689646b2c8a67ee1d)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231016.23/8545349-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/92f23bf2fa5594be68102be51c4dc35d) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8545349&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7](https://github.com/xamarin/xamarin-macios/pull/19107/commits/7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-17 00:53 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 14 tests failed, 221 tests passed.

## Failures

### :x: dotnettests tests

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>3 tests failed, 5 tests passed.</summary>
<details>

 * introspection/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 33 Passed: 31 Inconclusive: 0 Failed: 1 Ignored: 1)
 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)

### :x: monotouch tests

<summary>2 tests failed, 39 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)

### :x: xcframework tests

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios [...]

2023-10-17 03:27 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [PR Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8545349&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7](https://github.com/xamarin/xamarin-macios/pull/19107/commits/7d713a943a0d1282f3e8cfbeca5f8b0f738d38c7)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-17 05:03 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 14 tests failed, 221 tests passed.

## Failures

### :x: dotnettests tests [attempt 2]

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_dotnettests-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_dotnettests-2&api-version=6.0&$format=zip)

### :x: fsharp tests [attempt 2]

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * fsharp/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_fsharp-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_fsharp-2&api-version=6.0&$format=zip)

### :x: framework tests [attempt 2]

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_framework-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_framework-2&api-version=6.0&$format=zip)

### :x: interdependent_binding_projects tests [attempt 2]

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_interdependent_binding_projects-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-2&api-version=6.0&$format=zip)

### :x: introspection tests [attempt 2]

<summary>3 tests failed, 5 tests passed.</summary>
<details>

 * introspection/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 33 Passed: 31 Inconclusive: 0 Failed: 1 Ignored: 1)
 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_introspection-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_introspection-2&api-version=6.0&$format=zip)

### :x: linker tests [attempt 2]

<summary>4 tests failed, 61 tests passed.</summary>
<details>

 * dont link/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * dont link/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * trimmode copy/Mac Catalyst [dotnet]/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_linker-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_linker-2&api-version=6.0&$format=zip)

### :x: monotouch tests [attempt 2]

<summary>2 tests failed, 39 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_monotouch-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_monotouch-2&api-version=6.0&$format=zip)

### :x: xcframework tests [attempt 2]

<summary>1 tests failed, 7 tests passed.</summary>
<details>

 * xcframework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_xcframework-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_xcframework-2&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231016.23/8545349//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8545349/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All  [...]

2023-10-17 06:29 UTC, rolfbjarne approved these changes

2023-10-17 06:33 UTC, rolfbjarne commented
Looks like MetalFX doesn't work on Mac Catalyst?

> ld: building for Mac Catalyst, but linking in .tbd built for macOS, file '/Applications/Xcode_15.0.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks//MetalFX.framework/MetalFX.tbd' for architecture x86_64

This may need some testing in Xcode

2023-10-17 19:04 UTC, stephen-hawley approved these changes

2023-10-17 19:48 UTC, mandel-macaque commented
> Looks like MetalFX doesn't work on Mac Catalyst?
> 
> > ld: building for Mac Catalyst, but linking in .tbd built for macOS, file '/Applications/Xcode_15.0.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks//MetalFX.framework/MetalFX.tbd' for architecture x86_64
> 
> This may need some testing in Xcode

Funny enough in a m1 machine I get the following:

--- !tapi-tbd
tbd-version:     4
targets:         [ x86_64-macos, arm64-macos, arm64e-macos ]
install-name:    '/System/Library/Frameworks/MetalFX.framework/Versions/A/MetalFX'
exports:
  - targets:         [ x86_64-macos, arm64-macos, arm64e-macos ]
    objc-classes:    [ MFXSpatialScalingEffectDescriptor, MFXTemporalScalingEffectDescriptor,
                       MTLFXSpatialScalerDescriptor, MTLFXTemporalScalerDescriptor,
                       _MTLFXEffect, _MTLFXSpatialScaler, _MTLFXTemporalScaler ]
    objc-ivars:      [ _MTLFXEffect._effectID, _MTLFXEffect._encodeID, _MTLFXEffect._tracingDelegate ]
...
(END)

2023-10-18 17:09 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* introspection


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8555742&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-18 19:19 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8555742&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3e31d91e32a5deae6fa1fd4c6f4acedfb8f8674b](https://github.com/xamarin/xamarin-macios/pull/19107/commits/3e31d91e32a5deae6fa1fd4c6f4acedfb8f8674b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-18 19:37 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e80fd490787bb5284e9e8180d0a9d871) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9f9a14296ccc60090d8e157392a92e5d) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/59a46e804573c756ef25c6052f62b4b9) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/25e3d53bf1be8ec2b39349a7aa11bd1d) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4e6372ed0032761fcbef41757437cac6) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2ac3ec472e590295707820d577775b05) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ec6ea3be3c1e6f7d494268096d54ebf1) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/042106967bbc492afc29592e1389f3fb) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1aa2785748a9805b097f7f2c1117f08a) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/dfa368cb810d78b0ac27e724d252410f) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a5b8685bd7052c940c8e03e7dba56940) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fabed97c92b49b4cb1450ee7e4359c29) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/39f0fd4eeee1b2d6496d83d718db1e89) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/69d4187e8ecad816dec465cf46062d97)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3abf4cd8026a2c18040e0e4657807edc)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/060cb61c79fc78717fa2055b9d8637d4)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e56a45f1e3b81df31b3e44e771569252)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231018.10/8555742-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/88e6d6f7d64ed8b750b0e0c121d53c18) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8555742&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3e31d91e32a5deae6fa1fd4c6f4acedfb8f8674b](https://github.com/xamarin/xamarin-macios/pull/19107/commits/3e31d91e32a5deae6fa1fd4c6f4acedfb8f8674b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-18 19:44 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.1.0.35.pkg](https://dl.internalx.com/wrench/merge/c3564231e3c1990936a08e09026706affa0aa90c/8555742/package/xamarin.ios-17.1.0.35.pkg)
* [xamarin.mac-9.1.0.35.pkg](https://dl.internalx.com/wrench/merge/c3564231e3c1990936a08e09026706affa0aa90c/8555742/package/xamarin.mac-9.1.0.35.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8555742&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-18 22:30 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 2 tests failed, 233 tests passed.

## Failures

### :x: introspection tests

<summary>2 tests failed, 6 tests passed.</summary>
<details>

 * introspection/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 33 Passed: 31 Inconclusive: 0 Failed: 1 Ignored: 1)
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 41 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231018.10/8555742//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8555742/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8555742&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3e31d91e32a5deae6fa1fd4c6f4acedfb8f8674b](https://github.com/xamarin/xamarin-macios/pull/19107/com [...]

2023-10-20 02:17 UTC, vs-mobiletools-engineering-service2 commented
# :x: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) failed :x:

Failed tests are:

* introspection


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8566016&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 02:19 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8566016&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [a8a82e08f273420f691e9e29302227d44d926c06](https://github.com/xamarin/xamarin-macios/pull/19107/commits/a8a82e08f273420f691e9e29302227d44d926c06)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 02:22 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8566016&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 02:36 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.1.0.36.pkg](https://dl.internalx.com/wrench/merge/1ae4976298dd1038a860359b6272f04417f33c03/8566016/package/xamarin.ios-17.1.0.36.pkg)
* [xamarin.mac-9.1.0.36.pkg](https://dl.internalx.com/wrench/merge/1ae4976298dd1038a860359b6272f04417f33c03/8566016/package/xamarin.mac-9.1.0.36.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8566016&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 05:50 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 4 tests failed, 231 tests passed.

## Failures

### :x: introspection tests

<summary>2 tests failed, 6 tests passed.</summary>
<details>

 * introspection/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 33 Passed: 31 Inconclusive: 0 Failed: 1 Ignored: 1)
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
 * Xtro/.NET: Failed (Test run failed.)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 41 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231019.16/8566016//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8566016/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8566016&view=m [...]

2023-10-20 16:38 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8569931&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 17:52 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8569931&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d56e0a7c48af92c9a4d3d05373405f944fcc5c5d](https://github.com/xamarin/xamarin-macios/pull/19107/commits/d56e0a7c48af92c9a4d3d05373405f944fcc5c5d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 18:06 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.1.0.48.pkg](https://dl.internalx.com/wrench/merge/a4c22ec4cb5f67e00ab3748c7aa747efcb479da8/8569931/package/xamarin.ios-17.1.0.48.pkg)
* [xamarin.mac-9.1.0.48.pkg](https://dl.internalx.com/wrench/merge/a4c22ec4cb5f67e00ab3748c7aa747efcb479da8/8569931/package/xamarin.mac-9.1.0.48.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8569931&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 18:25 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/900c7ce411ff6266b6ac3ff808a6de45) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d600d6af4576484be272a2e54ab440b4) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ae34c5a26e85a2540c65acb959edac68) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/98316a6d5b9e257f2f6c91032b88005b) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0a4264fe619ac16c7c9fabfabe0157e3) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2a725c387778b415846481b0e13f5d1a) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b04e6462bcc1e59d02e7fec5b6ce5c18) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1d7ccb1caa72f4b126ce1ce36a5d0b53) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/94f2797b4c496165b9730930c5407b2c) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/55c1b866204dc378267aa5b1f717f500) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2f19ada08c4c8297bd1c562c007ab703) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2bd67f19cdd9fc5c90a8c951d6dc7d95) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d9f1e82d7fd88612a222cc7be488708e) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/50df8138c17a540d71b78fbf10c7ee41)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3a6c60acdb4afd204206559b9e26c1ef)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c7c70d74b12e6df46eebb0db76ddfaf9)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/167ffed8eeca3c044e529793ab28ef9a)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.2/8569931-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/13856b049b6c5a6c9098cbed2f527db5) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8569931&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d56e0a7c48af92c9a4d3d05373405f944fcc5c5d](https://github.com/xamarin/xamarin-macios/pull/19107/commits/d56e0a7c48af92c9a4d3d05373405f944fcc5c5d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 20:50 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: simulator tests

0 tests crashed, 4 tests failed, 231 tests passed.

## Failures

### :x: introspection tests

<summary>2 tests failed, 6 tests passed.</summary>
<details>

 * introspection/Mac [dotnet]/Debug [dotnet]: Failed (Test run failed.
Tests run: 33 Passed: 31 Inconclusive: 0 Failed: 1 Ignored: 1)
 * introspection/Mac Modern/Debug: Failed (Test run failed.
Tests run: 37 Passed: 35 Inconclusive: 0 Failed: 1 Ignored: 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)

### :x: xtro tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * Xtro/Legacy Xamarin: Failed (Test run failed.)
 * Xtro/.NET: Failed (Test run failed.)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 41 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.2/8569931//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8569931/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8569931&view=ms.vss-test-web.test [...]

2023-10-20 23:07 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8572025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [86438e2e5609f6b3327de14876b353dccf2e03f5](https://github.com/xamarin/xamarin-macios/pull/19107/commits/86438e2e5609f6b3327de14876b353dccf2e03f5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 23:12 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11.5) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11.5) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8572025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 23:15 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13.0) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13.0) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=8572025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 23:20 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.1.0.49.pkg](https://dl.internalx.com/wrench/merge/a2db4bcc563fde1f878ad74f13ff4535d96f2ce8/8572025/package/xamarin.ios-17.1.0.49.pkg)
* [xamarin.mac-9.1.0.49.pkg](https://dl.internalx.com/wrench/merge/a2db4bcc563fde1f878ad74f13ff4535d96f2ce8/8572025/package/xamarin.mac-9.1.0.49.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8572025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/19107/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-20 23:23 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/previous-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6cc98f278c46079f5640619a248daa34) (No breaking changes)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/previous-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ca4c7a1422d6321069381d89a1dbeff7) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/157b8cf658e69133a0ace1bb7063ec63) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e44a1adb25cb651644abb5c59b317a31) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/57c669c92d1ecd9f1b20c3d1241be97f) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8be7f04e1f76c3376d26ba3324edcaf9) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/acd617633fe444cf6286bd03eed26583) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1b5b3083c67007e0d55fc041bad269e9) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c5101ca8d3630a2d3e9a5689d7dcbe50) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b9b3fd9e524876a142fa16f4cecf0c11) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/27710d1c63adb6de328b110c5d058ed7) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/161c46bf32f247f12849cc09cb0dca46) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4ba5278029f2040578b9eb89048cd634) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8dc30469e3d517892256ce532237213e)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6a765d5840aa477e8819c6ca47e51461)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/58c348858a0fc66b4bd9e0a56b14d3ab)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d688adfe12382ee3f2202c5708a37998)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20231020.10/8572025-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7cc8a4dfee4ff290535c208d739bcd2b) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8572025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [86438e2e5609f6b3327de14876b353dccf2e03f5](https://github.com/xamarin/xamarin-macios/pull/19107/commits/86438e2e5609f6b3327de14876b353dccf2e03f5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-21 02:06 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: simulator tests.

:tada: All 235 tests passed :tada:

## Tests counts
:white_check_mark: bcl: All 69 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_bcl-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_bcl-1&api-version=6.0&$format=zip)
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_cecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_cecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_dotnettests-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_dotnettests-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_fsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_fsharp-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_framework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_framework-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_generator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_generator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent_binding_projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_interdependent_binding_projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_interdependent_binding_projects-1&api-version=6.0&$format=zip)
:white_check_mark: install_source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_install_source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_install_source-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_introspection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_introspection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_linker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_linker-1&api-version=6.0&$format=zip)
:white_check_mark: mac_binding_project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_mac_binding_project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_mac_binding_project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_mmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_mmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_mononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_mononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch: All 41 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_monotouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_monotouch-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_msbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_msbuild-1&api-version=6.0&$format=zip)
:white_check_mark: mtouch: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_mtouch-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_mtouch-1&api-version=6.0&$format=zip)
:white_check_mark: xammac: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_xammac-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_xammac-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_xcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_xcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20231020.10/8572025//simulator_xtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/8572025/artifacts?artifactName=HtmlReport-simulator_xtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=8572025&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [86438e2e5609f6b3327de14876b353dccf2e03f5](https://github.com/xamarin/xamarin-macios/pull/19107/commits/86438e2e5609f6b3327de14876b353dccf2e03f5)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2023-10-23 06:00 UTC, rolfbjarne approved these changes

2023-10-23 14:40 UTC, merged

2023-10-23 14:41 UTC, mandel-macaque commented
/sudo backport release/8.0.1xx

2023-10-23 14:41 UTC, vs-mobiletools-engineering-service2 commented
Backport Job to branch **release/8.0.1xx** Created! The magic is happening [here](https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=8578212)

2023-10-23 14:43 UTC, vs-mobiletools-engineering-service2 commented
Hooray! Backport succeeded! Please see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8578212 for more details.