[msbuild] Disable stripping symbols by default for Debug builds
xamarin/xamarin-macios pull request #20308
Opened 2024-03-15 06:05 UTC by haritha-mohan

Fixes https://github.com/xamarin/xamarin-macios/issues/20235

2024-03-15 07:21 UTC, rolfbjarne requested changes
This document needs to be updated too: https://github.com/xamarin/xamarin-macios/blob/main/docs/configuration-properties.md

2024-03-15 07:39 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.3.0.371.pkg](https://dl.internalx.com/wrench/merge/97102723c227e91797d569fb8ea2db326d45bba9/9248587/package/xamarin.ios-17.3.0.371.pkg)
* [xamarin.mac-9.3.0.371.pkg](https://dl.internalx.com/wrench/merge/97102723c227e91797d569fb8ea2db326d45bba9/9248587/package/xamarin.mac-9.3.0.371.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9248587&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 07:40 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9248587&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 07:41 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9248587&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 07:42 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9248587&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 07:52 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9248587&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [58fa98aec37c7316e1a37bdfa654cb4980059502](https://github.com/xamarin/xamarin-macios/pull/20308/commits/58fa98aec37c7316e1a37bdfa654cb4980059502)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 08:26 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/336d861aa917935fa07598acf21a2d4c) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/09be61b02ae40481ab4af214c51a42f3) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2d1a8321c6a981834c839159dc81a2f9) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/78e1a887735d6b73c8526a6a7ad30055) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net9.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e2bef304a8344221790c8e0dbe8bcf1b) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net9.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/37da7a3d4edd557ebcd32c0c3e7e2f02) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net9.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2b31155832cb985d7f8640b4bc5afba2) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net9.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8b0879f9ee110f111e32873fa9aa19d8) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net9.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/46728b78edf209a47408cd01c76ba078)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net9.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/5f3a69eec60bd871cc996445357ed0df)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net9.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d002d2d0d126a836cf3607a6c9f5368b)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net9.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0816861572809dbcdc1717dde5965a4d)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.1/9248587-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/abeab7aa694f5147b6ddd0a9c187950e) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9248587&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [58fa98aec37c7316e1a37bdfa654cb4980059502](https://github.com/xamarin/xamarin-macios/pull/20308/commits/58fa98aec37c7316e1a37bdfa654cb4980059502)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 09:07 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: test results.

:tada: All 172 tests passed :tada:

## Tests counts
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: mac-binding-project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 11 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9248587/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 11 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.1/9248587//simulator_te [...]

2024-03-15 14:37 UTC, rolfbjarne approved these changes

2024-03-15 15:12 UTC, mandel-macaque approved these changes
After the docs are updated.

2024-03-15 15:15 UTC, stephen-hawley approved these changes

2024-03-15 16:02 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.3.0.372.pkg](https://dl.internalx.com/wrench/merge/68d6708492c0985373e7b1cf33c0491eea2befb1/9249765/package/xamarin.ios-17.3.0.372.pkg)
* [xamarin.mac-9.3.0.372.pkg](https://dl.internalx.com/wrench/merge/68d6708492c0985373e7b1cf33c0491eea2befb1/9249765/package/xamarin.mac-9.3.0.372.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9249765&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 16:03 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9249765&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 16:06 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9249765&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 16:07 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9249765&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20308/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 16:11 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9249765&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1d3369a3e0c4be50234a55107aa52a32ccb2bed1](https://github.com/xamarin/xamarin-macios/pull/20308/commits/1d3369a3e0c4be50234a55107aa52a32ccb2bed1)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 16:47 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/71256251e5e7446dd8d19094b02e4227) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/091700cb910a13f33988f77a24d7c114) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7f21720edc4664c0f66ee1f5f4564418) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/041f639c88d63334ed20c4811ada7186) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net9.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/93f615b2ee7351293fd25feab8fbdef1) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net9.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e2b59bd53ed7eed4c5e06478b559f5c7) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net9.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/aca35359d54531358b17137c95b45152) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net9.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1a61c5ba735141b8838c9b7f1b4489ab) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net9.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/030efc60c85e79ace5529db2499d42b6)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net9.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2f3756e21477109102e39e1d1de07eba)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net9.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1e47d21d2b3247a963b6c272a5ea6646)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net9.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f3fea5493723108e14c7dbe22ee03522)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240315.5/9249765-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f0934ba68d294cc534ff4776f3e732fb) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9249765&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1d3369a3e0c4be50234a55107aa52a32ccb2bed1](https://github.com/xamarin/xamarin-macios/pull/20308/commits/1d3369a3e0c4be50234a55107aa52a32ccb2bed1)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-03-15 17:31 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: test results.

:tada: All 172 tests passed :tada:

## Tests counts
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: mac-binding-project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 11 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9249765/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 11 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240315.5/9249765//simulator_te [...]

2024-03-18 12:56 UTC, dalexsoto approved these changes

2024-03-18 15:13 UTC, merged