[cecil-tests] Fix blittability check for parameters whose types are pointers.
xamarin/xamarin-macios pull request #20683
Opened 2024-06-04 13:15 UTC by rolfbjarne

2024-06-04 14:51 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 14:52 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.3.0.484.pkg](https://dl.internalx.com/wrench/merge/2ed97e0d0aedf1bf4b366c0037d1fc848b0b4f5e/9675170/package/xamarin.ios-17.3.0.484.pkg)
* [xamarin.mac-9.3.0.484.pkg](https://dl.internalx.com/wrench/merge/2ed97e0d0aedf1bf4b366c0037d1fc848b0b4f5e/9675170/package/xamarin.mac-9.3.0.484.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9675170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 14:52 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 14:52 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 15:05 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9675170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [bd0f3e0386da8c76973016db39131452c70c2033](https://github.com/xamarin/xamarin-macios/pull/20683/commits/bd0f3e0386da8c76973016db39131452c70c2033)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 15:39 UTC, mandel-macaque requested changes

2024-06-04 15:39 UTC, mandel-macaque commented on tests/cecil-tests/BlittablePInvokes.cs
> +			return true;
What is the point of the localResult variable? I don't see it getting any value appended to it at all, nor it is passed to any function within the function.

2024-06-04 15:53 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a49966f9082ba63cf55b52f2e92b0171) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a85daae593d9972bfdc29debbd4ef988) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/58309d4d55a4e064e2815492b2cbc5ac) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/576772c4bd6a7c58a0d99735c1e9e8d5) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fb5d508ea01f776eff55eabc5cd3c9e4) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3bfe1319acaf39175a57590625fc38ce) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/84025fa1f82d718733b78b47e844bc68) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/87ff2c42749cedb390cf5932260a64bf) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/40ca75d23541ef33ea709e8e8ac03034)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9537f03247028407464b9d1e287da5ff)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/4720e1e27b31687387b4460f3eb0011f)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0037379941caf8837c78629688dbe46c)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.8/9675170-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2f8c5d1c792bf893c8168cf3838d89a2) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9675170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [bd0f3e0386da8c76973016db39131452c70c2033](https://github.com/xamarin/xamarin-macios/pull/20683/commits/bd0f3e0386da8c76973016db39131452c70c2033)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 16:26 UTC, mandel-macaque approved these changes

2024-06-04 17:22 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675170&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 17:56 UTC, vs-mobiletools-engineering-service2 commented
# :books: [PR Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

* [xamarin.ios-17.3.0.487.pkg](https://dl.internalx.com/wrench/merge/8fe1d9c89a3e373729aa07ff9bd9a20ff8309ef5/9675628/package/xamarin.ios-17.3.0.487.pkg)
* [xamarin.mac-9.3.0.487.pkg](https://dl.internalx.com/wrench/merge/8fe1d9c89a3e373729aa07ff9bd9a20ff8309ef5/9675628/package/xamarin.mac-9.3.0.487.pkg)
</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 19:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 19:34 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Big Sur (11) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 19:36 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 19:36 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [PR Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/20683/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 20:01 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4ef3427048893c0b953de5985e038db09e0c735d](https://github.com/xamarin/xamarin-macios/pull/20683/commits/4ef3427048893c0b953de5985e038db09e0c735d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 20:12 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* ~iOS~ (no change detected)
* ~tvOS~ (no change detected)
* ~watchOS~ (no change detected)
* ~macOS~ (no change detected)

</details>

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>Legacy Xamarin (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/ios-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d98a39cfdc4861b00bad2f9dd1d18c7d) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/tvos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8c5b4e83c34f049ee8748915c3875009) (No breaking changes)
* watchOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/watchos-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1f536938bffe9e598c34176e7a4ab6b3) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/mac-api-diff.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/953a617dea84179bb8292f39ed9d1628) (No breaking changes)

</details>

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ad09a7d5278e25c871f43ca2dc071965) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3bc076de6cc596c37e6f5430b14805e7) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8559d65ade104400c55452ad8e671414) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c3cb33110d7aabf5713b0b5cfc51581f) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/d3a49ba4cbc82c0abf98b36a65863e39)

</details>

<details><summary>Legacy Xamarin (stable) vs .NET</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/cf84d3a19cf2f40d9eccc62674581175)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a5493bb2594050dfc1389ab34e37aee9)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/stable-api-comparison/diff/dotnet/legacy-diff/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/52517fe691a071747602eb15133067a8)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240604.13/9675628-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c9c4febbac0984fb1181dc7caee91be3) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4ef3427048893c0b953de5985e038db09e0c735d](https://github.com/xamarin/xamarin-macios/pull/20683/commits/4ef3427048893c0b953de5985e038db09e0c735d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-04 20:12 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

5 tests crashed, 3 tests failed, 149 tests passed.

## Failures

### :x: generator tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * Generator tests/.NET: TimedOut (Execution timed out after 10 minutes.)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)

### :x: install-source tests

:fire: Failed catastrophically on VSTS: test results - install-source (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)

### :x: interdependent-binding-projects tests

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * interdependent-binding-projects/Mac Catalyst [dotnet]/Debug [dotnet]: TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)

### :x: monotouch tests (MacCatalyst)

<summary>1 tests failed, 8 tests passed.</summary>
<details>

 * monotouch-test/Mac Catalyst [dotnet]/Debug (managed static registrar) [dotnet]: Failed (Test run failed.
Tests run: 2985 Passed: 2850 Inconclusive: 10 Failed: 14 Ignored: 121)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)

### :x: monotouch tests (tvOS)

:fire: Failed catastrophically on VSTS: test results - monotouch_tvos (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)

### :x: mtouch tests

:fire: Failed catastrophically on VSTS: test results - mtouch (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsmtouch--1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsmtouch--1&api-version=6.0&$format=zip)

### :x: xammac tests

:fire: Failed catastrophically on VSTS: test results - xammac (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsxammac--1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsxammac--1&api-version=6.0&$format=zip)

### :x: xtro tests

:fire: Failed catastrophically on VSTS: test results - xtro (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsxtro--1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsxtro--1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675170/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.8/9675170//simulator_testsl [...]

2024-06-04 20:18 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: test results.

:tada: All 168 tests passed :tada:

## Tests counts
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 65 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: mac-binding-project: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:white_check_mark: mmp: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:white_check_mark: mononative: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 11 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9675628//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/9675628/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 11 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240604.13/9 [...]

2024-06-05 01:13 UTC, haritha-mohan approved these changes

2024-06-05 02:07 UTC, dalexsoto approved these changes

2024-06-05 11:51 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=9675628&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [4ef3427048893c0b953de5985e038db09e0c735d](https://github.com/xamarin/xamarin-macios/pull/20683/commits/4ef3427048893c0b953de5985e038db09e0c735d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-06-05 12:04 UTC, merged