[CI] Split the sim tests and the macOS tests.
xamarin/xamarin-macios pull request #21215
Opened 2024-09-10 17:33 UTC by mandel-macaque

Resource triggers do an or on the stage, not and and. That means that the tests pipelines are triggered once per stage. A way to solve this is to split the tests and each of the pipelines will listen to specific stage.

2024-09-10 19:31 UTC, dalexsoto approved these changes

2024-09-10 19:49 UTC, vs-mobiletools-engineering-service2 commented
# :books: [CI Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10197772&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/21215/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-10 20:02 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240910.16/10197774-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f4bb6661918dfa520f9634bdcb3339b8) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240910.16/10197774-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/83c73528a730d806fff6c8f2d1bb2f67) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240910.16/10197774-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b07cc86edd7b05420a951f3873f6f2bd) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240910.16/10197774-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f64f46b79dbfba8fc3da7340377e40aa) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240910.16/10197774-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ea0c75186296e2f1dd078b64a9477601)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240910.16/10197774-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240910.16/10197774-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c910d8fb10df7503447eb535d9810a86) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10197774&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3591985ba2df1c15fa9b6bcb1d07dcb0e557a73d](https://github.com/xamarin/xamarin-macios/pull/21215/commits/3591985ba2df1c15fa9b6bcb1d07dcb0e557a73d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-10 21:19 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 3 tests failed, 95 tests passed.

## Failures

### :x: dotnettests tests (macOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)

### :x: dotnettests tests (tvOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)

### :x: monotouch tests (tvOS)

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * monotouch-test/tvOS - simulator/Release (NativeAOT, x64) [dotnet]: Crashed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmonotouch_ [...]

2024-09-11 10:23 UTC, rolfbjarne approved these changes

2024-09-11 10:26 UTC, rolfbjarne requested changes
Two things:

1. The macOS tests didn't run.
2. To check that all the tests passed, we have to check another pipeline (which is exacerbated by the fact that the tests don't add statuses), which might turn out to be somewhat annoying. I guess time will tell here though.

2024-09-11 20:51 UTC, mandel-macaque commented
@rolfbjarne  they cannot run because I cannot create a pipeline before I land the yaml with the changes, so until this lands, I can't create it :) 

I need your +1

I am going to be fixing the comments, I have been side tracked by other CI issues, but it will be fixed.

2024-09-11 21:25 UTC, rolfbjarne approved these changes

2024-09-11 23:41 UTC, vs-mobiletools-engineering-service2 commented
# :books: [CI Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10208152&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/21215/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 00:44 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

2 tests crashed, 1 tests failed, 89 tests passed.

## Failures

### :x: dotnettests tests (macOS) [attempt 2]

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_macos-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-2&api-version=6.0&$format=zip)

### :x: dotnettests tests (tvOS)

:fire: Failed catastrophically on VSTS: test results - dotnettests_tvos (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_tvos--1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos--1&api-version=6.0&$format=zip)

### :x: monotouch tests (tvOS)

:fire: Failed catastrophically on VSTS: test results - monotouch_tvos (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmonotouch_tvos--1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos--1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10198750/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240910.12/10198750//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/buil [...]

2024-09-12 02:38 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>NET (empty diffs)</summary>

* ~iOS~: (empty diff detected)
* ~tvOS~: (empty diff detected)
* ~MacCatalyst~: (empty diff detected)
* ~macOS~: (empty diff detected)

</details>


## :white_check_mark: API diff vs stable

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240911.30/10208153-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3a9917c5efee39872921e3b873c3f199) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240911.30/10208153-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/eb67f51bfe86251e2016ae549adb6a42) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240911.30/10208153-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/6cb87ba2aa4d1fdcd9626e53772f89c9) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240911.30/10208153-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/844824fb1c9dbc6de825d9033b3727b5) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240911.30/10208153-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2032ed6e3fb5cf48eeb99415bc985883)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240911.30/10208153-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240911.30/10208153-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b7f90ebab5fc656cd28448030569b1bc) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10208153&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ce4612fffbee657e3b7353b4120edd026f991467](https://github.com/xamarin/xamarin-macios/pull/21215/commits/ce4612fffbee657e3b7353b4120edd026f991467)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 02:47 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10210001&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ce4612fffbee657e3b7353b4120edd026f991467](https://github.com/xamarin/xamarin-macios/pull/21215/commits/ce4612fffbee657e3b7353b4120edd026f991467)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 05:00 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 5 tests failed, 93 tests passed.

## Failures

### :x: dotnettests tests (tvOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)

### :x: fsharp tests

<summary>2 tests failed, 2 tests passed.</summary>
<details>

 * fsharp/iOS Unified 64-bits - simulator/Debug [dotnet]: HarnessException (Harness exception for 'fsharp': System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted()
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.DotNet.XHarness.iOS.Shared.CrashSnapshotReporter.EndCaptureAsync(TimeSpan timeout)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetResult()
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted()
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult()
   at Xharness.AppRunner.RunAsync() in /Users/builder/azdo/_work/4/s/xamarin-macios/tests/xharness/AppRunner.cs:line 453
   at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync() in /Users/builder/azdo/_work/4/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:line 128
   at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync() in /Users/builder/azdo/_work/4/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunTest.cs:line 113
   at Xharness.Jenkins.TestTasks.TestTasks.RunInternalAsync() in /Users/builder/azdo/_work/4/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/TestTask.cs:line 269)
 * fsharp/tvOS - simulator/Debug [dotnet]: HarnessException (Harness exception for 'fsharp': System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted()
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.DotNet.XHarness.iOS.Shared.CrashSnapshotReporter.EndCaptureAsync(TimeSpan timeout)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.get_TestExecutionStarted()
   at Microsoft.DotNet.XHarness.iOS.Shared.TestReporter.ParseResult()
   at Xharness.AppRunner.RunAsync() in /Users/builder/azdo/_work/4/s/xamarin-macios/tests/xharness/AppRunner.cs:line 453
   at Xharness.Jenkins.TestTasks.RunSimulator.RunTestAsync() in /Users/builder/azdo/_work/4/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/RunSimulator.cs:line 128
   at Xharness.Jenkins.TestTasks.RunTest.ExecuteAsync() in /Users/builder/azdo/_work/4/s/xamarin-macios/tests/xharness/Jenkins/TestTasks/R [...]

2024-09-12 13:12 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: test results.

:tada: All 98 tests passed :tada:

## Tests counts
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsdotnettests_tvos-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-2&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsfsharp-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsfsharp-2&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsmonotouch_ios-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-2&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.3/10210001//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10210001/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/devi [...]

2024-09-12 21:16 UTC, merged