[HealthKit] Implement Xcode 16 RC changes.
xamarin/xamarin-macios pull request #21225
Opened 2024-09-12 12:23 UTC by rolfbjarne

2024-09-12 14:13 UTC, vs-mobiletools-engineering-service2 commented
# :books: [CI Build] Artifacts :books:

## Packages generated

<details><summary>View packages</summary>

</details>

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10212328&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/21225/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 14:35 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10212600&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c2af54de5b3325192a8832856ee00c5799487a6f](https://github.com/xamarin/xamarin-macios/pull/21225/commits/c2af54de5b3325192a8832856ee00c5799487a6f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 14:38 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10212600&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c2af54de5b3325192a8832856ee00c5799487a6f](https://github.com/xamarin/xamarin-macios/pull/21225/commits/c2af54de5b3325192a8832856ee00c5799487a6f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 14:45 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10212600&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c2af54de5b3325192a8832856ee00c5799487a6f](https://github.com/xamarin/xamarin-macios/pull/21225/commits/c2af54de5b3325192a8832856ee00c5799487a6f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 14:50 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10212600&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [c2af54de5b3325192a8832856ee00c5799487a6f](https://github.com/xamarin/xamarin-macios/pull/21225/commits/c2af54de5b3325192a8832856ee00c5799487a6f)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-12 15:58 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: test results.

:tada: All 98 tests passed :tada:

## Tests counts
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912.10/10212600//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10212600/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240912 [...]

2024-09-12 20:18 UTC, stephen-hawley requested changes

2024-09-12 20:18 UTC, stephen-hawley commented on src/HealthKit/HKAppleSleepingBreathingDisturbances.cs
> +		/// <summary>Get the breathing disturbances classification a given quantity of breathing disturbance.</summary>
should this be `classification given a quantity`?

2024-09-13 10:18 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:19 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:21 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:22 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:23 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:24 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:24 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:26 UTC, vs-mobiletools-engineering-service2 commented
# :books: [CI Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10218338&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/21225/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:50 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 10:55 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2f04c957bebdfb517be0c43bd0bb1787) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/eb3b290d8ad0fee3e333854f57c2c410) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/c9fe607f1eb3557958ba8244eba112e1) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e00abcd60afbf633eb373a787a9ba3cc) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9838e68debdb9c5b2ff71ffa1fe0a545) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/95bb97dd13cc7274d4677469290935cc) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8ded57d4513819588c0b650239abc3f8) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/eed6dfeea9a441a0218d3d6a456e4804)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.1/10218339-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/ff1940507234b16b87b4adfdd97976e1) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10218339&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:05 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:05 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:09 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:14 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:23 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:24 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:24 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:27 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:42 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10218589&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 11:52 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 1 tests failed, 97 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 3 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.6/10218589//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218589/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 [...]

2024-09-13 12:21 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 2 tests failed, 96 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 3 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)

### :x: msbuild tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * MSBuild tests/Tasks: Failed (Execution failed with exit code 4)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.5/10218588//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10218588/artifacts?artifactName=HtmlReport-simulato [...]

2024-09-13 13:52 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 13:53 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 13:53 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ae3b19b178a2d2a153f15c954fb15e063e32f1ff](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ae3b19b178a2d2a153f15c954fb15e063e32f1ff)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 13:57 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10218588&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 14:41 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10219303&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 14:43 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10219303&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 16:08 UTC, stephen-hawley approved these changes

2024-09-13 16:08 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/previous-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2581aa8d50f3a7af34713c7f56f4ed99) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/previous-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/7b0c2c83bcbd65479097e6ffd10d0de5) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/previous-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/f62cd50dc31793df27954ceacbefa236) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/stable-api-comparison/diff/dotnet/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/0f2eacec28d7cf7b8d883a4f94d63e88) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/stable-api-comparison/diff/dotnet/Microsoft.tvOS.Ref/ref/net8.0/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/87f4dd27492b5f883257eb22f635bcc7) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/stable-api-comparison/diff/dotnet/Microsoft.MacCatalyst.Ref/ref/net8.0/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/16033201772d6d9849fa91da59071c8b) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/stable-api-comparison/diff/dotnet/Microsoft.macOS.Ref/ref/net8.0/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a3f519b4a67e7c66580bf44d12687dab) (No breaking changes)
* Microsoft.iOS vs Microsoft.MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/stable-api-comparison/diff/dotnet/iOS-MacCatalyst-diff/Microsoft.iOS.Ref/ref/net8.0/Microsoft.iOS.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/9ee951fa11c078746b2bd4c05b2735fc)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240913.5/10219304-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/82d31735f1ca1fcd3ad363ac90957c9d) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10219304&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 16:32 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed :fire:

Build failed for the job 'Build packages'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10219303&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 17:14 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed :fire:

Build failed for the job 'Build macOS tests'

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10219303&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:02 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220432&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:02 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220432&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:02 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220432&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:03 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Tests on macOS M1 - Mac Big Sur (11) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220433&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:04 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220433&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:04 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220433&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:05 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220432&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:07 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10220433&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:11 UTC, vs-mobiletools-engineering-service2 commented
# :books: [CI Build] Artifacts :books:

Artifacts were not provided.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10219303&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [](https://github.com/xamarin/xamarin-macios/pull/21225/commits/)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:45 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10220432&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 18:45 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10220433&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af](https://github.com/xamarin/xamarin-macios/pull/21225/commits/ff6c06a6fb8296ed9a5a1c4f7d656b2373a455af)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-13 19:44 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 2 tests failed, 96 tests passed.

## Failures

### :x: dotnettests tests (iOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

### :x: introspection tests

<summary>1 tests failed, 3 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220433/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.13/10220433//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/1022043 [...]

2024-09-13 20:06 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 3 tests failed, 95 tests passed.

## Failures

### :x: introspection tests

<summary>2 tests failed, 2 tests passed.</summary>
<details>

 * introspection/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)

### :x: msbuild tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * MSBuild tests/Tasks: Failed (Execution failed with exit code 4)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: install-source: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsinstall-source-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsinstall-source-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:warning: mac-binding-project: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsmac-binding-project-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsmac-binding-project-1&api-version=6.0&$format=zip)
:warning: mmp: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsmmp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsmmp-1&api-version=6.0&$format=zip)
:warning: mononative: No tests selected. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsmononative-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsmononative-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10220432/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240913.12/10220432//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.v [...]

2024-09-17 17:29 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Big Sur (11) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-17 17:29 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-17 17:30 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-17 17:31 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-17 17:41 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/previous-api-comparison/diff/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/2a8ff3dcc1c13df2fd1e64268b946def) (No breaking changes)
* ~tvOS~: (empty diff detected)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/previous-api-comparison/diff/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/569c1ddd6133fb1dca1d330012199ac7) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/previous-api-comparison/diff/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/fad255758b7149442714cdf73ef8791a) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/stable-api-comparison/diff/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/717959225727a9c88ab3315ada5d88f0) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/stable-api-comparison/diff/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/932ab13641c833878d3cf9dd58612d86) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/stable-api-comparison/diff/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/17c16b35e08b9bf1733217aafbe90b02) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/stable-api-comparison/diff/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/805d1a68ce61578e7144a9d57f2e70af) (No breaking changes)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20240917.24/10234987-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/bd7dffd8cdbfa09b57dca2ae63ca1aac) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10234987&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-17 18:08 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-17 20:16 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 18 tests failed, 79 tests passed.

## Failures

### :x: introspection tests

<summary>1 tests failed, 3 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)

### :x: linker tests

<summary>10 tests failed, 30 tests passed.</summary>
<details>

 * dont link/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * dont link/iOS Unified 64-bits - simulator/Release [dotnet]: BuildFailure
 * link sdk/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * link sdk/iOS Unified 64-bits - simulator/Release [dotnet]: BuildFailure
 * link all/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * link all/iOS Unified 64-bits - simulator/Release [dotnet]: BuildFailure
 * trimmode copy/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * trimmode copy/iOS Unified 64-bits - simulator/Release [dotnet]: BuildFailure
 * trimmode link/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
 * trimmode link/iOS Unified 64-bits - simulator/Release [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)

### :x: monotouch tests (iOS)

<summary>7 tests failed, 0 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (managed static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (managed static registrar, all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (NativeAOT, x64) [dotnet]: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (t [...]

2024-09-18 06:47 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Big Sur (11) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Big Sur (11) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-18 07:30 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-18 07:45 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

1 tests crashed, 1 tests failed, 89 tests passed.

## Failures

### :x: introspection tests [attempt 2]

<summary>1 tests failed, 3 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsintrospection-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsintrospection-2&api-version=6.0&$format=zip)

### :x: monotouch tests (iOS) [attempt 2]

:fire: Failed catastrophically on VSTS: test results - monotouch_ios (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_ios-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-2&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testslinker-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testslinker-2&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/1023536 [...]

2024-09-18 07:58 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-18 08:34 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 8 tests failed, 89 tests passed.

## Failures

### :x: introspection tests [attempt 3]

<summary>1 tests failed, 3 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsintrospection-3/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsintrospection-3&api-version=6.0&$format=zip)

### :x: monotouch tests (iOS) [attempt 3]

<summary>7 tests failed, 0 tests passed.</summary>
<details>

 * monotouch-test/iOS Unified 64-bits - simulator/Debug [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (managed static registrar) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (managed static registrar, all optimizations) [dotnet]: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (NativeAOT, x64) [dotnet]: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_ios-3/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-3&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testslinker-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testslinker-2&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: [...]

2024-09-18 09:00 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-18 09:24 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 1 tests failed, 96 tests passed.

## Failures

### :x: introspection tests [attempt 4]

<summary>1 tests failed, 3 tests passed.</summary>
<details>

 * introspection/iOS Unified 64-bits - simulator/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsintrospection-4/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsintrospection-4&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [attempt 2] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testslinker-2/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testslinker-2&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [attempt 4] [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_ios-4/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-4&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20240917.21/10235363//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10235363/artifacts?artifactName=HtmlReport-simulator_testsxtro-1&api-vers [...]

2024-09-18 10:23 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-18 11:53 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Windows Integration Tests failed :x:

:x: Failed :x:

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10235363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8b857a407bb0cd975bad783dbcc53d85862281b2](https://github.com/xamarin/xamarin-macios/pull/21225/commits/8b857a407bb0cd975bad783dbcc53d85862281b2)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps)

2024-09-18 15:40 UTC, rolfbjarne commented
Introspection test failure is unrelated (#21236).

2024-09-18 15:40 UTC, merged