[dotnet] Ensure appropriate IL Strip value for multi-rid builds
xamarin/xamarin-macios pull request #21378
Opened 2024-10-05 20:47 UTC by haritha-mohan

`IsMultiRidBuild` tracks if we are executing an **inner** build for a multi-rid case. With this approach, if the user specifies a value for `EnableAssemblyILStripping` it will still be honored. Otherwise, to ensure we don't duplicate assemblies when merging the app bundles due to a strip vs non-strip scenario,  IL stripping for the multi-rid build is disabled by default.

There have been past examples of optimizing in the outer-build: https://github.com/xamarin/xamarin-macios/pull/12847
But because IL Stripping is contingent on the evaluation of other RID-specific properties, not sure if that is a feasible approach here.

Fixes https://github.com/xamarin/xamarin-macios/issues/17115

2024-10-07 17:28 UTC, rolfbjarne commented on dotnet/targets/Xamarin.Shared.Sdk.targets
> +			<EnableAssemblyILStripping Condition="'$(_RunAotCompiler)' == 'true' And '$(Configuration)' == 'Release' And '$(_IsMultiRidBuild)' != 'true'">true</EnableAssemblyILStripping>
I think this looks good!

2024-10-08 14:04 UTC, dalexsoto approved these changes

2024-10-08 14:05 UTC, dalexsoto commented
@haritha-mohan you need to push this to a branch in the main repo not from a fork so it actually builds the PR

2024-10-08 14:05 UTC, dalexsoto requested changes
@haritha-mohan you need to push this to a branch in the main repo not from a fork so it actually builds the PR

2024-10-08 16:07 UTC, haritha-mohan commented
> @haritha-mohan you need to push this to a branch in the main repo not from a fork so it actually builds the PR

thanks for catching that! was moving between repos 😅 also need to add a test here so will open a updated PR.

2024-10-08 16:07 UTC, closed without merging