[docs] Add docs about our build items and properties.
xamarin/xamarin-macios pull request #21578
Opened 2024-11-05 10:09 UTC by rolfbjarne

This was migrated from our wiki, and will eventually be published on learn.microsoft.com.

2024-11-05 21:48 UTC, dalexsoto approved these changes

2024-11-07 15:05 UTC, stephen-hawley requested changes
Minor typos

2024-11-07 15:05 UTC, stephen-hawley commented on docs/building-apps/build-targets.md
> +description: .NET for iOS, Mac Catalyst, macOS, and tvOS build bargets
bargets -> targets

2024-11-12 14:41 UTC, stephen-hawley approved these changes

2024-11-19 16:05 UTC, mcumming approved these changes

2024-11-19 17:01 UTC, mandel-macaque approved these changes

2024-12-10 08:00 UTC, merged