[Accessibility] Implement Xcode 16.2 beta 1-3 changes.
xamarin/xamarin-macios pull request #21686
Opened 2024-11-22 08:12 UTC by rolfbjarne

2024-11-22 09:38 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10601690&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [045d64a00d00f53acf91e71f73f411f936ef5fa3](https://github.com/xamarin/xamarin-macios/pull/21686/commits/045d64a00d00f53acf91e71f73f411f936ef5fa3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-11-22 09:52 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10601690&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [045d64a00d00f53acf91e71f73f411f936ef5fa3](https://github.com/xamarin/xamarin-macios/pull/21686/commits/045d64a00d00f53acf91e71f73f411f936ef5fa3)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-11-22 11:13 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: test results.

:tada: All 103 tests passed :tada:

## Tests counts
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241122.5/10601603//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10601603/artifacts?artifactName=HtmlReport-simulator_testsxtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10601603&view=ms.vss-test-web.test- [...]

2024-11-22 16:25 UTC, dalexsoto requested changes

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionNumber {
This has a ctor and properties are readonly

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionNumber {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionIdentifier {
Same, this has a ctor and properties are readonly

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionIdentifier {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionOperator {
Same

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionOperator {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionText {
Same
```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionText {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionFenced {
Same
```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionFenced {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionRow {
Same

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionRow {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionTable {
Same

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionTable {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionTableRow {
Same

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionTableRow {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionTableCell {
```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionTableCell {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionUnderOver {
Same

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionUnderOver {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionSubSuperscript {
```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionSubSuperscript {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionFraction {
Same

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionFraction {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionMultiscript {
Same

```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionMultiscript {
```

2024-11-22 16:25 UTC, dalexsoto commented on src/accessibility.cs
> +	interface AXMathExpressionRoot {
Same
```suggestion
	[BaseType (typeof (AXMathExpression))]
	[DisableDefaultCtor]
	interface AXMathExpressionRoot {
```

2024-11-25 15:53 UTC, haritha-mohan approved these changes
after Alex's comments 👍

2024-11-28 18:00 UTC, rolfbjarne commented on src/accessibility.cs
> +	interface AXMathExpression {
```suggestion
	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	interface AXMathExpression {
```

2024-11-28 19:19 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10632623&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [268108d8f220cdebff8ad8f5814bdf2855e6a9f6](https://github.com/xamarin/xamarin-macios/pull/21686/commits/268108d8f220cdebff8ad8f5814bdf2855e6a9f6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-11-28 19:19 UTC, vs-mobiletools-engineering-service2 commented
## :white_check_mark: API diff for current PR / commit

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/previous-api-comparison/diff/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b6b9f7327d9fddafcc72902e315b1e53) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/previous-api-comparison/diff/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/3a11fbfb766aefdb2a72ecbf37a7e55a) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/previous-api-comparison/diff/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/06142e09b719bb2fe533a1582a1a56c0) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/previous-api-comparison/diff/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/1485bc0ff5fa81f3ac23e9ecc231ffcb) (No breaking changes)

</details>


## :white_check_mark: API diff vs stable

<details><summary>.NET (No breaking changes)</summary>

* iOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/stable-api-comparison/diff/Microsoft.iOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/e1a6ebb09610c3ada4dee58f0408d80a) (No breaking changes)
* tvOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/stable-api-comparison/diff/Microsoft.tvOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/126e840d37d3028683e1a140e15a9f74) (No breaking changes)
* MacCatalyst: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/stable-api-comparison/diff/Microsoft.MacCatalyst.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/a815ee76b17d11242e52c7a854b5f662) (No breaking changes)
* macOS: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/stable-api-comparison/diff/Microsoft.macOS.html) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/8ffa75edf7600c6c1518c2ca888377d1) (No breaking changes)

</details>


## :information_source: Generator diff

Generator Diff: [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/generator-diff/index.html) (html) [vsdrops](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/detected-changes/20241128.9/10632565-1/;/generator-diff/generator.diff) (raw diff) [gist](https://gist.github.com/vs-mobiletools-engineering-service2/b8a3b6726fe1f468406f496f714771fe) (raw diff) - Please review changes)


[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10632565&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [268108d8f220cdebff8ad8f5814bdf2855e6a9f6](https://github.com/xamarin/xamarin-macios/pull/21686/commits/268108d8f220cdebff8ad8f5814bdf2855e6a9f6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: api diff)

2024-11-28 19:20 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10632623&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [268108d8f220cdebff8ad8f5814bdf2855e6a9f6](https://github.com/xamarin/xamarin-macios/pull/21686/commits/268108d8f220cdebff8ad8f5814bdf2855e6a9f6)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-11-28 21:09 UTC, vs-mobiletools-engineering-service2 commented
# :rocket: [CI Build] Test results :rocket:

# Test results
:white_check_mark: All tests passed on VSTS: test results.

:tada: All 103 tests passed :tada:

## Tests counts
:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 3 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 6 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241128.6/10632599//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10632599/artifacts?artifactName=HtmlReport-simulator_testsxtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10632599&view=ms.vss-test-web.test- [...]

2024-12-02 19:42 UTC, dalexsoto approved these changes

2024-12-02 19:43 UTC, merged