[CI] Do not double checkout macios-adr to keep the crendetials.
xamarin/xamarin-macios pull request #21807
Opened 2024-12-12 23:00 UTC by mandel-macaque

Doing a second checkout is error prone. One of the reason is that there is no guarantee that any of our other scripts is not going to remove a random temp directory (actually, the API diff make does remove it).

If the checkout directory is removed, the post checkout action from VSTS will fail with something of the kind:

```
[error]An error occurred trying to start process '/usr/local/bin/git'
with working directory
'/Users/builder/azdo/_work/22/a/change-detection/tmp/src/macios-adr'. No
such file or directory
```

The correct way to workaround the issue is to 'mimic' the way VSTS uses git via https.extraheaders (note that this might not work with old versions of git lfs, but should work with versions newer than 2.7.1).

We add a script that will update the configuration of a vsts git repo to use an extra base auth header with the system.token of the pipeline, which should have access to the repo.

I have added some extra docs in the older script for github so that other developers understand the usage and will not make the same mistake with API diff again.

2024-12-12 23:08 UTC, dalexsoto approved these changes

2024-12-12 23:15 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed (Detect API changes) :fire:

Build failed for the job 'Detect API changes' (with job status 'Failed')


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703206&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3276298c4e5ebbeff0929bdd4ba5968763f24f46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/3276298c4e5ebbeff0929bdd4ba5968763f24f46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-12 23:18 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed (Build macOS tests) :fire:

Build failed for the job 'Build macOS tests' (with job status 'Failed')


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703200&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3276298c4e5ebbeff0929bdd4ba5968763f24f46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/3276298c4e5ebbeff0929bdd4ba5968763f24f46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-12 23:20 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed (Build packages) :fire:

Build failed for the job 'Build packages' (with job status 'Failed')


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703200&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [3276298c4e5ebbeff0929bdd4ba5968763f24f46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/3276298c4e5ebbeff0929bdd4ba5968763f24f46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-12 23:22 UTC, borrillis approved these changes

2024-12-13 00:32 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703445&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [34e7e8bd669327c181597fc9e7c93823ced5e09d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/34e7e8bd669327c181597fc9e7c93823ced5e09d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-13 00:39 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Detect API changes) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703446&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [34e7e8bd669327c181597fc9e7c93823ced5e09d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/34e7e8bd669327c181597fc9e7c93823ced5e09d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-13 00:43 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10703446&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [34e7e8bd669327c181597fc9e7c93823ced5e09d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/34e7e8bd669327c181597fc9e7c93823ced5e09d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: api diff)

2024-12-13 01:18 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703445&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [34e7e8bd669327c181597fc9e7c93823ced5e09d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/34e7e8bd669327c181597fc9e7c93823ced5e09d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-13 01:31 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-13 01:34 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-13 01:34 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-13 01:38 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10703716&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-13 01:43 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704004&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-13 01:43 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Detect API changes) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703867&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-13 01:50 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703866&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-13 01:50 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10703867&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: api diff)

2024-12-13 02:12 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10703866&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-13 02:18 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10704127&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-13 02:25 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704347&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-13 02:27 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704347&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-13 02:27 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704347&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [d5089fa0515094a5181704b8c2a0de549eaeacdd](https://github.com/xamarin/xamarin-macios/pull/21807/commits/d5089fa0515094a5181704b8c2a0de549eaeacdd)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-13 03:43 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

1 tests crashed, 1 tests failed, 101 tests passed.

## Failures

### :x: dotnettests tests (iOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

### :x: dotnettests tests (MacCatalyst)

:fire: Failed catastrophically on VSTS: test results - dotnettests_maccatalyst (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.1/10703716//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10703716/artifacts?artifactName=HtmlReport-simulator_testsxtro-1&api- [...]

2024-12-13 03:45 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704625&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cc086daff048baab29a1014df83ff9381b599c0d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/cc086daff048baab29a1014df83ff9381b599c0d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-13 03:59 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Detect API changes) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704626&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cc086daff048baab29a1014df83ff9381b599c0d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/cc086daff048baab29a1014df83ff9381b599c0d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-13 04:07 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10704625&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cc086daff048baab29a1014df83ff9381b599c0d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/cc086daff048baab29a1014df83ff9381b599c0d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-13 04:16 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10704801&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [cc086daff048baab29a1014df83ff9381b599c0d](https://github.com/xamarin/xamarin-macios/pull/21807/commits/cc086daff048baab29a1014df83ff9381b599c0d)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-13 04:20 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705020&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-13 04:23 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705020&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-13 04:23 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705020&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-13 04:30 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705020&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-13 04:52 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705030&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-13 05:00 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

1 tests crashed, 0 tests failed, 102 tests passed.

## Failures

### :x: dotnettests tests (iOS)

:fire: Failed catastrophically on VSTS: test results - dotnettests_ios (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.4/10704127//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704127/artifacts?artifactName=HtmlReport-simulator_testsxtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report added by Azure DevOps)

[Pipeline](https://devdiv.visualstu [...]

2024-12-13 05:09 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Detect API changes) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705035&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-13 05:24 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705030&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-13 05:33 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10705234&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-13 05:37 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Failed tests are:

* monotouch-test


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705321&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-13 05:39 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705321&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-13 05:40 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705321&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-13 05:40 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10705321&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [74964723ceddc7c748a15789b9e7ca74725808f8](https://github.com/xamarin/xamarin-macios/pull/21807/commits/74964723ceddc7c748a15789b9e7ca74725808f8)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-13 06:13 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 2 tests failed, 101 tests passed.

## Failures

### :x: dotnettests tests (iOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

### :x: monotouch tests (tvOS)

<summary>1 tests failed, 6 tests passed.</summary>
<details>

 * monotouch-test/tvOS - simulator/Debug (LinkSdk) [dotnet]: Failed
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.5/10704801//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10704801/artifac [...]

2024-12-13 08:05 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

1 tests crashed, 2 tests failed, 100 tests passed.

## Failures

### :x: dotnettests tests (iOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

### :x: dotnettests tests (MacCatalyst)

:fire: Failed catastrophically on VSTS: test results - dotnettests_maccatalyst (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)

### :x: dotnettests tests (Multiple platforms)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10705234/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.6/10705234//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https: [...]

2024-12-13 13:07 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10706498&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-13 13:19 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10706372&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-13 13:32 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10706583&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-13 13:35 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10706583&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-13 13:42 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10706583&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-13 17:50 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed (Detect API changes) :fire:

Build failed for the job 'Detect API changes' (with job status 'Canceled')


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10706373&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ed62e79c760cf2130c229f3cdc5b35b03b6cdb9b)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-13 18:34 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10707493&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-13 18:47 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10707494&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: api diff)

2024-12-13 19:01 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10707493&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-13 19:10 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10707796&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-13 19:14 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10707925&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-13 19:17 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10707925&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-13 19:17 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10707925&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-13 19:26 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Failed tests are:

* dontlink


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10707925&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [8a8dcb2ded221fe701eb2413028a754c037a0b08](https://github.com/xamarin/xamarin-macios/pull/21807/commits/8a8dcb2ded221fe701eb2413028a754c037a0b08)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-13 20:18 UTC, mcumming approved these changes

2024-12-13 21:18 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

1 tests crashed, 1 tests failed, 97 tests passed.

## Failures

### :x: dotnettests tests (iOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

### :x: generator tests

:fire: Failed catastrophically on VSTS: test results - generator (no summary found).

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.13/10707796//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10707796/artifacts?artifactName=HtmlReport-simulator_testsxtro-1& [...]

2024-12-13 21:25 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Detect API changes) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10708416&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-13 21:31 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10708416&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: api diff)

2024-12-13 21:38 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10708415&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-13 22:00 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10708415&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-13 22:10 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10708761&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-13 22:13 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10708889&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-13 22:16 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10708889&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-13 22:16 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10708889&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-13 22:19 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10708889&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [b4271fba3e6dd7c8fca14c45343d345ddfafa3de](https://github.com/xamarin/xamarin-macios/pull/21807/commits/b4271fba3e6dd7c8fca14c45343d345ddfafa3de)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-14 00:12 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 3 tests failed, 100 tests passed.

## Failures

### :x: dotnettests tests (iOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

### :x: framework tests

<summary>2 tests failed, 0 tests passed.</summary>
<details>

 * framework-test/Mac [dotnet]/Debug [dotnet]: TimedOut
 * framework-test/Mac Catalyst [dotnet]/Debug [dotnet]: BuildFailure
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10708761/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241213.14/10708761//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download [...]

2024-12-16 16:19 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716349&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7e2dc2093ab33276234fd52665bf6510d42a4566](https://github.com/xamarin/xamarin-macios/pull/21807/commits/7e2dc2093ab33276234fd52665bf6510d42a4566)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-16 16:27 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Detect API changes) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716350&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7e2dc2093ab33276234fd52665bf6510d42a4566](https://github.com/xamarin/xamarin-macios/pull/21807/commits/7e2dc2093ab33276234fd52665bf6510d42a4566)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-16 16:33 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10716350&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7e2dc2093ab33276234fd52665bf6510d42a4566](https://github.com/xamarin/xamarin-macios/pull/21807/commits/7e2dc2093ab33276234fd52665bf6510d42a4566)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: api diff)

2024-12-16 16:48 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716349&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [7e2dc2093ab33276234fd52665bf6510d42a4566](https://github.com/xamarin/xamarin-macios/pull/21807/commits/7e2dc2093ab33276234fd52665bf6510d42a4566)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-16 17:02 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716550&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-16 17:02 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10716482&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-16 17:04 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716550&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-16 17:05 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716550&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-16 17:20 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716535&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-16 17:45 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716535&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-16 17:56 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10716673&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-16 18:01 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716761&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-16 18:02 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716761&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-16 18:02 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716761&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-16 18:04 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716761&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-16 19:51 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed (Detect API changes) :fire:

Build failed for the job 'Detect API changes' (with job status 'Failed')


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10716536&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [816aa06b974927bebf301d4685720a6b44222c46](https://github.com/xamarin/xamarin-macios/pull/21807/commits/816aa06b974927bebf301d4685720a6b44222c46)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-16 19:55 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 4 tests failed, 99 tests passed.

## Failures

### :x: dotnettests tests (iOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)

### :x: monotouch tests (iOS)

<summary>3 tests failed, 4 tests passed.</summary>
<details>

 * monotouch-test/iOS - simulator/Debug [dotnet]: TimedOut
 * monotouch-test/iOS - simulator/Debug (LinkSdk) [dotnet]: TimedOut
 * monotouch-test/iOS - simulator/Debug (static registrar) [dotnet]: TimedOut
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10716673/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241216.5/10716673 [...]

2024-12-17 17:09 UTC, mandel-macaque commented
/azp run

2024-12-17 17:15 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ec0f5250a29968e28412398493fd5e16fdf9108c](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ec0f5250a29968e28412398493fd5e16fdf9108c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-17 17:15 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) failed :x:

Tests on macOS arm64 - Mac Sequoia (15) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ec0f5250a29968e28412398493fd5e16fdf9108c](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ec0f5250a29968e28412398493fd5e16fdf9108c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-17 17:16 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Ventura (13) failed :x:

Tests on macOS M1 - Mac Ventura (13) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723363&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ec0f5250a29968e28412398493fd5e16fdf9108c](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ec0f5250a29968e28412398493fd5e16fdf9108c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-17 17:56 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723365&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [ec0f5250a29968e28412398493fd5e16fdf9108c](https://github.com/xamarin/xamarin-macios/pull/21807/commits/ec0f5250a29968e28412398493fd5e16fdf9108c)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-17 18:23 UTC, mandel-macaque commented
/azp run

2024-12-17 18:29 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS M1 - Mac Monterey (12) failed :x:

Tests on macOS M1 - Mac Monterey (12) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723797&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-17 18:33 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Tests on macOS X64 - Mac Sonoma (14) failed for unknown reasons.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723797&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-17 18:37 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723804&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-17 18:39 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723804&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-17 18:39 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723804&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-17 18:49 UTC, vs-mobiletools-engineering-service2 commented
# :x: [CI Build] Tests on macOS X64 - Mac Sonoma (14) failed :x:

Failed tests are:

* dontlink


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723804&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-17 18:59 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10723592&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-17 19:20 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build packages) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723799&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build packages)

2024-12-17 19:26 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Build failed (Detect API changes) :fire:

Build failed for the job 'Detect API changes' (with job status 'Failed')


[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723802&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-17 19:41 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Build macOS tests) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723799&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Build macOS tests)

2024-12-17 19:54 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Windows Integration Tests passed :computer:

:white_check_mark: **All** Windows Integration Tests passed.

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10724172&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: windows tests)

2024-12-17 19:55 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Monterey (12) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Monterey (12) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10724267&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Monterey _12_)

2024-12-17 19:56 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS arm64 - Mac Sequoia (15) passed :computer:

:white_check_mark: **All** tests on macOS arm64 - Mac Sequoia (15) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10724267&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS arm64 - Mac Sequoia _15_)

2024-12-17 19:57 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS M1 - Mac Ventura (13) passed :computer:

:white_check_mark: **All** tests on macOS M1 - Mac Ventura (13) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10724267&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS M1 - Mac Ventura _13_)

2024-12-17 20:00 UTC, vs-mobiletools-engineering-service2 commented
# :computer: [CI Build] Tests on macOS X64 - Mac Sonoma (14) passed :computer:

:white_check_mark: **All** tests on macOS X64 - Mac Sonoma (14) passed.

[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10724267&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: macOS X64 - Mac Sonoma _14_)

2024-12-17 20:36 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 1 tests failed, 102 tests passed.

## Failures

### :x: msbuild tests

<summary>1 tests failed, 1 tests passed.</summary>
<details>

 * MSBuild tests/Tasks: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (tvOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (macOS): All 9 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.4/10723592//simulator_testsxtro-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10723592/artifacts?artifactName=HtmlReport-simulator_testsxtro-1&api-version=6.0&$format=zip)

[comment]: <> (This is a test result report [...]

2024-12-17 21:19 UTC, stephen-hawley requested changes
typos

2024-12-17 21:19 UTC, stephen-hawley commented on tools/devops/automation/scripts/set_vsts_extra_header.ps1
> +  Adds extra headers to a vsts repository so that we can perform git operaitons without the need of auth.
operaitions -> operations

2024-12-17 21:19 UTC, stephen-hawley commented on tools/devops/automation/scripts/clean_git_vsts.ps1
> +  The url pattern for this to wori is "https://$GithubToken@github.com/xamarin/maccore.git"
wori -> work

2024-12-17 21:43 UTC, vs-mobiletools-engineering-service2 commented
# :white_check_mark: [CI Build] Build passed (Detect API changes) :white_check_mark:




[Pipeline](https://dev.azure.com/devdiv/DevDiv/_build/index?buildId=10723802&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: build Detect API changes)

2024-12-17 21:47 UTC, vs-mobiletools-engineering-service2 commented
:fire: Unable to find the contents for the comment: D:\a\1\s\change-detection\results\gh-comment.md does not exist :fire

[Pipeline](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=10723802&view=ms.vss-test-web.test-result-details) on Agent 
Hash: [1dd1dec5b9b07eff22ada120cea18c808e8d8874](https://github.com/xamarin/xamarin-macios/pull/21807/commits/1dd1dec5b9b07eff22ada120cea18c808e8d8874)  [PR build]

[comment]: <> (This is a comment added by Azure DevOps, id: api diff)

2024-12-17 21:57 UTC, vs-mobiletools-engineering-service2 commented
# :fire: [CI Build] Test results :fire:

# Test results
:x: Tests failed on VSTS: test results

0 tests crashed, 2 tests failed, 101 tests passed.

## Failures

### :x: dotnettests tests (tvOS)

<summary>1 tests failed, 0 tests passed.</summary>
<details>

 * DotNet tests: Failed (Execution failed with exit code 1)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsdotnettests_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_tvos-1&api-version=6.0&$format=zip)

### :x: monotouch tests (macOS)

<summary>1 tests failed, 8 tests passed.</summary>
<details>

 * monotouch-test/Mac [dotnet]/Debug (static registrar) [dotnet]: Failed (Test run failed.
Tests run: 3019 Passed: 2801 Inconclusive: 4 Failed: 1 Ignored: 217)
</details>
</details>

[Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsmonotouch_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_macos-1&api-version=6.0&$format=zip)

## Successes

:white_check_mark: cecil: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testscecil-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testscecil-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (iOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsdotnettests_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_ios-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (MacCatalyst): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsdotnettests_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (macOS): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsdotnettests_macos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_macos-1&api-version=6.0&$format=zip)
:white_check_mark: dotnettests (Multiple platforms): All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsdotnettests_multiple-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsdotnettests_multiple-1&api-version=6.0&$format=zip)
:white_check_mark: framework: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsframework-1&api-version=6.0&$format=zip)
:white_check_mark: fsharp: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsfsharp-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsfsharp-1&api-version=6.0&$format=zip)
:white_check_mark: generator: All 5 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsgenerator-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsgenerator-1&api-version=6.0&$format=zip)
:white_check_mark: interdependent-binding-projects: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsinterdependent-binding-projects-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsinterdependent-binding-projects-1&api-version=6.0&$format=zip)
:white_check_mark: introspection: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsintrospection-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsintrospection-1&api-version=6.0&$format=zip)
:white_check_mark: linker: All 40 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testslinker-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testslinker-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (iOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsmonotouch_ios-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_ios-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (MacCatalyst): All 8 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsmonotouch_maccatalyst-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_maccatalyst-1&api-version=6.0&$format=zip)
:white_check_mark: monotouch (tvOS): All 7 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsmonotouch_tvos-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsmonotouch_tvos-1&api-version=6.0&$format=zip)
:white_check_mark: msbuild: All 2 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsmsbuild-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsmsbuild-1&api-version=6.0&$format=zip)
:white_check_mark: xcframework: All 4 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsxcframework-1/;/tests/vsdrops_index.html) [Download](https://devdiv.visualstudio.com/DevDiv/_apis/build/builds/10724172/artifacts?artifactName=HtmlReport-simulator_testsxcframework-1&api-version=6.0&$format=zip)
:white_check_mark: xtro: All 1 tests passed. [Html Report (VSDrops)](https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests/20241217.5/10724172//simulator_testsxtro-1/;/tests/vsdrops_index [...]

2024-12-17 22:24 UTC, mandel-macaque commented
Needs to be merge for API diff to work. The real issue as a typo in the variable name.

2024-12-17 22:25 UTC, merged