Bump to Xcode 12.2 beta 1.
xamarin/xamarin-macios pull request #9665
Opened 2020-09-18 08:50 UTC by rolfbjarne

2020-09-18 10:14 UTC, monojenkins commented
Build failure
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15211//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15211//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15211//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
✅ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15211//Generator_20Diff) (no change)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15211//Test_20Report) 🔥

# Test results

<details>
<summary>26 tests failed, 50 tests passed.</summary>

## Failed tests

 * Xtro/Mac: HarnessException (Harness exception for 'Xtro': System.NullReferenceException: Object reference not set to an instance of an object
  at Xharness.TestTasks.RunTest.BuildAsync () [0x00227] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xharness/TestTasks/RunTest.cs:71 
  at Xharness.TestTasks.RunTest.ExecuteAsync () [0x000d8] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xharness/TestTasks/RunTest.cs:97 
  at Microsoft.DotNet.XHarness.iOS.Shared.Tasks.TestTasks.RunInternalAsync () [0x00226] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/TestTask.cs:282 )
 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * introspection/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
 * monotouch-test/tvOS - simulator/Debug: Failed
 * monotouch-test/tvOS - simulator/Debug (LinkSdk): Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar): Failed
 * monotouch-test/tvOS - simulator/Release (all optimizations): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed
 * framework-test/watchOS 32-bits - simulator/Debug: Failed
 * interdependent-binding-projects/watchOS 32-bits - simulator/Debug: Failed
 * fsharp/watchOS 32-bits - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Release: Failed
 * link all/watchOS 32-bits - simulator/Debug: Failed
 * link all/watchOS 32-bits - simulator/Release: Failed
 * link sdk/watchOS 32-bits - simulator/Debug: Failed
 * link sdk/watchOS 32-bits - simulator/Release: Failed
 * mono-native-compat/watchOS 32-bits - simulator/Debug: Failed
 * mono-native-unified/watchOS 32-bits - simulator/Debug: Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): Failed
</details>

2020-09-18 11:12 UTC, dalexsoto commented
Thanls @rolfbjarne not sure what happened locally heh, I’ll take over and fix the tests etc

2020-09-18 11:15 UTC, dalexsoto commented
Looks lime watchOS is having a hard time heh

2020-09-18 15:38 UTC, tj-devel709 approved these changes

2020-09-18 16:28 UTC, rolfbjarne commented on src/gamecontroller.cs
> +		[TV (14, 0), Mac (11, 0), iOS (14, 0)]
Shouldn't this be tvOS 14.2?

2020-09-18 16:40 UTC, dalexsoto commented on src/gamecontroller.cs
> +		[TV (14, 0), Mac (11, 0), iOS (14, 0)]
Whoops yup you are right

2020-09-18 17:59 UTC, mandel-macaque approved these changes

2020-09-18 21:37 UTC, monojenkins commented
Build failure
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15220//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15220//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15220//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15220//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15220//Test_20Report) 🔥

# Test results

<details>
<summary>38 tests failed, 38 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 64-bits - simulator/Debug: TimedOut
 * framework-test/iOS Unified 64-bits - simulator/Debug: TimedOut
 * interdependent-binding-projects/iOS Unified 64-bits - simulator/Debug: TimedOut
 * fsharp/iOS Unified 64-bits - simulator/Debug: TimedOut
 * introspection/iOS Unified 64-bits - simulator/Debug: TimedOut
 * dont link/iOS Unified 64-bits - simulator/Debug: TimedOut
 * dont link/iOS Unified 64-bits - simulator/Release: TimedOut
 * link all/iOS Unified 64-bits - simulator/Debug: TimedOut
 * link all/iOS Unified 64-bits - simulator/Release: TimedOut
 * link sdk/iOS Unified 64-bits - simulator/Debug: TimedOut
 * link sdk/iOS Unified 64-bits - simulator/Release: TimedOut
 * mono-native-compat/iOS Unified 64-bits - simulator/Debug: TimedOut
 * mono-native-compat/iOS Unified Today Extension 64-bits - simulator/Debug: TimedOut
 * mono-native-unified/iOS Unified 64-bits - simulator/Debug: TimedOut
 * mono-native-unified/iOS Unified Today Extension 64-bits - simulator/Debug: TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): TimedOut
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): TimedOut
 * monotouch-test/tvOS - simulator/Debug: Failed
 * monotouch-test/tvOS - simulator/Debug (LinkSdk): Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar): Failed
 * monotouch-test/tvOS - simulator/Release (all optimizations): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed
 * framework-test/watchOS 32-bits - simulator/Debug: Failed
 * interdependent-binding-projects/watchOS 32-bits - simulator/Debug: Failed
 * fsharp/watchOS 32-bits - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Release: Failed
 * link all/watchOS 32-bits - simulator/Debug: Failed
 * link all/watchOS 32-bits - simulator/Release: Failed
 * link sdk/watchOS 32-bits - simulator/Debug: Failed
 * link sdk/watchOS 32-bits - simulator/Release: Failed
 * mono-native-compat/watchOS 32-bits - simulator/Debug: Failed
 * mono-native-unified/watchOS 32-bits - simulator/Debug: Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): Failed
</details>

2020-09-18 23:10 UTC, dalexsoto commented
build

2020-09-19 04:04 UTC, monojenkins commented
Build failure
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15225//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15225//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15225//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15225//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15225//Test_20Report) 🔥

# Test results

<details>
<summary>24 tests failed, 52 tests passed.</summary>

## Failed tests

 * monotouch-test/iOS Unified 64-bits - simulator/Debug: Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/iOS Unified 64-bits - simulator/Release (all optimizations): Failed
 * monotouch-test/tvOS - simulator/Debug: Failed
 * monotouch-test/tvOS - simulator/Debug (LinkSdk): Failed
 * monotouch-test/tvOS - simulator/Debug (static registrar): Failed
 * monotouch-test/tvOS - simulator/Release (all optimizations): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed
 * framework-test/watchOS 32-bits - simulator/Debug: Failed
 * interdependent-binding-projects/watchOS 32-bits - simulator/Debug: Failed
 * fsharp/watchOS 32-bits - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Release: Failed
 * link all/watchOS 32-bits - simulator/Debug: Failed
 * link all/watchOS 32-bits - simulator/Release: Failed
 * link sdk/watchOS 32-bits - simulator/Debug: Failed
 * link sdk/watchOS 32-bits - simulator/Release: Failed
 * mono-native-compat/watchOS 32-bits - simulator/Debug: Failed
 * mono-native-unified/watchOS 32-bits - simulator/Debug: Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): Failed
</details>

2020-09-22 12:07 UTC, spouliot requested changes

2020-09-22 12:07 UTC, spouliot commented on Make.versions
> +IOS_PACKAGE_VERSION=14.0.1.$(IOS_COMMIT_DISTANCE)
too close
that should be `14.3` so we can release a stable `14.2` whenever (or if) Xcode 12.1 comes out

2020-09-22 22:38 UTC, monojenkins commented
Build failure
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15237//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15237//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15237//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15237//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15237//Test_20Report) 🔥

# Test results

<details>
<summary>51 tests failed, 88 tests passed.</summary>

## Failed tests

 * monotouch-test/watchOS 32-bits - simulator/Debug: Failed
 * framework-test/watchOS 32-bits - simulator/Debug: Failed
 * interdependent-binding-projects/watchOS 32-bits - simulator/Debug: Failed
 * fsharp/watchOS 32-bits - simulator/Debug: Failed
 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Debug: Failed
 * dont link/watchOS 32-bits - simulator/Release: Failed
 * link all/watchOS 32-bits - simulator/Debug: Failed
 * link all/watchOS 32-bits - simulator/Release: Failed
 * link sdk/watchOS 32-bits - simulator/Debug: Failed
 * link sdk/watchOS 32-bits - simulator/Release: Failed
 * mono-native-compat/watchOS 32-bits - simulator/Debug: Failed
 * mono-native-unified/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemCoreXunit Part 1/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemCoreXunit Part 2/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemXunit/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemCoreTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemNumericsTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemRuntimeSerializationTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemTransactionsTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemXmlTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemXmlLinqTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemComponentModelDataAnnotationsTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemJsonTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemServiceModelWebTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemIOCompressionTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemIOCompressionFileSystemTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono MonoCSharpTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemSecurityTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono MonoDataSqliteTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono MonoRuntimeTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemDataTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemDataDataSetExtensionsTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemNetHttpTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemServiceModelTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono CorlibTests/watchOS 32-bits - simulator/Debug: Failed
 * [NUnit] Mono SystemWebServicesTests/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemDataXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemJsonXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemSecurityXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemLinqXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemXmlXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemRuntimeCompilerServicesUnsafeXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemNumericsXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono MicrosoftCSharpXunit/watchOS 32-bits - simulator/Debug: Failed
 * [xUnit] Mono SystemNetHttpUnitTestsXunit/watchOS 32-bits - simulator/Debug: Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): Failed
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): Failed
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): Failed
 * MTouch tests/NUnit: Failed (Execution failed with exit code 5)
</details>

2020-09-23 01:24 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15239/)

🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15239//console) 🔥

2020-09-23 01:36 UTC, spouliot approved these changes

2020-09-23 01:36 UTC, spouliot commented on tests/common/TestRuntime.cs
> +				return CheckMacSystemVersion (11, 0, 0);
the 12,0 check will need to be brought back to 10,15 too

2020-09-23 04:08 UTC, monojenkins commented
Build failure
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15240//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15240//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15240//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15240//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15240//Test_20Report) 🔥

# Test results

<details>
<summary>1 tests failed, 88 tests passed.</summary>

## Failed tests

 * MTouch tests/NUnit: Failed (Execution failed with exit code 5)
</details>

2020-09-23 12:11 UTC, merged