[xcode12] Merge xcode12 into d16-8
xamarin/xamarin-macios pull request #9672
Opened 2020-09-18 22:29 UTC by mandel-macaque

2020-09-18 22:44 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15222/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15222//console)
🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15222//console) 🔥

2020-09-18 22:45 UTC, mandel-macaque commented
build

2020-09-18 23:00 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15223/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15223//console)
🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15223//console) 🔥

2020-09-21 07:07 UTC, rolfbjarne approved these changes

2020-09-21 12:49 UTC, emaf approved these changes

2020-09-21 15:34 UTC, tj-devel709 commented
So we are mostly looking to make sure the merge conflicts were settled the correct way right? We're not looking to fix whitespace and things like that?

2020-09-21 15:37 UTC, mandel-macaque commented
@tj-devel709 just merge, we do not fix anything in this branch, except possible issues like the one that Rolf fixed in the last commit. This is just brings all the commits from xcode12.

2020-09-21 16:33 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15230/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15230//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15230//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15230//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15230//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15230//Generator_20Diff) (please review changes)

2020-09-21 17:21 UTC, tj-devel709 approved these changes

2020-09-21 18:27 UTC, monojenkins commented
Build failure
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15231//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15231//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15231//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15231//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15231//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15231//Test_20Report) 🔥

# Test results

<details>
<summary>54 tests failed, 54 tests passed.</summary>

## Failed tests

 * monotouch-test/watchOS 32-bits - simulator/Debug: BuildFailure
 * monotouch-test/watchOS 32-bits - simulator/Debug (LinkSdk): BuildFailure
 * monotouch-test/watchOS 32-bits - simulator/Debug (static registrar): BuildFailure
 * monotouch-test/watchOS 32-bits - simulator/Release (all optimizations): BuildFailure
 * framework-test/watchOS 32-bits - simulator/Debug: BuildFailure
 * interdependent-binding-projects/watchOS 32-bits - simulator/Debug: BuildFailure
 * fsharp/watchOS 32-bits - simulator/Debug: BuildFailure
 * introspection/watchOS 32-bits - simulator/Debug: BuildFailure
 * dont link/watchOS 32-bits - simulator/Debug: BuildFailure
 * dont link/watchOS 32-bits - simulator/Release: BuildFailure
 * link all/watchOS 32-bits - simulator/Debug: BuildFailure
 * link all/watchOS 32-bits - simulator/Release: BuildFailure
 * link sdk/watchOS 32-bits - simulator/Debug: BuildFailure
 * link sdk/watchOS 32-bits - simulator/Release: BuildFailure
 * mono-native-compat/watchOS 32-bits - simulator/Debug: BuildFailure
 * mono-native-unified/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 1/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemCoreXunit Part 2/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemCoreTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemNumericsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemRuntimeSerializationTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemTransactionsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemXmlTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemXmlLinqTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemComponentModelDataAnnotationsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemJsonTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemServiceModelWebTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemIOCompressionTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemIOCompressionFileSystemTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono MonoCSharpTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemSecurityTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono MonoDataSqliteTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono MonoRuntimeTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemDataTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemDataDataSetExtensionsTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemNetHttpTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemServiceModelTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono CorlibTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [NUnit] Mono SystemWebServicesTests/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemDataXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemJsonXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemSecurityXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemLinqXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemXmlXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemRuntimeCompilerServicesUnsafeXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemNumericsXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono MicrosoftCSharpXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * [xUnit] Mono SystemNetHttpUnitTestsXunit/watchOS 32-bits - simulator/Debug: BuildFailure
 * MSBuild tests/iOS: Failed (Execution failed with exit code 2)
 * MTouch tests/NUnit: Failed (Execution failed with exit code 2)
 * Cecil-based tests/NUnit: Failed (Execution failed with exit code 1)
 * DotNet tests: Failed (Execution failed with exit code 1)
</details>

2020-09-21 18:55 UTC, dalexsoto approved these changes

2020-09-21 19:17 UTC, whitneyschmidt approved these changes

2020-09-21 22:20 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15232/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15232//console)
🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15232//console) 🔥

2020-09-22 00:30 UTC, monojenkins commented
Build failure
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15233//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15233//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15233//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15233//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15233//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15233//Test_20Report) 🔥

# Test results

<details>
<summary>2 tests failed, 106 tests passed.</summary>

## Failed tests

 * introspection/watchOS 32-bits - simulator/Debug: Failed
 * MSBuild tests/iOS: Failed (Execution failed with exit code 1)
</details>

2020-09-22 03:48 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15234/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15234//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15234//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15234//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15234//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15234//Generator_20Diff) (please review changes)

2020-09-22 05:57 UTC, monojenkins commented
Build failure
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15235//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15235//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15235//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15235//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15235//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15235//Test_20Report) 🔥

# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * MSBuild tests/iOS: Failed (Execution failed with exit code 1)
</details>

2020-09-22 07:28 UTC, rolfbjarne requested changes

2020-09-22 07:28 UTC, rolfbjarne commented on tests/cecil-tests/TaskAssemblyTests.cs
> +			if (assembly.Contains ("Xamarin.Mac.Tasks.dll"))
This should check `Configuration.include_mac` and Assert.Ignore if true. That way we don't have to remember to turn it back on later.

2020-09-22 07:28 UTC, rolfbjarne commented on tests/dotnet/UnitTests/ProjectTest.cs
> +			if (platform == "macOS")
Same: this should check `Configuration.include_mac` and Assert.Ignore if true.

2020-09-22 07:28 UTC, rolfbjarne commented on tests/dotnet/UnitTests/ProjectTest.cs
> +			Assert.Ignore ("Ignore until Xamarin.Mac is re-enabled. Issue: https://github.com/xamarin/xamarin-macios/issues/9680");
Same: this should check `Configuration.include_mac` and Assert.Ignore if true.

2020-09-22 14:10 UTC, spouliot approved these changes

2020-09-22 18:11 UTC, monojenkins commented
Build failure
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15236//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15236//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15236//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15236//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15236//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15236//Test_20Report) 🔥

# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * MSBuild tests/iOS: Failed (Execution failed with exit code 1)
</details>

2020-09-22 22:36 UTC, monojenkins commented
Build failure
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15238//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15238//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15238//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15238//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15238//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15238//Test_20Report) 🔥

# Test results

<details>
<summary>1 tests failed, 107 tests passed.</summary>

## Failed tests

 * [NUnit] Mono BCL tests group 2/iOS Unified 64-bits - simulator/Debug: Failed
</details>

2020-09-22 22:51 UTC, mandel-macaque commented
Last failure is a known network related issue: https://github.com/xamarin/maccore/issues/2103

2020-09-22 22:51 UTC, merged