[CarPlay] Update bindings to Xcode 12.2 Beta 1
xamarin/xamarin-macios pull request #9719
Opened 2020-09-29 01:26 UTC by dalexsoto

CPEntity docs got removed https://developer.apple.com/documentation/carplay/cpentity
so it is very likely that Apple will keep this out from the API.

2020-09-29 01:35 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15283/)

2020-09-29 01:45 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15284/)

🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15284//console) 🔥

2020-09-29 01:56 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15285/)

🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15285//console) 🔥

2020-09-29 03:19 UTC, monojenkins commented
Build failure
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15286//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15286//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15286//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15286//Generator_20Diff) (please review changes)
🔥 [Test run failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15286//Test_20Report) 🔥

# Test results

<details>
<summary>1 tests failed, 59 tests passed.</summary>

## Failed tests

 * link all/tvOS - simulator/Release: Failed
</details>

2020-09-29 06:53 UTC, rolfbjarne approved these changes

2020-09-29 06:53 UTC, rolfbjarne commented on src/CarPlay/CPCompat.cs
> +		public CPEntity () => throw new NotImplementedException ();
I think we usually throw `NotSupportedException` instead of `NotImplementedException`.

2020-09-29 12:21 UTC, spouliot requested changes

2020-09-29 12:21 UTC, spouliot commented on src/CarPlay/CPCompat.cs
> +	[Obsolete ("'CPEntity' has been removed from iOS.")]
we need to normalize those strings (to reduce the metadata size of our assemblies)
pick up an existing one, there's no need to mention the type name (or the OS), the IDE will put this in context

2020-09-29 12:21 UTC, spouliot commented on src/CarPlay/CPCompat.cs
> +		[EditorBrowsable (EditorBrowsableState.Advanced)]
there's already a `.Never` on the type
not sure what happens with the extra one - but `.Never` is the right one for obsolete code such as this

2020-09-29 12:21 UTC, spouliot commented on src/CarPlay/CPCompat.cs
> +		[EditorBrowsable (EditorBrowsableState.Advanced)]
same

2020-09-29 15:53 UTC, whitneyschmidt approved these changes

2020-09-29 17:05 UTC, spouliot approved these changes

2020-09-29 18:21 UTC, monojenkins commented
Build success
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15296//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15296//API_20diff_20_28from_20stable_29)
✅ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15296//API_20diff_20_28PR_20only_29) (no change)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15296//Generator_20Diff) (please review changes)
✅ [Test run succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15296//Test_20Report)

2020-09-29 19:15 UTC, mandel-macaque requested changes
The compat code should maintain the API that was public.

2020-09-29 19:23 UTC, dalexsoto commented
@mandel-macaque ?? What am I missing here?

2020-10-01 15:58 UTC, mandel-macaque approved these changes

2020-10-01 19:22 UTC, merged