[Xcode12.1] Bring Xcode12.1 support.
xamarin/xamarin-macios pull request #9932
Opened 2020-10-20 21:28 UTC by mandel-macaque

2020-10-20 21:31 UTC, dalexsoto commented on Make.config
> +XCODE_DEVELOPER_ROOT=/Applications/Xcode_12.1.0-GM.app/Contents/Developer
This is right because there is no package yer

2020-10-20 21:35 UTC, spouliot requested changes

2020-10-20 21:35 UTC, dalexsoto approved these changes

2020-10-20 21:35 UTC, spouliot commented on Make.config
> +APIDIFF_REFERENCES=https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12/7ec3751a1077e5d77d7375ef61182538d9d11f8d/234/package/bundle.zip
that should be the `.../xcode12.1/commit-you-merged/...`

2020-10-20 21:35 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15543/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15543//console)
🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15543//console) 🔥

2020-10-20 21:37 UTC, dalexsoto commented on Make.config
> +APIDIFF_REFERENCES=https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12/7ec3751a1077e5d77d7375ef61182538d9d11f8d/234/package/bundle.zip
```suggestion
APIDIFF_REFERENCES=https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12.1/e0ce496804e49056ab8eb41da55813083ab7f58b/15/package/bundle.zip
```

2020-10-20 21:45 UTC, monojenkins commented
Build failure
❌ [Build failed or was aborted](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15544/)

✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15544//console)
🔥 [Build failed](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15544//console) 🔥

2020-10-20 21:48 UTC, spouliot approved these changes

2020-10-20 22:05 UTC, tj-devel709 approved these changes

2020-10-20 22:11 UTC, whitneyschmidt approved these changes

2020-10-21 00:38 UTC, monojenkins commented
Build success
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15545//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15545//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15545//API_20diff_20_28from_20stable_29)
⚠️ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15545//API_20diff_20_28PR_20only_29) (🔥 breaking changes 🔥)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15545//Generator_20Diff) (please review changes)
✅ [Test run succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15545//Test_20Report)

2020-10-21 01:21 UTC, dalexsoto commented
`ARFrameSemantics` breaking change is expected and correct

2020-10-21 01:22 UTC, merged