[dotnet-linker] Catch any exceptions from our custom steps and show them using our error reporting logic.
xamarin/xamarin-macios pull request #9954
Opened 2020-10-23 10:34 UTC by rolfbjarne

* Letting the linker handle the exceptions will not result in a particularly
  good experience, because the linker will crash.

* We can also show better information, since we have more knowledge about many
  of the exceptions we raise ourselves.

2020-10-23 12:17 UTC, spouliot requested changes

2020-10-23 12:17 UTC, spouliot commented on tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
> +		}
might want to share code/pattern with `tools/linker/ExceptionalSubStep.cs` since it faced a similar issue

2020-10-23 12:17 UTC, spouliot commented on tools/dotnet-linker/Steps/ConfigurationAwareSubStep.cs
> +
that one should subclass `ExceptionalSubStep`

2020-10-23 13:36 UTC, monojenkins commented
Build success
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15568//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15568//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15568//API_20diff_20_28from_20stable_29)
✅ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15568//API_20diff_20_28PR_20only_29) (no change)
✅ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15568//Generator_20Diff) (no change)
✅ [Test run succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15568//Test_20Report)

2020-10-23 15:55 UTC, tj-devel709 approved these changes

2020-10-26 14:24 UTC, mandel-macaque approved these changes
+1 to @spouliot comments.

2020-10-26 15:45 UTC, spouliot approved these changes

2020-10-26 18:29 UTC, monojenkins commented
Build success
✅ [Provisioning succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15578//console)
✅ [Build succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15578//console)
✅ [API Diff (from stable)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15578//API_20diff_20_28from_20stable_29)
✅ [API Diff (from PR only)](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15578//API_20diff_20_28PR_20only_29) (no change)
ℹ️ [Generator Diff](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15578//Generator_20Diff) (please review changes)
✅ [Test run succeeded](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/15578//Test_20Report)

2020-10-26 19:16 UTC, merged